# Bucket A — program-rule sketches for programs/upstream_mirror_is_pinned_check.py
# Corpus-sweep REQUIRED before merging into programs/upstream_mirror_is_pinned_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A module states in prose that it re-implements a computation from an upstream tool -- the variable names verbatim, the numbered steps in the same order. Our half of the shared invariant is pinned by a test. The upstream half is not, so the sentence 'upstream does it this way' is true when it is typed and unchecked from then on. The re-implementation then drifts on a quantity the two sides read differently, the drift produces a wrong number rather than an error, and it surfaces later as an unrelated refusal in a different subsystem. A test on our side alone does not catch it: our side was already pinned when the drift happened, and it was pinned to the wrong value.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_declared_upstream_mirror_is_pinned_by_a_test_that_reads_upstream(sample_text, ports):
    """A borrowing stated only in prose is not a borrowing that is maintained. A module that mirrors an upstream computation must declare that machine-readably -- the upstream artefact, what is mirrored, and the test that pins it -- and the named test must exist, must define the named function, and must actually read the upstream artefact. A pin that asserts only our own invariant is the state this rule exists to improve on. Zero declared mirrors is NOT CHECKED and never PASS: a question with no subject is not a clean answer to it."""
    # Expected signal: ERROR
    # Suggested fix action: Read (never import) each module's literal declaration; require the three fields, resolve the named pin file, require the named test to be defined in it, and require the pin to reference either the declared artefact path, its tail, or the declaration itself. Accept the third form deliberately: a pin that takes the path FROM the declaration keeps one copy of the fact, so the two cannot drift apart the way the mirror did -- and that form is what the gate's own first pin used, which is how the case was found. COUNT, and print on every run, the modules whose own prose claims a borrowing while declaring none; do not fail on them, because deciding whether a citation is a borrowing or a reference is a judgement this program has no input for, and turning a prose scan into a blocking predicate is how a checker earns a reputation for firing on correct code. MEASURED across three states: green against the real upstream artefact in the shipped image, RED against an upstream mutated to accumulate the other dimension, and an honest named skip on a host that ships no upstream at all. The pin also refuted the sentence the mirror had been documented with -- upstream does read the other dimension, twice, inside the same loop, and prints it without ever using it in arithmetic -- so the conclusion held and the stated evidence did not.
    return []  # list of findings — TODO implement
