# Bucket A — program-rule sketches for programs/gate_host_independence_check.py
# Corpus-sweep REQUIRED before merging into programs/gate_host_independence_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.68
# Pattern: A gate drives other gates and tidies up after each one, restoring any tracked file that was clean before the drive and dirty after, on the reasoning that the child it just ran must have made the difference. Clean-before and dirty-after identifies a TIME WINDOW, not a writer. Anything else that writes inside that window matches the rule, and the restore command takes every uncommitted change in the file, because that command's meaning is make this equal the committed state and not undo the last write. The editor is told nothing: the work is gone, it was never committed, and the first sign of it is an unrelated failure later. And the lost work is the smaller half: because the repair attributes the change to whichever child happened to be running, the run also PUBLISHES A FINDING against that child — naming an innocent subject as having corrupted the checkout, in a list beside the real ones, where nothing distinguishes it.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_repair_that_cannot_attribute_a_change_has_not_attributed_it(sample_text, ports):
    """A repair may undo only a change it can ATTRIBUTE. Timing is not attribution, and a docstring saying it is does not make it one. Where the writer cannot be established, the honest verdict is to NAME what changed and leave it, which is the rule this repository already applies to every other check that cannot answer its question. Three deterministic forms, any of which closes it: re-read the path immediately before restoring and refuse when it changed a second time inside one drive; make repair opt-in for a root the run does not own, since the argument that supplies that root is what takes it out of its designed setting; and in every case print the restored paths and the assumption behind the attribution, so an editor learns it from the gate and not from a later failure."""
    # Expected signal: ERROR
    # Suggested fix action: NOT SHIPPED HERE, and the reason is scope and not difficulty. This was found while running the gate against the tree this lane was editing, it destroyed that work twice before it was identified, and a live positive control settles it: one line appended to a tracked file while the gate ran was gone twenty-six seconds later, silently. The evidence is in the bundle with the three fixes named. It is not patched here because the gate is shared, an instance was executing at the time, and a change to a restore path needs its own acceptance run rather than a same-night edit inside a brief about something else. It does NOT reproduce on a quiet tree, which is the setting it was designed for; it needs a second writer, which on a fleet where several agents share one repository is the normal condition.
    return []  # list of findings — TODO implement
