# Bucket A — program-rule sketches for programs/upstream_contract_parity_check.py
# Corpus-sweep REQUIRED before merging into programs/upstream_contract_parity_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.68
# Pattern: A step re-implements an upstream flow's configuration contract and reads a SUBSET of the variables that contract declares. Nothing anywhere records which subset. The step then refuses a declared thing as absent, because the declaration lives in a view reached only through one of the variables it never read, and the refusal is indistinguishable from a real absence: it names a count of the files it did open, it is worded correctly, and it is wrong. The omission is invisible from both sides -- our artefact never lists what we left out, and upstream has no idea anyone is mirroring it.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_upstream_name_inside_a_registered_re_implementation_is_accounted_for(sample_text, ports):
    """Where this plugin re-implements an upstream flow, every variable that flow declares must fall in exactly one recorded class: implemented, declared-unperformed, omitted with a reason, or a known gap with a reference. A name in no class is a finding the day it appears. This does not decide that the register is complete -- a re-implementation nobody registered is invisible to any program, and that judgement is a reader's. It removes the other failure, the one that actually happened, where the upstream was known, the re-implementation was known, and still no artefact said which parts of the contract had been left out."""
    # Expected signal: ERROR
    # Suggested fix action: SHIPPED in this bundle. A register names each re-implementation, its upstream file, the extraction that yields the upstream declaration, a snapshot of that declaration with the content hash of the file it was read from, and our classification of every name in it. The check enforces classification completeness in BOTH directions, cross-checks every implemented name against our own module source so the register cannot claim an implementation the code does not contain, refuses a known gap that carries no reference, and refuses a known gap the module now implements so a closed gap cannot linger in the count of what is still wrong. Given a distribution root it re-measures the snapshot, reporting a name upstream has gained, a name upstream has dropped, and a content hash that no longer matches. An unreadable register, an entry with no upstream names, or an unreachable distribution is NOT DETERMINED, never a pass. Denominator printed at every verdict. Runs clean on this tree.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.68
# Pattern: A deterministic re-implementation of an upstream computation drifts from it. Upstream reads one dimension of a cell in both places it measures a side; ours read whichever dimension the oriented footprint presented, so one pair of sides summed the other dimension and over-counted by more than a factor of four. Nothing in the repository compared the two. The divergence produced no failure of its own -- it surfaced much later as a refusal about something else entirely, on a brief that was not about it, and every test of the module passed throughout because every test was written against the module's own arithmetic.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_re_implemented_computation_names_its_pin_or_names_its_gap(sample_text, ports):
    """A registered re-implementation of an upstream computation must name either a pin test that compares ours against theirs, or a known gap with a reference. The upstream side is anchored by the STRING it is recognised by, not by a line number: a line number points ten lines above its subject after the next edit and still looks precise. When the anchor stops occurring in the upstream file, the computation we mirror has moved and the entry points at nothing, which is a finding. The check verifies the pin EXISTS and never that it is a good test -- that distinction is stated where a reader meets it, because a check that quietly implied more would be the same defect one layer up."""
    # Expected signal: ERROR
    # Suggested fix action: SHIPPED in this bundle, as the second entry kind of the same register. A computation entry names our module, the upstream file, the anchor strings the computation is recognised by, a content hash of the upstream file at the moment it was read, and either a pin test as file-plus-function -- verified to exist and to define that function -- or a known gap carrying a reason and a reference. An entry with no anchors is NOT DETERMINED rather than a pass, because an entry that cannot describe the parity it asserts has not established one.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.68
# Pattern: A step declares a configuration variable, passes it to a tool, and the tool does not deliver what the variable's name promises. The step proceeds and reports a verdict. An author who sets the knob is told nothing: the run passes, the geometry is whatever the tool chose, and the setting that was supposed to control it changed nothing they can see. The failure is worst exactly where the author was most deliberate, and it is silent at every other setting because the default happens to be the identity.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_knob_the_flow_cannot_honour_degrades_loudly(sample_text, ports):
    """Every variable in a step's declared contract is classified as honoured or not honoured, and the classification is a MEASUREMENT, not an assertion -- driven at the default and at one non-default value, comparing the observable result. A variable measured not honoured must degrade loudly in both directions: at the value indistinguishable from never having set it, PROCEED and record the finding in every report including the skipped ones, because a disclosure only on the happy path is not a disclosure; at a deliberately declared value, refuse NOT DETERMINED naming the variable. Never a pass, never a finding about the design -- I cannot honour what you asked is neither. Generalise the rule, never the one variable: what makes this a rule is that a knob an author can set and that changes nothing is a lie the flow tells, and nothing about that sentence mentions what the knob controls."""
    # Expected signal: ERROR
    # Suggested fix action: NOT SHIPPED IN THIS BUNDLE, AND THE REASON IS NOT THAT IT NEEDS JUDGEMENT. The input is fully named: the step's declared variable contract, plus two runs of the step differing in one variable, plus the observable each run produces. The decision -- did the observable move -- is a comparison, with no judgement in it. What is missing is the SUBJECT: on this tree no step carries an honoured-versus-not-honoured classification at all, and the ruling that creates the first one is in an open, unlanded branch. A guard shipped tonight would therefore fire on the tree it shipped on, which is a bug and not a guard; and a guard narrowed until it stopped firing would be a guard that no longer asks the question. Land the ruling, then add the classification to the register that this bundle ships, then wire this check to drive the two runs and compare. The one thing that must not happen is the classification being written as a claim nobody measured, which is the same defect one layer up.
    return []  # list of findings — TODO implement
