#!/usr/bin/env python3
"""One-shot, re-runnable amendment of verdicts_shard_c.tsv: record the ignored-content
measurement on every deletion-bound row, and replace the UNTRACKED NOT EXAMINED
disclosure on the 11 rows whose hosts have now been reached.

Kept in the tree because the edit it makes is a claim about a measurement, and a
claim whose producer is not readable is a claim nobody can re-derive. Idempotent:
running it twice changes nothing.
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
HARV = os.path.abspath(os.path.join(HERE, ".."))
MAIN = "a4caccefeab577a5337f1854c9c857e4d7a2bd42"
DBOUND = ("LANDED", "ABANDON")

RE_NOTEXAMINED = re.compile(
    r"\s*UNTRACKED NOT EXAMINED -- READ BEFORE DELETING\..*?"
    r"before acting on this verdict\.", re.S)
RE_IGN = re.compile(r"\s*IGNORED ACCOUNTED:.*?(?=$)", re.S)
RE_ABS = re.compile(r"\s*HELD BUT ABSENT FROM MAIN.S TIP:.*?(?= IGNORED ACCOUNTED:|$)", re.S)


def load_measured(path):
    rows = {}
    with open(path, encoding="utf-8") as fh:
        head = fh.readline().rstrip("\n").split("\t")
        for ln in fh:
            f = ln.rstrip("\n").split("\t")
            if len(f) == len(head):
                rows[f[head.index("path")]] = dict(zip(head, f))
    return rows


def load_entries(path):
    out = {}
    with open(path, encoding="utf-8") as fh:
        head = fh.readline().rstrip("\n").split("\t")
        for ln in fh:
            f = ln.rstrip("\n").split("\t")
            out.setdefault(f[head.index("path")], []).append(f[head.index("ignored_entry")])
    return out


def untracked_sentence(m):
    h, head, mb, owned = m["host"], m["head"], m["merge_base"], m["owned"]
    mbnote = ("its merge-base with origin/main is HEAD itself, so the owned set is empty "
              "by construction" if mb == head else
              f"its merge-base with origin/main is {mb[:11]}")
    return (
        f" UNTRACKED CHECKED: 0 untracked files and 0 tracked modifications in this "
        f"directory, measured on host .{h} on 2026-08-22 with "
        f"`git status --porcelain --untracked-files=all`. The earlier version of this row "
        f"disclosed this input as UNEXAMINED because .112 and .121 refuse a direct ssh "
        f"from .108; `ssh .102 \"ssh .{h} ...\"` reaches both and is the route used here. "
        f"Re-measured on the host at the same time: HEAD is {head} (unchanged since "
        f"judging), its commit OBJECT is present in the store -- not a pruned ref that "
        f"answers rev-parse from the ref file and then scores 0 on every ancestry query, "
        f"which is byte-identical to clean -- {mbnote}, and {owned} owned file(s) of which "
        f"0 differ from origin/main {MAIN}.")


def ignored_sentence(m, entries):
    n = int(m["ignored_entries"])
    if n == 0:
        return (" IGNORED ACCOUNTED: 0 gitignored entries in this directory, measured "
                "with `git status --porcelain --untracked-files=all --ignored=matching`. "
                "`-uall` reports untracked files and NOT ignored ones, so an untracked "
                "check alone is a universal over a domain that cannot contain an ignored "
                "file -- and `rm -rf` has never read .gitignore.")
    lst = "; ".join(sorted(entries))
    return (
        f" IGNORED ACCOUNTED: {n} gitignored entr{'y' if n == 1 else 'ies'} "
        f"({m['ignored_files']} file(s), {m['ignored_bytes']} bytes) measured with "
        f"`git status --porcelain --untracked-files=all --ignored=matching`: {lst}. "
        f"`-uall` reports untracked files and NOT ignored ones, so the untracked check "
        f"above is a universal over a domain that cannot contain an ignored file, and "
        f"`rm -rf` has never read .gitignore. `git check-ignore -v`, asked against a "
        f"skeleton built from origin/main's own .gitignore files, attributes every one of "
        f"these to a rule main DECLARES generated or scratch and for three of which main "
        f"names the producer (__pycache__/, .pytest_cache/, "
        f"**/tests/fixtures/synthetic_benchmark_phase1/ 'rebuilt by "
        f"build_synthetic_benchmark_phase1', "
        f"vibe-ic-marketplace/plugins/vibe-ic/reports/ 'generated by plugin_full_audit.py', "
        f"docs/reports/, scratch_geom_signoff_tests/ 'session scratch, never committed'). "
        f"Raw measurement: tools/harvest/raw_ignored_entries_shard_c_jharv3.tsv. "
        f"Gate: tools/harvest/bin_jharv3/ignored_accounted.py "
        f"(`--self-test` shows each of its five guarantees going red).")


def absent_sentence(a):
    n, same, mb, head = (int(a["held_absent_from_main_tip"]), int(a["identical_at_merge_base"]),
                         a["merge_base"], a["head"])
    if n == 0:
        return (" HELD BUT ABSENT FROM MAIN'S TIP: 0 -- every path in this worktree's HEAD "
                "tree is also in origin/main " + MAIN + ".")
    lead = (f" HELD BUT ABSENT FROM MAIN'S TIP: {n} path(s) in this worktree's HEAD tree are "
            f"not in origin/main {MAIN} (e.g. {a['examples']}). The L0 owned-set rule cannot "
            f"see these -- they are not in this branch's own diff against its merge-base -- so "
            f"they are measured separately: a file the tree HOLDS and main's tip lacks is "
            f"destroyed by the deletion this verdict authorises. ")
    if same == n:
        return lead + (f"All {n} are byte-identical to the same path at merge-base {mb[:11]}, "
                       f"a commit origin/main contains: they are main's OWN content, deleted "
                       f"from main after this point, and reachable from origin forever.")
    return lead + (f"{same} of {n} are byte-identical to the same path at merge-base "
                   f"{mb[:11]}; the remaining {n - same} exist in NO commit main contains and "
                   f"survive only because the whole HEAD commit {head[:11]} is contained by a "
                   f"LIVE origin branch this row names -- which is why this row's survivability "
                   f"claim is load-bearing rather than decorative.")


TWIN_OLD = ("byte-for-byte the same tree as /home/reyerchu/jf-63x8-work/base-mml, which is "
            "kept. Every file either owns hashes identically and BOTH working trees are "
            "clean (owns>=1 file AND clean, so the comparison covers all their content -- "
            "an empty owned-set would make every such worktree collide).")
TWIN_NEW = (
    "byte-for-byte the same tree as /home/reyerchu/jf-63x8-work/base-mml. "
    "CORRECTION 2026-08-22, measured on this host: this row previously said the twin "
    "\"is kept\" and that BOTH working trees are clean. Neither was checked and neither "
    "is true as written. The twin is NOT clean -- 1640 tracked modifications and 10 "
    "untracked files -- and it is a row in NO shard and carries NO verdict in any of the "
    "three verdict files, so \"is kept\" was an assumption about a path nobody decided. "
    "This ABANDON does not need the twin and does not rest on it: THIS directory is clean "
    "(0 untracked, 0 tracked modifications, measured with --untracked-files=all), so its "
    "entire content IS its HEAD tree a9f2edf43 = commit 3ab7fc723e49, and that commit is "
    "reachable from the LIVE origin branch jmatrix/63x8-main-reds. Deleting this directory "
    "loses nothing whatever the twin's state. Separately measured so the twin is not left "
    "as an open exposure: base-mml's whole working state -- all 1640 modifications AND all "
    "10 untracked files together -- hashes to tree 7840974874537d10, which is exactly the "
    "tree of commit 867de428920c, an ANCESTOR of origin/main. Its \"untracked\" files are "
    "old main files main has since deleted, not new work; nothing there is single-copy and "
    "no rescue ref is needed. Judged by name they read as new tests and a 64 KB new tool; "
    "judged by content they are main's own history.")


def main():
    meas = load_measured(os.path.join(HARV, "raw_untracked_ignored_shard_c_jharv3.tsv"))
    absent = load_measured(os.path.join(HARV, "raw_absent_from_main_shard_c_jharv3.tsv"))
    ents = load_entries(os.path.join(HARV, "raw_ignored_entries_shard_c_jharv3.tsv"))
    src = os.path.join(HARV, "verdicts_shard_c.tsv")
    out, changed, missing = [], 0, []
    with open(src, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    for i, ln in enumerate(lines):
        f = ln.split("\t")
        if i == 0 or len(f) != 3 or f[1] not in DBOUND:
            out.append(ln)
            continue
        path, verdict, ev = f
        m = meas.get(path)
        if not m:
            missing.append(path)
            out.append(ln)
            continue
        new = ev
        if path == "/home/reyerchu/wt-j63x8c" and TWIN_OLD in new:
            new = new.replace(TWIN_OLD, TWIN_NEW)
        new = RE_IGN.sub("", new).rstrip()
        new = RE_ABS.sub("", new).rstrip()
        if RE_NOTEXAMINED.search(new):
            new = RE_NOTEXAMINED.sub("", new).rstrip() + untracked_sentence(m)
        if path not in absent:
            missing.append(path)
            out.append(ln)
            continue
        new = new + absent_sentence(absent[path]) + ignored_sentence(m, ents.get(path, []))
        if new != ev:
            changed += 1
        out.append("\t".join([path, verdict, new]))
    if missing:
        sys.exit("REFUSING: deletion-bound rows with no measurement: " + ", ".join(missing))
    with open(src, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"rows rewritten: {changed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
