#!/usr/bin/env python3
"""A deletion-bound row must account for GITIGNORED content, not only untracked.

    usage: ignored_accounted.py [--repo DIR] [--raw FILE] [--verdicts FILE]
           ignored_accounted.py --self-test      # prove each check fires; see the red

WHY THIS EXISTS.
`git status --porcelain --untracked-files=all` was the fix for `-uno`, and it is
still not the whole domain. `-uall` reports untracked files; it does NOT report
IGNORED ones. Deleting a directory destroys ignored bytes exactly as thoroughly as
it destroys untracked ones -- `rm -rf` has never read .gitignore. So "0 untracked,
0 modified" is a universal over a domain that cannot contain an ignored file, which
is the same shape of unexamined input as the `-uno` measurement it replaced and the
empty-set universals `vacuous_universal.py` catches.

Measured on shard C's 19 deletion-bound rows: 121 ignored entries, every single one
of them present, and none of them examined by anything before this.

WHAT WOULD MAKE AN IGNORED ENTRY SAFE, AND WHY THAT IS NOT AN OPINION.
Not "it looks like a cache". origin/main's own `.gitignore` is a written record of
what this repository considers generated or scratch, and for several classes it
names the producer in the adjacent comment. An ignored entry is ACCOUNTED FOR when
git itself -- not this script's guesswork -- attributes it to one of those declared
rules. `git check-ignore -v` is asked, against a skeleton built from main's own
.gitignore files, so the answer is main's answer.

Anything else is RED. An ignored entry whose rule is not in the declared table is
not "probably fine": it is content nobody has looked at, sitting under a verdict
that authorises deleting it.

FAILING CLOSED.
  * an entry that no rule matches            -> RED (it should not have been listed)
  * an entry whose rule is not declared      -> RED (unexamined class)
  * a declared rule that is GONE from main   -> RED (the table is stale, not the tree)
  * a deletion-bound row with no measurement -> RED (unexamined input, the whole point)
A missing raw file is a loud exit, never an empty result that reads as clean.
"""
import argparse, os, subprocess, sys, tempfile

DELETION_BOUND = ("LANDED", "ABANDON")

# rule text on origin/main:.gitignore  ->  what main says produces it.
# The text is re-read from main at runtime; if it is gone, this gate goes red.
DECLARED = {
    "__pycache__/":
        "CPython bytecode cache; rebuilt by running any Python in the tree",
    ".pytest_cache/":
        "pytest's own cache; rebuilt by the next pytest run",
    "**/tests/fixtures/synthetic_benchmark_phase1/":
        "main's .gitignore: 'Test-generated synthetic fixtures "
        "(rebuilt by build_synthetic_benchmark_phase1)'",
    "vibe-ic-marketplace/plugins/vibe-ic/reports/":
        "main's .gitignore: 'Plugin audit reports (generated by plugin_full_audit.py)'",
    "docs/reports/":
        "generated report output, ignored by main",
    "scratch_geom_signoff_tests/":
        "main's .gitignore names it session scratch, never committed (ORGANIC #720); "
        "written by programs/tests/test_gds_geometry_signoff_wiring.py",
}


def run(cmd, cwd=None, check=True):
    p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if check and p.returncode not in (0, 1):
        sys.exit(f"FAIL: {' '.join(cmd)} -> rc={p.returncode}\n{p.stderr}")
    return p


def repo_of_this_file():
    """Locate the clone from this file's own path -- never a constant, never FETCH_HEAD.

    A hardcoded path is what made a peer's coverage checker report covered=0 on four
    hosts, which reads exactly like a total loss. FETCH_HEAD is worse: it means
    'whatever was fetched last', so the same command validates a different file
    depending on what else ran.
    """
    d = os.path.dirname(os.path.abspath(__file__))
    p = run(["git", "rev-parse", "--show-toplevel"], cwd=d, check=False)
    if p.returncode != 0:
        sys.exit("FAIL: this file is not inside a git clone; pass --repo")
    return p.stdout.strip()


def build_skeleton(repo, ref, tmp):
    """A throwaway clone carrying only main's .gitignore files, so `check-ignore`
    answers with MAIN's rules and not with those of whatever tree we happen to be in."""
    ls = run(["git", "ls-tree", "-r", "--name-only", ref], cwd=repo)
    names = [n for n in ls.stdout.splitlines() if os.path.basename(n) == ".gitignore"]
    if not names:
        sys.exit(f"FAIL: {ref} has no .gitignore at all -- refusing to judge on that")
    run(["git", "init", "-q", tmp])
    for n in names:
        blob = run(["git", "show", f"{ref}:{n}"], cwd=repo).stdout
        dst = os.path.join(tmp, n)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(dst, "w", encoding="utf-8") as fh:
            fh.write(blob)
    return names


def check_ignore(tmp, entry):
    """Ask git, in the skeleton, which rule ignores this entry. Returns (src,line,pat)."""
    rel = entry.rstrip("/")
    d = os.path.join(tmp, rel)
    os.makedirs(d, exist_ok=True)          # a directory rule needs a directory to see
    p = run(["git", "check-ignore", "-v", "--", rel + "/"], cwd=tmp, check=False)
    out = p.stdout.strip()
    if not out:
        p = run(["git", "check-ignore", "-v", "--", rel], cwd=tmp, check=False)
        out = p.stdout.strip()
    if not out:
        return None
    src, line, pat = out.split("\t")[0].rsplit(":", 2)[0], None, None
    first = out.split("\t")[0]
    parts = first.split(":")
    return (":".join(parts[:-2]), parts[-2], parts[-1])


def verify_declared_still_on_main(repo, ref):
    """The table above is a claim ABOUT main. Re-read main and fail if it has moved."""
    gi = run(["git", "show", f"{ref}:.gitignore"], cwd=repo).stdout.splitlines()
    missing = [r for r in DECLARED if r not in gi]
    return missing


def load_rows(path, cols):
    if not os.path.exists(path):
        sys.exit(f"FAIL: missing input {path} -- an absent measurement is not a clean one")
    rows = []
    with open(path, encoding="utf-8") as fh:
        head = fh.readline().rstrip("\n").split("\t")
        for ln in fh:
            ln = ln.rstrip("\n")
            if not ln:
                continue
            rows.append(dict(zip(head, ln.split("\t"))))
    for c in cols:
        if rows and c not in rows[0]:
            sys.exit(f"FAIL: {path} has no column {c!r}")
    return rows


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo")
    ap.add_argument("--ref", default="origin/main")
    ap.add_argument("--raw")
    ap.add_argument("--measured")
    ap.add_argument("--verdicts")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args(argv)
    if a.self_test:
        return self_test()

    repo = a.repo or repo_of_this_file()
    here = os.path.dirname(os.path.abspath(__file__))
    raw = a.raw or os.path.join(here, "..", "raw_ignored_entries_shard_c_jharv3.tsv")
    meas = a.measured or os.path.join(here, "..", "raw_untracked_ignored_shard_c_jharv3.tsv")
    verd = a.verdicts or os.path.join(here, "..", "verdicts_shard_c.tsv")

    print(f"repo   {repo}")
    print(f"ref    {a.ref} = {run(['git','rev-parse',a.ref],cwd=repo).stdout.strip()}")

    bad = []
    gone = verify_declared_still_on_main(repo, a.ref)
    for g in gone:
        bad.append(f"DECLARED RULE GONE FROM {a.ref}:.gitignore: {g!r} -- table is stale")

    entries = load_rows(raw, ["host", "path", "ignored_entry"])
    measured = load_rows(meas, ["host", "path", "untracked_all", "tracked_modified"])
    verdicts = load_rows(verd, ["path", "verdict"])

    # every deletion-bound row must have been measured
    seen = {r["path"] for r in measured}
    for r in verdicts:
        if r["verdict"] in DELETION_BOUND and r["path"] not in seen:
            bad.append(f"UNMEASURED {r['verdict']} row, no untracked/ignored measurement: {r['path']}")

    # every measured row must actually be clean on the untracked/modified axis
    dbound = {r["path"] for r in verdicts if r["verdict"] in DELETION_BOUND}
    for r in measured:
        if r["path"] not in dbound:
            continue
        if r["untracked_all"] != "0" or r["tracked_modified"] != "0":
            bad.append(f"DIRTY deletion-bound row {r['path']}: "
                       f"untracked={r['untracked_all']} modified={r['tracked_modified']}")

    ok = unaccounted = 0
    with tempfile.TemporaryDirectory() as tmp:
        build_skeleton(repo, a.ref, tmp)
        cache = {}
        for r in entries:
            e = r["ignored_entry"]
            if e not in cache:
                cache[e] = check_ignore(tmp, e)
            hit = cache[e]
            if hit is None:
                unaccounted += 1
                bad.append(f"NO RULE MATCHES {e} ({r['host']} {r['path']}) -- "
                           f"listed as ignored but {a.ref} does not ignore it")
                continue
            src, line, pat = hit
            if pat not in DECLARED:
                unaccounted += 1
                bad.append(f"UNDECLARED CLASS {e} ({r['host']} {r['path']}) -- "
                           f"ignored by {src}:{line} {pat!r}, which no entry in this "
                           f"gate's table declares generated or scratch")
            else:
                ok += 1

    print(f"ignored entries examined: {len(entries)}  accounted: {ok}  unaccounted: {unaccounted}")
    print(f"deletion-bound rows: {len(dbound)}  measured: {len(dbound & seen)}")
    if bad:
        print()
        for b in bad:
            print(b)
        print(f"\nFAIL: {len(bad)} finding(s). An ignored entry nobody classified, and a "
              f"deletion-bound row measured dirty, are both unexamined or contradicted inputs "
              f"under a verdict that authorises deleting a directory.")
        return 1
    print(f"\nIGNORED ACCOUNTED OK — for {os.path.basename(verd)}: every deletion-bound row "
          f"is clean on disk, and every ignored entry under one is attributed by git to a rule "
          f"origin/main declares generated or scratch.")
    return 0


def self_test():
    """Each guarantee must go RED on a violating input, or it is decoration.

    Both arms are shown: the violating input and the clean one, because a check that
    fails on everything is as useless as one that passes on everything.
    """
    import shutil
    repo = repo_of_this_file()
    here = os.path.dirname(os.path.abspath(__file__))
    raw = os.path.join(here, "..", "raw_ignored_entries_shard_c_jharv3.tsv")
    meas = os.path.join(here, "..", "raw_untracked_ignored_shard_c_jharv3.tsv")
    verd = os.path.join(here, "..", "verdicts_shard_c.tsv")
    fails = 0
    with tempfile.TemporaryDirectory() as tmp:
        def copy(name, src):
            dst = os.path.join(tmp, name)
            shutil.copy(src, dst)
            return dst

        def run_gate(r, m, v):
            from io import StringIO
            buf, old = StringIO(), sys.stdout
            sys.stdout = buf
            try:
                rc = main(["--repo", repo, "--raw", r, "--measured", m, "--verdicts", v])
            finally:
                sys.stdout = old
            return rc, buf.getvalue()

        r0, m0, v0 = copy("r.tsv", raw), copy("m.tsv", meas), copy("v.tsv", verd)
        rc, out = run_gate(r0, m0, v0)
        print(f"[clean arm] rc={rc} (expect 0)")
        if rc != 0:
            fails += 1
            print(out)

        # G1: an ignored entry in an undeclared class
        r1 = copy("r1.tsv", raw)
        with open(r1, "a") as fh:
            fh.write("108\t/home/reyerchu/wt-main62\tsimv\t1\t10\n")
        rc, out = run_gate(r1, m0, v0)
        red = rc != 0 and "UNDECLARED CLASS" in out
        print(f"[G1 undeclared class] rc={rc} caught={red}")
        fails += 0 if red else 1

        # G2: an entry main does not ignore at all
        r2 = copy("r2.tsv", raw)
        with open(r2, "a") as fh:
            fh.write("108\t/home/reyerchu/wt-main62\tREADME.md\t1\t10\n")
        rc, out = run_gate(r2, m0, v0)
        red = rc != 0 and "NO RULE MATCHES" in out
        print(f"[G2 not actually ignored] rc={rc} caught={red}")
        fails += 0 if red else 1

        # G3: a deletion-bound row with no measurement
        m3 = copy("m3.tsv", meas)
        keep = [l for l in open(m3) if "/home/reyerchu/wt-main62" not in l]
        open(m3, "w").writelines(keep)
        rc, out = run_gate(r0, m3, v0)
        red = rc != 0 and "UNMEASURED" in out
        print(f"[G3 unmeasured deletion-bound row] rc={rc} caught={red}")
        fails += 0 if red else 1

        # G4: a measured deletion-bound row that is dirty
        m4 = copy("m4.tsv", meas)
        lines = open(m4).read().splitlines(True)
        for i, l in enumerate(lines):
            f = l.rstrip("\n").split("\t")
            if len(f) > 8 and f[1] == "/home/reyerchu/wt-main62":
                f[7] = "1"
                lines[i] = "\t".join(f) + "\n"
        open(m4, "w").writelines(lines)
        rc, out = run_gate(r0, m4, v0)
        red = rc != 0 and "DIRTY deletion-bound row" in out
        print(f"[G4 dirty deletion-bound row] rc={rc} caught={red}")
        fails += 0 if red else 1

        # G5: the declared table drifting from main
        saved = dict(DECLARED)
        DECLARED["this-rule-is-not-on-main/"] = "invented"
        rc, out = run_gate(r0, m0, v0)
        red = rc != 0 and "DECLARED RULE GONE" in out
        DECLARED.clear(); DECLARED.update(saved)
        print(f"[G5 stale table] rc={rc} caught={red}")
        fails += 0 if red else 1

    print(f"\nself-test: {5 - fails} of 5 guarantees proven load-bearing"
          if fails == 0 else f"\nSELF-TEST FAILED: {fails} guarantee(s) not load-bearing")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(main())
