# SYNTHESIZED MATRIX FIXTURE — not a real run artefact (vibe-ic#1028)
Declared by matrix_d3_output_manifest.json as 'phase2/stage2/constraints/spm.sdc' (1049 B in the withdrawn cell). Generated by matrix_corpus_gen.py; the content is representative of the artefact's KIND, never a copy of the withdrawn bytes.
create_clock -name clk -period 10.0 [get_ports clk]
