# Bucket A — program-rule sketches for programs/absence_verdict_names_its_search_space_check.py
# Corpus-sweep REQUIRED before merging into programs/absence_verdict_names_its_search_space_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A step refuses a thing the distribution DOES declare, in a view the step never opened, and the refusal reads as thorough because it carries a count over the one view it did open. Every part of the count is measured and true. A reader cannot tell 'I looked in the two places this is declared and it is in neither' from 'I looked in one of them', because both print the same sentence and only one of them is a finding about the input. The defect survives review precisely because the disclosure looks complete: a denominator is present, so the usual question -- did this examine anything? -- has already been answered yes.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_absence_verdict_names_the_search_space_it_exhausted(sample_text, ports):
    """Every absence-class refusal must carry an ADDRESS: something that tells the reader where the program looked. The repo already asks a PASS to disclose how much it examined; this asks the same question of a REFUSAL, which is the half that was open. An address is a filesystem path, a glob, an environment reference, or a document pointer -- an address is an address whether or not it has a slash in it. What the rule cannot decide from source alone is whether the address is COMPLETE, because completeness is a property of the distribution and not of our code; that half needs the artefact to record which view each resolved value came from, and it is named as out of reach rather than pretended away."""
    # Expected signal: ERROR
    # Suggested fix action: Parse every module under the programs tree and collect each refusal CONSTRUCTION whose rule id matches the repo's own absence convention. Require an address among the refusal's companions, resolving one level of local binding (a reason built from the path one line above) and one level of enclosing call (a refusal nested inside the report that carries the paths). Exclude lookups, which are not refusals, and exclude test fixtures, which are deliberately minimal. Report file, line and rule id for each refusal that names nowhere. Answer NOT CHECKED, never PASS, when the directory is absent or the population is empty. MEASURED: the predicate was narrowed four times, each narrowing removing a real false positive rather than a hypothetical one; the surviving population is 31 absence verdicts over 1277 files, and the two genuine findings were fixed by ADDING information -- one refusal now names the file and the four variables it found empty, the other names the character window it searched and its size, so a zero-length window can no longer read as an absent row.
    return []  # list of findings — TODO implement
