// SYNTHESIZED MATRIX FIXTURE — not a real run artefact (vibe-ic#1028)
Declared by matrix_d3_output_manifest.json as 'phase2/stage2/synth/post_dft_netlist.v' (39179 B in the withdrawn cell). Generated by matrix_corpus_gen.py; the content is representative of the artefact's KIND, never a copy of the withdrawn bytes.
module fixture_representative (input wire clk);
endmodule
