"""`program inventory fresh` — a program lands and the inventory is not re-run.

THE MUTATION IS THE MEASURED DEFECT ITSELF, from this repository and dated.
`5555901e0` ("fix(benchmark): preserve the final reviewed RTL bundle") added
`programs/rtl_final_bundle_integrity.py`. It regenerated one of the two derived
inventories over that population and left the other behind, and the drift then
survived four landings (v1.15.77 through .80). The shape is exactly this: a new
top-level program on disk, a committed `PROGRAM_INVENTORY.json` that still
states the count from before it, and two files that are byte-identical to a
reader whether they agree or not.

BOTH ARMS HAVE THE SAME DENOMINATOR, and here that is the whole design. The
cheap ways to redden this gate — delete the artefact, or hand it a directory
with no programs at all — prove nothing about the predicate: a missing artefact
is its own separate refusal ("run without --check to generate"), and an
unreadable programs directory is rc 2 NOT CHECKED. So both arms carry the SAME
three synthetic programs and a committed artefact that is present, well-formed
and generated by the shipped generator itself. What moves is one program on
disk that the committed artefact was never told about.

THE ARTEFACT IS GENERATED, NOT TYPED. `can_pass` runs the shipped generator
once over the synthetic tree, so the accepted arm is correct by construction
rather than by my having transcribed a population table correctly. A fixture
that hand-writes the artefact tests the transcription; this one tests the gate.

THE SUBJECT IS A REPOSITORY, AND THE FIRST VERSION OF THIS FIXTURE WAS WRONG
ABOUT THAT. The generator enumerates from the TRACKED set — `git ls-files -z`
against the plugin directory — and falls back to a filesystem walk only when
there is no repository. A fixture built as a bare directory therefore proves
the gate on the FALLBACK path, which the landing invocation never takes. It was
not a theoretical difference: the same negative control run against the real
tree with the new program merely WRITTEN returned rc 0 and the line "OK:
committed PROGRAM_INVENTORY.json matches the tree", a green over a program the
enumeration could not see. Both arms are committed repositories here, and the
late program is COMMITTED too, so what the gate reads is what a landing leaves.

WHY THIS FIXTURE SUPPLIES THE EXECUTABLE
========================================
The dispatcher declares this gate as

    run "program inventory fresh" "$ROOT" \
        python3 "$ROOT/vibe-ic-marketplace/plugins/vibe-ic/programs/gen_program_inventory.py" \
        --check-artifact

The program resolves its own subject as `Path(__file__).resolve().parent`, so
the declaration reaches the subject only by naming the SUBJECT'S copy — that is
the argv the dispatcher really runs, and pointing `$ROOT` at a fixture tree is
therefore how this gate's input is chosen. The shipped program is COPIED OUT OF
THE REAL TREE AT RUN TIME, byte for byte, never stubbed and never vendored into
this directory: the bytes executed are the bytes that land, and a copy kept here
could drift from the program while both arms stayed green.

It imports nothing private — argparse, hashlib, json, os, re, subprocess, sys,
pathlib — so it is one file and not a set.

chip-AGNOSTIC: three invented program names, no IC, vendor, PDK or process.
"""
from pathlib import Path
import shutil
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import gate_mutation_fixtures as F  # noqa: E402

GATE = "program inventory fresh"

#: The gate's own code, taken from the tree under test at run time.
_SHIPPED = ("gen_program_inventory.py",)

#: Invented names. They must not collide with real programs, because the point
#: is that the gate reads THIS tree and not the repository's own. `_check`
#: suffixes because the generator counts a `gate_programs_check_suffix`
#: population, and a fixture whose programs fall outside every population would
#: move no number when one is added.
_PROGRAMS = ("alpha_probe_check", "beta_probe_check", "gamma_probe_check")

#: The one the committed artefact is never told about.
_LATE = "delta_probe_check"

#: The relative home of the plugin inside a repository checkout. Spelled out
#: because the declaration spells it out: the gate is found at this path under
#: `$ROOT` and nowhere else.
_PLUGIN_REL = Path("vibe-ic-marketplace") / "plugins" / "vibe-ic" / "programs"


def _program(name: str) -> str:
    return ('#!/usr/bin/env python3\n'
            f'"""{name} — synthetic fixture program, not a real gate."""\n')


def _tree(work: Path, leaf: str, late: bool) -> Path:
    root = F.git_init(work / leaf)
    programs = root / _PLUGIN_REL
    programs.mkdir(parents=True)
    for name in _SHIPPED:
        shutil.copy2(F.PROGRAMS / name, programs / name)
    for name in _PROGRAMS:
        (programs / f"{name}.py").write_text(_program(name), encoding="utf-8")
    # TRACKED BEFORE MEASURED. The generator enumerates `git ls-files`, so a
    # generation run before the first commit would record a population of zero
    # and the accepted arm would then be rejected by its own artefact.
    F.git_commit(root, "the tree the inventory is generated from")

    # GENERATE the artefact from this tree, with the shipped generator, so the
    # accepted arm is correct by construction.
    #
    # `--artifact-only` and not a bare run: a bare run ALSO rewrites the stated
    # counts in the two bound READMEs, which this tree does not carry, and it
    # exits 2 having already written the artefact — a fixture that ignored that
    # rc would be building on a step it had not checked, and one that demanded
    # rc 0 from it would fail for a reason that is not the gate's. The flag's
    # documented contract is exactly this one path.
    #
    # `-B` because the run must not leave bytecode in a tree the gate is about
    # to enumerate.
    subprocess.run(
        [sys.executable, "-B", str(programs / "gen_program_inventory.py"),
         "--artifact-only"],
        cwd=str(root), check=True,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    # The arm is worthless if the artefact was not written, and a fixture that
    # discovers that as "the gate refused" would blame the gate.
    if not (programs / "PROGRAM_INVENTORY.json").is_file():
        raise RuntimeError(
            "fixture could not build its subject: the shipped generator wrote "
            f"no PROGRAM_INVENTORY.json under {programs}")
    F.git_commit(root, "commit the derived inventory")

    if late:
        # The landing that adds a program and does not re-run the generator.
        # AFTER the artefact is written and committed, which is the whole
        # point: nothing is missing and nothing is malformed, the committed
        # count is simply one behind the tree. COMMITTED, because the
        # enumeration is `git ls-files` and an untracked file moves no
        # population — see the docstring.
        (programs / f"{_LATE}.py").write_text(_program(_LATE), encoding="utf-8")
        F.git_commit(root, "a program lands; nothing regenerates the inventory")
    return root


def can_pass(work: Path) -> Path:
    """Three programs on disk, and the committed artefact counts three: rc 0."""
    return _tree(work, "accepted", late=False)


def can_fail(work: Path):
    """A fourth program on disk that the artefact was never regenerated for —
    the same tree, one population behind. Same denominator, opposite answer."""
    return _tree(work, "refused", late=True), "is stale — committed 3, tree 4"
