#!/usr/bin/env python3
"""
agent_report_sha256_attestation_check.py — verify the project's
final report attests every canonical chip / FPGA artefact with a
SHA256 hash.

Per the v1.6.30 anti-fabrication doctrine (rule #5):

    Final report carries a SHA256 attestation table of every
    canonical artefact (SOF / GDS / synth-netlist / LEF / Liberty /
    sign-off reports). Without that table, "PASS" is unverifiable
    and counts as incomplete.

`agent_report_presence_check` (v1.6.24) already enforces that the
report exists and carries the 5 mandatory sections; this gate adds
the next layer — that the **content** of the report carries
verifiable SHA256 attestations of the deliverables.

Report-file lookup (v1.6.34)
---------------------------
The gate inspects up to TWO canonical report files (whichever
exists; both are accepted, and hashes from either count):

  1. `<project>/reports/final_summary.md` — auto-generated by
     `final_report_generate.py`, wired into all 5 one-shot runners
     since v1.6.32. Contains the SHA-256 Attestation table since
     v1.6.34.
  2. `<project>/AGENT_REPORT.md` — hand-authored by an agent that
     does not run the canonical generator. Allowed for
     back-compatibility and ad-hoc workflows.

If both exist, declared hashes from either file count toward
attestation. If neither exists, the gate emits VACUOUS_PASS — the
presence requirement is owned by `agent_report_presence_check`.

Failure modes (chip-AGNOSTIC):

1. NO_ATTESTATION_TABLE — AGENT_REPORT.md exists but contains zero
   `sha256:<64-hex>` tokens. The report is unverifiable.

2. MISSING_ATTESTATION — a canonical artefact exists on disk but
   its on-disk-computed SHA256 does NOT appear anywhere in
   AGENT_REPORT.md. The report omits attestation for an artefact
   the project actually produced.

   Canonical artefact globs (chip-AGNOSTIC, no chip-specific names):
     phase2/stage1/fpga/output_files/*.sof          (FPGA bitstream)
     phase3/stage4/gds/*.gds                         (chip GDS)
     phase3/stage4/foundry_handoff/**/*.gds          (mask GDS)
     phase2/stage2/synth/*.v                        (synth netlist)
     phase3/stage3/pnr/*.v                           (PnR netlist)
     phase3/stage4/foundry_handoff/**/*.lef          (LEF)
     phase3/stage4/foundry_handoff/**/*.lib          (Liberty)
     phase3/analog/hardmacro/**/*.lef                (analog LEF)
     phase3/analog/hardmacro/**/*.lib                (analog Liberty)

VACUOUS_PASS conditions:
* AGENT_REPORT.md missing — `agent_report_presence_check` handles
  that as FAIL; this gate stays out of the way and emits VACUOUS.
* No canonical artefacts exist on disk — pre-output project,
  attestation gate inapplicable.

Usage:
    python3 agent_report_sha256_attestation_check.py <project_dir>
                                                      [--json <out>]

Exit codes:
    0  PASS / VACUOUS_PASS
    1  no attestation table OR canonical artefact lacks attestation
    2  argument or I/O error

chip-AGNOSTIC. No vendor / IC / specific filename hardcoded.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional, Set, Tuple


_RE_SHA256_TOKEN = re.compile(r"sha256:([0-9a-fA-F]{64})", re.IGNORECASE)


# Canonical artefact glob set. Order is presentation-stable; gate
# walks each pattern and aggregates findings. Each pattern is
# rooted at the project tree.
_CANONICAL_ARTEFACT_GLOBS: Tuple[Tuple[str, str], ...] = (
    ("FPGA SOF",       "phase2/stage1/fpga/output_files/*.sof"),
    ("chip GDS",       "phase3/stage4/gds/*.gds"),
    ("foundry GDS",    "phase3/stage4/foundry_handoff/**/*.gds"),
    ("synth netlist",  "phase2/stage2/synth/*.v"),
    ("PnR netlist",    "phase3/stage3/pnr/*.v"),
    ("foundry LEF",    "phase3/stage4/foundry_handoff/**/*.lef"),
    ("foundry Liberty","phase3/stage4/foundry_handoff/**/*.lib"),
    # Canonical analog hardmacro location is phase3/analog/hardmacro/
    # per _path_layout.phase3_hardmacro_dir; the entries below glob that
    # canonical path for the attestation chain.
    ("analog LEF",     "phase3/analog/hardmacro/**/*.lef"),
    ("analog Liberty", "phase3/analog/hardmacro/**/*.lib"),
)


@dataclass
class AttestationFinding:
    rule: str
    artefact_kind: str
    rel_path: str
    expected_sha256: str
    detail: str = ""


def _sha256_of_file(path: Path) -> Optional[str]:
    """Compute lowercase hex SHA256 of `path`. Returns None on read
    failure (broken symlink, permission denied)."""
    h = hashlib.sha256()
    try:
        with path.open("rb") as f:
            while True:
                buf = f.read(1 << 20)  # 1 MiB chunks
                if not buf:
                    break
                h.update(buf)
    except OSError:
        return None
    return h.hexdigest()


def _extracted_hashes(text: str) -> Set[str]:
    """Lower-case hex SHA256 tokens declared anywhere in `text`."""
    return {m.group(1).lower() for m in _RE_SHA256_TOKEN.finditer(text)}


def _collect_canonical_artefacts(project: Path
                                 ) -> List[Tuple[str, Path]]:
    """Return (kind, path) for every canonical artefact present on
    disk. Symlinks are resolved before SHA256 (matches the
    provenance gate's behaviour)."""
    out: List[Tuple[str, Path]] = []
    for kind, pattern in _CANONICAL_ARTEFACT_GLOBS:
        for p in sorted(project.glob(pattern)):
            if p.is_file():
                out.append((kind, p))
    return out


_REPORT_CANDIDATE_REL_PATHS: Tuple[str, ...] = (
    "reports/final_summary.md",   # v1.6.32 canonical (auto-generated)
    "AGENT_REPORT.md",            # back-compat hand-authored alternative
)


def _resolve_report_files(project: Path) -> List[Path]:
    """Return every canonical report file that exists on disk, in
    declaration order. v1.6.34 widened the lookup from 1→2 candidates
    so the v1.6.32 auto-generator and the legacy hand-authored
    convention are both accepted."""
    out: List[Path] = []
    for rel in _REPORT_CANDIDATE_REL_PATHS:
        p = project / rel
        if p.is_file():
            out.append(p)
    return out


def audit(project: Path) -> Tuple[str, List[AttestationFinding]]:
    report_files = _resolve_report_files(project)
    if not report_files:
        # No report file at any canonical location. Presence gate owns
        # this failure mode; we stay out of the way and emit VACUOUS.
        return "VACUOUS_PASS", []

    artefacts = _collect_canonical_artefacts(project)
    if not artefacts:
        # Pre-output project; nothing to attest.
        return "VACUOUS_PASS", []

    declared: Set[str] = set()
    for rp in report_files:
        text = rp.read_text(encoding="utf-8", errors="replace")
        declared |= _extracted_hashes(text)

    findings: List[AttestationFinding] = []

    if not declared:
        # NO attestation hashes at all across either report file.
        report_paths_str = " / ".join(
            str(rp.relative_to(project)) for rp in report_files)
        findings.append(AttestationFinding(
            rule="NO_ATTESTATION_TABLE",
            artefact_kind="-",
            rel_path=report_paths_str,
            expected_sha256="-",
            detail=(f"{report_paths_str} contains zero sha256:<64hex> "
                    "tokens but project ships "
                    f"{len(artefacts)} canonical artefact(s) — final "
                    "report is unverifiable.")))
        return "FAIL", findings

    for kind, path in artefacts:
        actual = _sha256_of_file(path)
        if actual is None:
            findings.append(AttestationFinding(
                rule="ARTEFACT_UNREADABLE",
                artefact_kind=kind,
                rel_path=str(path.relative_to(project)),
                expected_sha256="-",
                detail="artefact file present but unreadable "
                       "(broken symlink / permission denied)"))
            continue
        if actual not in declared:
            findings.append(AttestationFinding(
                rule="MISSING_ATTESTATION",
                artefact_kind=kind,
                rel_path=str(path.relative_to(project)),
                expected_sha256=f"sha256:{actual}",
                detail=("artefact present on disk but its sha256 is "
                        "not declared in any of the canonical report "
                        "files (reports/final_summary.md / "
                        "AGENT_REPORT.md)")))

    return ("FAIL" if findings else "PASS"), findings


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Verify AGENT_REPORT.md attests canonical "
                    "artefacts with SHA256.")
    ap.add_argument("project_dir")
    ap.add_argument("--json", help="write JSON report to this path")
    args = ap.parse_args(argv)

    project = Path(args.project_dir).resolve()
    if not project.is_dir():
        print(f"error: project dir not found: {project}", file=sys.stderr)
        return 2

    verdict, findings = audit(project)

    artefacts = _collect_canonical_artefacts(project)
    report = {
        "gate": "agent_report_sha256_attestation_check",
        "verdict": verdict,
        "project": str(project),
        "canonical_artefacts_found": len(artefacts),
        "findings_count": len(findings),
        "findings": [asdict(f) for f in findings],
    }
    if verdict == "VACUOUS_PASS":
        if not _resolve_report_files(project):
            report["reason"] = ("no canonical report file at "
                                + " / ".join(_REPORT_CANDIDATE_REL_PATHS)
                                + "; agent_report_presence_check owns "
                                "that failure mode.")
        else:
            report["reason"] = ("no canonical artefacts on disk; "
                                "pre-output project.")

    if args.json:
        out = Path(args.json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2) + "\n")

    if verdict == "VACUOUS_PASS":
        print(f"VACUOUS_PASS: {report['reason']}")
        return 0
    if verdict == "PASS":
        rep = _resolve_report_files(project)
        rep_str = " / ".join(str(p.relative_to(project)) for p in rep)
        print(f"PASS: {len(artefacts)} canonical artefact(s) all "
              f"attested in {rep_str}")
        return 0
    print(f"FAIL: {len(findings)} attestation gap(s):", file=sys.stderr)
    for f in findings[:10]:
        print(f"  [{f.rule}] {f.artefact_kind} ({f.rel_path}): "
              f"{f.detail}", file=sys.stderr)
    if len(findings) > 10:
        print(f"  … and {len(findings) - 10} more", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
