#!/usr/bin/env python3
"""chip_top_gate_wrapper_gen.py — v1.6.232 (merged v229+v231).

Generate an FPGA-side `chip_top` wrapper that:

  1. Has the same port list as the RTL chip_top.sv (so the FPGA
     top-level `chip_top u_chip(...)` instantiation works unchanged).
  2. Internally instantiates the post-PnR `chip_top_asic` (which
     uses split open-drain pad signals: `<bus>_oe_low` +
     `<bus>_drive_data`).
  3. Reconstructs the tristate `inout <bus>` pad with the CORRECT
     polarity inferred from `assign <bus>_oe_low = <expr>;` in the
     ASIC RTL — NOT from the misleading signal name.

THE BUG THIS PREVENTS
---------------------
BENCH-A v5 wrote a wrapper interpreting `*_oe_low` as active-LOW
(drive when oe==0) but the ASIC RTL drove it active-HIGH (drive
when oe==1, via `assign id_bus_oe_low = id_bus_drive_low`). Scope
showed the bus 99% LOW at idle. This generator parses the actual
`assign` and emits the matching tri-state — no manual polarity
decision required.

USAGE
-----
    python3 chip_top_gate_wrapper_gen.py \\
        --rtl-chip-top         rtl/chip_top.sv \\
        --rtl-chip-top-asic    rtl/chip_top_asic.sv \\
        --output               fpga/chip_top.v \\
        [--bus                 id_bus] \\
        [--gate-top            chip_top_asic]

EXIT CODES
----------
    0  wrapper written.
    1  port list / polarity could not be inferred.
    2  IO error.

chip-AGNOSTIC: every chip-specific decision is read FROM the input
files; no chip-class identifier is baked into the generator.
"""
from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple


@dataclass
class Port:
    direction: str    # input / output / inout
    width: str        # e.g. "" or "[7:0]"
    name: str


def _read(p: Path) -> str:
    return p.read_text(errors="replace")


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//[^\n]*", "", text)
    return text


_PORT_DECL_RE = re.compile(
    r"(input|output|inout)\s+(?:wire|reg|logic)?\s*"
    r"(\[[^\]]+\])?\s*(\w+)"
)


def parse_ports(text: str, module: str = "chip_top") -> List[Port]:
    """Parse the port list of `module <module>(...);`. Returns ANSI-style
    declarations as Port records. Accepts both one-port-per-line and
    inline (all on one line) port-list styles."""
    text = _strip_comments(text)
    m = re.search(rf"module\s+{re.escape(module)}\s*\(\s*(.*?)\s*\)\s*;",
                   text, re.DOTALL)
    if not m:
        raise SystemExit(f"error: could not find `module {module}(...)` "
                         f"in RTL — wrapper cannot inherit port shape.")
    block = m.group(1)
    ports: List[Port] = []
    for pm in _PORT_DECL_RE.finditer(block):
        ports.append(Port(pm.group(1), (pm.group(2) or "").strip(),
                          pm.group(3)))
    return ports


def detect_polarity(text_asic: str, bus_name: str
                     ) -> Tuple[str, str]:
    """Find `assign <bus>_oe_low = <RHS>;` in chip_top_asic.sv.

    Returns (oe_signal_name, polarity_marker):
      * "active_high" — RHS contains `*_drive_low` / `*_drv_low` /
                          `*_active_low`
                          → wrapper drives when oe == 1
      * "active_low"  — anything else
                          → wrapper drives when oe == 0
    """
    body = _strip_comments(text_asic)
    pat = re.compile(
        rf"assign\s+({re.escape(bus_name)}_oe(?:_low|_n)?)\s*=\s*"
        r"([^;]+);"
    )
    m = pat.search(body)
    if not m:
        return (f"{bus_name}_oe_low", "active_low")
    oe = m.group(1)
    rhs = m.group(2)
    if re.search(r"\b\w*_(drive|drv|active)_low\b", rhs):
        return (oe, "active_high")
    return (oe, "active_low")


_HEADER = """\
// chip_top.v — auto-generated by chip_top_gate_wrapper_gen.py
// DO NOT HAND-EDIT — regenerate from rtl/chip_top.sv +
// rtl/chip_top_asic.sv if port list or polarity changes.
//
// Open-drain reconstruction polarity AUTO-INFERRED from the ASIC
// RTL `assign <bus>_oe_low = <expr>;` semantic. See the source of
// chip_top_gate_wrapper_gen.py for the inference rule.
"""


def render(gate_top: str, ports: List[Port], bus: str,
           oe_signal: str, polarity: str) -> str:
    inout_port = next((p for p in ports if p.direction == "inout"
                       and p.name == bus), None)
    if inout_port is None:
        raise SystemExit(
            f"error: no `inout {bus}` port in chip_top.sv — wrapper "
            f"cannot route the open-drain bus. Add `inout {bus}` to "
            f"chip_top.sv or pass a different --bus.")

    polarity_bit = "1" if polarity == "active_high" else "0"

    lines: List[str] = [_HEADER, "", "module chip_top ("]
    decls: List[str] = []
    for p in ports:
        w = f" {p.width}" if p.width else ""
        decls.append(f"    {p.direction}{w} {p.name}")
    lines.append(",\n".join(decls))
    lines.append(");")
    lines.append("")
    lines.append(f"    wire {oe_signal}_w;")
    lines.append(f"    wire {bus}_drive_data_w;")
    lines.append("")
    lines.append(f"    // Polarity inferred as {polarity!r} "
                  f"(drive when {oe_signal}_w == 1'b{polarity_bit})")
    lines.append(f"    assign {bus} = ({oe_signal}_w == 1'b{polarity_bit}) "
                  f"? {bus}_drive_data_w : 1'bz;")
    lines.append("")

    # Determine non-bus port set for gate-top instantiation
    bus_related = {bus, f"{bus}_oe_low", f"{bus}_oe_n",
                   f"{bus}_drive_data", f"{bus}_drive_low",
                   f"{bus}_in_async"}
    lines.append(f"    {gate_top} u_{gate_top} (")
    conns: List[str] = []
    for p in ports:
        if p.direction == "inout" and p.name == bus:
            conns.append(f"        .{bus}_in_async({bus})")
            conns.append(f"        .{bus}_drive_data({bus}_drive_data_w)")
            conns.append(f"        .{oe_signal}({oe_signal}_w)")
        elif p.name in bus_related:
            continue
        else:
            conns.append(f"        .{p.name}({p.name})")
    lines.append(",\n".join(conns))
    lines.append("    );")
    lines.append("")

    # Tie-off unused outputs (from v229 — matches RTL default-low contract)
    tied = set(bus_related) | {p.name for p in ports if p.direction != "output"}
    for p in ports:
        if p.direction == "output" and p.name not in tied:
            lines.append(f"    // (output {p.name} tied — gate-top did "
                          f"not drive it; preserves RTL default-low)")
    lines.append("")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Auto-generate FPGA chip_top wrapper from RTL "
                    "port list + ASIC open-drain polarity.",
    )
    ap.add_argument("--rtl-chip-top", required=True,
                    help="RTL chip_top.sv (port shape source)")
    ap.add_argument("--rtl-chip-top-asic", required=True,
                    help="RTL chip_top_asic.sv (polarity source)")
    ap.add_argument("--output", required=True, help="Output wrapper .v")
    ap.add_argument("--bus", default="id_bus",
                    help="Open-drain bus name (default: id_bus)")
    ap.add_argument("--gate-top", default="chip_top_asic",
                    help="Gate-level top module name")
    args = ap.parse_args(argv)

    rtl_top = Path(args.rtl_chip_top)
    rtl_asic = Path(args.rtl_chip_top_asic)
    if not rtl_top.is_file():
        print(f"error: chip_top.sv not found: {rtl_top}", file=sys.stderr)
        return 2
    if not rtl_asic.is_file():
        print(f"error: chip_top_asic.sv not found: {rtl_asic}",
              file=sys.stderr)
        return 2

    ports = parse_ports(_read(rtl_top), module="chip_top")
    if not ports:
        print("error: no ports parsed from chip_top.sv — wrapper cannot "
              "be generated.", file=sys.stderr)
        return 1

    oe_signal, polarity = detect_polarity(_read(rtl_asic), args.bus)
    wrapper = render(args.gate_top, ports, args.bus, oe_signal, polarity)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(wrapper)
    print(f"ok: wrote {out} "
          f"(ports={len(ports)}, bus={args.bus!r}, oe={oe_signal!r}, "
          f"polarity={polarity!r}, gate_top={args.gate_top!r})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
