#!/usr/bin/env python3
"""enhancement_emit.py — driver for the benchmark-enhancement-capture skill.

Takes a recoveries.json listing (step, design, before-state, after-state,
ai-reasoning, bucket) records and produces concrete artifacts ROUTED PER STEP
via benchmark/CAPTURE_ROUTING.json:
  - markdown fragments appended to the RIGHT skill file per step
    (ic-expert-agent.md for design judgment; sta-review for timing;
     drc-fix for DRC; analog-topology-select for analog; etc.) (Bucket B)
  - python patch sketches targeting the RIGHT program file per step
    (rtl_hygiene_lint.py for RTL hygiene; phase3_one_shot_runner.py for
     PnR; analog_a2_topology_select_check.py for analog A2; etc.) (Bucket A)
  - YAML backlog entries for community/backlogs/ (Bucket C)
  - a discard log for Bucket D entries

The actual program/skill modifications are NEVER applied automatically — this
script just emits candidates for human review (Bucket A) or direct append
(Bucket B / C). Bucket A patches require a corpus-sweep verification before
being merged, per the skill's honesty rule.

recoveries.json schema (v0.1.35+):
  [{
    "step": "phase3.pnr_setup_repair",     # canonical step ID (see CAPTURE_ROUTING.json)
    "design": "sha256",
    "bucket": "A" | "B" | "C" | "D" | "T",
    # Bucket-T (forked-EDA-tool enhancement) fields — REQUIRED when bucket=="T"
    # (owner directive 2026-07-11: a defect GENERATED by a forked OSS EDA tool is
    # fixed IN THAT FORKED TOOL, not band-aided downstream). Enforced by
    # check_bucket_t(). `step` (above) names the GENERATING step -> which tool.
    "tool": "OpenROAD"|"KLayout"|"magic"|"netgen"|"yosys"|"ngspice"|"iverilog"|"verilator",
    "problem": "one precise sentence: the tool's actual vs expected behaviour",
    "golden_sample": "path to expected/good output, or 'none — <why>'",
    "bad_sample": "path to the current bad output (the tool's wrong result)",
    "tool_enhancement": "the concrete fix/guideline in the forked tool "
                        "(function/file + how it must behave to match commercial)",
    # PROGRAM-FIRST gate: Bucket B and C records MUST carry a non-empty
    # `why_not_bucket_a` (one honest sentence: the exact decision a
    # deterministic program could not make). Missing/empty -> emit refuses
    # (exit 1). Bucket A and D do not need it.
    "why_not_bucket_a": "...",
    # Bucket-B (skill section) fields:
    "skill_title": "...",
    "pattern": "...",
    "when": "...",
    "what": "...",
    "example": "...",
    "generality": "...",
    # Bucket-A (program rule) fields:
    "rule_name": "...",
    "docstring": "...",
    "expected_signal": "WARN"|"ERROR"|"AUTO-FIX",
    "fix_action": "...",
    # Bucket-C (backlog) fields:
    "title": "...",
    # `pattern` is REQUIRED for Bucket C too — it is what
    # `backlog_sanitize_check.REQUIRED_FIELDS` demands of the emitted YAML,
    # and `emit_backlog` refuses without it. It states the CLASS of defect in
    # terms that let a reader recognise a DIFFERENT instance: what shape of
    # input meets what shape of handling, and what wrong outcome follows. It
    # is NOT a restatement of `title` and NOT a description of this one
    # symptom. It was previously documented only under Bucket B above, where
    # a backlog author never looks.
    "pattern": "...",
    "suggested_fix": "...",
    "backlog_slug": "...",
    "backlog_type": "bug"|"enhancement",
    "severity": "P0"|"P1"|"P2"|"P3",
    "component": "...",
    "session_context": "...",
    # Bucket-D fields:
    "why_discard": "..."
  }, ...]

Usage:
    python3 enhancement_emit.py --records recoveries.json --out-dir candidates/
"""
from __future__ import annotations
import argparse, json, datetime, sys
from pathlib import Path

ROUTING_FILE = Path(__file__).resolve().parent.parent / "benchmark" / "CAPTURE_ROUTING.json"
PLUGIN_ROOT = Path(__file__).resolve().parent.parent

# The value emitted when the shipped version cannot be READ. It is deliberately
# not a semver: a provenance field nobody measured must be visibly non-data, so
# that it fails the first time anyone sorts or compares by it. A plausible
# semver constant never fails, which is exactly how a stale one survives.
UNRESOLVED_VERSION = "unknown"


def resolved_plugin_version() -> str:
    """The version of the plugin DOING the emitting, READ from the single source
    of truth (``.claude-plugin/plugin.json`` — the same file
    ``gatekeeper_assign_version.py`` writes).

    Every provenance field this module stamps comes from here. It is never
    restated as a literal anywhere in this file: a version that is restated
    stops tracking the thing it names the moment the next release lands, and an
    emitted record then claims a plugin generation it did not come from. That
    failure is silent, plausible, and biased in one direction (always older),
    so no reader can see it.

    Returns ``UNRESOLVED_VERSION`` when the manifest cannot be read.
    """
    try:
        _here = str(Path(__file__).resolve().parent)
        if _here not in sys.path:
            sys.path.insert(0, _here)
        import plugin_manifest_discovery as _pmd
        v = _pmd.read_plugin_version(PLUGIN_ROOT)
    except Exception:
        v = None
    return (str(v).strip() if v else "") or UNRESOLVED_VERSION


def _load_routing() -> dict:
    if not ROUTING_FILE.is_file():
        return {"steps": {}, "default_routing": {
            "bucket_A_program": None,
            "bucket_B_skill_file": "agents/ic-expert-agent.md",
        }}
    return json.loads(ROUTING_FILE.read_text())


def route_for(step: str, routing: dict) -> dict:
    """Return the target paths for a given step ID, with default fallback."""
    return routing.get("steps", {}).get(step, routing.get("default_routing", {}))


def _slug(s: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in s.lower()).strip("-")[:80]


# v0.1.39 (audit Finding 1 fix) — DESIGN_LEAK_PATTERN matches benchmark-design
# identifiers that the honesty rule forbids in Bucket-B skill text:
#   - VerilogEval Prob IDs:  ProbNNN_…  (e.g. Prob089_ece241_2014_q5a)
#   - benchmark family tags: RTLLM, VerilogEval-{v2,Human,Machine}, CVDP, MetRex, …
# When matched, emit_skill_section sanitizes them OUT of the worked-pattern field
# so the captured skill stays general regardless of what the caller passed.
#
# #798 — both boundaries used to be `\b`, and `\b` treats `_` as a WORD
# character, so the family branch fired only on a bare, standalone tag. It
# missed every real benchmark cell id, which embeds the tag in an identifier:
#   `cvdp_copilot_64b66b_encoder_0001`  — `\bCVDP\b` fails on the trailing `_`
#   `base_cvdp_copilot_scrambler_0001`  — and on the leading `_`
# HARVEST DEFINITION for every cell-id cardinal quoted in this file — quote it
# with the definition or not at all, because the same corpus counts differently
# under four defensible ones (126 / 148 / 369 / 391) and none of those is
# "about 100":
#     ids = { m for path in `git ls-files`                      # PATHS ONLY
#             for m in re.findall(
#                 r"cvdp_(?:copilot|agentic)_[A-Za-z0-9_]*?_\d{4}", path) }
# File CONTENTS are deliberately excluded: this commit's own tests add cell-id
# literals, so a contents-inclusive count measures itself and drifts commit to
# commit. Paths-only yields |ids| = 126 on this tree. Measured over those 126:
# the family rule caught 0, and 76 were refused at all — every one of the 76 by
# the 30-char cap alone, and the other 50 accepted outright. Refusal by length
# is an ACCIDENT, not leak detection, and it is the reason narrowing that cap
# looked like a coverage loss. This branch refuses 126 of 126 as family leaks.
# `_` is a SEPARATOR in every identifier convention this repo uses, so the
# boundaries are alphanumeric-only: the tag must not be glued to a letter or a
# digit, but an underscore-delimited segment is exactly how a real leak looks.
# The `ProbNNN` branch already carried the identifier tail; it gets the same
# leading boundary so `base_Prob089_…` is caught like `Prob089_…`.
#
# The tail is NOT open-ended, because a family tag also legitimately prefixes
# this plugin's own thin benchmark IO/scorer adapters. The open-benchmark
# doctrine permits benchmark prefixes only at those record-format boundaries.
# Refusing those would just re-create the false-positive class this issue is
# about. What separates a DATASET IDENTIFIER from an adapter is that the
# dataset numbers things: a cell carries a 4-digit ordinal
# (`cvdp_copilot_scrambler_0001`), a release carries a dotted version
# (`cvdp_v1.1.0_nonagentic_….jsonl`). Requiring THREE digits anywhere in the
# tail admits both and still excludes thin adapter symbols such as
# `cvdp_complete_extract.py` and `rtllm_iface_recover.py`, which carry no
# numbered dataset cell identity. A bare standalone tag is refused on its own.
_TAG_L = r"(?<![A-Za-z0-9])"                # not glued to a letter/digit left
_TAG = (r"(?:RTLLM|VerilogEval(?:-(?:v[12]|Human|Machine))?|CVDP|MetRex"
        r"|ResBench|RTL-Repo|PyHDL-Eval)")
#: dataset tail: any identifier/version run carrying >= 3 digit characters.
_TAG_TAIL = r"_(?:[A-Za-z0-9_.\-]*\d){3}[A-Za-z0-9_.\-]*"
_DESIGN_LEAK_PATTERN = (
    _TAG_L + r"Prob\d+[A-Za-z0-9_]*"                    # ProbNNN_xxx
    + r"|" + _TAG_L + _TAG + _TAG_TAIL                  # cvdp_copilot_…_0001
                                                        # cvdp_v1.1.0_….jsonl
    + r"|" + r"\b" + _TAG + r"\b"                       # the bare family tag
)
import re as _leak_re  # local alias to avoid clobbering caller's `re` if any


def _scrub_design_leak(text: str) -> str:
    """Strip benchmark-design-identifier leaks from free-text fields.

    Layered strategy (each layer catches what the prior one missed):

      Layer 1 — known-leak parentheticals. Drop ONLY brackets whose lead-in
        is an attribution keyword AND whose contents look like an
        identifier (or an enumerated benchmark token). This preserves
        legitimate spec text like "(e.g. mod-256)" / "(per IEEE 1364)"
        that doesn't contain identifiers. The narrower rule was added in
        v0.1.40 after the v0.1.39 broad-strip damaged technical content
        (re-audit NEW-4 fix).

      Layer 2 — enumerated benchmark-identifier tokens (ProbNNN_…, RTLLM,
        VerilogEval-{v2,Human,Machine,…}, CVDP, MetRex, ResBench,
        RTL-Repo, PyHDL-Eval) anywhere they appear.

      Layer 3 — design-name shapes that aren't in any enumeration. Strict
        heuristic: an identifier of >=2 underscore-separated lowercase
        tokens (e.g. radix2_div, sequence_detector, freq_divbyeven,
        adder_pipe_64bit) appearing in `(from X)` / `(captured by X)` /
        `(refs X)` / `worked example: X:` contexts. Added in v0.1.40 —
        catches design leaf names that no enumeration can list. Outside
        attribution contexts, snake_case identifiers are technical RTL
        signal/module names that should NOT be touched.

    Honest about scrubbing — appends an `[anonymized]` marker so the reader
    can see the sanitisation happened. chip-AGNOSTIC.
    """
    if not text:
        return text
    original = text
    # Layer 1 — narrow attribution-bracket strip. v0.1.40 (re-audit NEW-4)
    # requires the bracket interior to look like an identifier list (alphanum
    # + `_` + commas + whitespace + Prob-or-bench token) so legitimate spec
    # parentheticals like "(per IEEE 1364)" and "(e.g. mod-256)" survive.
    # Identifier-shape: contains at least one token matching either an
    # enumerated bench token OR a 2+-underscore-separated identifier.
    _ATTR_LEAD = r"(?:from|captured\s+by|worked\s+(?:miss|example))\s+"
    _IDENT_INSIDE = (r"[A-Za-z0-9_,\s\-]*"
                     r"(?:" + _DESIGN_LEAK_PATTERN +
                     r"|[a-z][a-z0-9]*(?:_[a-z0-9]+){1,})"
                     r"[A-Za-z0-9_,\s\-]*")
    text = _leak_re.sub(
        r"\(\s*" + _ATTR_LEAD + _IDENT_INSIDE + r"\)",
        "", text, flags=_leak_re.IGNORECASE)
    # Layer 2 — enumerated tokens anywhere outside (…).
    text = _leak_re.sub(_DESIGN_LEAK_PATTERN, "", text, flags=_leak_re.IGNORECASE)
    # Layer 3 — design leaf names in `Worked example:` / `Refs:` style prose
    # (no parenthesis). Only fires in explicit attribution contexts.
    text = _leak_re.sub(
        r"(?i)(worked\s+(?:miss|example)|refs?)\s*[:\-]\s*[a-z][a-z0-9_]*(?:_[a-z0-9]+){1,}",
        r"\1: [anonymized]", text)
    text = _leak_re.sub(r"\s{2,}", " ", text)
    text = _leak_re.sub(r"\s+([,.;:])", r"\1", text)
    text = text.strip()
    if text != original:
        text += "  [identifiers anonymized per benchmark-enhancement-capture honesty rule]"
    return text


import unicodedata as _ucd


def _normalize_text(text: str) -> str:
    """v0.1.43 (Round-5 R5-2 fix) — Unicode normalization.

    The v0.1.42 regex used Python's default Unicode-aware `\\w`, which means:
      - Fullwidth underscore U+FF3F doesn't match ASCII `_` → snake_case rule misses
      - Cyrillic `а`/`о` (look like ASCII a/o) are `\\w` chars → break `\\b` word
        boundaries → ProbNNN scanner misses `рrоb089`

    Fix: NFKC-normalize so fullwidth/compatibility characters fold to ASCII;
    refuse mixed-script tokens (a token containing both Latin AND Cyrillic
    characters is a homoglyph attack — no legitimate IC text mixes scripts).
    """
    # NFKC: fullwidth ＿ → ASCII _, fullwidth digits → ASCII digits, etc.
    n = _ucd.normalize("NFKC", text)
    # Detect mixed-script identifiers (≥1 Latin letter AND ≥1 non-Latin letter
    # in the SAME word). Greek/math letters are intentionally allowed
    # (ΔΣ topology titles); but a single token mixing Latin + Cyrillic is
    # never legitimate skill prose. Refuse here so the structural regex
    # doesn't have to deal with it.
    for m in _leak_re.finditer(r"\w{2,}", n, _leak_re.UNICODE):
        tok = m.group()
        has_latin = any("LATIN" in _ucd.name(c, "") for c in tok if c.isalpha())
        has_cyrillic = any("CYRILLIC" in _ucd.name(c, "") for c in tok if c.isalpha())
        if has_latin and has_cyrillic:
            raise ValueError(
                f"input contains a mixed-script identifier ({tok!r}); "
                f"refusing. A token mixing Latin and Cyrillic letters is a "
                f"homoglyph (Cyrillic 'а' / 'о' / 'р' look like ASCII "
                f"'a' / 'o' / 'p'). Skill prose should be ASCII / Greek "
                f"letters only.")
    return n


def _check_backtick_content(field_name: str, value: str) -> None:
    """v0.1.43 (Round-5 R5-1 fix) — validate the contents of each
    backtick-wrapped token. The v0.1.42 backtick exemption was UNCONDITIONAL
    (any string wrapped in `…` shipped verbatim), so an attacker could write
    `` `radix2_div` `` and bypass the entire structural rule.

    v0.1.43 distinguishes two legitimate uses of markdown backticks:

      (1) Single identifier (`rst_n`, `data_width`, `eda_cocotb`):
          Apply strict identifier-shape rules. Refuse ProbNNN, the
          lowercase-then-digits leaf-name shape (radix2div, mux256to1,
          lemmings1), and tokens carrying an over-long UNBROKEN alphanumeric
          run (freqdivbyeven-style separator-stripped concatenations).
          #798: the run, not the total length — the plugin's own program
          filenames are long BY CONVENTION
          (`declared_pdk_is_the_pdk_used_check.py`) and a total-length cap
          refused 31.49% of them. The digit rule is NOT narrowed to
          compensate; its false positives are finite industry vocabulary and
          go in `industry_tech_allowlist.yaml`, because `ddr4` and
          `lemmings1` have the same shape.

      (2) Multi-token CODE SNIPPET (`initial clk=X; always #(PERIOD/2) ...`,
          `assign MATCH = state == MATCH_STATE`):
          Skill text often quotes multi-statement Verilog/Python in
          backticks. Apply only the absolute taboos: ProbNNN, mixed-script
          homoglyphs, enumerated benchmark family names. Skip the
          single-identifier rules (length, snake_case, digit-embed).

    Distinguishing: a backtick content with whitespace OR Verilog/Python
    operator characters is a code snippet. A contiguous alphanumeric+
    underscore token is an identifier.
    """
    if not value or "`" not in value:
        return
    for m in _leak_re.finditer(r"`([^`]*)`", value):
        tok = m.group(1).strip()
        if not tok:
            continue
        # Absolute taboos (apply to BOTH identifier and code-snippet form):
        # Reject ProbNNN inside backticks (case-insensitive).
        if _leak_re.search(r"\bprob\d+\b", tok, _leak_re.IGNORECASE | _leak_re.ASCII):
            raise ValueError(
                f"{field_name} contains a backtick-wrapped Prob ID "
                f"(`{tok}`); refusing. Backtick wrapping does not exempt "
                f"benchmark-specific identifiers from the honesty rule.")
        # Reject enumerated benchmark family tokens.
        if _leak_re.search(_DESIGN_LEAK_PATTERN, tok, _leak_re.IGNORECASE):
            raise ValueError(
                f"{field_name} contains a backtick-wrapped benchmark "
                f"family name (`{tok}`); refusing.")
        # Distinguish identifier vs code snippet by presence of operator
        # characters or whitespace (code snippets have these; identifiers
        # don't).
        is_code_snippet = bool(_leak_re.search(r"[\s=;,()\[\]<>&|+\-*/!#@]", tok))
        if is_code_snippet:
            continue  # Code snippets: only Prob/family checks above apply.
        # Identifier-form additional rules:
        # Allowlist match passes unconditionally.
        if tok.lower() in _INDUSTRY_TECH_ALLOWLIST:
            continue
        # Reject digit-embedded-in-lowercase (radix2div, mux256to1 style)
        # — this is the exact shape Round-4 NEW-2 used to bypass v0.1.41.
        # Snake-case forms like `radix2_div` also match (the `2_` boundary
        # makes the trailing `_div` not interfere with the `[a-z0-9]*` tail).
        #
        # #798 — this shape DOES over-fire: it refused 11 of this plugin's own
        # 86 shipped `*_protocol_synth.py` protocol names (12.8%) — `ddr4`,
        # `ddr5`, `gddr6`, `hbm3`, `lpddr5`, `usb4`, `rs485`, `psi5`,
        # `jesd204`, `arinc429`, `milstd1553` — plus `crc32`, `sha256`,
        # `base64`, `utf8`, `axi4`, `int8`, `float32`.
        #
        # The tempting narrowing — require an alphabetic tail after the digit
        # run, so a "generation suffix" like `ddr4` terminates at its digits
        # while `radix2_div` continues — was AUTHORED AND REVERTED here,
        # because it is a leak. Measured over `verilogeval_v2/problems.list`
        # with the `ProbNNN_` prefix stripped (the leaf-name a leaking author
        # would actually write), it takes the caught count from 85/156 to
        # 38/156: `lemmings1`, `kmap1`..`kmap4`, `circuit1`..`circuit10`,
        # `fsm1`..`fsm3`, `vector0`..`vector5`, `popcount255`, `rule90`,
        # `rule110`, `lfsr32`, `dff8`, `count10`, `shift18` — 47 real design
        # leaf-names, all terminating at their digits exactly like `ddr4`. The
        # bare-text rule at step 1b already requires that alphabetic tail, so
        # THIS rule is the only guard on the whole class.
        #
        # `ddr4` and `lemmings1` are structurally identical. This is therefore
        # the same residue as `sg13g2` vs `radix2_div` below: no shape rule can
        # separate them, and the honest discriminator is the finite, public,
        # enumerable list in `industry_tech_allowlist.yaml` (checked above),
        # whose `protocol_generation` + `encoding_and_width` categories carry
        # these 50 terms and are pinned against collision with any benchmark
        # leaf-name.
        if _leak_re.search(
                r"^[a-z]{2,}\d+[a-z0-9_]*$", tok, _leak_re.ASCII):
            raise ValueError(
                f"{field_name} contains a backtick-wrapped identifier "
                f"that matches a benchmark-leaf-name shape (`{tok}`); "
                f"refusing. Examples of this shape: radix2_div, "
                f"freq_divbyeven, mux256to1, lemmings1, kmap4, circuit10. "
                f"Wrap legitimate industry identifiers like `rst_n` (no "
                f"digits) or use a generic description instead. If this is "
                f"universal industry vocabulary (a protocol generation like "
                f"ddr4, an encoding/width like sha256), propose it for "
                f"industry_tech_allowlist.yaml with a standards citation.")
        # Cap the longest UNBROKEN alphanumeric run, not the total length.
        #
        # #798 — the pre-fix rule was `len(tok) > 30`, which refused 348 of
        # this plugin's own 1105 `programs/*.py` filenames (31.49%). Every one
        # of them is a convention-conformant `descriptive_name_check.py`, and
        # every one of them is a name the BARE-text rule at step 1 of
        # `_validate_general_text` explicitly instructs the author to wrap in
        # backticks — so `declared_pdk_is_the_pdk_used_check.py` could be
        # written neither bare (step 1: "wrap it in markdown backticks") nor
        # backticked (this rule: "longer than 30 chars"). Total length is not
        # the concatenation signal; the ABSENCE of the convention's separators
        # is. The outer step-4 rule already measures exactly that — it splits
        # on non-alphanumerics via `findall(r"[A-Za-z][A-Za-z0-9]+")` — so
        # this is the inner rule catching up to the outer one, on the same
        # 30-char budget.
        #
        # Non-weakening FOR CONCATENATION: a token with no separators IS its
        # own longest run, so every genuinely concatenated identifier the old
        # rule refused is still refused. The tokens that change verdict are
        # exactly those that carry separators.
        #
        # That is NOT the same as "tokens that were never benchmark names",
        # and the difference is a real, measured coverage loss. Six CVDP
        # DESIGN leaf-names carry separators AND are over 30 characters, so
        # the old cap refused them and this one does not:
        #     arithmetic_progression_generator          (32)
        #     configurable_digital_low_pass_filter      (36)
        #     reed_solomon_encoder_and_decoder          (32)
        #     secure_read_write_register_bank           (31)
        #     sequencial_binary_to_one_hot_decoder      (36)
        #     write_through_data_direct_mapped_cache    (38)
        # Over the 229 unique CVDP design leaf-names in tracked paths and file
        # contents this is 14 caught -> 8. It is accepted, not repaired: the
        # cap cannot tell them from `declared_pdk_is_the_pdk_used_check.py`
        # (37) — no length or shape discriminator exists — and restoring it
        # re-creates the 31.49% catch-22 that is the actual bug. The class is
        # therefore UNGUARDED BY DESIGN at the identifier level; the cell IDs
        # that carry these names are still caught in full by the family branch
        # (126 of 126 under the harvest definition at the top of this file, and
        # the two ids for these specific leaves are pinned as literals in the
        # test module).
        #
        # WHICH FLOOR GUARDS THIS RULE — not `_CVDP_LEAF_FLOOR = 8`. Replace
        # this `if` with `if False:`, deleting the cap outright, and that 8 is
        # still 8: none of the 229 raw CVDP leaf-names has an unbroken run over
        # 30 chars, so all 8 survivors come from the digit-shape rule above and
        # the constant is BLIND to this one. `_VE_LEAF_FLOOR` (85) and
        # `_VE_LEAF_CONCAT_FLOOR` (91) are blind for the same reason. The
        # constants this cap can actually move are both measured on the
        # separator-STRIPPED corpus, where the six names above become unbroken
        # runs again: `_CVDP_LEAF_RUN_FLOOR = 3` counts only the leaves refused
        # by THIS rule's own message, so no other rule can satisfy it, and
        # `_CVDP_LEAF_CONCAT_FLOOR = 17` is 14 digit-shape + those 3. Under
        # `if False:` they go 3 -> 0 and 17 -> 14 and both assertions fail.
        runs = _leak_re.findall(r"[A-Za-z0-9]+", tok)
        longest = max(runs, key=len) if runs else ""
        if len(longest) > 30:
            raise ValueError(
                f"{field_name} contains a backtick-wrapped identifier with a "
                f"{len(longest)}-character unbroken alphanumeric run "
                f"({longest!r} inside `{tok}`); refusing as likely "
                f"concatenated identifier. A separator-bearing name such as "
                f"`a_b_c_check.py` is accepted at any total length — it is "
                f"the unbroken run, not the length, that signals "
                f"concatenation.")


def _strip_backticks(text: str) -> str:
    """v0.1.42 — replace `code` spans with same-length whitespace.

    v0.1.43 (Round-5 R5-1 fix): backtick-wrapped contents are now also
    leak-checked by `_validate_general_text` via `_check_backtick_content`
    BEFORE this strip runs. The strip itself is for finding leaks OUTSIDE
    backticks; the prior check handles leaks INSIDE. The strip is still
    needed so a legitimate backtick-wrapped industry term (`rst_n`,
    `always_ff`) is exempt from the snake_case rule on the outer text.
    """
    return _leak_re.sub(r"`[^`]*`", lambda m: " " * len(m.group()), text)


def _load_industry_tech_allowlist() -> frozenset:
    """v0.1.44 — load the allowlist from `industry_tech_allowlist.yaml`
    so the community can propose additions via PR without touching code.

    YAML schema:
        categories:
          <category_name>:
            description: <one-line>
            entries: [<lowercase-term>, ...]

    Each `entries` value is normalised to lowercase and added to the
    returned frozenset. Categories are organisational only; lookup is flat.

    Falls back to the v0.1.43-shipped seed set if YAML is missing or
    malformed (so a corrupted-yaml PR can't break the validator).
    """
    yaml_path = _Path(__file__).parent / "industry_tech_allowlist.yaml"
    seed = frozenset({
        # Minimal safe-fallback set; identical to the v0.1.43 inline list.
        "rst_n", "reset_n", "rst", "clk", "clk_n", "clk_p",
        "always_ff", "always_comb", "always_latch", "chip_top",
        "next_state", "current_state",
        "res_valid", "res_ready", "dout_valid", "din_valid",
        "data_width", "addr_width", "fifo_depth",
        "compile_error", "sim_timeout", "functional_mismatch", "work_dir",
        "skywater", "gf180", "tsmc", "sky130",
        "module_not_found_error",
        "dbm", "mah", "mhz", "ghz", "khz",
        "t_setup", "t_hold", "t_su", "t_h", "t_cyc", "t_recovery", "t_removal",
    })
    if not yaml_path.is_file():
        return seed
    try:
        import yaml as _yaml
        data = _yaml.safe_load(yaml_path.read_text())
        out = set()
        for cat in (data.get("categories") or {}).values():
            for entry in (cat.get("entries") or []):
                if isinstance(entry, str) and entry:
                    out.add(entry.lower())
        return frozenset(out) if out else seed
    except Exception:
        # PyYAML missing or YAML malformed → safe fallback.
        return seed


# Lazy + cached: read the YAML once on first use.
from pathlib import Path as _Path
_INDUSTRY_TECH_ALLOWLIST = _load_industry_tech_allowlist()


def _validate_general_text(field_name: str, value: str,
                            *, allow_underscores: bool = False) -> str:
    """v0.1.42 (Round-4 audit fix) — universal structural check applied to
    EVERY field that becomes plugin content (title, slug, body fields).

    Round-4 auditor's verdict: the v0.1.41 inversion only protected
    title+slug; the 5 free-text body fields (pattern, when, what, example,
    generality) still leaked. v0.1.42 applies the same structural rule to
    all 7 fields, with a meaningful escape hatch:

      Backtick-wrapped identifiers ARE allowed.
      Bare underscore identifiers (snake_case) NOT in the industry-tech
        allowlist ARE refused.
      Case-insensitive `prob\\d+` ANYWHERE — refused.
      Enumerated benchmark family names (RTLLM / VerilogEval-* / CVDP /
        MetRex / etc.) — refused.
      Any single token > 25 chars without a space — refused.

    The escape hatch means a skill author who wants to discuss `rst_n` as
    an industry convention can write `` `rst_n` `` in markdown style;
    the bare snake_case `radix2_div` (a benchmark leaf name) is refused
    structurally. The rule applies symmetrically across the 7 fields so
    a Round-5 auditor cannot produce a clean-title + dirty-body leak.

    Raises ValueError citing the structural violation; caller MUST fix
    the input (either by wrapping a legitimate identifier in backticks
    OR by rewriting in general-pattern language).
    """
    if not value:
        return value
    # v0.1.43 (Round-5 R5-2 fix) — Unicode-normalize + reject homoglyphs
    # BEFORE the regex pass so fullwidth ＿ / Cyrillic а / ProbＮＮＮ all
    # get caught.
    value = _normalize_text(value)
    # v0.1.43 (Round-5 R5-1 fix) — validate INSIDE backticks too: a token
    # wrapped in backticks must be a real industry term or a safely-shaped
    # identifier, NOT just any string the caller chose to backtick.
    _check_backtick_content(field_name, value)
    # Backtick-wrapped identifiers are exempt from the outer-text rules
    # (the caller's positive declaration that this is a known technical
    # term, not a benchmark leaf-name).
    text = _strip_backticks(value)
    # All structural regexes use re.ASCII so Unicode `\\w` doesn't break
    # `\\b` word boundaries (Round-5 R5-2 fix supplements R5-2-A above).
    # 1. Snake-case identifiers OUTSIDE the industry allowlist.
    for m in _leak_re.finditer(
            r"\b[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z0-9]+)+\b", text, _leak_re.ASCII):
        tok = m.group()
        if tok.lower() in _INDUSTRY_TECH_ALLOWLIST:
            continue
        raise ValueError(
            f"{field_name} contains a bare underscore-bearing identifier "
            f"({tok!r}); refusing. Per benchmark-enhancement-capture "
            f"honesty rule (v0.1.42 structural rule): if {tok!r} is a "
            f"legitimate industry-convention term (rst_n, always_ff), "
            f"wrap it in markdown backticks: `{tok}`. If {tok!r} is a "
            f"benchmark design leaf-name (radix2_div, freq_divbyeven), "
            f"rewrite the {field_name} to describe the GENERAL pattern "
            f"without naming the specific design.")
    # 1b. Digit-embedded-in-lowercase token: `radix2div`, `mux256to1`.
    for m in _leak_re.finditer(
            r"\b[a-z]{2,}\d+[a-z][A-Za-z0-9]*\b", text, _leak_re.ASCII):
        tok = m.group()
        if tok in _INDUSTRY_TECH_ALLOWLIST:
            continue
        raise ValueError(
            f"{field_name} contains a digit-embedded-in-lowercase "
            f"identifier ({tok!r}); refusing. This shape matches benchmark "
            f"design leaf-names. Wrap in backticks if legitimate: `{tok}` "
            f"— or rewrite as general pattern.")
    # 1c. camelCase / PascalCase compound identifier. v0.1.43 (Round-5
    #     R5-10 fix) — require min length 5 so `dBm`, `aBc`, `mAh` etc.
    #     short unit suffixes don't get refused. Real PascalCase compound
    #     identifiers (`SequenceDetector`, `TopModule`) are ≥7 chars; the
    #     5-char floor keeps the rule effective without false-positives
    #     on industry unit suffixes.
    for m in _leak_re.finditer(
            r"\b[A-Za-z]*[a-z][A-Z][a-z]+[A-Za-z0-9]*\b", text, _leak_re.ASCII):
        tok = m.group()
        if tok in _INDUSTRY_TECH_ALLOWLIST or tok.lower() in _INDUSTRY_TECH_ALLOWLIST:
            continue
        if len(tok) < 5:
            continue  # Unit suffixes / 3-char abbreviations exempt.
        raise ValueError(
            f"{field_name} contains a camelCase/PascalCase compound "
            f"identifier ({tok!r}); refusing. Wrap in backticks if "
            f"legitimate: `{tok}` — or rewrite as space-separated words.")
    # 1d. Kebab-case identifier with digit-bearing leading token.
    for m in _leak_re.finditer(
            r"\b[a-z]{2,}\d+(?:-[a-z0-9]+){1,}\b", text, _leak_re.ASCII):
        tok = m.group()
        if tok in _INDUSTRY_TECH_ALLOWLIST:
            continue
        raise ValueError(
            f"{field_name} contains a kebab-case identifier with a "
            f"digit-bearing token ({tok!r}); refusing. This shape matches "
            f"benchmark design leaf-names. Wrap in backticks if legitimate: "
            f"`{tok}`, or rewrite without the digit-bearing token.")
    # 2. Prob## case-insensitive.
    pm = _leak_re.search(r"\bprob\d+\b", text, _leak_re.IGNORECASE | _leak_re.ASCII)
    if pm:
        raise ValueError(
            f"{field_name} contains a benchmark Prob ID ({pm.group()!r}); "
            f"refusing. Skill content must describe general patterns, not "
            f"specific benchmark problems.")
    # 3. Enumerated benchmark-family tokens (RTLLM / VerilogEval-* / CVDP /
    #    MetRex / ResBench / RTL-Repo / PyHDL-Eval).
    em = _leak_re.search(_DESIGN_LEAK_PATTERN, text, _leak_re.IGNORECASE)
    if em:
        raise ValueError(
            f"{field_name} contains a benchmark family name "
            f"({em.group()!r}); refusing. Describe the general convention "
            f"without naming the source benchmark.")
    # 4. Over-long contiguous alphanumeric token (likely a concatenated
    #    identifier like 'radix2divbyeven' or 'freqdivbyeven').
    for tok in _leak_re.findall(r"[A-Za-z][A-Za-z0-9]+", text):
        if len(tok) > 25:
            raise ValueError(
                f"{field_name} contains an over-long contiguous token "
                f"({tok!r}, {len(tok)} chars) — likely a concatenated "
                f"identifier. Insert spaces or wrap in backticks.")
    # 5. Field-specific shape — slug must be kebab-case AFTER all leak
    #    checks pass.
    if field_name == "backlog_slug":
        if not _leak_re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", value):
            raise ValueError(
                f"backlog_slug must be kebab-case "
                f"([a-z0-9-], no uppercase, no underscore): {value!r}")
        for tok in value.split("-"):
            # Note: prob\d+ check at step 2 already catches `prob089`. The
            # NEW-3 Round-4 case `prob-089-issue` has separate `prob` and
            # `089` tokens; the `\bprob\d+\b` check at step 2 won't match
            # split tokens. Catch the dispersed Prob## here:
            if tok == "prob" or _leak_re.fullmatch(r"prob\d+", tok):
                raise ValueError(
                    f"backlog_slug token {tok!r} suggests a benchmark "
                    f"Prob ID (possibly separated by dashes): {value!r}.")
    return value


def _refuse_if_leaks(field_name: str, value: str) -> str:
    """v0.1.42 — thin wrapper preserving v0.1.41 callsites. The structural
    work moved to `_validate_general_text` which is applied to all 7 fields.
    """
    return _validate_general_text(field_name, value)


# v0.1.43 (Round-5 R5-8 fix) — `_refuse_if_leaks_v0141_DEPRECATED` was
# 99 lines of unreachable code carried since v0.1.42 for "audit traceability".
# Removed in v0.1.43; the v0.1.41 → v0.1.42 transition rationale lives in
# the git history (commits d3ae455 v0.1.41 and 0622db4 v0.1.42).


def emit_skill_section(rec: dict) -> str:
    # v0.1.39 (audit Finding 1) — REQUIRE skill_title; never default to the
    # design slug (which would inject the benchmark identifier into the section
    # header).
    name = rec.get("skill_title")
    if not name:
        raise ValueError(
            "emit_skill_section: rec missing 'skill_title' — refusing to "
            "default to design slug per benchmark-enhancement-capture honesty "
            "rule ('NEVER add a Bucket B skill section that names specific "
            "benchmark design identifiers'). Caller must supply a generic "
            "skill title describing the general PATTERN.")
    # v0.1.40 (re-audit F1 補洞) — title must itself be leak-free; refuse on
    # leaky title (a sloppy caller is the failure mode the prior audit
    # warned about).
    name = _validate_general_text("skill_title", name)
    # v0.1.42 (Round-4 audit fix) — the structural rule applies to ALL 5
    # body fields, not just title. A Round-4 reproducer (clean title +
    # `radix2_div` in pattern) would otherwise emit a leaked artifact.
    pattern = _validate_general_text("pattern", rec.get("pattern", ""))
    when = _validate_general_text("when", rec.get("when", ""))
    what = _validate_general_text("what", rec.get("what", ""))
    example = _validate_general_text("example", rec.get("example", ""))
    generality = _validate_general_text("generality", rec.get("generality", ""))
    return (
        f"### Skill: {name}\n\n"
        f"**Pattern**: {pattern}\n\n"
        f"**When to apply**: {when}\n\n"
        f"**What to do**: {what}\n\n"
        f"**Worked pattern** (anonymized): {example}\n\n"
        f"**Why this is GENERAL**: {generality}\n\n"
        f"_Captured by benchmark-enhancement-capture {datetime.date.today().isoformat()}._\n"
    )


def emit_program_rule_sketch(rec: dict) -> str:
    # v0.1.39 (audit Finding 1) — drop the "Source: <design>" breadcrumb so the
    # in-tree program sketch is chip-AGNOSTIC. Pattern + docstring still capture
    # the lesson without naming the originating benchmark design.
    rname = _slug(rec.get("rule_name", "todo")).replace("-", "_")
    pattern = _validate_general_text("pattern", rec.get("pattern", ""))
    docstring = _validate_general_text("docstring", rec.get("docstring", ""))
    fix_action = _validate_general_text("fix_action", rec.get("fix_action", ""))
    return (
        f"# Auto-captured by benchmark-enhancement-capture at plugin "
        f"v{resolved_plugin_version()}\n"
        f"# Pattern: {pattern}\n"
        f"# CORPUS-SWEEP REQUIRED before merging: zero false-positives across\n"
        f"# the open-benchmark corpora used by `score_iverilog_tb.py`.\n"
        f"\n"
        f"def rule_{rname}(sample_text, ports):\n"
        f"    \"\"\"{docstring}\"\"\"\n"
        f"    # Expected signal: {rec.get('expected_signal', 'WARN')}\n"
        f"    # Suggested fix action: {fix_action}\n"
        f"    return []  # list of findings — TODO implement\n"
    )


def emit_backlog(rec: dict, today: str, now: "datetime.datetime | None" = None):
    """Emit one ORGANIC backlog YAML.

    ``now`` is the tz-aware instant the record was submitted. It is a parameter
    only so a caller can pass ONE instant for a whole batch (and so a test can
    inject one); when omitted the real current instant is read. It is never a
    constant — ``submitted_at`` is a measurement or it is nothing.
    """
    # v0.1.39 (audit Finding 1) — REQUIRE backlog_slug; never default to the
    # design slug. Backlog filenames become part of the repo's permanent
    # record; a Prob ID baked into a filename can never be silently scrubbed
    # later without breaking links.
    slug = rec.get("backlog_slug")
    if not slug:
        raise ValueError(
            "emit_backlog: rec missing 'backlog_slug' — refusing to default "
            "to design slug. Caller must supply a generic kebab-case slug "
            "describing the issue category (e.g. 'rtl-hygiene-internal-reg-"
            "init'), not the originating benchmark design name.")
    # v0.1.40 (re-audit F1 補洞) — slug becomes part of the permanent
    # filename and YAML id. Refuse on leaky slug.
    slug = _validate_general_text("backlog_slug", slug)
    slug = _slug(slug)
    fname = f"ORGANIC-{today.replace('-','')}-{slug}.yaml"
    indent = "  "
    # `pattern` is REQUIRED, and is refused here exactly as `backlog_slug` is
    # refused above. It used to be read as `rec.get("pattern", "")`, and
    # `_validate_general_text` returns the value unchanged when it is falsy —
    # so an omitted pattern emitted well-formed YAML with an empty block and
    # no error, while `backlog_sanitize_check.REQUIRED_FIELDS` demands the
    # field of the very file this function writes. Required downstream,
    # undefined upstream (the schema above documented it only under Bucket B)
    # and unenforced here is the shape that let two authors an hour apart
    # resolve the same field the two available wrong ways: one left it empty,
    # one pasted in the text of an unrelated record.
    if not str(rec.get("pattern") or "").strip():
        raise ValueError(
            "emit_backlog: rec missing 'pattern' — refusing to emit an empty "
            "one. A pattern states the CLASS of defect: what shape of input "
            "meets what shape of handling, and what wrong outcome follows — "
            "written so a reader can recognise a DIFFERENT instance of it. "
            "It is not a restatement of the title and not a description of "
            "this one symptom; a sentence that only fits the record it sits "
            "on cannot match the next occurrence, which is the only thing "
            "the field is for. Do not copy one from another record: a "
            "pattern that came from a different defect is worse than none, "
            "because it reads as measured.")
    # v0.1.42 — structural validation across body fields (Round-4 NEW-4 fix).
    pat = _validate_general_text("pattern", rec.get("pattern", "")).replace("\n", "\n" + indent)
    fix = _validate_general_text("suggested_fix", rec.get("suggested_fix", "")).replace("\n", "\n" + indent)
    ctx = _validate_general_text("session_context", rec.get("session_context", ""))
    # Bucket-T (forked-EDA-tool enhancement) attribution block. Present whenever
    # the record names a `tool` (always for bucket=="T"). These fields tell the
    # gatekeeper WHICH forked tool owns the fix and give the golden/bad samples
    # + the concrete tool enhancement (owner directive 2026-07-11).
    tool_block = ""
    if (rec.get("bucket") or "").upper() == "T" or rec.get("tool"):
        prob = _validate_general_text("problem", rec.get("problem", "")).replace(
            "\n", "\n" + indent)
        tenh = _validate_general_text(
            "tool_enhancement", rec.get("tool_enhancement", "")).replace(
            "\n", "\n" + indent)
        tool_block = (
            f"root_cause_layer: forked_tool\n"
            f"tool: \"{rec.get('tool', '')}\"\n"
            f"generating_step: \"{rec.get('step', '')}\"\n"
            f"golden_sample: \"{rec.get('golden_sample', 'none — not captured')}\"\n"
            f"bad_sample: \"{rec.get('bad_sample', '')}\"\n"
            f"problem: |\n  {prob}\n"
            f"tool_enhancement: |\n  {tenh}\n"
        )
    # PROVENANCE, NOT DECORATION (#795). Two fields below name WHICH plugin
    # produced this record and WHEN. Both used to be constants: the version was
    # a literal semver that stopped being current ~180 releases ago, and the
    # time-of-day was a literal midnight. A constant in a field that is
    # formatted like a measurement is unreadable as wrong — every emitted
    # record looked measured, and `backlog_sanitize_check.py` (which requires
    # the field) only checks that it is non-empty, while
    # `tools/ci/staged_version_claim_check.py` exempts `community/backlogs/`
    # outright. So nothing downstream could ever have caught it.
    #
    # An author-supplied `plugin_version` still wins — the record may be
    # describing a version other than the one running the emitter, and the fix
    # must not overwrite author intent.
    version = str(rec.get("plugin_version") or "").strip() or resolved_plugin_version()
    submitted = (now or datetime.datetime.now().astimezone()).isoformat(
        timespec="seconds")
    body = (
        f"type: {rec.get('backlog_type', 'enhancement')}\n"
        f"severity: {rec.get('severity', 'P2')}\n"
        f"component: {rec.get('component', '')}\n"
        f"plugin_version: \"{version}\"\n\n"
        f"title: >-\n  {_validate_general_text('title', rec.get('title', ''))}\n\n"
        + (tool_block + "\n" if tool_block else "")
        + f"pattern: |\n  {pat}\n\n"
        f"suggested_fix: |\n  {fix}\n\n"
        f"id: \"ORGANIC-{today.replace('-','')}-{slug}\"\n"
        f"submitted_at: \"{submitted}\"\n"
        f"session_context: >-\n  {ctx}\n"
    )
    return fname, body


def emit_discard_note(rec: dict) -> str:
    # v0.1.39 (audit Finding 1) — discard log is an INTERNAL session record
    # (lives in candidates/, NOT shipped as plugin content), so keeping the
    # design name here is fine for audit traceability. But scrub the why-discard
    # prose so a copy-pasted discard reason can't smuggle a Prob ID into a
    # downstream Bucket-B section.
    return (f"- **{rec.get('design', '?')}**: "
            f"{_scrub_design_leak(rec.get('why_discard', 'no reason given'))}\n")


def check_program_first(recs: list) -> list:
    """PROGRAM-FIRST gate (user directive: capture must enforce program-first).

    Bucket B (skill) and Bucket C (backlog) are a DOWNGRADE from the default
    Bucket A (deterministic program rule). A downgrade is only honest if the
    author states why a program could not do it. Returns a list of human
    -readable offender strings; empty list == pass.
    """
    offenders = []
    for i, r in enumerate(recs):
        b = (r.get("bucket") or "D").upper()
        if b in ("B", "C"):
            why = (r.get("why_not_bucket_a") or "").strip()
            if len(why) < 10:
                who = r.get("skill_title") or r.get("title") or r.get(
                    "design") or f"record[{i}]"
                offenders.append(
                    f"Bucket {b} '{who}' lacks a non-empty why_not_bucket_a "
                    f"(>=10 chars). Program-first: justify why no deterministic "
                    f"program rule (Bucket A) can make this fix, or reclassify.")
    return offenders


# Bucket-T (forked-EDA-tool enhancement) — the mandatory identification fields
# (owner directive 2026-07-11). A defect generated by a forked OSS EDA tool is
# fixed IN THAT TOOL; the record must name the generating step, the tool, the
# problem, the golden/bad samples, and the concrete tool enhancement.
_BUCKET_T_TOOLS = frozenset({
    "OpenROAD", "KLayout", "magic", "netgen", "yosys", "ngspice",
    "iverilog", "verilator",
})
_BUCKET_T_REQUIRED = ("step", "tool", "problem", "tool_enhancement")


def check_bucket_t(recs: list) -> list:
    """Every Bucket-T record must carry the forked-tool attribution fields so the
    fix lands in the RIGHT forked tool of the GENERATING step, with a verifiable
    golden/bad diff. Returns human-readable offender strings; empty == pass."""
    offenders = []
    for i, r in enumerate(recs):
        if (r.get("bucket") or "").upper() != "T":
            continue
        who = r.get("title") or r.get("design") or f"record[{i}]"
        for f in _BUCKET_T_REQUIRED:
            if not (r.get(f) or "").strip():
                offenders.append(
                    f"Bucket T '{who}' missing required field '{f}'. A "
                    f"forked-tool fix must name the generating step, the tool, "
                    f"the problem, and the concrete tool enhancement.")
        tool = (r.get("tool") or "").strip()
        if tool and tool not in _BUCKET_T_TOOLS:
            offenders.append(
                f"Bucket T '{who}' tool '{tool}' is not a known forked EDA tool "
                f"({', '.join(sorted(_BUCKET_T_TOOLS))}).")
        # golden_sample must be present OR explicitly declared absent (never
        # silently omitted) — the 'none — <why>' escape hatch is honest.
        gs = (r.get("golden_sample") or "").strip()
        if not gs:
            offenders.append(
                f"Bucket T '{who}' missing 'golden_sample' — supply a path or "
                f"'none — <why>' (never silently omit).")
    return offenders


# ── cross-record duplicate `pattern` (#822) ─────────────────────────────────
# WHERE THIS LIVES, AND WHY IT LIVES HERE
# A duplicate needs TWO records in ONE process to be arithmetically possible.
# `backlog_sanitize_check` — the gate that reads the emitted YAML — is driven
# `--file <one yaml>` by every caller in this repo (community-backlog-submit
# SKILL.md Step 4, field-agent-loop SKILL.md, phase1-coverage-loop SKILL.md;
# there is no `--dir` caller). It would therefore receive a one-element list
# and report "0 duplicates" on every real run while reading as coverage — a
# detector that exists is not a detector that is on the path. `main()` below
# holds the whole batch in one process, which makes it the one place in the
# repo where >=2 records provably co-occur, so the check is non-vacuous by
# construction and needs no caller change.
#
# SCOPE, STATED — a duplicate detector is not a correctness check
# CATCHES: the same `pattern` text on two or more records of a SINGLE emit
#   batch. That is #796's shape exactly, where both records carried
#   byte-identical text.
# DOES NOT CATCH: a `pattern` copied from OUTSIDE the batch (an issue body, a
#   skill's worked example, a chat message) onto exactly ONE record; a
#   `pattern` that merely restates its own title in different words; or one
#   that is populated, plausible, and about the wrong defect. Those are the
#   judgment only a reader makes, and nothing here should read as covering
#   them.
#
# POPULATION: the buckets that EMIT A BACKLOG — C and T. Both go through
# `emit_backlog`, both write a `pattern:` block into a YAML whose required
# fields `backlog_sanitize_check` then enforces, and for both a duplicate is
# unambiguous: one backlog is one defect, so two backlogs sharing a pattern
# means one of them was copied. Bucket B (skill sections) is DELIBERATELY
# excluded: two B records at different steps route to different skill files on
# purpose, and two instances of one general pattern captured at two steps is a
# defensible authoring choice rather than a copy. Flagging it would be a guess
# dressed as a finding.
_BACKLOG_EMITTING_BUCKETS = ("C", "T")


def _pattern_key(value) -> str:
    """Whitespace-collapsed, case-folded. #796's two records were byte-identical,
    but a copy that gained a newline or a capitalised first word is the same
    defect and must not pass on the difference."""
    return " ".join(str(value or "").split()).casefold()


def check_duplicate_patterns(recs: list) -> list:
    """Records of ONE batch that share a `pattern`. Returns human-readable
    offender strings; empty list == pass.

    A blank/missing `pattern` is SKIPPED here, not grouped. It is a different
    defect with its own refusal at the write site, and grouping the blanks
    would report them as duplicates of each other — naming the wrong bug and
    burying the real one.
    """
    groups: dict = {}
    for i, r in enumerate(recs):
        if (r.get("bucket") or "D").upper() not in _BACKLOG_EMITTING_BUCKETS:
            continue
        key = _pattern_key(r.get("pattern"))
        if not key:
            continue
        who = (r.get("title") or r.get("backlog_slug")
               or r.get("design") or f"record[{i}]")
        groups.setdefault(key, []).append(f"record[{i}] {who!r}")
    offenders = []
    for key, members in groups.items():
        if len(members) < 2:
            continue
        excerpt = key if len(key) <= 120 else key[:117] + "..."
        offenders.append(
            f"{len(members)} records share ONE `pattern`: "
            f"{', '.join(members)} — the shared text reads {excerpt!r}. A "
            f"pattern states the CLASS of defect of the record it sits on; the "
            f"same sentence cannot be the class of two different defects, so "
            f"one of these was copied from the other and describes something "
            f"it did not measure. Write each record its own, or merge them "
            f"into the one record they actually are.")
    return offenders


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--records", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--allow-unjustified-downgrade", action="store_true",
                    help="bypass the program-first why_not_bucket_a gate "
                         "(discouraged; for migrating legacy record sets only)")
    a = ap.parse_args()

    recs = json.loads(Path(a.records).read_text())

    offenders = check_program_first(recs)
    if offenders and not a.allow_unjustified_downgrade:
        print("PROGRAM-FIRST GATE FAILED — Bucket B/C downgrades need "
              "why_not_bucket_a:", file=sys.stderr)
        for o in offenders:
            print("  - " + o, file=sys.stderr)
        sys.exit(1)

    # Bucket-T forked-tool attribution gate (owner directive 2026-07-11) — a
    # forked-tool fix without step/tool/problem/tool_enhancement/golden_sample
    # cannot be routed to the right tool or verified, so it is refused.
    t_offenders = check_bucket_t(recs)
    if t_offenders:
        print("BUCKET-T GATE FAILED — forked-tool records need their "
              "attribution fields:", file=sys.stderr)
        for o in t_offenders:
            print("  - " + o, file=sys.stderr)
        sys.exit(1)

    # #822 — the cross-record check, on the ONE path where two records
    # provably co-occur. It sits with the other pre-flight gates and BEFORE
    # `out.mkdir`, so a refusal costs nothing: raising it later, mid-emit,
    # would abort the batch after some artifacts were already written and
    # leave a half-populated output dir — the failure mode the Bucket-A
    # routing loop below carries a comment about.
    dup_offenders = check_duplicate_patterns(recs)
    if dup_offenders:
        print("DUPLICATE-PATTERN GATE FAILED — one `pattern` on more than one "
              "record of this batch:", file=sys.stderr)
        for o in dup_offenders:
            print("  - " + o, file=sys.stderr)
        sys.exit(1)

    out = Path(a.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    # ONE instant for the whole batch, and the batch's date DERIVED from it, so
    # a run that straddles midnight cannot file a record whose id says one day
    # and whose submitted_at says the next.
    now = datetime.datetime.now().astimezone()
    today = now.date().isoformat()
    routing = _load_routing()

    by_bucket = {"A": [], "B": [], "C": [], "D": [], "T": []}
    for r in recs:
        b = (r.get("bucket") or "D").upper()
        by_bucket.setdefault(b, []).append(r)

    summary = {"date": today, "totals": {k: len(v) for k, v in by_bucket.items()},
               "routing_used": {}}

    # v0.1.35+ — route Bucket A and Bucket B per `step` field
    # #197 finding 1 — Bucket-A records whose step has no program layer.
    # Defined here so it is always in scope for the end-of-run summary even
    # when there are no Bucket-A records at all.
    unrouted_A: list[dict] = []
    if by_bucket["A"]:
        # group by target program file
        by_target: dict[str, list[dict]] = {}
        for r in by_bucket["A"]:
            # WARNING (#197 finding 1): dict.get(key, default) returns the
            # `default` argument ONLY when the key is ABSENT. Two very
            # reachable cases yield a PRESENT key whose value is null — so
            # `.get("bucket_A_program", "…")` returns None, NOT the string
            # default:
            #   (a) an UNLISTED step falls through to `default_routing`, whose
            #       `bucket_A_program` is explicitly null; and
            #   (b) a LISTED step that declares an explicit null program layer
            #       because it has no dedicated deterministic check program yet
            #       (e.g. `analog.sizing_loop`).
            # A None target means "this step has no Bucket-A program layer".
            # SKIP this record's program-rule sketch and record it as unrouted;
            # NEVER raise. Raising here aborted the entire batch AFTER some
            # artifacts were already written — losing every other captured
            # recovery and leaving a half-populated output dir with a bare
            # AttributeError traceback. A lost routing target must cost at most
            # that one record's Bucket-A emission, never the whole capture.
            tgt = route_for(r.get("step", ""), routing).get("bucket_A_program")
            if not tgt:
                unrouted_A.append(r)
                continue
            by_target.setdefault(tgt, []).append(r)
        bucket_A_files = []
        for tgt, items in by_target.items():
            safe = tgt.replace("/", "_").replace(".py", "")
            p = out / f"bucket_A_{safe}_rule_sketches.py"
            chunks = [f"# Bucket A — program-rule sketches for {tgt}\n"
                      f"# Corpus-sweep REQUIRED before merging into {tgt}.\n"]
            for r in items:
                chunks.append(emit_program_rule_sketch(r))
            p.write_text("\n".join(chunks))
            bucket_A_files.append(str(p))
        summary["bucket_A_files"] = bucket_A_files
        summary["routing_used"]["bucket_A"] = list(by_target.keys())

    if by_bucket["B"]:
        by_target = {}
        for r in by_bucket["B"]:
            # `... or "agents/ic-expert-agent.md"` (not `.get(k, default)`) so a
            # LISTED step with an explicit null `bucket_B_skill_file` falls back
            # to the general-judgment catch-all instead of crashing on None
            # (#197 finding 1 — same None-vs-missing hazard as Bucket A; for
            # skills the honest fallback is the catch-all, since there is always
            # a general skill that can hold the section).
            tgt = route_for(r.get("step", ""), routing).get(
                "bucket_B_skill_file") or "agents/ic-expert-agent.md"
            by_target.setdefault(tgt, []).append(r)
        bucket_B_files = []
        for tgt, items in by_target.items():
            safe = tgt.replace("/", "_").replace(".md", "")
            p = out / f"bucket_B_{safe}_sections.md"
            chunks = [f"# Bucket B — skill sections to APPEND to {tgt}\n"]
            for r in items:
                chunks.append(emit_skill_section(r))
            p.write_text("\n".join(chunks))
            bucket_B_files.append({"target": tgt, "patch": str(p)})
        summary["bucket_B_files"] = bucket_B_files
        summary["routing_used"]["bucket_B"] = sorted({x["target"] for x in bucket_B_files})

    if by_bucket["C"]:
        d = out / "bucket_C_backlogs"
        d.mkdir(exist_ok=True)
        files = []
        for r in by_bucket["C"]:
            fname, body = emit_backlog(r, today, now)
            (d / fname).write_text(body)
            files.append(fname)
        summary["bucket_C_dir"] = str(d)
        summary["bucket_C_files"] = files

    if by_bucket["T"]:
        # Forked-EDA-tool enhancement records: emit a backlog carrying the
        # tool-attribution block (root_cause_layer/tool/generating_step/
        # golden_sample/bad_sample/problem/tool_enhancement) so the gatekeeper
        # routes the fix to the RIGHT forked tool of the generating step.
        d = out / "bucket_T_forked_tool"
        d.mkdir(exist_ok=True)
        files = []
        for r in by_bucket["T"]:
            fname, body = emit_backlog(r, today, now)
            (d / fname).write_text(body)
            files.append(fname)
        summary["bucket_T_dir"] = str(d)
        summary["bucket_T_files"] = files
        summary["routing_used"]["bucket_T"] = sorted(
            {r.get("tool", "") for r in by_bucket["T"]})

    if by_bucket["D"]:
        p = out / "bucket_D_discarded.md"
        chunks = [f"# Bucket D — discarded ({len(by_bucket['D'])} entries)\n"]
        for r in by_bucket["D"]:
            chunks.append(emit_discard_note(r))
        p.write_text("\n".join(chunks))
        summary["bucket_D_file"] = str(p)

    # #197 finding 1 — surface every Bucket-A record that had no program layer
    # so a capture is NEVER silently lost. Recorded in summary.json AND printed
    # to stderr; the batch still completed and emitted all other buckets.
    if unrouted_A:
        summary["bucket_A_unrouted"] = [
            {"step": r.get("step") or "(no step)",
             "design": r.get("design", "?"),
             "rule_name": r.get("rule_name", "")}
            for r in unrouted_A
        ]
        print(
            f"WARNING: {len(unrouted_A)} Bucket-A record(s) had no routable "
            f"`bucket_A_program` (step unlisted in CAPTURE_ROUTING.json, or "
            f"listed with an explicit null program layer). Their program-rule "
            f"sketch was SKIPPED and they are reported below as unrouted — the "
            f"rest of the batch emitted normally. Add a routing entry (or a "
            f"real program) for:",
            file=sys.stderr)
        for u in summary["bucket_A_unrouted"]:
            print(f"  - step={u['step']!r} rule={u['rule_name']!r} "
                  f"(design {u['design']})", file=sys.stderr)

    (out / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
