#!/usr/bin/env python3
"""flow_doc_emit.py — auto-generate the RUNNER-MARKER view of the Vibe-IC flow.

The flow docs (CANONICAL_FLOW / ALL_STEPS) kept going stale because the step lists were
hand-maintained while the runners moved. This generator makes the *ground-truth* part —
the actual `[N/15]` markers and `def step_*` functions the runners contain — a DERIVED
artefact, the same way `tools/gen_programs_index.py` makes `INDEX.md` derived.

Source of truth = the runner files. This script parses them and emits
`docs/architecture/FLOW_STEPS_GENERATED.md`. The narrative docs (CANONICAL_FLOW_v2.2.0,
ALL_STEPS_v2.2.0) and the curated 33-step / LVS-chain / sign-off tables stay hand-authored
(they are not derivable from markers) and link to this generated file for the live step lists.

Usage:
    python3 flow_doc_emit.py            # write FLOW_STEPS_GENERATED.md
    python3 flow_doc_emit.py --check    # exit 1 if the committed file is stale (CI freshness)
    python3 flow_doc_emit.py --stdout   # print to stdout, write nothing
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

PROGRAMS = Path(__file__).resolve().parent
# programs/ = <repo>/vibe-ic-marketplace/plugins/vibe-ic/programs → repo root = parents[3].
REPO = PROGRAMS.parents[3]
OUT = REPO / "docs" / "architecture" / "FLOW_STEPS_GENERATED.md"

P1 = PROGRAMS / "phase1_doc_one_shot_runner.py"
P2 = PROGRAMS / "phase2_one_shot_runner.py"
P3 = PROGRAMS / "phase3_one_shot_runner.py"
PA = PROGRAMS / "analog_one_shot_runner.py"


def _read(p: Path) -> str:
    return p.read_text(errors="replace") if p.is_file() else ""


def phase1_markers(src: str) -> List[Tuple[str, str]]:
    """[(marker, description)] from `print(f"[N/15] desc ...")`, first occurrence, in order.

    Only matches print() strings (not comments), so a `# ... [14b/15] ...` comment is ignored.
    """
    out: List[Tuple[str, str]] = []
    seen = set()
    pat = re.compile(r'print\(\s*f?"(\s*\[[0-9]+[a-z0-9]*/15\])\s*([^"]*?)"', re.IGNORECASE)
    for m in pat.finditer(src):
        marker = m.group(1).strip()
        desc = m.group(2).strip()
        # strip trailing " ..." progress dots
        desc = re.sub(r"\s*\.\.\.\s*$", "", desc).strip()
        if marker in seen:
            continue
        seen.add(marker)
        out.append((marker, desc))
    return out


def step_functions(src: str) -> List[str]:
    """Ordered, de-duplicated `def step_*` names (source order = definition order)."""
    out: List[str] = []
    seen = set()
    for m in re.finditer(r"^def (step_[a-z0-9_]+)\s*\(", src, re.MULTILINE):
        name = m.group(1)
        if name not in seen:
            seen.add(name)
            out.append(name)
    return out


def analog_steps(src: str) -> List[Tuple[str, str, str]]:
    """[(Ax, name, output)] from the header block `  A1 spec_extract  -> analog/...`."""
    out: List[Tuple[str, str, str]] = []
    seen = set()
    pat = re.compile(r"^\s*(A[1-9])\s+(\w+)\s+→\s+(.*)$", re.MULTILINE)
    for m in pat.finditer(src):
        ax = m.group(1)
        if ax in seen:
            continue
        seen.add(ax)
        out.append((ax, m.group(2), m.group(3).strip()))
    return out


def _table(headers: List[str], rows: List[List[str]]) -> str:
    line = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join(["---"] * len(headers)) + "|"
    body = "\n".join("| " + " | ".join(r) + " |" for r in rows)
    return f"{line}\n{sep}\n{body}"


def render() -> str:
    p1 = phase1_markers(_read(P1))
    p2 = step_functions(_read(P2))
    p3 = step_functions(_read(P3))
    pa = analog_steps(_read(PA))

    parts: List[str] = []
    parts.append("# Vibe-IC Flow — runner-marker view (AUTO-GENERATED)\n")
    parts.append(
        "> **AUTO-GENERATED by `programs/flow_doc_emit.py` — do not hand-edit.** This is the\n"
        "> ground-truth step list parsed directly from the runners. The narrative docs\n"
        "> (`CANONICAL_FLOW_v2.2.0.md`, `ALL_STEPS_v2.2.0.md`) and the curated 33-step / LVS-chain\n"
        "> / sign-off tables link here for the live lists. Regenerate: `python3 flow_doc_emit.py`.\n"
    )

    parts.append(f"\n## Phase 1 — `phase1_doc_one_shot_runner.py` ({len(p1)} markers)\n")
    parts.append(_table(["Marker", "Step"], [[mk, ds or "—"] for mk, ds in p1]))

    parts.append(f"\n## Phase 2 — `phase2_one_shot_runner.py` ({len(p2)} step functions)\n")
    parts.append(_table(["#", "Step function"],
                        [[str(i + 1), f"`{s}`"] for i, s in enumerate(p2)]))

    parts.append(f"\n## Phase 3 — `phase3_one_shot_runner.py` ({len(p3)} step functions)\n")
    parts.append(_table(["#", "Step function"],
                        [[str(i + 1), f"`{s}`"] for i, s in enumerate(p3)]))

    parts.append(f"\n## Analog — `analog_one_shot_runner.py` ({len(pa)} steps)\n")
    parts.append(_table(["Step", "Name", "Output"],
                        [[ax, f"`{nm}`", out] for ax, nm, out in pa]))

    parts.append(
        f"\n## Totals\n\nPhase 1 markers: {len(p1)} · Phase 2 steps: {len(p2)} · "
        f"Phase 3 steps: {len(p3)} · Analog: {len(pa)}\n"
    )
    return "\n".join(parts) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed FLOW_STEPS_GENERATED.md is stale")
    ap.add_argument("--stdout", action="store_true", help="print, write nothing")
    args = ap.parse_args(argv)

    content = render()
    if args.stdout:
        sys.stdout.write(content)
        return 0
    if args.check:
        existing = OUT.read_text(errors="replace") if OUT.is_file() else ""
        if existing != content:
            print(f"STALE: {OUT} differs from generator output — run "
                  f"`python3 flow_doc_emit.py`.", file=sys.stderr)
            return 1
        print(f"FRESH: {OUT.name} matches the runner markers.")
        return 0
    OUT.write_text(content)
    print(f"wrote {OUT} "
          f"(P1={content.count('/15]')} markers shown)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
