#!/usr/bin/env python3
"""generated_artifact_conflict_resolve.py — resolve the merge conflicts that
carry no information, and REFUSE every conflict that does.

THE DEFECT (vibe-ic#1363), measured
===================================
`programs/INDEX.md` is a DERIVED artefact — its own first line says
`AUTO-GENERATED by tools/gen_programs_index.py — DO NOT EDIT BY HAND`, a
freshness test regenerates it and FAILs on drift, and `tools/ci/
repo_hygiene_gates.sh` runs the generator's `--check` on every landing. It is
also COMMITTED, and git 3-way-merges it as ordinary text.

So every PR that adds a program rewrites the same generated lines, and any one
landing makes the alphabetically-adjacent ones conflict. Measured over all 163
open PRs at `24ff9530`: 29 conflicting, and **26 of them conflicted on
`programs/INDEX.md` and on nothing else**. Three PRs disagreed about real
content. The repo's conflict rate was one unmanaged generated file.

Because the resolution never depends on what either side wrote — regenerate,
stage, done — the conflict carries NO INFORMATION. A conflict that is always
resolved the same way is pure cost, and it is paid once per PR per landing.

WHY A PROGRAM AND NOT A MERGE DRIVER
====================================
The obvious answer is `.gitattributes` + a merge driver. Both variants were
measured on git 2.43.0 and both are dead ends:

  `merge=ours`, attribute alone   NO-OP. `ours` is not one of git's built-in
                                  drivers (`text`/`binary`/`union` are), so
                                  without a per-clone `merge.ours.driver` the
                                  merge still conflicts: rc=1, 2 markers.

  `merge=ours` + the config       Merges clean — AND STILL CANNOT LAND. The
                                  incoming side's row is silently dropped, so
                                  `gen_programs_index.py --check` goes rc=1
                                  (`INDEX.md is stale`). The refusal MOVES from
                                  the merge to the freshness gate; it does not
                                  go away. Nothing is unblocked.

  a driver that REGENERATES       IMPOSSIBLE. A merge driver runs BEFORE the
                                  working tree is complete. Instrumented on the
                                  two-adjacent-programs repro, at driver time:
                                      zz_probe_aaa.py on disk: YES
                                      zz_probe_aab.py on disk: NO
                                  and `YES` only after the merge returned. A
                                  driver that regenerates therefore emits an
                                  INDEX missing exactly the program the incoming
                                  side added — a wrong answer, confidently.

Regeneration is only correct AFTER the file-level merge finishes. That is what
this program does, and it is why it is a post-merge step rather than a merge
policy.

WHAT IT REFUSES, AND WHY THAT IS THE POINT
==========================================
The hand recipe posted on #1253 is `git merge; regenerate; git add`. It has no
guard: run it on a merge that conflicted on INDEX.md **and** on a real file and
it stages a regenerated catalog on top of an unresolved conflict, which looks
like progress. So the verdict here is not "regenerate" — it is:

    is every conflicted path a registered derived artefact?

and a single foreign path REFUSES THE WHOLE RESOLUTION, including the derived
half. Partially resolving hides a real conflict behind a smaller-looking one,
and a human is in the loop for the foreign path anyway.

EVERY WAY THIS CAN DEGRADE, DEGRADES TOWARD REFUSING
====================================================
  no conflict in progress          rc=2 — a resolver that reports a resolution
                                   it did not perform is a liar.
  regenerator absent (cache tree)  rc=2 — not "nothing to do".
  regenerator non-zero / times out rc=2 — an unmeasured tree is not a clean one.
  markers survive regeneration     rc=2 — the artefact is not fully derived.
  `--check` still red afterwards   rc=2 — the bytes written are not the bytes
                                   the freshness gate demands, so staging them
                                   would only move the failure again.
  a path still conflicted after    rc=2.
  a foreign conflicted path        rc=1, and it is NAMED.

Only "every conflicted path is registered, regenerated, verified fresh, and
staged" exits 0.

THE INNER TIMEOUT IS 60s AND THAT IS A CEILING, NOT AN ESTIMATE
===============================================================
The landing harness runs at `--timeout=180 --timeout-method=thread`. An inner
bound above that lets one hung regenerator kill the whole SESSION instead of one
step, losing every other result in the run unnamed. So the bound is 60s.

`gen_programs_index.py` over 1165 files measured 25-28s warm and EXCEEDED 60s on
a cold tree (first run after a `git worktree add`). A cold-tree timeout is
therefore expected and is reported as rc=2 with that fact in the message — the
question could not be put, which is not the same as an answer.

Usage:
    generated_artifact_conflict_resolve.py [--repo DIR] [--dry-run] [--json OUT]

Exit codes:
    0 = RESOLVED     every conflicted path was a registered derived artefact;
                     each was regenerated, verified fresh, and staged
    1 = REFUSED      at least one conflicted path is not a derived artefact
    2 = UNMEASURABLE the question could not be put (see the table above)
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))  # so the sibling import below resolves however this is invoked
from _atomic_artefact import write_json  # noqa: E402  vibe-ic#1082 (helper from PR #1094)

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _progress_run as _pr  # noqa: E402

# The landing harness runs at --timeout=180 --timeout-method=thread; an inner
# bound above that turns one hung regenerator into a lost SESSION.
SUBPROCESS_TIMEOUT_S = 60

CONFLICT_MARKERS = ("<<<<<<< ", "=======", ">>>>>>> ")


# ─── the registry ───────────────────────────────────────────────────
@dataclass(frozen=True)
class DerivedArtifact:
    """A COMMITTED file whose correct bytes are a pure function of the tree.

    `regenerate` writes those bytes; `check` exits 0 iff the committed bytes
    already are those bytes. Both are argv run at the REPO ROOT. `generator`
    is the path that must exist for the entry to be usable at all — on the
    flattened plugin cache the repo-root tools are absent, and that is an
    UNMEASURABLE state, not a clean one.
    """

    path: str
    generator: str
    regenerate: tuple[str, ...]
    check: tuple[str, ...]


_INV = "vibe-ic-marketplace/plugins/vibe-ic/programs/gen_program_inventory.py"

REGISTRY: tuple[DerivedArtifact, ...] = (
    DerivedArtifact(
        path="vibe-ic-marketplace/plugins/vibe-ic/programs/INDEX.md",
        generator="tools/gen_programs_index.py",
        regenerate=("python3", "tools/gen_programs_index.py"),
        check=("python3", "tools/gen_programs_index.py", "--check"),
    ),
    # PROGRAM_INVENTORY.json is the SECOND file every program-adding branch
    # rewrites, and it conflicted alongside INDEX.md on a real merge of
    # jdistmat/matrix-distil into main a4caccefe. Unregistered, it was named as
    # a FOREIGN path and refused the whole resolution -- including the derived
    # half that was resolvable -- so the merge was finished by hand.
    #
    # `--check-artifact`, NOT `--check`. Full --check also binds stated counts
    # in the two READMEs, which regenerating this artefact cannot fix. Measured:
    # with the JSON freshly regenerated, --check was still red on five README
    # lines. Registered with --check, this entry would therefore leave `check`
    # red after a correct regeneration, and the degradation table above turns
    # that into rc 2, UNMEASURABLE -- reporting an unmeasurable tree where the
    # artefact is provably correct. The prose obligation is real and full
    # --check still enforces it at landing; it is not the question a
    # post-merge resolver asks.
    DerivedArtifact(
        path="vibe-ic-marketplace/plugins/vibe-ic/programs/PROGRAM_INVENTORY.json",
        generator=_INV,
        regenerate=("python3", _INV),
        check=("python3", _INV, "--check-artifact"),
    ),
)


# ─── the verdict ────────────────────────────────────────────────────
@dataclass
class Verdict:
    code: int                       # 0 RESOLVED / 1 REFUSED / 2 UNMEASURABLE
    reason: str
    conflicted: tuple[str, ...] = ()
    derived: tuple[str, ...] = ()   # conflicted AND registered
    foreign: tuple[str, ...] = ()   # conflicted AND not registered
    regenerated: list[str] = field(default_factory=list)
    staged: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "code": self.code,
            "verdict": {0: "RESOLVED", 1: "REFUSED", 2: "UNMEASURABLE"}[self.code],
            "reason": self.reason,
            "conflicted": list(self.conflicted),
            "derived": list(self.derived),
            "foreign": list(self.foreign),
            "regenerated": list(self.regenerated),
            "staged": list(self.staged),
        }


def decide(
    conflicted: Sequence[str],
    registry: Sequence[DerivedArtifact] = REGISTRY,
) -> Verdict:
    """THE DECISION, in one function, with no side effects.

    Kept separate from the regeneration so a mutant that neuters the refusal
    has exactly one site to neuter and has to leave every other line standing —
    which is the only way to show the tests read the DECISION and not the
    plumbing.
    """
    conflicted = tuple(sorted(set(conflicted)))
    known = {a.path for a in registry}
    if not conflicted:
        return Verdict(
            2,
            "no conflicted path — this resolver was invoked outside a "
            "conflicted merge, and a resolver that reports a resolution it did "
            "not perform is worse than one that refuses",
        )
    derived = tuple(p for p in conflicted if p in known)
    foreign = tuple(p for p in conflicted if p not in known)
    if foreign:
        return Verdict(
            1,
            f"{len(foreign)} conflicted path(s) carry real disagreement and "
            f"cannot be regenerated; refusing the whole resolution so the "
            f"derived half cannot hide them",
            conflicted=conflicted,
            derived=derived,
            foreign=foreign,
        )
    return Verdict(
        0,
        f"every conflicted path ({len(derived)}) is a registered derived "
        f"artefact",
        conflicted=conflicted,
        derived=derived,
    )


# ─── the git surface ────────────────────────────────────────────────
def _git(root: Path, *args: str) -> subprocess.CompletedProcess:
    return _pr.run(
        ("git", "-C", str(root)) + args,
        capture_output=True,
        text=True,
        
    )


def conflicted_paths(root: Path) -> Optional[tuple[str, ...]]:
    """Repo-relative paths git reports as unmerged, or None if it could not
    be asked (which is UNMEASURABLE, never an empty list)."""
    try:
        cp = _git(root, "diff", "--name-only", "--diff-filter=U")
    except (OSError, subprocess.SubprocessError):
        return None
    if cp.returncode != 0:
        return None
    return tuple(p for p in cp.stdout.splitlines() if p.strip())


def _has_markers(p: Path) -> bool:
    try:
        text = p.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return True  # unreadable is not "clean"
    return any(
        line.startswith(m) for line in text.splitlines() for m in CONFLICT_MARKERS
    )


def resolve(
    root: Path,
    registry: Sequence[DerivedArtifact] = REGISTRY,
    dry_run: bool = False,
) -> Verdict:
    """Read the conflicted set, decide, and — only on a RESOLVED decision and
    only when not a dry run — regenerate, verify, and stage."""
    paths = conflicted_paths(root)
    if paths is None:
        return Verdict(2, f"git could not report the unmerged paths under {root}")
    v = decide(paths, registry)
    if v.code != 0 or dry_run:
        if dry_run and v.code == 0:
            v.reason += " (dry run — nothing was regenerated or staged)"
        return v

    by_path = {a.path: a for a in registry}
    for rel in v.derived:
        art = by_path[rel]
        gen = root / art.generator
        if not gen.exists():
            return Verdict(
                2,
                f"{rel}: its generator {art.generator} is not present under "
                f"{root} (the repo-root tools are absent on the flattened "
                f"plugin cache); the artefact cannot be regenerated here",
                conflicted=v.conflicted, derived=v.derived,
            )
        try:
            cp = _pr.run(
                art.regenerate, cwd=str(root), capture_output=True,
                text=True)
        except _pr.Stalled:
            return Verdict(
                2,
                f"{rel}: {' '.join(art.regenerate)} STOPPED MAKING PROGRESS "
                f"and was killed. A cold tree is no longer the explanation — "
                f"this generator measured 25-28s warm and over 60s cold, and "
                f"both now run to completion. The question was not answered.",
                conflicted=v.conflicted, derived=v.derived,
            )
        except OSError as e:
            return Verdict(
                2, f"{rel}: {' '.join(art.regenerate)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived,
            )
        if cp.returncode != 0:
            return Verdict(
                2,
                f"{rel}: {' '.join(art.regenerate)} exited {cp.returncode}; "
                f"an unmeasured tree is not a clean one. "
                f"{(cp.stderr or cp.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
            )
        v.regenerated.append(rel)

        if _has_markers(root / rel):
            return Verdict(
                2,
                f"{rel}: conflict markers SURVIVED regeneration, so this file "
                f"is not fully derived from the tree and the registry entry is "
                f"wrong about it",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )

        try:
            chk = subprocess.run(
                art.check, cwd=str(root), capture_output=True,
                text=True, timeout=SUBPROCESS_TIMEOUT_S,
            )
        except (OSError, subprocess.SubprocessError) as e:
            return Verdict(
                2, f"{rel}: {' '.join(art.check)} could not be run: {e}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )
        if chk.returncode != 0:
            return Verdict(
                2,
                f"{rel}: regenerated, but {' '.join(art.check)} is still "
                f"rc={chk.returncode} — the bytes written are not the bytes the "
                f"freshness gate demands, so staging them would only move the "
                f"failure. {(chk.stderr or chk.stdout).strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated,
            )

        add = _git(root, "add", "--", rel)
        if add.returncode != 0:
            return Verdict(
                2, f"{rel}: git add failed: {add.stderr.strip()[:300]}",
                conflicted=v.conflicted, derived=v.derived,
                regenerated=v.regenerated, staged=v.staged,
            )
        v.staged.append(rel)

    left = conflicted_paths(root)
    if left is None:
        return Verdict(
            2, "git could not re-report the unmerged paths after staging",
            conflicted=v.conflicted, derived=v.derived,
            regenerated=v.regenerated, staged=v.staged,
        )
    if left:
        return Verdict(
            2,
            f"{len(left)} path(s) are STILL unmerged after staging "
            f"({', '.join(left)}); the resolution did not take",
            conflicted=v.conflicted, derived=v.derived,
            regenerated=v.regenerated, staged=v.staged,
        )
    return v


# ─── CLI ────────────────────────────────────────────────────────────
def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Resolve merge conflicts on registered derived artefacts; "
                    "refuse every other conflict."
    )
    ap.add_argument("--repo", default=".",
                    help="repo root (default: cwd)")
    ap.add_argument("--dry-run", action="store_true",
                    help="report the verdict without regenerating or staging")
    ap.add_argument("--json", dest="json_out", default=None,
                    help="write the verdict record to this path")
    a = ap.parse_args(argv)

    root = Path(a.repo).resolve()
    top = None
    try:
        cp = _git(root, "rev-parse", "--show-toplevel")
        if cp.returncode == 0 and cp.stdout.strip():
            top = Path(cp.stdout.strip())
    except (OSError, subprocess.SubprocessError):
        top = None
    if top is None:
        v = Verdict(2, f"{root} is not inside a git work tree")
    else:
        v = resolve(top, REGISTRY, dry_run=a.dry_run)

    if a.json_out:
        try:
            # vibe-ic#1082 / #1462: the verdict record is the artefact a later
            # reader opens to learn whether the merge was resolved or refused.
            # `.write_text` creates that name before filling it, so a death
            # mid-write leaves a truncated record under the name a
            # `required_outputs` check reads as "this step produced its
            # evidence". `ensure_ascii=True` keeps the payload byte-identical
            # to the call this replaces — the conversion moves WHEN the name
            # appears, never WHAT is written.
            write_json(a.json_out, v.to_dict(), ensure_ascii=True)
        except OSError as e:
            print(f"[WARN] could not write {a.json_out}: {e}", file=sys.stderr)

    if v.code == 1:
        for p in v.foreign:
            print(f"  CONFLICT (real)  {p}", file=sys.stderr)
        print(f"[REFUSED] {v.reason}", file=sys.stderr)
    elif v.code == 2:
        print(f"[UNMEASURABLE] {v.reason}", file=sys.stderr)
    else:
        for p in v.staged:
            print(f"  regenerated + staged  {p}", file=sys.stderr)
        print(f"[RESOLVED] {v.reason}.", file=sys.stderr)
    return v.code


if __name__ == "__main__":
    # A stall is not a verdict about the commit: reach the stamp as rc 2
    # (this gate's 'could not measure'), announced, never as a finding.
    raise SystemExit(_pr.exit_undetermined_on_stall(main))
