"""magic_extract_spice_emit.py — Magic parasitic-RC extraction TCL emitter + validator.

What this is (Bucket-B program extracted from skills/analog-extraction-resim)
=============================================================================

The `analog-extraction-resim` skill embedded a fixed Magic TCL recipe as
prose:

    load <block>
    extract all
    ext2spice lvs
    ext2spice

This recipe is the canonical post-layout *parasitic-RC* extraction used to
re-simulate an analog block (Step A7) — it loads the `.mag` LAYOUT (not a
GDS) and emits an RC-annotated SPICE netlist that is then substituted for
the ideal subcircuit in the existing testbench.

It is FULLY deterministic given (block_cell, out_spice, options) — no LLM
judgment — so per the closed-loop-enhancement-capture-doctrine it belongs
in a program, not skill prose. This mirrors `magic_port_extract_emit.py`
(which is the *different* GDS-read + port-promote recipe for LVS anchoring),
but is a distinct flow:

    magic_port_extract_emit.py  : `gds read` + `port makeall`  -> LVS port anchor
    magic_extract_spice_emit.py : `load` (.mag) + `extract all` -> parasitic-RC resim

Two entry points
================

1. EMIT (build_extraction_tcl): generate the deterministic TCL.
2. VALIDATE (validate_extraction_tcl / CLI --validate): given an
   already-written extraction TCL, confirm it contains every command the
   parasitic-RC resim flow REQUIRES. The single most common silent defect
   this catches: an extraction script that omits `ext2spice lvs`, which
   makes Magic emit a netlist WITHOUT the `.subckt`/port wrapper, so the
   re-sim testbench cannot bind the extracted block to its ideal port order
   — the resim then silently runs the *pre-layout* ideal subcircuit and the
   pre-vs-post comparison shows a (false) 0% degradation. A second defect:
   omitting `extract all` (or substituting a hierarchical extract that
   skips parasitics) yields an R/C-free netlist — a vacuous "no degradation"
   PASS. The validator FAILs honestly on both, and on missing/garbage input.

CLI
===
    # emit
    python3 magic_extract_spice_emit.py --block ldo_1v8 --out-spice ldo_1v8_extracted.spice
    python3 magic_extract_spice_emit.py --block ldo --out-spice o.spice --out extract.tcl

    # validate an existing TCL (honest FAIL on missing/garbage)
    python3 magic_extract_spice_emit.py --validate extract.tcl
    python3 magic_extract_spice_emit.py --validate extract.tcl --json report.json

Exit codes:
    0 = PASS (emit succeeded, or validate found a conformant recipe)
    1 = FAIL (validate found a non-conformant / RC-free recipe)
    2 = IO / usage error (missing file, empty arg, etc.)

Unit-tested in `programs/tests/test_magic_extract_spice_emit.py`.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import List, Optional


# ---------------------------------------------------------------------------
# EMIT
# ---------------------------------------------------------------------------
@dataclass
class MagicResimExtractOptions:
    """Knobs for the parasitic-RC extraction TCL, all deterministic.

    `cthresh` / `rthresh`: Magic `extract` thresholds — capacitances below
        `cthresh` (fF) and resistances below `rthresh` (ohms) are dropped.
        Defaults (0 / 0) keep ALL parasitics, which is the conservative
        post-layout-resim choice (no parasitic is silently discarded).
    `ext2spice_scale_off`: emit `ext2spice scale off` so device geometries
        are absolute, matching the PDK SPICE models.
    """
    cthresh: float = 0.0
    rthresh: float = 0.0
    ext2spice_scale_off: bool = True


def build_extraction_tcl(
    block_cell: str,
    out_spice: str,
    options: Optional[MagicResimExtractOptions] = None,
) -> str:
    """Generate the Magic parasitic-RC extraction TCL for post-layout resim.

    Chip-agnostic: every cell-specific token is a parameter. Returns a
    multi-line string ready to be written to a `.tcl` and fed to magic.
    Raises ValueError on an empty block_cell / out_spice (honest failure).
    """
    if not (block_cell or "").strip():
        raise ValueError("block_cell must be a non-empty cell name")
    if not (out_spice or "").strip():
        raise ValueError("out_spice must be a non-empty output path")
    opts = options or MagicResimExtractOptions()

    out: List[str] = []
    out.append(
        "#---------------------------------------------------------------\n"
        "# Vibe-IC plugin — Magic parasitic-RC extraction (post-layout resim)\n"
        "# Loads the .mag LAYOUT and emits an RC-annotated .subckt netlist\n"
        "# for substitution into the existing analog testbench (Step A7).\n"
        "# Generated by programs/magic_extract_spice_emit.py\n"
        "#---------------------------------------------------------------"
    )
    out.append(f"load {block_cell}")
    out.append("select top cell")
    # extract thresholds: keep all parasitics by default (cthresh/rthresh 0).
    out.append(f"extract style ngspice")
    out.append(f"extresist all")
    out.append(f"extract all")
    if opts.ext2spice_scale_off:
        out.append("ext2spice scale off")
    out.append(f"ext2spice cthresh {opts.cthresh}")
    out.append(f"ext2spice rthresh {opts.rthresh}")
    # `ext2spice lvs` MUST precede the final ext2spice so the emitted netlist
    # is wrapped in a .subckt with the block's ports (the resim binds to it).
    out.append("ext2spice lvs")
    out.append(f"ext2spice -o {out_spice}")
    out.append(
        "# Audit: the emitted file MUST contain a non-empty `.subckt {blk}`\n"
        "# with R/C parasitic elements; an R/C-free netlist means extract all\n"
        "# dropped parasitics -> the resim would falsely show 0% degradation."
        .replace("{blk}", block_cell)
    )
    out.append(f"puts stdout \"MAGIC_EXTRACT_RESIM_DONE {block_cell} -> {out_spice}\"")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------
# VALIDATE
# ---------------------------------------------------------------------------
# The commands the parasitic-RC resim recipe REQUIRES, each with the silicon
# reason it is mandatory. A validated TCL must contain every one of these.
_REQUIRED = [
    ("load",
     r"^\s*load\b",
     "load the .mag layout cell (the source of the parasitics)"),
    ("extract_all",
     r"^\s*extract\s+all\b",
     "extract all — without it the netlist carries NO R/C parasitics "
     "(vacuous 0% post-layout degradation)"),
    ("ext2spice_lvs",
     r"^\s*ext2spice\s+lvs\b",
     "ext2spice lvs — wraps the netlist in a .subckt with ports so the "
     "resim testbench can bind the block (else the ideal subckt runs)"),
    ("ext2spice_out",
     r"^\s*ext2spice\b(?!\s+(lvs|scale|cthresh|rthresh|format)\b)",
     "a bare ext2spice (or ext2spice -o) to actually WRITE the netlist"),
]


@dataclass
class Finding:
    rule: str
    severity: str
    message: str


@dataclass
class ValidateResult:
    program: str = "magic_extract_spice_emit"
    version: str = "1.0.0"
    mode: str = "validate"
    passed: bool = False
    tcl_file: str = ""
    findings: List[Finding] = field(default_factory=list)
    summary: dict = field(default_factory=dict)


def validate_extraction_tcl(text: str, tcl_file: str = "") -> ValidateResult:
    """Validate that `text` is a conformant parasitic-RC extraction recipe.

    Honest failure semantics:
      - empty / whitespace-only text  -> FAIL (EMPTY_TCL)
      - text with none of the required commands -> FAIL (NOT_AN_EXTRACTION_TCL)
      - any single required command missing -> FAIL (MISSING_<cmd>)
    A vacuous PASS is impossible: PASS requires ALL required commands present.
    """
    result = ValidateResult(tcl_file=tcl_file)

    if not (text or "").strip():
        result.passed = False
        result.findings.append(Finding(
            "EMPTY_TCL", "ERROR",
            "extraction TCL is empty/whitespace — nothing to extract"))
        result.summary = {"present": [], "missing": [k for k, _, _ in _REQUIRED]}
        return result

    lines = text.splitlines()

    def _present(pattern: str) -> bool:
        rx = re.compile(pattern, re.IGNORECASE)
        for ln in lines:
            stripped = ln.split("#", 1)[0]  # ignore comments
            if rx.search(stripped):
                return True
        return False

    present: List[str] = []
    missing: List[str] = []
    for key, pattern, reason in _REQUIRED:
        if _present(pattern):
            present.append(key)
        else:
            missing.append(key)
            result.findings.append(Finding(
                f"MISSING_{key.upper()}", "ERROR",
                f"required command missing: {reason}"))

    # If NOTHING matched, this isn't an extraction TCL at all — distinct
    # ERROR so a caller can tell "wrong file" from "incomplete recipe".
    if not present:
        result.findings = [Finding(
            "NOT_AN_EXTRACTION_TCL", "ERROR",
            "no Magic extraction commands found — not a parasitic-RC "
            "extraction recipe")]

    result.passed = not missing
    if result.passed:
        result.findings.append(Finding(
            "EXTRACTION_RECIPE_OK", "INFO",
            "all required parasitic-RC extraction commands present"))
    result.summary = {"present": present, "missing": missing}
    return result


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main(argv: list = None) -> int:
    p = argparse.ArgumentParser(
        description="Emit OR validate a Magic parasitic-RC extraction TCL "
                    "(deterministic, chip-agnostic).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--validate", metavar="TCL", default=None,
                   help="Validate an existing extraction TCL instead of emitting")
    p.add_argument("--block", default=None, help="Block/cell name (emit mode)")
    p.add_argument("--out-spice", default=None,
                   help="Output SPICE path written by the emitted TCL (emit mode)")
    p.add_argument("--cthresh", type=float, default=0.0)
    p.add_argument("--rthresh", type=float, default=0.0)
    p.add_argument("--no-scale-off", action="store_true")
    p.add_argument("--out", type=Path, default=None,
                   help="Write the emitted TCL here; default stdout (emit mode)")
    p.add_argument("--json", default=None, help="JSON report path (validate mode)")
    args = p.parse_args(argv)

    # ----- VALIDATE MODE -----
    if args.validate is not None:
        tcl_path = Path(args.validate)
        if not tcl_path.is_file():
            print(f"ERROR: {tcl_path} is not a file", file=sys.stderr)
            return 2
        try:
            text = tcl_path.read_text(errors="replace")
        except OSError as e:
            print(f"ERROR: cannot read {tcl_path}: {e}", file=sys.stderr)
            return 2
        result = validate_extraction_tcl(text, str(tcl_path))
        out = json.dumps(asdict(result), indent=2, ensure_ascii=False)
        if args.json:
            Path(args.json).parent.mkdir(parents=True, exist_ok=True)
            Path(args.json).write_text(out)
        else:
            status = "PASS" if result.passed else "FAIL"
            print(f"[{status}] magic_extract_spice_emit --validate {tcl_path}")
            for f in result.findings:
                if f.severity in ("ERROR", "WARNING"):
                    print(f"  [{f.severity}] {f.rule}: {f.message}")
        return 0 if result.passed else 1

    # ----- EMIT MODE -----
    if not args.block or not args.out_spice:
        print("ERROR: emit mode requires --block and --out-spice "
              "(or use --validate <tcl>)", file=sys.stderr)
        return 2
    opts = MagicResimExtractOptions(
        cthresh=args.cthresh,
        rthresh=args.rthresh,
        ext2spice_scale_off=not args.no_scale_off,
    )
    try:
        tcl = build_extraction_tcl(args.block, args.out_spice, opts)
    except ValueError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2
    if args.out:
        args.out.write_text(tcl, encoding="utf-8")
        print(f"wrote: {args.out}", file=sys.stderr)
    else:
        print(tcl, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
