#!/usr/bin/env python3
"""
migrate_to_canonical_taxonomy.py — one-shot migration tool that moves
stray top-level entries and stray `reports/` flat artefacts into the
canonical Phase/Stage/Step layout enforced by v1.6.26's
`top_level_outputs_in_canonical_check` and
`reports_subfolder_taxonomy_check`.

Why this exists
---------------
v1.6.26 added two enforcement gates whitelisting the project root
(`input/`, `phase1/`, `phase2/`, `phase3/`, `analog/`, `reports/` +
3 metadata files) and `reports/` subfolders (the 6 phase-aligned
parents `phase1/phase2/phase3/analog/audit/orchestrator`). Existing
benchmarks (v10623, v10619 etc.) were generated by older runners that
wrote to flat top-level paths (`fpga/`, `logs/`, `sim/`, `rtl.pre_gen_backup/`)
plus 4 phase1 metadata files at the project root. v1.6.26's commit
msg claimed the benchmarks were migrated; independent audit shows
they were NOT. This tool actually finishes the job.

Behaviour (chip-AGNOSTIC)
-------------------------
1. Top-level dir migrations (project/<name> → canonical parent):
     fpga              → phase2/stage1/fpga              (merge if exists)
     sim               → phase2/stage1/sim
     formal            → phase2/stage1/formal
     tb                → phase2/stage1/tb
     sim_full_stack    → phase2/stage1/sim_full_stack
     rtl.pre_gen_backup→ phase2/stage1/rtl.pre_gen_backup
     synth             → phase2/stage2/synth
     constraints       → phase2/stage2/constraints
     dft               → phase2/stage2/dft
     pnr               → phase3/stage3/pnr
     cts               → phase3/stage3/cts
     extracted         → phase3/stage3/extracted
     eco               → phase3/stage3/eco
     spice             → phase3/stage3/spice
     sta               → phase3/stage3/sta
     sim_postlayout    → phase3/stage3/sim_postlayout
     gds               → phase3/stage4/gds
     foundry_handoff   → phase3/stage4/foundry_handoff
     mixed_signal      → phase3/mixed_signal
     cosim             → phase3/mixed_signal/cosim
     hardmacro         → analog/hardmacro
     extracted_docs    → phase1/input_doc
     generated_docs    → phase1/generated_docs
     logs / run_logs   → reports/orchestrator/logs

2. Top-level metadata files → phase1/ (per v1.6.26 helpers):
     extraction_patterns.json      / .auto.json
     completeness_check_config.json
     ai_deep_review_patches.json

3. reports/<flat_subdir>/ → reports/<phase_parent>/<flat_subdir>/
   Heuristic (chip-AGNOSTIC, name-based):
     phase2 parent: cdc, coverage, lint, fpga, gates
     phase2 stage2: dft, synth
     phase3 parent:  pnr, cts, sta, mixed_signal, signoff
     audit:          (default for unknown)

4. reports/<file> at top → routed via `_pl.report_path()` auto-router.

Whitelisted (left in place):
     input/, phase1/, phase2/, phase3/, analog/, reports/
     provenance.jsonl, rig_topology.json, waivers.json
     AGENT_REPORT.md (top-level *.md is housekeeping per v1.6.26 spec)

Usage:
    python3 migrate_to_canonical_taxonomy.py <project_dir> [--dry-run]
                                                            [--json <out>]
Exit codes:
    0  PASS (migration completed or VACUOUS — nothing stray)
    1  one or more moves blocked by destination conflict (manual fix)
    2  argument or I/O error
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import List, Optional, Tuple

import _path_layout as _pl


# Top-level dir → canonical destination relative path.
_DIR_MIGRATIONS = {
    "fpga":               "phase2/stage1/fpga",
    "sim":                "phase2/stage1/sim",
    "formal":             "phase2/stage1/formal",
    "tb":                 "phase2/stage1/tb",
    "sim_full_stack":     "phase2/stage1/sim_full_stack",
    "rtl.pre_gen_backup": "phase2/stage1/rtl.pre_gen_backup",
    "rtl":                "phase2/stage1/rtl",
    "synth":              "phase2/stage2/synth",
    "constraints":        "phase2/stage2/constraints",
    "dft":                "phase2/stage2/dft",
    "pnr":                "phase3/stage3/pnr",
    "cts":                "phase3/stage3/cts",
    "extracted":          "phase3/stage3/extracted",
    "eco":                "phase3/stage3/eco",
    "spice":              "phase3/stage3/spice",
    "sta":                "phase3/stage3/sta",
    "sim_postlayout":     "phase3/stage3/sim_postlayout",
    "gds":                "phase3/stage4/gds",
    "foundry_handoff":    "phase3/stage4/foundry_handoff",
    "mixed_signal":       "phase3/mixed_signal",
    "cosim":              "phase3/mixed_signal/cosim",
    "hardmacro":          "analog/hardmacro",
    "extracted_docs":     "phase1/input_doc",
    "generated_docs":     "phase1/generated_docs",
    "logs":               "reports/orchestrator/logs",
    "run_logs":           "reports/orchestrator/logs",
}

# Top-level metadata file → phase1/ destination relative path.
_FILE_MIGRATIONS = {
    "extraction_patterns.json":       "phase1/extraction_patterns.json",
    "extraction_patterns.auto.json":  "phase1/extraction_patterns.auto.json",
    "completeness_check_config.json": "phase1/completeness_check_config.json",
    "ai_deep_review_patches.json":    "phase1/ai_deep_review_patches.json",
}

# Mapping for reports/<flat>/ → reports/<phase_parent>/<flat>/. Captures
# stage-aligned semantics; everything not listed defaults to `audit/`
# (the bucket reserved for cross-cutting / late / one-off artefacts).
_REPORTS_FLAT_TO_PARENT = {
    "cdc":          "phase2",
    "coverage":     "phase2",
    "lint":         "phase2",
    "fpga":         "phase2",
    "gates":        "phase2",
    "dft":          "phase2",
    "synth":        "phase2",
    "pnr":          "phase3",
    "cts":          "phase3",
    "sta":          "phase3",
    "mixed_signal": "phase3",
    "signoff":      "phase3",
    "manufacturing": "phase3",
    "hardware":     "audit",
}


@dataclass
class Move:
    src: str
    dst: str
    kind: str           # "dir" / "file"
    note: str = ""
    skipped_files: List[str] = field(default_factory=list)
    # For dir merges: relative paths inside src/ that already existed
    # at dst/ and were left in place (caller can audit / resolve).


@dataclass
class MigrationResult:
    moves: List[Move] = field(default_factory=list)
    blocked: List[Move] = field(default_factory=list)


def _safe_move_dir(src: Path, dst: Path, dry_run: bool
                   ) -> Tuple[Optional[str], List[str]]:
    """Merge src/ into dst/. If dst already exists, recursively merge
    file-by-file. Files whose destination already exists are LEFT in
    place inside src/ — they are reported as skipped so the caller can
    flag them. (v1.6.30 change: previously silently dropped them; now
    they remain at src/ so a re-run / manual resolution sees the truth.)
    Returns (error_string_or_None, list_of_skipped_relative_paths).
    """
    if not src.exists():
        return None, []
    if not dst.exists():
        if dry_run:
            return None, []
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dst))
        return None, []
    # dst exists — merge
    skipped: List[str] = []
    if dry_run:
        # Preview which files would skip (destination exists at dst).
        for child in src.rglob("*"):
            if child.is_dir():
                continue
            rel = child.relative_to(src)
            if (dst / rel).exists():
                skipped.append(str(rel))
        return None, skipped
    for child in src.rglob("*"):
        if child.is_dir():
            continue
        rel = child.relative_to(src)
        target = dst / rel
        if target.exists():
            skipped.append(str(rel))
            continue  # leave at src/ — caller decides
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(child), str(target))
    # Remove now-empty subdirs and src/ itself if fully drained.
    # If skipped files remain, src/ stays so the user sees them.
    try:
        for empty in sorted(src.rglob("*"), key=lambda p: -len(p.parts)):
            if empty.is_dir() and not any(empty.iterdir()):
                empty.rmdir()
        if src.exists() and not any(src.iterdir()):
            src.rmdir()
    except OSError:
        pass
    return None, skipped


def _safe_move_file(src: Path, dst: Path, dry_run: bool) -> Optional[str]:
    if not src.is_file():
        return None
    if dst.exists():
        # Resume support: if src and dst are byte-identical the move is
        # already "done" — drop the redundant src/ entry and return OK.
        try:
            if src.stat().st_size == dst.stat().st_size and \
               src.read_bytes() == dst.read_bytes():
                if not dry_run:
                    src.unlink()
                return None
        except OSError:
            pass
        return f"destination exists: {dst}"
    if dry_run:
        return None
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.move(str(src), str(dst))
    return None


def migrate(project: Path, dry_run: bool) -> MigrationResult:
    result = MigrationResult()

    # 1. Top-level dirs
    for name, dst_rel in _DIR_MIGRATIONS.items():
        src = project / name
        if not src.is_dir():
            continue
        dst = project / dst_rel
        err, skipped = _safe_move_dir(src, dst, dry_run)
        mv = Move(src=name + "/", dst=dst_rel + "/", kind="dir",
                  skipped_files=skipped)
        if err:
            mv.note = err
            result.blocked.append(mv)
        elif skipped:
            mv.note = (f"merged with conflicts; {len(skipped)} file(s) "
                       f"left at src/ (destination exists)")
            result.blocked.append(mv)
        else:
            result.moves.append(mv)

    # 2. Top-level metadata files
    for name, dst_rel in _FILE_MIGRATIONS.items():
        src = project / name
        if not src.is_file():
            continue
        dst = project / dst_rel
        err = _safe_move_file(src, dst, dry_run)
        mv = Move(src=name, dst=dst_rel, kind="file")
        if err:
            mv.note = err
            result.blocked.append(mv)
        else:
            result.moves.append(mv)

    # 3. reports/<flat_subdir>/ → reports/<parent>/<flat_subdir>/
    reports = project / "reports"
    if reports.is_dir():
        for child in sorted(reports.iterdir()):
            if not child.is_dir():
                continue
            if child.name in _pl.REPORTS_VALID_SUBDIRS:
                continue
            parent = _REPORTS_FLAT_TO_PARENT.get(child.name, "audit")
            dst = reports / parent / child.name
            err, skipped = _safe_move_dir(child, dst, dry_run)
            mv = Move(src=f"reports/{child.name}/",
                      dst=f"reports/{parent}/{child.name}/", kind="dir",
                      skipped_files=skipped)
            if err:
                mv.note = err
                result.blocked.append(mv)
            elif skipped:
                mv.note = (f"merged with conflicts; {len(skipped)} file(s) "
                           f"left in src")
                result.blocked.append(mv)
            else:
                result.moves.append(mv)

    # 4. reports/<file> at top → auto-routed via _pl.report_path()
    if reports.is_dir():
        for child in sorted(reports.iterdir()):
            if not child.is_file():
                continue
            dst = _pl.report_path(project, child.name)
            if dst.parent == reports:
                # Already at the right level (auto-router said reports/
                # root); leave it. But this conflicts with the gate's
                # taxonomy (no flat reports/ files allowed). Default
                # such files into reports/audit/.
                dst = reports / "audit" / child.name
            err = _safe_move_file(child, dst, dry_run)
            rel_dst = dst.relative_to(project)
            mv = Move(src=f"reports/{child.name}",
                      dst=str(rel_dst), kind="file")
            if err:
                mv.note = err
                result.blocked.append(mv)
            else:
                result.moves.append(mv)

    return result


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(
        description="Migrate stray entries to v1.6.26 canonical taxonomy.")
    ap.add_argument("project_dir")
    ap.add_argument("--dry-run", action="store_true",
                    help="Preview moves without touching the filesystem.")
    ap.add_argument("--json", help="write JSON migration report to this path")
    args = ap.parse_args(argv)

    project = Path(args.project_dir).resolve()
    if not project.is_dir():
        print(f"error: project dir not found: {project}", file=sys.stderr)
        return 2

    result = migrate(project, args.dry_run)

    report = {
        "tool": "migrate_to_canonical_taxonomy",
        "project": str(project),
        "dry_run": args.dry_run,
        "moves_planned" if args.dry_run else "moves_applied":
            [asdict(m) for m in result.moves],
        "blocked": [asdict(m) for m in result.blocked],
        "summary": {
            "moved": len(result.moves),
            "blocked": len(result.blocked),
        },
    }
    if args.json:
        out = Path(args.json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2) + "\n")

    label = "PLANNED" if args.dry_run else "APPLIED"
    print(f"{label} {len(result.moves)} move(s); {len(result.blocked)} blocked")
    for m in result.moves[:20]:
        print(f"  [{m.kind}] {m.src} → {m.dst}")
    if len(result.moves) > 20:
        print(f"  … and {len(result.moves) - 20} more")
    if result.blocked:
        print(f"BLOCKED moves (manual review needed):", file=sys.stderr)
        for m in result.blocked:
            print(f"  [{m.kind}] {m.src} → {m.dst}: {m.note}",
                  file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
