#!/usr/bin/env python3
"""qsf_gen.py — auto-generate Quartus QSF (FPGA pin assignments).

Wave 72 deliverable. Wave 73 (v0.128) renamed from aid_class_qsf_gen.py
to reflect that the generator is class-AGNOSTIC: it works for any chip
whose L9 declares its top-module pins, not just AID-class ICs. A
backwards-compat shim at the old path forwards calls until v0.130.

Closes the last manual-prep gap so a fresh-agent can go from empty
input/ → byte[6] verdict in one phase23_one_shot_runner call.

The QSF is BOARD-specific (default DE10-Lite) but chip-AGNOSTIC: pin names,
device family/part, and IO standards come from the board manual; nothing
about the chip-under-test (<chip-class> / <PDK> / etc.) is hardcoded.

Inputs (read from <project_dir>):
    generated_docs/L9_INTEGRATION_SPEC.json
        - top_module                  → TOP_LEVEL_ENTITY (after wrapper choice)
        - top_module_pins[]           → port-to-board-signal mapping
        - submodules[*].file          → RTL file list (fallback: rtl/*.{sv,v})

Optional:
    rtl/<board>_top.sv (e.g. rtl/de10lite_top.sv)
        If present, that wrapper module is used as TOP_LEVEL_ENTITY and its
        ports drive the pin map directly (CLOCK_50/KEY/GPIO_0 → board pins).
        This matches the Wave 71 hand-written QSF baseline.

    input/docs/DE10-Lite_User_Manual.pdf or input_doc/DE10-Lite_User_Manual.txt
        Future hook for dynamic pin extraction. Currently the DE10-Lite pin
        map is embedded as a literal table (sourced verbatim from Terasic's
        public DE10-Lite User Manual v1.2 §3 pin-out tables).

Output:
    <project_dir>/fpga/<top>.qsf

Logic (chip-AGNOSTIC):
    1. Pick top_module:
        a. If rtl/<board>_top.sv exists → use it (board-pin namespace).
        b. Else use L9.top_module (IC-namespace ports — auto-mapped).
    2. Resolve every top-module port → board pin via _BOARD_PIN_MAP rules:
         CLOCK_50 / clk*       → P11
         reset_n / KEY[0]      → B8
         id_bus / GPIO_0[0]    → V10  (open-drain single-wire, weak-pull-up)
         GPIO_0[N]             → board GPIO_0 header pin
         GPIO_1[N]             → board GPIO_1 header pin
         LEDR[N] / led*[N]     → board LEDR pin
         KEY[N]                → board KEY pin
         SW[N]                 → board SW pin
         HEXn[m]               → board HEX seven-seg pin
       Any port not in the map is reported as a WARN comment in the QSF.
    3. Emit QSF with global assignments + RTL file list (sorted: pkg → sv → v)
       + pin assignments + IO_STANDARD + (open-drain → WEAK_PULL_UP_RESISTOR).
       SDC_FILE points to <top>.sdc (peer file, generated by sdc_gen).

CLI:
    python3 qsf_gen.py <project_dir> [--board de10lite]
                                      [--top-name chip_top]
                                      [--force]

Exit codes:
    0  PASS (QSF generated)
    1  FAIL (missing L9 or RTL)
    2  IO / arg error
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple
import _path_layout as _pl


# ---------------------------------------------------------------------------
# DE10-Lite (Terasic, MAX10 10M50DAF484C7G) board pin catalogue.
# Sourced verbatim from "DE10-Lite User Manual v1.2" §3 pin-out tables and
# matches the hand-written reference QSF that produces byte[6]=0xF2 PASS.
# Chip-AGNOSTIC: this is BOARD data, not chip data.
# ---------------------------------------------------------------------------
_DE10LITE_DEVICE = {
    "family": "MAX 10",
    "device": "10M50DAF484C7G",
    "package": "FBGA",
    "pin_count": 484,
    "speed_grade": 7,
    "default_io_standard": "3.3-V LVTTL",
    "stratix_default_io_standard": "3.3-V LVTTL",
    "min_core_temp": 0,
    "max_core_temp": 85,
}

_DE10LITE_PINS: Dict[str, str] = {
    # Clocks
    "CLOCK_50":         "PIN_P11",
    "MAX10_CLK1_50":    "PIN_P11",
    "MAX10_CLK2_50":    "PIN_N14",
    "ADC_CLK_10":       "PIN_N5",
    # Push-buttons (active-low; SCHMITT_TRIGGER but LVTTL works)
    "KEY[0]":           "PIN_B8",
    "KEY[1]":           "PIN_A7",
    # Slide switches
    "SW[0]":            "PIN_C10", "SW[1]": "PIN_C11",
    "SW[2]":            "PIN_D12", "SW[3]": "PIN_C12",
    "SW[4]":            "PIN_A12", "SW[5]": "PIN_B12",
    "SW[6]":            "PIN_A13", "SW[7]": "PIN_A14",
    "SW[8]":            "PIN_B14", "SW[9]": "PIN_F15",
    # LEDs
    "LEDR[0]":          "PIN_A8",  "LEDR[1]": "PIN_A9",
    "LEDR[2]":          "PIN_A10", "LEDR[3]": "PIN_B10",
    "LEDR[4]":          "PIN_D13", "LEDR[5]": "PIN_C13",
    "LEDR[6]":          "PIN_E14", "LEDR[7]": "PIN_D14",
    "LEDR[8]":          "PIN_A11", "LEDR[9]": "PIN_B11",
    # GPIO_0 header (JP1) — used for chip-under-test signals
    "GPIO_0[0]": "PIN_V10",  "GPIO_0[1]": "PIN_W10",
    "GPIO_0[2]": "PIN_V9",   "GPIO_0[3]": "PIN_W9",
    "GPIO_0[4]": "PIN_V8",   "GPIO_0[5]": "PIN_W8",
    "GPIO_0[6]": "PIN_V7",   "GPIO_0[7]": "PIN_W7",
    "GPIO_0[8]": "PIN_W6",   "GPIO_0[9]": "PIN_V5",
    "GPIO_0[10]": "PIN_W5",  "GPIO_0[11]": "PIN_AA15",
    "GPIO_0[12]": "PIN_AA14", "GPIO_0[13]": "PIN_W13",
    "GPIO_0[14]": "PIN_W12", "GPIO_0[15]": "PIN_AB13",
    "GPIO_0[16]": "PIN_AB12", "GPIO_0[17]": "PIN_Y11",
    "GPIO_0[18]": "PIN_AB11", "GPIO_0[19]": "PIN_W11",
    "GPIO_0[20]": "PIN_AB10", "GPIO_0[21]": "PIN_AA10",
    "GPIO_0[22]": "PIN_AA9", "GPIO_0[23]": "PIN_Y8",
    "GPIO_0[24]": "PIN_AA8", "GPIO_0[25]": "PIN_Y7",
    "GPIO_0[26]": "PIN_AA7", "GPIO_0[27]": "PIN_Y6",
    "GPIO_0[28]": "PIN_AA6", "GPIO_0[29]": "PIN_Y5",
    "GPIO_0[30]": "PIN_AA5", "GPIO_0[31]": "PIN_Y4",
    "GPIO_0[32]": "PIN_AB3", "GPIO_0[33]": "PIN_Y3",
    "GPIO_0[34]": "PIN_AB2", "GPIO_0[35]": "PIN_AA2",
}

# Wave 73 (v0.128) S3 — open-drain set is now driven by L9 port flags
# (top_module_pins[i].open_drain == true), not by a hard-coded list of
# port names. The board-side GPIO_0[0] entry remains here because it
# is a physical DE10-Lite pin attribute (single-wire bus footprint),
# not a property of any specific chip-internal port.
_DE10LITE_BOARD_OPEN_DRAIN_PORTS = {"GPIO_0[0]"}    # weak pull-up enabled
# Backwards-compat alias kept temporarily for any out-of-tree caller
# importing the old symbol. Remove in v0.130.
_DE10LITE_OPEN_DRAIN_PORTS = _DE10LITE_BOARD_OPEN_DRAIN_PORTS
_DE10LITE_WEAK_PULLUP_PORTS = {"KEY[0]", "KEY[1]"}


# ---------------------------------------------------------------------------
# IC-namespace → board-pin convention.
# Used only when L9.top_module ports use IC-level names (clk/reset_n/id_bus).
# Maps to a *single* board pin; bus ports require either a board wrapper
# (preferred) or explicit per-bit board pins.
# Chip-AGNOSTIC: this rule is "any clock-named port → CLOCK_50, any reset →
# KEY[0], any single-bit inout → GPIO_0[0]".
# ---------------------------------------------------------------------------
def _ic_port_to_board_signal(port_name: str) -> Optional[str]:
    """Return the board signal name (e.g. 'CLOCK_50', 'KEY[0]', 'GPIO_0[0]')
    for an IC-namespace port. None if no convention matches."""
    n = port_name.lower()
    if n in ("clk", "clock", "clk_in", "clk_50", "sysclk"):
        return "CLOCK_50"
    if "clk" in n or "clock" in n:
        return "CLOCK_50"
    if n in ("reset_n", "rst_n", "rstn", "reset", "rst"):
        return "KEY[0]"
    if "reset" in n or "rst" in n:
        return "KEY[0]"
    if n in ("id_bus", "id", "bus", "data", "io"):
        return "GPIO_0[0]"
    # Any other single-bit signal lands on a sequential GPIO_0 — caller
    # must allocate via _allocate_gpio0() instead.
    return None


# ---------------------------------------------------------------------------
# L9 reading
# ---------------------------------------------------------------------------
def _load_l9(project: Path) -> dict:
    p = _pl.generated_docs_dir(project) / "L9_INTEGRATION_SPEC.json"
    if not p.is_file():
        raise FileNotFoundError(f"missing L9: {p}")
    return json.loads(p.read_text(encoding="utf-8"))


def _list_rtl_files(project: Path) -> List[Path]:
    rtl = _pl.rtl_dir(project)
    if not rtl.is_dir():
        return []
    pkgs = sorted(p for p in rtl.glob("*pkg*.sv"))
    sv = sorted(p for p in rtl.glob("*.sv") if "pkg" not in p.name)
    v = sorted(p for p in rtl.glob("*.v"))
    return pkgs + sv + v


def _detect_board_wrapper(rtl_files: List[Path], board: str
                          ) -> Optional[Tuple[str, Path]]:
    """If a board-pin wrapper module exists (e.g. de10lite_top.sv with
    CLOCK_50/KEY/GPIO_0 ports), return (module_name, file_path)."""
    candidates = [f for f in rtl_files
                  if board.replace("-", "").lower() in f.name.lower()]
    for f in candidates:
        try:
            txt = f.read_text(encoding="utf-8", errors="ignore")
        except Exception:
            continue
        if "CLOCK_50" in txt or "GPIO_0" in txt:
            # First module declared in the file
            for line in txt.splitlines():
                line = line.strip()
                if line.startswith("module "):
                    name = line.split()[1].split("(")[0].strip()
                    return (name, f)
    return None


# ---------------------------------------------------------------------------
# Pin allocation
# ---------------------------------------------------------------------------
def _expand_port_signals(port: dict) -> List[str]:
    """A single L9 port entry may be vector or scalar. Returns the list of
    board-signal element names this port covers (e.g. KEY[0], KEY[1])."""
    name = port.get("name", "")
    width = port.get("width", 1)
    if isinstance(width, str):
        try:
            width = int(width, 0)
        except Exception:
            width = 1
    width = max(1, int(width or 1))
    if width == 1:
        # Caller decides whether name maps to scalar (CLOCK_50) or [0].
        return [name]
    return [f"{name}[{i}]" for i in range(width)]


def _resolve_board_signal(port_name: str, board: str
                          ) -> Tuple[Optional[str], Optional[str]]:
    """For a given port name, return (board_signal, board_pin).

    Tries direct match first (port already named CLOCK_50/KEY[0]/GPIO_0[0]),
    then IC-namespace heuristic.
    """
    if board != "de10lite":
        return (None, None)
    pin_map = _DE10LITE_PINS
    # 1. direct hit
    if port_name in pin_map:
        return (port_name, pin_map[port_name])
    # 2. IC-namespace convention
    sig = _ic_port_to_board_signal(port_name)
    if sig and sig in pin_map:
        return (sig, pin_map[sig])
    # 3. trailing index hint, e.g. ledr[0] → LEDR[0]
    upper = port_name.upper()
    if upper in pin_map:
        return (upper, pin_map[upper])
    return (None, None)


# ---------------------------------------------------------------------------
# QSF rendering
# ---------------------------------------------------------------------------
def _render_qsf(top: str, board: str, rtl_files: List[Path],
                fpga_dir: Path, port_assignments: List[Tuple[str, str, dict]],
                project_root: Path) -> str:
    """port_assignments = [(board_signal, pin, props), ...]"""
    if board != "de10lite":
        raise ValueError(f"unsupported board: {board}")
    dev = _DE10LITE_DEVICE
    lines: List[str] = []
    lines.append("# =========================================================================")
    lines.append(f"# Auto-generated by qsf_gen.py (Wave 72/73) — board={board}")
    lines.append(f"# Top entity: {top}")
    lines.append(f"# Source: L9_INTEGRATION_SPEC.json + rtl/")
    lines.append("# DO NOT hand-edit; regenerate via:")
    lines.append("#   python3 qsf_gen.py <project_dir>")
    lines.append("# =========================================================================")
    lines.append("")
    lines.append(f'set_global_assignment -name FAMILY                    "{dev["family"]}"')
    lines.append(f'set_global_assignment -name DEVICE                    {dev["device"]}')
    lines.append(f'set_global_assignment -name TOP_LEVEL_ENTITY          {top}')
    lines.append('set_global_assignment -name ORIGINAL_QUARTUS_VERSION  18.1')
    lines.append('set_global_assignment -name PROJECT_OUTPUT_DIRECTORY  output_files')
    lines.append(f'set_global_assignment -name MIN_CORE_JUNCTION_TEMP    {dev["min_core_temp"]}')
    lines.append(f'set_global_assignment -name MAX_CORE_JUNCTION_TEMP    {dev["max_core_temp"]}')
    lines.append('set_global_assignment -name ERROR_CHECK_FREQUENCY_DIVISOR 256')
    lines.append(f'set_global_assignment -name DEVICE_FILTER_PACKAGE     {dev["package"]}')
    lines.append(f'set_global_assignment -name DEVICE_FILTER_PIN_COUNT   {dev["pin_count"]}')
    lines.append(f'set_global_assignment -name DEVICE_FILTER_SPEED_GRADE {dev["speed_grade"]}')
    lines.append("")

    # SDC reference
    lines.append("# SDC constraints (peer file, generated by sdc_gen.py)")
    lines.append(f'set_global_assignment -name SDC_FILE                  {top}.sdc')
    lines.append("")

    # RTL sources — paths relative to fpga/ (project_dir/fpga is the QSF cwd)
    lines.append("# ----- RTL sources (relative to fpga/) ---------------------------------")
    lines.append('set_global_assignment -name SEARCH_PATH               ../rtl')

    # altsyncram / $readmemh init_file lookup: Quartus resolves init_file
    # parameters relative to the QSF cwd (fpga/) or any SEARCH_PATH entry.
    # Add every directory that ships *.mif / *.hex (excluding fpga/output_files/
    # to avoid pointing Quartus at its own outputs). chip-AGNOSTIC: discovered
    # by scan; no chip / vendor / file name hardcoded.
    # All paths in QSF are interpreted relative to the QSF cwd (fpga_dir),
    # not the project_root. Compute paths via os.path.relpath for portability
    # across canonical layout (phase2/stage1/fpga/) and any future layouts.
    import os as _os
    fpga_abs = fpga_dir.resolve()
    proj_abs = project_root.resolve()
    init_dirs: List[str] = []
    fpga_rel_parts = fpga_abs.relative_to(proj_abs).parts  # e.g. ('phase2','stage1','fpga')
    for ext in ("*.mif", "*.hex"):
        for f in project_root.rglob(ext):
            try:
                rel_parent = f.parent.resolve().relative_to(proj_abs)
            except ValueError:
                continue
            parts = rel_parent.parts
            # skip files inside the fpga build dir itself (already on SEARCH_PATH ".")
            if len(parts) >= len(fpga_rel_parts) and parts[:len(fpga_rel_parts)] == fpga_rel_parts:
                continue
            rel = _os.path.relpath(f.parent.resolve(), fpga_abs)
            if rel not in init_dirs:
                init_dirs.append(rel)
    if init_dirs:
        lines.append("# altsyncram/$readmemh init_file lookup (auto-discovered .mif/.hex dirs)")
        for d in init_dirs:
            lines.append(f'set_global_assignment -name SEARCH_PATH               {d}')
    for f in rtl_files:
        rel = _os.path.relpath(f.resolve(), fpga_abs)
        kind = "SYSTEMVERILOG_FILE" if f.suffix.lower() == ".sv" else "VERILOG_FILE"
        lines.append(f'set_global_assignment -name {kind}        {rel}')
    lines.append("")

    # Pin assignments
    lines.append("# ----- Pin assignments (board reference) -------------------------------")
    seen: Dict[str, str] = {}        # signal → pin
    seen_pins: Dict[str, str] = {}   # pin → signal (conflict detect)
    for sig, pin, props in port_assignments:
        if sig in seen:
            lines.append(f"# DUPLICATE skipped: {sig}")
            continue
        if pin in seen_pins:
            lines.append(f"# CONFLICT {sig} would collide with {seen_pins[pin]} on {pin} — skipped")
            continue
        seen[sig] = pin
        seen_pins[pin] = sig
        lines.append(f'set_location_assignment {pin} -to {sig}')
        io_std = props.get("io_standard", dev["default_io_standard"])
        lines.append(f'set_instance_assignment -name IO_STANDARD "{io_std}" -to {sig}')
        if props.get("weak_pull_up"):
            lines.append(f'set_instance_assignment -name WEAK_PULL_UP_RESISTOR ON -to {sig}')
        if props.get("output_open_drain"):
            lines.append(f'set_instance_assignment -name OUTPUT_OPEN_DRAIN ON -to {sig}')
    lines.append("")

    # Top-of-bus IO_STANDARD blanket (matches Wave 71 baseline)
    if any(s.startswith("GPIO_0[") for s, _, _ in port_assignments):
        lines.append('# Blanket IO_STANDARD for GPIO_0 vector')
        lines.append('set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to GPIO_0')
        lines.append("")

    # Tail global assignments matching Wave 71 baseline
    lines.append(f'set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "{dev["stratix_default_io_standard"]}"')
    lines.append("")
    lines.append("# MAX10 internal-flash mode that allows ROM init (.mif) inside altsyncram.")
    lines.append("# Default (Single Compressed Image) does not allow init; switch to one that does.")
    lines.append('set_global_assignment -name INTERNAL_FLASH_UPDATE_MODE "SINGLE COMP IMAGE WITH ERAM"')
    lines.append("")
    # Best-effort determinism. Pinning SEED narrows fitter randomness;
    # SMART_RECOMPILE off avoids cache-dependent re-seeding. These cut
    # the bit drift but do NOT make MAX10 Quartus 23.1 fully
    # bit-deterministic in this environment — empirically the .sof
    # hash still differs run-to-run (likely from parallel placement
    # ordering and embedded build-id metadata). The load-bearing fix
    # remains the v1.6.49 final_summary regen between fpga_compile
    # and fpga_burn (so the attestation table reflects the just-built
    # SOF). Keeping these flags anyway: they reduce SOF drift on
    # incremental rebuilds and make seed-pinned regression diffs more
    # tractable.
    lines.append("set_global_assignment -name SEED 1")
    lines.append("set_global_assignment -name SMART_RECOMPILE OFF")
    lines.append("")
    lines.append('set_global_assignment -name LAST_QUARTUS_VERSION "23.1std.0 Lite Edition"')
    lines.append("")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------
def _build_port_assignments_from_wrapper(rtl_file: Path, board: str
                                         ) -> List[Tuple[str, str, dict]]:
    """Parse a board-pin wrapper file and return board pin assignments
    for each port. Wrapper ports are board-namespace already."""
    txt = rtl_file.read_text(encoding="utf-8", errors="ignore")
    # naive port list extraction between first '(' and ')' after 'module'
    if "module " not in txt:
        return []
    after = txt.split("module ", 1)[1]
    if "(" not in after or ")" not in after:
        return []
    port_block = after.split("(", 1)[1]
    depth = 1
    chars: List[str] = []
    for c in port_block:
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                break
        chars.append(c)
    body = "".join(chars)
    assignments: List[Tuple[str, str, dict]] = []
    for raw in body.split(","):
        line = raw.strip().split("//")[0].strip()
        if not line:
            continue
        # patterns:
        #   input  wire CLOCK_50
        #   input  wire [1:0] KEY
        #   inout  wire [35:0] GPIO_0
        toks = line.replace(",", " ").split()
        # find vector range and identifier
        ident = None
        width = 1
        offset = 0
        for i, t in enumerate(toks):
            if t.startswith("[") and "]" in t:
                # vector spec like [35:0]
                inner = t.strip("[]")
                if ":" in inner:
                    try:
                        hi, lo = inner.split(":")
                        hi = int(hi); lo = int(lo)
                        width = abs(hi - lo) + 1
                        offset = min(hi, lo)
                    except Exception:
                        pass
            elif t in ("input", "output", "inout", "wire", "reg", "logic"):
                continue
            elif t.isidentifier():
                ident = t
        if not ident:
            continue
        # build per-bit signals
        if width == 1:
            sigs = [ident]
        else:
            sigs = [f"{ident}[{offset+i}]" for i in range(width)]
        for s in sigs:
            sig, pin = _resolve_board_signal(s, board)
            if not sig or not pin:
                continue
            props: dict = {"io_standard": _DE10LITE_DEVICE["default_io_standard"]}
            if sig in _DE10LITE_BOARD_OPEN_DRAIN_PORTS or sig in _DE10LITE_WEAK_PULLUP_PORTS:
                props["weak_pull_up"] = True
            assignments.append((sig, pin, props))
    return assignments


def _build_port_assignments_from_l9(l9: dict, board: str
                                    ) -> List[Tuple[str, str, dict]]:
    out: List[Tuple[str, str, dict]] = []
    for port in l9.get("top_module_pins", []):
        if not isinstance(port, dict):
            continue
        name = port.get("name")
        io_kind = str(port.get("io", "")).lower()
        mode = str(port.get("mode", "")).lower()
        # Wave 73 (v0.128) S3 — explicit L9 flag drives OUTPUT_OPEN_DRAIN.
        # An entry like {"name": "scl", "open_drain": true} now produces
        # `set_instance_assignment -name OUTPUT_OPEN_DRAIN ON -to scl`.
        l9_open_drain = bool(port.get("open_drain", False))
        if not name:
            continue
        sig, pin = _resolve_board_signal(name, board)
        if not sig or not pin:
            continue
        props: dict = {"io_standard": _DE10LITE_DEVICE["default_io_standard"]}

        # Open-drain inference: prefer the explicit L9 flag; the
        # io-string heuristic stays as a fallback for legacy fixtures
        # that say io: "open-drain" without an open_drain bool.
        io_string_says_od = (
            "open-drain" in io_kind or "open_drain" in io_kind
        )
        if l9_open_drain or io_string_says_od:
            props["weak_pull_up"] = True
            props["output_open_drain"] = True

        # inout pins (without an explicit open-drain flag) still get a
        # weak pull-up (legacy <chip-class> behaviour) but NOT the
        # OUTPUT_OPEN_DRAIN attribute — that only fires when L9 says so.
        if mode == "inout" and not (l9_open_drain or io_string_says_od):
            props["weak_pull_up"] = True

        if sig in _DE10LITE_WEAK_PULLUP_PORTS:
            props["weak_pull_up"] = True
        out.append((sig, pin, props))
    return out


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("project", type=Path)
    p.add_argument("--board", default="de10lite",
                   choices=["de10lite"])
    p.add_argument("--top-name", default=None,
                   help="Override TOP_LEVEL_ENTITY (default: auto-detect "
                        "board wrapper, else L9.top_module).")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing QSF.")
    args = p.parse_args()

    project = args.project.resolve()
    if not project.is_dir():
        print(f"ERROR: not a directory: {project}", file=sys.stderr)
        return 2

    try:
        l9 = _load_l9(project)
    except FileNotFoundError as e:
        print(f"FAIL: {e}", file=sys.stderr)
        return 1

    rtl_files = _list_rtl_files(project)
    if not rtl_files:
        print(f"FAIL: rtl/ empty under {project}", file=sys.stderr)
        return 1

    # Decide top entity
    wrapper = _detect_board_wrapper(rtl_files, args.board)
    if args.top_name:
        top = args.top_name
        wrapper_file = next((f for f in rtl_files
                             if f.read_text(encoding="utf-8", errors="ignore")
                             .find(f"module {top}") >= 0), None)
    elif wrapper:
        top, wrapper_file = wrapper
    else:
        top = l9.get("top_module") or "chip_top"
        wrapper_file = None

    # Build pin assignments
    if wrapper_file is not None:
        port_assignments = _build_port_assignments_from_wrapper(wrapper_file, args.board)
        source = f"wrapper {wrapper_file.name}"
    else:
        port_assignments = _build_port_assignments_from_l9(l9, args.board)
        source = "L9.top_module_pins"

    if not port_assignments:
        print(f"FAIL: no port→board-pin mapping resolved (source={source}). "
              f"Top {top!r} ports do not match board {args.board}.",
              file=sys.stderr)
        return 1

    # Render and write
    fpga_dir = _pl.fpga_early_dir(project)
    fpga_dir.mkdir(parents=True, exist_ok=True)
    out = fpga_dir / f"{top}.qsf"
    if out.exists() and not args.force:
        print(f"SKIP: {out} exists (use --force to overwrite)")
        return 0
    text = _render_qsf(top, args.board, rtl_files, fpga_dir,
                       port_assignments, project)
    out.write_text(text, encoding="utf-8")

    # also emit minimal .qpf so quartus_sh --flow compile works on bare project
    qpf = fpga_dir / f"{top}.qpf"
    if not qpf.exists() or args.force:
        qpf.write_text(
            "QUARTUS_VERSION = \"18.1\"\n"
            "DATE = \"Auto-generated by qsf_gen.py\"\n\n"
            f"PROJECT_REVISION = \"{top}\"\n",
            encoding="utf-8")

    print(f"PASS qsf_gen: {out} "
          f"({len(port_assignments)} pins, top={top!r}, source={source})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
