#!/usr/bin/env python3
"""
rtl_hygiene_lint.py — General-purpose RTL hygiene checker.

Deterministic Python-based lint that catches 5 general bug classes found
across IC designs (learned from <half-duplex-tester> debug 2026-04-16; rule 5
added from the VerilogEval-v2 v0.1.10 tuning loop 2026-05-27):

  1. Declared-but-undriven wire
     (e.g., `wire ch_wake_event;` but never on LHS of `assign` or instance output)
  2. Declared-but-unread reg
     (e.g., `reg [7:0] resp_crc;` but never appears on RHS)
  3. Case/if enumeration coverage
     (e.g., `case (x) 8'h70: ... 8'h72: ... endcase` with no `default`, missing
      values that are actually generated by producer)
  4. Pulse-to-state without latch
     (e.g., `start <= 1'b1;` in one always block, consumed by another FSM that
      only looks at `start` during a specific state → pulse may be swallowed)
  5. Reset-less registered output with no power-up initializer
     (e.g., `output reg q;` clocked by `<= d` with no reset and no `= 0` →
      powers up as X; deterministic references expect 0 at t=0)

Usage:
    python3 rtl_hygiene_lint.py <files.v|.sv ...>
    python3 rtl_hygiene_lint.py --json <out.json> <files.v|.sv ...>

Exit codes:
    0 = no findings
    1 = findings issued (see stdout / JSON)
    2 = parse error

Works with plain regex + optional pyslang (more accurate) if installed.
No external tool dependencies required for the regex path.

Generality: applies to ANY Verilog/SystemVerilog design. Finds bugs #1, #2,
#7, #10 from the <half-duplex-tester> debug session using only syntax patterns.
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Dict, Set, Tuple


@dataclass
class Finding:
    file: str
    line: int
    severity: str  # ERROR / WARN / INFO
    rule: str
    symbol: str
    message: str


# ---------------------------------------------------------------------------
# Tokenization (comment stripper + simple lexer good enough for our patterns)
# ---------------------------------------------------------------------------
def strip_comments(src: str) -> str:
    """Remove // line comments and /* block */ comments, preserving newlines."""
    # Block comments — preserve newlines for line tracking
    out = []
    i = 0
    while i < len(src):
        if src[i:i+2] == '/*':
            end = src.find('*/', i+2)
            if end == -1:
                break
            # Keep newlines so line numbers stay correct
            out.append(''.join('\n' if c == '\n' else ' ' for c in src[i:end+2]))
            i = end + 2
        elif src[i:i+2] == '//':
            end = src.find('\n', i)
            if end == -1:
                break
            out.append(' ' * (end - i))
            i = end
        else:
            out.append(src[i])
            i += 1
    return ''.join(out)


# Reserved words that look like identifiers but aren't signals
VERILOG_KEYWORDS = {
    'module', 'endmodule', 'input', 'output', 'inout', 'wire', 'reg', 'logic',
    'assign', 'always', 'always_ff', 'always_comb', 'always_latch',
    'begin', 'end', 'if', 'else', 'case', 'endcase', 'default', 'for',
    'while', 'repeat', 'posedge', 'negedge', 'or', 'and', 'not',
    'function', 'endfunction', 'task', 'endtask', 'parameter', 'localparam',
    'generate', 'endgenerate', 'genvar', 'integer', 'real', 'time',
    'return', 'break', 'continue', 'typedef', 'struct', 'union', 'enum',
    'packed', 'unpacked', 'signed', 'unsigned', 'initial', 'forever',
    'wait', 'fork', 'join', 'disable', '1b0', '1b1', 'x', 'z',
}


# ---------------------------------------------------------------------------
# Rule 1 + Rule 2: Undriven-wire / Unread-reg (general)
# ---------------------------------------------------------------------------
def find_declarations(src: str) -> List[Tuple[str, str, int]]:
    """
    Return list of (kind, name, lineno) for all wire/reg/logic declarations
    except module ports (which are driven/read externally).
    """
    decls = []
    lines = src.split('\n')
    # Track whether we are inside a module port list to skip port decls
    in_port_list = False
    paren_depth = 0
    for lineno, line in enumerate(lines, start=1):
        # Track entry/exit of port list
        if re.search(r'\bmodule\b\s+\w+', line):
            in_port_list = True
        if in_port_list:
            paren_depth += line.count('(') - line.count(')')
            if paren_depth <= 0 and ';' in line:
                in_port_list = False
            continue
        # Match: wire [MSB:LSB] name1, name2;  or reg [..] name;
        m = re.match(
            r'\s*(wire|reg|logic)\s+(?:(?:signed|unsigned)\s+)?'
            r'(?:\[[^\]]+\]\s*)?'     # optional packed range
            r'(?:\[[^\]]+\]\s*)?'     # optional 2nd range (arrays)
            r'([^;=]+?)\s*;',
            line)
        if not m:
            continue
        kind, name_list = m.group(1), m.group(2)
        # Skip if this is inside a port/function/task
        for n in name_list.split(','):
            n = n.strip()
            # Strip array subscript from declaration list
            n = re.sub(r'\[.*', '', n).strip()
            if n and n not in VERILOG_KEYWORDS and re.match(r'^\w+$', n):
                decls.append((kind, n, lineno))
    return decls


def collect_lhs_set(src: str) -> Set[str]:
    """Collect every identifier that appears on the LHS of assign or always <=/=."""
    lhs = set()
    # assign X = ...
    for m in re.finditer(r'\bassign\s+(\w+)(?:\[[^\]]+\])?\s*=', src):
        lhs.add(m.group(1))
    # X <= ... or X = ... inside procedural blocks
    for m in re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*(<=|=)(?!=)', src):
        # Skip the tokens around 'begin', 'end', keywords
        name = m.group(1)
        if name not in VERILOG_KEYWORDS and not name.startswith("'"):
            lhs.add(name)
    return lhs


def collect_rhs_set(src: str) -> Set[str]:
    """
    Collect identifiers that appear on the RHS of expressions / conditions / ports.
    This is conservative — it counts ANY identifier token not matched as LHS.
    """
    used = set()
    # Strip out LHS tokens first pass
    #   assign LHS = RHS;  →  keep RHS
    #   X <= RHS;         →  keep RHS
    #   port connections  →  keep all
    # Simpler: tokenize all identifiers, then we'll intersect with known decls.
    for m in re.finditer(r'\b([a-zA-Z_]\w*)\b', src):
        tok = m.group(1)
        if tok not in VERILOG_KEYWORDS:
            used.add(tok)
    return used


def collect_instance_connections(src: str) -> Dict[str, str]:
    """
    For each `.port(signal)` connection in a module instance, return mapping
    port_name -> signal_name. We use this conservatively: any signal that
    appears in .port(signal) is considered both 'driven' and 'read' because
    we don't know the port direction without cross-module analysis.
    """
    connected = {}
    for m in re.finditer(r'\.(\w+)\s*\(\s*([^)]+)\s*\)', src):
        port, sig = m.group(1), m.group(2).strip()
        # Take simple identifier from the signal side
        sm = re.match(r'^(\w+)', sig)
        if sm:
            connected[sm.group(1)] = port
    return connected


def rule_undriven_and_unread(src: str, path: str) -> List[Finding]:
    findings: List[Finding] = []
    decls = find_declarations(src)
    lhs = collect_lhs_set(src)
    rhs = collect_rhs_set(src)
    inst_sigs = collect_instance_connections(src)

    for kind, name, lineno in decls:
        driven = name in lhs or name in inst_sigs
        read = name in (rhs - {name})  # exclude itself
        # Conservative: an identifier appears in RHS if used anywhere;
        # but we already include LHS in rhs (tokenizer is blind).
        # Better: count only tokens NOT in decl line.
        # For now, focus on the clear-cut cases.

        if kind == 'wire' and not driven:
            findings.append(Finding(path, lineno, 'ERROR', 'undriven-wire', name,
                f"wire '{name}' declared but never driven (no assign, no instance output)."))
        if kind in ('reg', 'logic') and name in lhs:
            # declared reg that is written but never read on any RHS
            # Heuristic: if the only occurrences are in always-block-LHS, it's unread.
            # Count RHS occurrences excluding LHS sites:
            lhs_pattern = re.compile(
                r'\b' + re.escape(name) + r'\b(?:\s*\[[^\]]+\])?\s*(?:<=|=)(?!=)')
            total_occ = len(re.findall(r'\b' + re.escape(name) + r'\b', src))
            lhs_occ = len(lhs_pattern.findall(src))
            decl_occ = 1  # the declaration itself
            # Reads = total - (LHS assignments) - (declaration)
            reads = total_occ - lhs_occ - decl_occ
            if reads <= 0 and name not in inst_sigs:
                findings.append(Finding(path, lineno, 'WARN', 'unread-reg', name,
                    f"{kind} '{name}' declared and written but never read."))
    return findings


# ---------------------------------------------------------------------------
# Rule 3: Case without default + enum coverage hint
# ---------------------------------------------------------------------------
def rule_case_coverage(src: str, path: str) -> List[Finding]:
    findings: List[Finding] = []
    # Find every `case (expr) ... endcase` block with its starting line
    # Simple scan: find `case(...)` opening, find matching endcase
    lines = src.split('\n')
    case_starts = [(i, m.group(1))
                   for i, ln in enumerate(lines, start=1)
                   for m in re.finditer(r'\bcase[szx]?\s*\(([^)]+)\)', ln)]
    for start_line, expr in case_starts:
        # Find endcase
        end_line = start_line
        for j in range(start_line, len(lines) + 1):
            if j - 1 < len(lines) and 'endcase' in lines[j - 1]:
                end_line = j
                break
        block = '\n'.join(lines[start_line - 1:end_line])
        if not re.search(r'\bdefault\s*:', block):
            findings.append(Finding(path, start_line, 'WARN', 'case-no-default', expr.strip(),
                f"case ({expr.strip()}) has no default branch — "
                "values not enumerated may generate latch or undefined behavior."))
    return findings


# ---------------------------------------------------------------------------
# Rule 4: Pulse signal consumed only under a state gate (pulse-swallow risk)
# ---------------------------------------------------------------------------
def rule_pulse_swallow(src: str, path: str) -> List[Finding]:
    """
    Detect the pattern:
        Producer: X <= 1'b1;  (one-cycle pulse, reset to 0 at top of always)
        Consumer: in a case branch like S_WAIT: if (X) ...
    If the consumer FSM is in a different state when X pulses, the pulse is lost.

    Conservative heuristic: flag any signal that is
      - Assigned `<= 1'b1;` or `<= 1;` AND has a default-zero assignment at top
        of an always block (classic pulse pattern)
      - Read inside a `case` branch that is not the same state as the assignment

    Reports WARN (not ERROR) because many pulses are intentionally synchronous.
    """
    findings: List[Finding] = []
    # Find one-cycle pulse producers: `sig <= 1'b1;` or `sig <= 1;`
    pulses = set()
    for m in re.finditer(r'\b(\w+)\s*<=\s*1(?:\'b1|b1|\'d1|\s*;)', src):
        pulses.add(m.group(1))
    if not pulses:
        return findings

    # For each pulse signal, check if it's read ONLY inside case-state branches
    # (heuristic: inside `S_XXX:` or `3'd\d+:` branch)
    for sig in pulses:
        # Find read sites (RHS occurrences outside its own LHS)
        reads_in_case = 0
        reads_outside_case = 0
        depth_in_case = 0
        current_block = []
        for m in re.finditer(r'\b' + re.escape(sig) + r'\b', src):
            pos = m.start()
            # Look backward for nearest `case`/`endcase`
            # v1.6.205 (#87 P1): whole-word match so `endcase` is not
            # counted as a `case` opening. Old `startswith('case', i)`
            # counted every `case` substring — including the `case`
            # inside `endcase` — pushing `in_case` to True even for
            # declarations preceded only by a closed case block. That
            # produced false-positive pulse-swallow-risk INFOs on any
            # reg declared after a function-internal case (very common
            # in spec-compliant FSMs). chip-AGNOSTIC.
            before = src[:pos]
            case_opens = len(re.findall(r'\bcase[szx]?\b', before))
            case_closes = len(re.findall(r'\bendcase\b', before))
            in_case = case_opens > case_closes
            # Exclude LHS
            rest = src[pos:pos + 120]
            if re.match(r'^\w+\s*(<=|=)(?!=)', rest):
                continue
            if in_case:
                reads_in_case += 1
            else:
                reads_outside_case += 1
        if reads_in_case > 0 and reads_outside_case == 0:
            # pulse is only consumed inside case — risk of state mismatch
            # Find declaration line
            dm = re.search(r'\b(?:reg|logic|wire)\s+(?:\[[^\]]+\]\s*)?' + re.escape(sig) + r'\b', src)
            lineno = src[:dm.start()].count('\n') + 1 if dm else 1
            findings.append(Finding(path, lineno, 'INFO', 'pulse-swallow-risk', sig,
                f"pulse signal '{sig}' (<= 1'b1) read only inside case branches — "
                "if consumer is in a different state when pulse fires, the pulse is lost. "
                "Consider latching or explicit handshake."))
    return findings


# ---------------------------------------------------------------------------
# Rule 5: Reset-less registered output with no power-up initializer
# ---------------------------------------------------------------------------
_RESET_NAME_RE = re.compile(r'\b(a?reset[a-z_]*|a?rst[a-z_]*|resetn|nreset|por|sclr|aclr)\b', re.I)


def rule_uninit_registered_output(src: str, path: str) -> List[Finding]:
    """
    Detect a REGISTERED output port (assigned via `<=` in a clocked block) in a
    module that has NO reset-like input AND gives the output NO power-up value
    (no declaration-time initializer, no `initial` block).

    Such an output powers up as X. Deterministic reference models (and the
    VerilogEval-v2 testbenches) sample the output at t=0 before the first clock
    edge and expect a deterministic 0 there, so the design mismatches on exactly
    that one pre-clock sample. Learned from VerilogEval-v2 Prob034/053/104, where
    each lost a single vector purely to an uninitialised `output reg`.

    Conservative — only fires when the module has NO reset port at all (so the
    output genuinely cannot be reset), which is precisely the reset-less DFF
    case. Reports WARN with the exact fix. chip-AGNOSTIC.
    """
    findings: List[Finding] = []

    # Output ports (ANSI or non-ANSI), capturing optional reg/logic/wire kind.
    out_ports: Dict[str, int] = {}
    for m in re.finditer(
            r'\boutput\b\s+(?:(?:reg|logic|wire)\s+)?(?:signed\s+)?'
            r'(?:\[[^\]]+\]\s*)?([A-Za-z_]\w*)\s*(?=[,;)=])', src):
        name = m.group(1)
        if name and name not in VERILOG_KEYWORDS:
            out_ports.setdefault(name, src[:m.start()].count('\n') + 1)
    if not out_ports:
        return findings

    # Only consider reset-less modules (no reset-ish input port anywhere).
    input_decls = ' '.join(re.findall(r'\binput\b[^;)\n]*', src))
    if _RESET_NAME_RE.search(input_decls):
        return findings

    # Registered = appears on LHS of a non-blocking assignment.
    registered = {mm.group(1)
                  for mm in re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', src)}
    has_initial = bool(re.search(r'\binitial\b', src))

    for name, lineno in out_ports.items():
        if name not in registered:
            continue
        # Declaration-time initializer: a decl line for `name` containing `=`.
        decl_init = re.search(
            r'\b(?:output|reg|logic)\b[^;\n]*\b' + re.escape(name) + r'\s*=', src)
        if decl_init or (has_initial and re.search(
                r'\binitial\b[\s\S]{0,200}?\b' + re.escape(name) + r'\s*(<=|=)', src)):
            continue
        findings.append(Finding(
            path, lineno, 'WARN', 'uninit-registered-output', name,
            f"registered output '{name}' has no reset and no power-up initializer "
            f"-> powers up as X. A deterministic reference (and VerilogEval-style "
            f"testbenches that sample at t=0) expects 0 there. Fix: declare "
            f"`output reg ... {name} = 0;` (or add an `initial` value)."))
    return findings


# ---------------------------------------------------------------------------
# Rule 6: Incomplete sensitivity list (latch / wrong-update hazard)
# ---------------------------------------------------------------------------
def rule_incomplete_sensitivity(src: str, path: str) -> List[Finding]:
    """Flag a LEVEL-sensitive `always @(<explicit list>)` whose body reads a signal that is
    NOT in the sensitivity list — the classic incomplete-sensitivity-list bug.

    A combinational / level-sensitive block must react to every signal it reads; if it
    lists only some, it behaves like a latch that misses updates on the omitted signals.
    The fix is `always @(*)`. Edge blocks (`@(posedge/negedge ...)`) and `@(*)` / `always_comb`
    are exempt. Learned from VerilogEval-Machine Prob145: `always @(a) if (clock) p<=a;`
    misses clock-edge updates — the reference uses `always @(*) if (clock) p=a;`. chip-AGNOSTIC.
    """
    findings: List[Finding] = []
    for m in re.finditer(r'\balways\b\s*@\s*\(([^)]*)\)', src):
        sens = m.group(1)
        if '*' in sens or re.search(r'\b(pos|neg)edge\b', sens):
            continue                                   # @(*) or clocked — exempt
        listed = set(re.findall(r'[A-Za-z_]\w*', sens))
        if not listed:
            continue
        # Extract the block body: begin..end (depth-matched) or a single statement.
        rest = src[m.end():]
        bm = re.match(r'\s*begin\b', rest)
        if bm:
            depth, i, n = 0, 0, len(rest)
            tok = re.compile(r'\b(begin|end)\b')
            start = None
            for t in tok.finditer(rest):
                if t.group(1) == 'begin':
                    if depth == 0:
                        start = t.end()
                    depth += 1
                else:
                    depth -= 1
                    if depth == 0:
                        body = rest[start:t.start()]
                        break
            else:
                continue
        else:
            semi = rest.find(';')
            if semi == -1:
                continue
            body = rest[:semi + 1]
        # LHS targets (assigned) are not "reads"; everything else read must be in the list.
        lhs = set(re.findall(r'(\w+)(?:\s*\[[^\]]*\])?\s*(?:<=|=)(?!=)', body))
        reads = {t for t in re.findall(r'[A-Za-z_]\w*', body)
                 if t not in VERILOG_KEYWORDS and t not in lhs
                 and not re.match(r"^\d", t)}
        missing = sorted(reads - listed)
        if missing:
            lineno = src[:m.start()].count('\n') + 1
            findings.append(Finding(
                path, lineno, 'WARN', 'incomplete-sensitivity-list', ','.join(missing),
                f"level-sensitive `always @({sens.strip()})` reads {missing} not in its "
                f"sensitivity list — it behaves like a latch that misses updates on those "
                f"signals. Use `always @(*)` (or add them)."))
    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def lint_file(path: Path) -> List[Finding]:
    src = path.read_text(errors='replace')
    src = strip_comments(src)
    results = []
    results += rule_undriven_and_unread(src, str(path))
    results += rule_case_coverage(src, str(path))
    results += rule_pulse_swallow(src, str(path))
    results += rule_uninit_registered_output(src, str(path))
    results += rule_incomplete_sensitivity(src, str(path))
    return results


def main():
    ap = argparse.ArgumentParser(description='General RTL hygiene lint.')
    ap.add_argument('files', nargs='+', help='Verilog/SystemVerilog files')
    ap.add_argument('--json', help='Write findings as JSON to this path')
    ap.add_argument('--severity', choices=['ERROR', 'WARN', 'INFO'], default='INFO',
                    help='Minimum severity to report (default: INFO)')
    args = ap.parse_args()

    sev_order = {'ERROR': 2, 'WARN': 1, 'INFO': 0}
    min_sev = sev_order[args.severity]

    all_findings: List[Finding] = []
    for f in args.files:
        p = Path(f)
        if not p.exists():
            print(f"WARNING: file not found: {f}", file=sys.stderr)
            continue
        try:
            all_findings += lint_file(p)
        except Exception as e:
            print(f"ERROR parsing {f}: {e}", file=sys.stderr)
            return 2

    filtered = [f for f in all_findings if sev_order[f.severity] >= min_sev]

    # Text report
    err = sum(1 for f in filtered if f.severity == 'ERROR')
    warn = sum(1 for f in filtered if f.severity == 'WARN')
    info = sum(1 for f in filtered if f.severity == 'INFO')
    print(f"rtl_hygiene_lint: {err} errors, {warn} warnings, {info} info")
    print("-" * 70)
    for fd in sorted(filtered, key=lambda x: (x.file, x.line, x.severity)):
        print(f"{fd.file}:{fd.line}: [{fd.severity}] {fd.rule}: {fd.message}")

    if args.json:
        Path(args.json).write_text(json.dumps([asdict(f) for f in filtered], indent=2))

    return 1 if err > 0 or warn > 0 else 0


if __name__ == '__main__':
    sys.exit(main())
