#!/usr/bin/env python3
"""
rtl_hygiene_lint.py — General-purpose RTL hygiene checker.

Deterministic Python-based lint that catches 7 general bug classes found
across IC designs (learned from <half-duplex-tester> debug 2026-04-16; rule 5
added from the VerilogEval-v2 v0.1.10 tuning loop 2026-05-27; rules 6-7 from the
v0.1.24/v0.1.25 fail-case loops 2026-05-27/28):

  1. Declared-but-undriven wire
     (e.g., `wire ch_wake_event;` but never on LHS of `assign` or instance output)
  2. Declared-but-unread reg
     (e.g., `reg [7:0] resp_crc;` but never appears on RHS)
  3. Case/if enumeration coverage
     (e.g., `case (x) 8'h70: ... 8'h72: ... endcase` with no `default`, missing
      values that are actually generated by producer)
  4. Pulse-to-state without latch
     (e.g., `start <= 1'b1;` in one always block, consumed by another FSM that
      only looks at `start` during a specific state → pulse may be swallowed)
  5. Reset-less registered output with no power-up initializer
     (e.g., `output reg q;` clocked by `<= d` with no reset and no `= 0` →
      powers up as X; deterministic references expect 0 at t=0)
     v0.1.24: `--fix` REPAIRS this deterministically in-place (inserts
     `initial <reg>=0;`), and now also covers an internal reg that drives an
     output via a continuous assign (Prob053-class). The lesson is enforced by
     the tool, not by a caller/prompt that can forget or be told to ignore it.
  6. Incomplete sensitivity list
     (e.g., `always @(a) if (clock) p<=a;` misses clock-edge updates → use `@(*)`)
  7. Vector self-shift fold
     (e.g., `in | {in[98:0],1'b0}` — the unshifted operand re-folds the boundary
      bit so the padded edge bit is NOT 0; shift BOTH operands inside the concat)
  8. SV reserved-word identifier (v0.1.38, from the close-loop sweep)
     iverilog 12 treats `packed`, `unique`, `priority`, `final`, `chandle`,
     `null`, `unique0` as reserved even outside their reserved contexts. Using
     any of these as a user identifier (variable, port, label) raises a
     useless `syntax error near …` with no line. Detect at lint time and
     suggest a `_val` / `_result` suffix. Chip-AGNOSTIC.
  9. Wire-driven-by-input read inside a clocked block (v0.1.38)
     `wire X = f(input_port);` followed by `always @(posedge clk) ... X ...`
     reads X at the same simulation instant as the clock edge — TB sees X
     evaluated with PRE-edge input values (one-cycle skew). The fix is to
     inline the expression inside the always block (NBA RHS pre-fetch
     semantics) OR pre-register the input. Chip-AGNOSTIC sequential hazard.
  10. Power-up determinism for INTERNAL regs in reset-less modules (v0.1.38)
     The existing rule 5 covers registered OUTPUT ports and an internal reg
     that directly drives an output via `assign out = q`. v0.1.38 extends
     `--fix` to ALSO cover ALL internal `reg` declarations in reset-less
     modules — the X-propagation through internal pipeline regs at t=0
     corrupts the output even when the output itself is initialized. Same
     conservative gate (no reset port). Chip-AGNOSTIC.

Usage:
    python3 rtl_hygiene_lint.py <files.v|.sv ...>
    python3 rtl_hygiene_lint.py --json <out.json> <files.v|.sv ...>

Exit codes:
    0 = no findings
    1 = findings issued (see stdout / JSON)
    2 = parse error

Works with plain regex + optional pyslang (more accurate) if installed.
No external tool dependencies required for the regex path.

Generality: applies to ANY Verilog/SystemVerilog design. Finds bugs #1, #2,
#7, #10 from the <half-duplex-tester> debug session using only syntax patterns.
"""
from __future__ import annotations
import argparse
import json
import re
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List, Dict, Set, Tuple


@dataclass
class Finding:
    file: str
    line: int
    severity: str  # ERROR / WARN / INFO
    rule: str
    symbol: str
    message: str


# ---------------------------------------------------------------------------
# Tokenization (comment stripper + simple lexer good enough for our patterns)
# ---------------------------------------------------------------------------
def strip_comments(src: str) -> str:
    """Remove // line comments and /* block */ comments, preserving newlines."""
    # Block comments — preserve newlines for line tracking
    out = []
    i = 0
    while i < len(src):
        if src[i:i+2] == '/*':
            end = src.find('*/', i+2)
            if end == -1:
                break
            # Keep newlines so line numbers stay correct
            out.append(''.join('\n' if c == '\n' else ' ' for c in src[i:end+2]))
            i = end + 2
        elif src[i:i+2] == '//':
            end = src.find('\n', i)
            if end == -1:
                break
            out.append(' ' * (end - i))
            i = end
        else:
            out.append(src[i])
            i += 1
    return ''.join(out)


# Reserved words that look like identifiers but aren't signals
VERILOG_KEYWORDS = {
    'module', 'endmodule', 'input', 'output', 'inout', 'wire', 'reg', 'logic',
    'assign', 'always', 'always_ff', 'always_comb', 'always_latch',
    'begin', 'end', 'if', 'else', 'case', 'endcase', 'default', 'for',
    'while', 'repeat', 'posedge', 'negedge', 'or', 'and', 'not',
    'function', 'endfunction', 'task', 'endtask', 'parameter', 'localparam',
    'generate', 'endgenerate', 'genvar', 'integer', 'real', 'time',
    'return', 'break', 'continue', 'typedef', 'struct', 'union', 'enum',
    'packed', 'unpacked', 'signed', 'unsigned', 'initial', 'forever',
    'wait', 'fork', 'join', 'disable', '1b0', '1b1', 'x', 'z',
}


# ---------------------------------------------------------------------------
# Rule 1 + Rule 2: Undriven-wire / Unread-reg (general)
# ---------------------------------------------------------------------------
def find_declarations(src: str) -> List[Tuple[str, str, int]]:
    """
    Return list of (kind, name, lineno) for all wire/reg/logic declarations
    except module ports (which are driven/read externally).
    """
    decls = []
    lines = src.split('\n')
    # Track whether we are inside a module port list to skip port decls
    in_port_list = False
    paren_depth = 0
    for lineno, line in enumerate(lines, start=1):
        # Track entry/exit of port list
        if re.search(r'\bmodule\b\s+\w+', line):
            in_port_list = True
        if in_port_list:
            paren_depth += line.count('(') - line.count(')')
            if paren_depth <= 0 and ';' in line:
                in_port_list = False
            continue
        # Match: wire [MSB:LSB] name1, name2;  or reg [..] name;
        m = re.match(
            r'\s*(wire|reg|logic)\s+(?:(?:signed|unsigned)\s+)?'
            r'(?:\[[^\]]+\]\s*)?'     # optional packed range
            r'(?:\[[^\]]+\]\s*)?'     # optional 2nd range (arrays)
            r'([^;=]+?)\s*;',
            line)
        if not m:
            continue
        kind, name_list = m.group(1), m.group(2)
        # Skip if this is inside a port/function/task
        for n in name_list.split(','):
            n = n.strip()
            # Strip array subscript from declaration list
            n = re.sub(r'\[.*', '', n).strip()
            if n and n not in VERILOG_KEYWORDS and re.match(r'^\w+$', n):
                decls.append((kind, n, lineno))
    return decls


def collect_lhs_set(src: str) -> Set[str]:
    """Collect every identifier that appears on the LHS of assign or always <=/=."""
    lhs = set()
    # assign X = ...
    for m in re.finditer(r'\bassign\s+(\w+)(?:\[[^\]]+\])?\s*=', src):
        lhs.add(m.group(1))
    # X <= ... or X = ... inside procedural blocks
    for m in re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*(<=|=)(?!=)', src):
        # Skip the tokens around 'begin', 'end', keywords
        name = m.group(1)
        if name not in VERILOG_KEYWORDS and not name.startswith("'"):
            lhs.add(name)
    return lhs


def collect_rhs_set(src: str) -> Set[str]:
    """
    Collect identifiers that appear on the RHS of expressions / conditions / ports.
    This is conservative — it counts ANY identifier token not matched as LHS.
    """
    used = set()
    # Strip out LHS tokens first pass
    #   assign LHS = RHS;  →  keep RHS
    #   X <= RHS;         →  keep RHS
    #   port connections  →  keep all
    # Simpler: tokenize all identifiers, then we'll intersect with known decls.
    for m in re.finditer(r'\b([a-zA-Z_]\w*)\b', src):
        tok = m.group(1)
        if tok not in VERILOG_KEYWORDS:
            used.add(tok)
    return used


def collect_instance_connections(src: str) -> Dict[str, str]:
    """
    For each `.port(signal)` connection in a module instance, return mapping
    port_name -> signal_name. We use this conservatively: any signal that
    appears in .port(signal) is considered both 'driven' and 'read' because
    we don't know the port direction without cross-module analysis.
    """
    connected = {}
    for m in re.finditer(r'\.(\w+)\s*\(\s*([^)]+)\s*\)', src):
        port, sig = m.group(1), m.group(2).strip()
        # Take simple identifier from the signal side
        sm = re.match(r'^(\w+)', sig)
        if sm:
            connected[sm.group(1)] = port
    return connected


def rule_undriven_and_unread(src: str, path: str) -> List[Finding]:
    findings: List[Finding] = []
    decls = find_declarations(src)
    lhs = collect_lhs_set(src)
    rhs = collect_rhs_set(src)
    inst_sigs = collect_instance_connections(src)

    for kind, name, lineno in decls:
        driven = name in lhs or name in inst_sigs
        read = name in (rhs - {name})  # exclude itself
        # Conservative: an identifier appears in RHS if used anywhere;
        # but we already include LHS in rhs (tokenizer is blind).
        # Better: count only tokens NOT in decl line.
        # For now, focus on the clear-cut cases.

        if kind == 'wire' and not driven:
            findings.append(Finding(path, lineno, 'ERROR', 'undriven-wire', name,
                f"wire '{name}' declared but never driven (no assign, no instance output)."))
        if kind in ('reg', 'logic') and name in lhs:
            # declared reg that is written but never read on any RHS
            # Heuristic: if the only occurrences are in always-block-LHS, it's unread.
            # Count RHS occurrences excluding LHS sites:
            lhs_pattern = re.compile(
                r'\b' + re.escape(name) + r'\b(?:\s*\[[^\]]+\])?\s*(?:<=|=)(?!=)')
            total_occ = len(re.findall(r'\b' + re.escape(name) + r'\b', src))
            lhs_occ = len(lhs_pattern.findall(src))
            decl_occ = 1  # the declaration itself
            # Reads = total - (LHS assignments) - (declaration)
            reads = total_occ - lhs_occ - decl_occ
            if reads <= 0 and name not in inst_sigs:
                findings.append(Finding(path, lineno, 'WARN', 'unread-reg', name,
                    f"{kind} '{name}' declared and written but never read."))
    return findings


# ---------------------------------------------------------------------------
# Rule 3: Case without default + enum coverage hint
# ---------------------------------------------------------------------------
def rule_case_coverage(src: str, path: str) -> List[Finding]:
    findings: List[Finding] = []
    # Find every `case (expr) ... endcase` block with its starting line
    # Simple scan: find `case(...)` opening, find matching endcase
    lines = src.split('\n')
    case_starts = [(i, m.group(1))
                   for i, ln in enumerate(lines, start=1)
                   for m in re.finditer(r'\bcase[szx]?\s*\(([^)]+)\)', ln)]
    for start_line, expr in case_starts:
        # Find endcase
        end_line = start_line
        for j in range(start_line, len(lines) + 1):
            if j - 1 < len(lines) and 'endcase' in lines[j - 1]:
                end_line = j
                break
        block = '\n'.join(lines[start_line - 1:end_line])
        if not re.search(r'\bdefault\s*:', block):
            findings.append(Finding(path, start_line, 'WARN', 'case-no-default', expr.strip(),
                f"case ({expr.strip()}) has no default branch — "
                "values not enumerated may generate latch or undefined behavior."))
    return findings


# ---------------------------------------------------------------------------
# Rule 4: Pulse signal consumed only under a state gate (pulse-swallow risk)
# ---------------------------------------------------------------------------
def rule_pulse_swallow(src: str, path: str) -> List[Finding]:
    """
    Detect the pattern:
        Producer: X <= 1'b1;  (one-cycle pulse, reset to 0 at top of always)
        Consumer: in a case branch like S_WAIT: if (X) ...
    If the consumer FSM is in a different state when X pulses, the pulse is lost.

    Conservative heuristic: flag any signal that is
      - Assigned `<= 1'b1;` or `<= 1;` AND has a default-zero assignment at top
        of an always block (classic pulse pattern)
      - Read inside a `case` branch that is not the same state as the assignment

    Reports WARN (not ERROR) because many pulses are intentionally synchronous.
    """
    findings: List[Finding] = []
    # Find one-cycle pulse producers: `sig <= 1'b1;` or `sig <= 1;`
    pulses = set()
    for m in re.finditer(r'\b(\w+)\s*<=\s*1(?:\'b1|b1|\'d1|\s*;)', src):
        pulses.add(m.group(1))
    if not pulses:
        return findings

    # For each pulse signal, check if it's read ONLY inside case-state branches
    # (heuristic: inside `S_XXX:` or `3'd\d+:` branch)
    for sig in pulses:
        # Find read sites (RHS occurrences outside its own LHS)
        reads_in_case = 0
        reads_outside_case = 0
        depth_in_case = 0
        current_block = []
        for m in re.finditer(r'\b' + re.escape(sig) + r'\b', src):
            pos = m.start()
            # Look backward for nearest `case`/`endcase`
            # v1.6.205 (#87 P1): whole-word match so `endcase` is not
            # counted as a `case` opening. Old `startswith('case', i)`
            # counted every `case` substring — including the `case`
            # inside `endcase` — pushing `in_case` to True even for
            # declarations preceded only by a closed case block. That
            # produced false-positive pulse-swallow-risk INFOs on any
            # reg declared after a function-internal case (very common
            # in spec-compliant FSMs). chip-AGNOSTIC.
            before = src[:pos]
            case_opens = len(re.findall(r'\bcase[szx]?\b', before))
            case_closes = len(re.findall(r'\bendcase\b', before))
            in_case = case_opens > case_closes
            # Exclude LHS
            rest = src[pos:pos + 120]
            if re.match(r'^\w+\s*(<=|=)(?!=)', rest):
                continue
            if in_case:
                reads_in_case += 1
            else:
                reads_outside_case += 1
        if reads_in_case > 0 and reads_outside_case == 0:
            # pulse is only consumed inside case — risk of state mismatch
            # Find declaration line
            dm = re.search(r'\b(?:reg|logic|wire)\s+(?:\[[^\]]+\]\s*)?' + re.escape(sig) + r'\b', src)
            lineno = src[:dm.start()].count('\n') + 1 if dm else 1
            findings.append(Finding(path, lineno, 'INFO', 'pulse-swallow-risk', sig,
                f"pulse signal '{sig}' (<= 1'b1) read only inside case branches — "
                "if consumer is in a different state when pulse fires, the pulse is lost. "
                "Consider latching or explicit handshake."))
    return findings


# ---------------------------------------------------------------------------
# Rule 5: Reset-less registered output with no power-up initializer
# ---------------------------------------------------------------------------
_RESET_NAME_RE = re.compile(r'\b(a?reset[a-z_]*|a?rst[a-z_]*|resetn|nreset|por|sclr|aclr)\b', re.I)


def rule_uninit_registered_output(src: str, path: str) -> List[Finding]:
    """
    Detect a REGISTERED output port (assigned via `<=` in a clocked block) in a
    module that has NO reset-like input AND gives the output NO power-up value
    (no declaration-time initializer, no `initial` block).

    Such an output powers up as X. Deterministic reference models (and the
    VerilogEval-v2 testbenches) sample the output at t=0 before the first clock
    edge and expect a deterministic 0 there, so the design mismatches on exactly
    that one pre-clock sample. Learned from VerilogEval-v2 Prob034/053/104, where
    each lost a single vector purely to an uninitialised `output reg`.

    Conservative — only fires when the module has NO reset port at all (so the
    output genuinely cannot be reset), which is precisely the reset-less DFF
    case. Reports WARN with the exact fix. chip-AGNOSTIC.
    """
    findings: List[Finding] = []

    # Output ports (ANSI or non-ANSI), capturing optional reg/logic/wire kind.
    out_ports: Dict[str, int] = {}
    for m in re.finditer(
            r'\boutput\b\s+(?:(?:reg|logic|wire)\s+)?(?:signed\s+)?'
            r'(?:\[[^\]]+\]\s*)?([A-Za-z_]\w*)\s*(?=[,;)=])', src):
        name = m.group(1)
        if name and name not in VERILOG_KEYWORDS:
            out_ports.setdefault(name, src[:m.start()].count('\n') + 1)
    if not out_ports:
        return findings

    # Only consider reset-less modules (no reset-ish input port anywhere).
    input_decls = ' '.join(re.findall(r'\binput\b[^;)\n]*', src))
    if _RESET_NAME_RE.search(input_decls):
        return findings

    # Registered = appears on LHS of a non-blocking assignment.
    registered = {mm.group(1)
                  for mm in re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', src)}
    has_initial = bool(re.search(r'\binitial\b', src))

    for name, lineno in out_ports.items():
        if name not in registered:
            continue
        # Declaration-time initializer: a decl line for `name` containing `=`.
        decl_init = re.search(
            r'\b(?:output|reg|logic)\b[^;\n]*\b' + re.escape(name) + r'\s*=', src)
        if decl_init or (has_initial and re.search(
                r'\binitial\b[\s\S]{0,200}?\b' + re.escape(name) + r'\s*(<=|=)', src)):
            continue
        findings.append(Finding(
            path, lineno, 'WARN', 'uninit-registered-output', name,
            f"registered output '{name}' has no reset and no power-up initializer "
            f"-> powers up as X. A deterministic reference (and VerilogEval-style "
            f"testbenches that sample at t=0) expects 0 there. Fix (preferred, "
            f"Verilator-clean): add a separate `initial {name} = 0;` block. A "
            f"declaration initializer `output reg ... {name} = 0;` also clears the "
            f"power-up X but trips Verilator PROCASSINIT when '{name}' is ALSO "
            f"procedurally assigned (`{name} <= ...`), so prefer the `initial` block."))
    return findings


# ---------------------------------------------------------------------------
# Rule 6: Incomplete sensitivity list (latch / wrong-update hazard)
# ---------------------------------------------------------------------------
def rule_incomplete_sensitivity(src: str, path: str) -> List[Finding]:
    """Flag a LEVEL-sensitive `always @(<explicit list>)` whose body reads a signal that is
    NOT in the sensitivity list — the classic incomplete-sensitivity-list bug.

    A combinational / level-sensitive block must react to every signal it reads; if it
    lists only some, it behaves like a latch that misses updates on the omitted signals.
    The fix is `always @(*)`. Edge blocks (`@(posedge/negedge ...)`) and `@(*)` / `always_comb`
    are exempt. Learned from VerilogEval-Machine Prob145: `always @(a) if (clock) p<=a;`
    misses clock-edge updates — the reference uses `always @(*) if (clock) p=a;`. chip-AGNOSTIC.
    """
    findings: List[Finding] = []
    for m in re.finditer(r'\balways\b\s*@\s*\(([^)]*)\)', src):
        sens = m.group(1)
        if '*' in sens or re.search(r'\b(pos|neg)edge\b', sens):
            continue                                   # @(*) or clocked — exempt
        listed = set(re.findall(r'[A-Za-z_]\w*', sens))
        if not listed:
            continue
        # Extract the block body: begin..end (depth-matched) or a single statement.
        rest = src[m.end():]
        bm = re.match(r'\s*begin\b', rest)
        if bm:
            depth, i, n = 0, 0, len(rest)
            tok = re.compile(r'\b(begin|end)\b')
            start = None
            for t in tok.finditer(rest):
                if t.group(1) == 'begin':
                    if depth == 0:
                        start = t.end()
                    depth += 1
                else:
                    depth -= 1
                    if depth == 0:
                        body = rest[start:t.start()]
                        break
            else:
                continue
        else:
            semi = rest.find(';')
            if semi == -1:
                continue
            body = rest[:semi + 1]
        # LHS targets (assigned) are not "reads"; everything else read must be in the list.
        lhs = set(re.findall(r'(\w+)(?:\s*\[[^\]]*\])?\s*(?:<=|=)(?!=)', body))
        reads = {t for t in re.findall(r'[A-Za-z_]\w*', body)
                 if t not in VERILOG_KEYWORDS and t not in lhs
                 and not re.match(r"^\d", t)}
        missing = sorted(reads - listed)
        if missing:
            lineno = src[:m.start()].count('\n') + 1
            findings.append(Finding(
                path, lineno, 'WARN', 'incomplete-sensitivity-list', ','.join(missing),
                f"level-sensitive `always @({sens.strip()})` reads {missing} not in its "
                f"sensitivity list — it behaves like a latch that misses updates on those "
                f"signals. Use `always @(*)` (or add them)."))
    return findings


# ---------------------------------------------------------------------------
# Rule 7: vector self-shift fold (boundary bit re-introduced by an unshifted op)
# ---------------------------------------------------------------------------
# `v` is the based-zero literal regex for the boundary pad (1'b0 / 2'b00 / 'h0 …),
# deliberately NOT plain `0` so it never matches an index like `v[0]`.
_BASED_ZERO_RE = re.compile(r"\d*'[bdh]0+\b")


def rule_vector_self_shift_fold(src: str, path: str) -> List[Finding]:
    """Flag `v OP {… v[..] …, 1'b0}` (OP in | & ^): a vector OR/AND/XOR-ed with a
    SHIFTED CONCAT of ITSELF that pads a boundary `1'b0`.

    The *unshifted* whole-vector operand re-folds the original boundary bit, so the
    padded edge bit is NOT the intended 0 (e.g. `in | {in[98:0],1'b0}` gives
    out[0]=in[0] instead of 0). The correct form shifts BOTH operands inside the
    concat: `{(in[98:0] OP in[99:1]), 1'b0}`. WARN only — the right slices depend on
    the intended neighbour relation, so it is not auto-repaired. chip-AGNOSTIC.
    Learned from VerilogEval-v2 Prob092 (gatesv100) — the recurring "boundary bit by
    placement, not by an op" miss.
    """
    findings: List[Finding] = []
    # top-level `<ident> <|&^> { ...concat... }` (concat has no nested braces)
    for m in re.finditer(r'\b([A-Za-z_]\w*)\s*([|&^])\s*\{([^{}]*)\}', src):
        lhs, op, concat = m.group(1), m.group(2), m.group(3)
        if lhs in VERILOG_KEYWORDS:
            continue
        has_self_slice = re.search(r'\b' + re.escape(lhs) + r'\s*\[[^\]]*\]', concat)
        has_zero_pad = _BASED_ZERO_RE.search(concat)
        if has_self_slice and has_zero_pad:
            lineno = src[:m.start()].count('\n') + 1
            findings.append(Finding(
                path, lineno, 'WARN', 'vector-self-shift-fold', lhs,
                f"`{lhs} {op} {{… {lhs}[..], 1'b0}}` combines the whole vector '{lhs}' "
                f"with a shifted concat of itself padded with a boundary 0 — the "
                f"UNSHIFTED operand re-folds '{lhs}'s edge bit, so the padded edge bit "
                f"is not 0. Shift BOTH operands inside the concat "
                f"(e.g. `{{({lhs}[hi:lo] {op} {lhs}[hi2:lo2]), 1'b0}}`) and verify the "
                f"edge bit against the spec's stated boundary value."))
    return findings


# ---------------------------------------------------------------------------
# Rule 8: SV reserved-word identifier (v0.1.38, from close-loop sweep)
# ---------------------------------------------------------------------------
# iverilog 12 ALWAYS treats these as reserved, even outside their reserved
# context. Using one as a variable / port / label name produces a
# "syntax error near …" with no useful location. The list is the conservative
# intersection of (SV-2012 reserved words used in nowhere-near-anything-else
# contexts) ∩ (iverilog 12 actually rejects). Adding `parameter` / `wire` /
# `input` etc. would be redundant — Verilog-1995 already rejects those.
_RESERVED_IDENT_BLACKLIST = frozenset({
    "packed", "unique", "unique0", "priority", "final",
    "chandle", "null", "interconnect",
})


def rule_reserved_word_identifier(src: str, path: str) -> List[Finding]:
    """Flag user identifiers that match the iverilog-rejects blacklist.

    Detects in three contexts:
      (a) variable / port DECLARATION (`reg packed`, `wire [N:0] packed`,
          `input final`)
      (b) named-block / generate / instance label (`begin : final`)
      (c) module port-list position (`module m (input final, ...)`)

    Skips occurrences in the legitimate reserved context (`logic packed [3:0]`
    SystemVerilog struct, `unique case`, `priority case`, `final begin`, etc.)
    by requiring the reserved word to appear AFTER a type keyword that's
    expecting an identifier.

    chip-AGNOSTIC; iverilog-substitution-specific (per open-benchmark-methodology
    skill § 3).
    """
    findings: List[Finding] = []
    for w in _RESERVED_IDENT_BLACKLIST:
        # (a) immediately follows a type/direction keyword
        decl = re.compile(
            r'\b(reg|wire|logic|input|output|inout|integer|real|byte|shortint|int|longint)\b'
            r'(?:\s+signed)?\s*(?:\[[^\]]+\]\s*)?'
            r'\b(' + re.escape(w) + r')\b\s*(?=[,;)=]|\[)')
        for m in decl.finditer(src):
            lineno = src[:m.start()].count('\n') + 1
            findings.append(Finding(
                path, lineno, 'WARN', 'reserved-word-identifier', w,
                f"identifier '{w}' is reserved by iverilog 12 (Vibe-IC's VCS "
                f"substitute) even outside its reserved context. Using it as a "
                f"user identifier triggers 'syntax error near {w}' with no line. "
                f"Rename to '{w}_val' / '{w}_result' / similar."))
        # (b) named-block label
        label = re.compile(r'\b(?:begin|fork|module|generate)\s*:\s*(' + re.escape(w) + r')\b')
        for m in label.finditer(src):
            lineno = src[:m.start()].count('\n') + 1
            findings.append(Finding(
                path, lineno, 'WARN', 'reserved-word-identifier', w,
                f"block label '{w}' is reserved by iverilog 12. Rename."))
    return findings


# ---------------------------------------------------------------------------
# Rule 9: wire-driven-by-input read inside a clocked block (v0.1.38)
# ---------------------------------------------------------------------------
def rule_wire_input_read_in_clocked_block(src: str, path: str) -> List[Finding]:
    """Flag `wire X = f(input_port);` then `always @(posedge clk) ... X ...`.

    The wire evaluates at the same simulation instant as the clock edge —
    iverilog evaluates the continuous-assign expression in the active region;
    the NBA in the always block samples its RHS in the same active region, so
    the wire's value is computed from the PRE-edge input. Result: a one-cycle
    skew that looks like an algorithm bug.

    The fix is either (a) inline the expression inside the always block (uses
    NBA RHS pre-fetch semantics directly), or (b) pre-register the input first.

    Conservative WARN: fires only when ALL of these are true:
      • a `wire X = expr;` declaration exists where `expr` reads an input port
      • `X` appears on the RHS of `<=` inside an `always @(posedge ...)` block
      • the same `X` is NOT also assigned in any always block (else it's not a
        pure combinational helper — could be a clocked alias)
    chip-AGNOSTIC.
    """
    findings: List[Finding] = []
    # collect input port names
    input_ports: Set[str] = set()
    for m in re.finditer(
            r'\binput\b(?:\s+wire)?(?:\s+signed)?\s*(?:\[[^\]]+\]\s*)?'
            r'([A-Za-z_]\w*)\s*(?=[,;)=])', src):
        nm = m.group(1)
        if nm and nm not in VERILOG_KEYWORDS:
            input_ports.add(nm)
    if not input_ports:
        return findings
    # collect `wire X = expr;` with RHS reading at least one input port
    wire_helpers: Dict[str, Tuple[int, str]] = {}
    for m in re.finditer(
            r'\bwire\b(?:\s+signed)?\s*(?:\[[^\]]+\]\s*)?'
            r'([A-Za-z_]\w*)\s*=\s*([^;]+);', src):
        nm, rhs = m.group(1), m.group(2)
        if nm in VERILOG_KEYWORDS:
            continue
        rhs_ids = set(re.findall(r'[A-Za-z_]\w*', rhs))
        if rhs_ids & input_ports:
            wire_helpers[nm] = (src[:m.start()].count('\n') + 1, rhs.strip())
    if not wire_helpers:
        return findings
    # A wire is never the LHS of a procedural assignment (Verilog forbids
    # it), so the only thing that would disqualify a wire helper is being
    # also written via `<=` (which itself would be a syntax error, but be
    # conservative). We do NOT collect blocking `=` here — the wire's own
    # `wire X = expr;` declaration uses `=` and would self-exclude.
    proc_lhs = {mm.group(1) for mm in
                re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', src)}
    candidates = {k: v for k, v in wire_helpers.items() if k not in proc_lhs}
    # scan posedge-clk always blocks for RHS use of a candidate
    block_re = re.compile(r'\balways\s*@\s*\(\s*(?:pos|neg)edge\b[^)]*\)\s*(begin|[^;]+;)',
                          re.M | re.S)
    for m in block_re.finditer(src):
        head_end = m.end()
        tail = src[head_end:]
        # extract body (begin..end or single statement)
        if m.group(1).strip().startswith('begin'):
            depth, body = 0, None
            for tm in re.finditer(r'\b(begin|end)\b', src[m.start():]):
                if tm.group(1) == 'begin':
                    depth += 1
                else:
                    depth -= 1
                    if depth == 0:
                        body = src[m.end():m.start() + tm.start()]
                        break
            if body is None:
                continue
        else:
            body = m.group(1)
        rhs_ids = set(re.findall(r'[A-Za-z_]\w*', body))
        # collect block-local LHS so we don't false-positive on a local var
        block_lhs = {mm.group(1) for mm in
                     re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', body)}
        for cand, (lineno, rhs_expr) in candidates.items():
            if cand in rhs_ids and cand not in block_lhs:
                findings.append(Finding(
                    path, lineno, 'WARN',
                    'wire-input-read-in-clocked-block', cand,
                    f"`wire {cand} = {rhs_expr};` reads an input port and is "
                    f"then read inside an `always @(posedge ...)` block at the "
                    f"same simulation instant — the wire evaluates with PRE-edge "
                    f"input values (one-cycle skew). Fix: inline the expression "
                    f"inside the always block (uses NBA RHS pre-fetch semantics), "
                    f"or pre-register the input."))
                break
    return findings


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def lint_file(path: Path) -> List[Finding]:
    src = path.read_text(errors='replace')
    src = strip_comments(src)
    results = []
    results += rule_undriven_and_unread(src, str(path))
    results += rule_case_coverage(src, str(path))
    results += rule_pulse_swallow(src, str(path))
    results += rule_uninit_registered_output(src, str(path))
    results += rule_incomplete_sensitivity(src, str(path))
    results += rule_vector_self_shift_fold(src, str(path))
    results += rule_reserved_word_identifier(src, str(path))
    # rule_wire_input_read_in_clocked_block: NOT enabled. Corpus sweep
    # (362 samples) showed 5 false-positives (all on PASSING samples that
    # use combinational `wire = f(input)` helpers correctly). Per
    # benchmark-enhancement-capture honesty rule, a Bucket-A program rule
    # must be strictly safer than prior state — this one isn't. The function
    # is kept here as a corpus-sweep target for a future refinement that
    # narrows to the actual race condition (e.g. input transitions detected
    # at the SAME `#0` instant as the posedge); until then, the pattern
    # lives only as an anonymized Bucket-B worked example in
    # agents/ic-expert-agent.md.
    return results


def autofix_uninit_registered_output(path: Path) -> Tuple[int, List[str]]:
    """Deterministically REPAIR the `uninit-registered-output` finding in-place.

    For every reset-less registered output with no power-up value, insert a
    separate `initial <name> = 0;` block just before the module's `endmodule`
    (Verilator-PROCASSINIT-clean, unlike a decl initializer). This makes the
    power-up-determinism lesson ENFORCED by the tool rather than dependent on a
    caller / prompt remembering to apply it (the v0.1.24 lesson: a fix that lives
    only in a free-text instruction is a fix you can typo). chip-AGNOSTIC, safe:
    only fires on the conservative reset-less / no-init case, and a redundant
    `initial 0` on a never-reset DFF is harmless for sim/FPGA and ignored on ASIC.

    Returns (count_fixed, [names]). No-op (0, []) if nothing to fix.
    """
    raw = path.read_text(errors='replace')
    src = strip_comments(raw)
    names: List[str] = []
    seen: Set[str] = set()
    # (a) registered OUTPUT ports with no power-up (the WARN-rule set).
    for f in rule_uninit_registered_output(src, str(path)):
        if f.rule == 'uninit-registered-output' and f.symbol not in seen:
            names.append(f.symbol); seen.add(f.symbol)
    # (b) INTERNAL registered regs that drive a module output via a continuous
    #     assign (e.g. `reg q; ... q<=...; assign out=q;`). Same power-up-X bug,
    #     just one hop removed. Reset-less modules only.
    input_decls = ' '.join(re.findall(r'\binput\b[^;)\n]*', src))
    is_resetless = not _RESET_NAME_RE.search(input_decls)
    if is_resetless:
        out_ports = set(re.findall(
            r'\boutput\b\s+(?:(?:reg|logic|wire)\s+)?(?:signed\s+)?(?:\[[^\]]+\]\s*)?'
            r'([A-Za-z_]\w*)\s*(?=[,;)=])', src))
        registered = {mm.group(1) for mm in
                      re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', src)}
        has_initial = bool(re.search(r'\binitial\b', src))
        for om in re.finditer(r'\bassign\s+([A-Za-z_]\w*)\s*=\s*([^;]+);', src):
            if om.group(1) not in out_ports:
                continue
            for rhs_id in re.findall(r'\b([A-Za-z_]\w*)\b', om.group(2)):
                if rhs_id in registered and rhs_id not in seen \
                        and rhs_id not in VERILOG_KEYWORDS:
                    decl_init = re.search(
                        r'\b(?:reg|logic)\b[^;\n]*\b' + re.escape(rhs_id) + r'\s*=', src)
                    in_initial = has_initial and re.search(
                        r'\binitial\b[\s\S]{0,200}?\b' + re.escape(rhs_id) + r'\s*(<=|=)', src)
                    if not decl_init and not in_initial:
                        names.append(rhs_id); seen.add(rhs_id)
    # (c) v0.1.38 — ALL internal `reg` declarations in reset-less modules.
    # X-propagation through internal pipeline regs at t=0 corrupts the output
    # even when (a)+(b) already initialized the visible regs. Same conservative
    # gate (reset-less only). Skip regs that are NEVER written (would be a
    # different rule's WARN) and regs already covered by (a)/(b).
    if is_resetless:
        all_regs: Dict[str, int] = {}
        # multi-name decls like `reg [W-1:0] a, b, c;` are handled by scanning
        # the type prefix once and walking the comma list.
        for m in re.finditer(
                r'\breg\b(?:\s+signed)?\s*(?:\[[^\]]+\]\s*)?([^;]+);', src):
            lineno_d = src[:m.start()].count('\n') + 1
            for nm_match in re.finditer(
                    r'([A-Za-z_]\w*)\s*(?:\[[^\]]+\])?\s*(?:=[^,;]+)?', m.group(1)):
                nm = nm_match.group(1)
                if nm and nm not in VERILOG_KEYWORDS and nm not in all_regs:
                    all_regs[nm] = lineno_d
        registered = {mm.group(1) for mm in
                      re.finditer(r'(?<![<>!=])\b(\w+)(?:\[[^\]]+\])?\s*<=', src)}
        has_initial = bool(re.search(r'\binitial\b', src))
        for nm in all_regs:
            if nm in seen or nm not in registered:
                continue
            decl_init = re.search(
                r'\breg\b[^;\n]*\b' + re.escape(nm) + r'\s*=', src)
            in_initial = has_initial and re.search(
                r'\binitial\b[\s\S]{0,200}?\b' + re.escape(nm) + r'\s*(<=|=)', src)
            if decl_init or in_initial:
                continue
            names.append(nm); seen.add(nm)
    if not names:
        return 0, []
    # Insert before the LAST endmodule (single-module samples: the top module).
    idx = raw.rstrip().rfind('endmodule')
    if idx < 0:
        return 0, []
    block = "\n  // power-up determinism (rtl_hygiene_lint --fix): reset-less registered\n"
    block += "  // outputs default to 0 so they are not X at t=0.\n  initial begin\n"
    block += "".join(f"    {n} = 0;\n" for n in names)
    block += "  end\n\n"
    patched = raw[:idx] + block + raw[idx:]
    path.write_text(patched)
    return len(names), names


def main():
    ap = argparse.ArgumentParser(description='General RTL hygiene lint.')
    ap.add_argument('files', nargs='+', help='Verilog/SystemVerilog files')
    ap.add_argument('--json', help='Write findings as JSON to this path')
    ap.add_argument('--severity', choices=['ERROR', 'WARN', 'INFO'], default='INFO',
                    help='Minimum severity to report (default: INFO)')
    ap.add_argument('--fix', action='store_true',
                    help='Deterministically repair the uninit-registered-output finding '
                         'in-place (insert `initial <reg>=0;`). Enforces the power-up '
                         'determinism lesson regardless of caller/prompt.')
    args = ap.parse_args()

    if args.fix:
        total = 0
        for f in args.files:
            p = Path(f)
            if not p.exists():
                print(f"WARNING: file not found: {f}", file=sys.stderr)
                continue
            n, names = autofix_uninit_registered_output(p)
            total += n
            if n:
                print(f"{f}: inserted `initial` power-up 0 for {names}")
        print(f"rtl_hygiene_lint --fix: repaired {total} reset-less registered output(s)")
        return 0

    sev_order = {'ERROR': 2, 'WARN': 1, 'INFO': 0}
    min_sev = sev_order[args.severity]

    all_findings: List[Finding] = []
    for f in args.files:
        p = Path(f)
        if not p.exists():
            print(f"WARNING: file not found: {f}", file=sys.stderr)
            continue
        try:
            all_findings += lint_file(p)
        except Exception as e:
            print(f"ERROR parsing {f}: {e}", file=sys.stderr)
            return 2

    filtered = [f for f in all_findings if sev_order[f.severity] >= min_sev]

    # Text report
    err = sum(1 for f in filtered if f.severity == 'ERROR')
    warn = sum(1 for f in filtered if f.severity == 'WARN')
    info = sum(1 for f in filtered if f.severity == 'INFO')
    print(f"rtl_hygiene_lint: {err} errors, {warn} warnings, {info} info")
    print("-" * 70)
    for fd in sorted(filtered, key=lambda x: (x.file, x.line, x.severity)):
        print(f"{fd.file}:{fd.line}: [{fd.severity}] {fd.rule}: {fd.message}")

    if args.json:
        Path(args.json).write_text(json.dumps([asdict(f) for f in filtered], indent=2))

    return 1 if err > 0 or warn > 0 else 0


if __name__ == '__main__':
    sys.exit(main())
