"""ORGANIC #554 (a) — shared staged-SDC ground-truth helpers.

Both phase1 (doc ingestion -> L8/L19) and phase3 (PnR/STA SDC
emission) need to read the project's staged ``input/constraints/*.sdc``
and ``input/reference_flow/**/*.sdc`` files for ``create_clock -period
<ns> [get_ports <port>]`` directives. A single shared module keeps the
two consumers from drifting (emitter/checker doctrine, v0.1.49).

It is also where the flow's OWN SDC generator and the flow's SDC
CONSUMERS agree on how a generated deck identifies itself — see
:data:`GENERATED_BANNER` / :func:`generated_top_entity`. Those two live
here for the same reason the clock helpers do: the emitter
(``sdc_gen``) and the checker (``sdc_validator_check``) must read one
constant, or "is this file ours?" drifts into two answers.

Chip-AGNOSTIC: pure standard-SDC syntax, no chip-class literals.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional

# ---------------------------------------------------------------------
# Generator self-attribution (shared emitter/checker vocabulary)
# ---------------------------------------------------------------------

#: The banner ``sdc_gen`` stamps on every deck it writes. It is ALSO how a
#: consumer proves a file on disk is the flow's own generator output rather
#: than a hand-authored or third-party SDC. Emitter and checker must read
#: this one constant; a second spelling anywhere is the drift this module
#: exists to prevent.
GENERATED_BANNER: str = "Auto-generated by sdc_gen.py"

#: ``# Top entity: <name>`` — the top the generated deck says it constrains.
#: Written by ``sdc_gen._render_sdc`` immediately under the banner.
_TOP_ENTITY_RE = re.compile(r"^#\s*Top entity:\s*([A-Za-z_]\w*)\s*$", re.M)

#: How much of a deck has to be read to decide attribution. The banner and
#: the ``# Top entity:`` line are the first two comment lines of the header,
#: so this is generous by orders of magnitude and keeps the check O(1) in
#: the size of a large constraint file.
_ATTRIBUTION_HEAD_BYTES = 4096


def generated_top_entity(text: str) -> Optional[str]:
    """The top module ``text`` claims, IFF ``text`` is a generated deck.

    Returns ``None`` for anything that does not carry BOTH
    :data:`GENERATED_BANNER` and a parseable ``# Top entity:`` line — i.e.
    for every hand-authored SDC, every file from another tool, and any
    generated deck too old to be attributable. ``None`` therefore means
    "this program cannot claim ownership of this file", which is the only
    answer that lets a caller treat ownership as a licence to do anything.
    """
    head = text[:_ATTRIBUTION_HEAD_BYTES]
    if GENERATED_BANNER not in head:
        return None
    m = _TOP_ENTITY_RE.search(head)
    return m.group(1) if m else None


def generated_top_entity_of(path: Path) -> Optional[str]:
    """:func:`generated_top_entity` for a file; ``None`` when unreadable."""
    try:
        head = Path(path).read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return None
    return generated_top_entity(head)


_PERIOD_RE = re.compile(r"-period\s+([0-9]+(?:\.[0-9]+)?)", re.IGNORECASE)
_PORT_RE = re.compile(r"get_ports\s+\{?\s*([A-Za-z_]\w*)", re.IGNORECASE)
_NAME_RE = re.compile(r"-name\s+\{?\s*([A-Za-z_]\w*)", re.IGNORECASE)

# A real-world SDC (e.g. OpenROAD-flow-scripts `constraint.sdc`) commonly
# uses Tcl variables rather than literals:
#
#   set clk_name      core_clock
#   set clk_port_name clk_i
#   set clk_period    10.0
#   set clk_port      [get_ports $clk_port_name]
#   create_clock -name $clk_name -period $clk_period $clk_port
#
# `_SET_RE` collects `set <var> <value>` assignments; `_VAR_REF_RE`
# substitutes `$var` / `${var}` references (multi-pass, so a variable
# whose value itself references another variable resolves fully)
# before the period/port/name regexes above run.
_SET_RE = re.compile(r"^\s*set\s+(\w+)\s+(.+?)\s*$")
_VAR_REF_RE = re.compile(r"\$\{?(\w+)\}?")
_MAX_SUBST_PASSES = 6


def collect_sdc_files(project: Path,
                      extra_dirs: Optional[List[Path]] = None) -> List[Path]:
    """Return every staged SDC file in priority order:
    ``input/constraints/*.sdc`` then ``input/reference_flow/**/*.sdc``.

    ``extra_dirs`` (ORGANIC #556 round-2) appends additional SDC
    directories AFTER the staged ground truth — e.g. phase3's synth step
    also reads the phase2-generated ``phase2/stage2/constraints/`` SDCs.
    Default behaviour (no extra dirs) is unchanged."""
    files: List[Path] = []
    cdir = project / "input" / "constraints"
    if cdir.is_dir():
        files.extend(sorted(cdir.glob("*.sdc")))
    rdir = project / "input" / "reference_flow"
    if rdir.is_dir():
        files.extend(sorted(rdir.rglob("*.sdc")))
    for d in (extra_dirs or []):
        if d.is_dir():
            files.extend(sorted(d.glob("*.sdc")))
    return files


def _collect_tcl_vars(text: str) -> Dict[str, str]:
    variables: Dict[str, str] = {}
    for line in text.splitlines():
        m = _SET_RE.match(line)
        if m:
            variables[m.group(1)] = m.group(2).strip()
    return variables


def _substitute_vars(text: str, variables: Dict[str, str]) -> str:
    for _ in range(_MAX_SUBST_PASSES):
        def repl(m: "re.Match") -> str:
            return variables.get(m.group(1), m.group(0))
        new_text = _VAR_REF_RE.sub(repl, text)
        if new_text == text:
            return new_text
        text = new_text
    return text


def collect_create_clocks(project: Path,
                          extra_dirs: Optional[List[Path]] = None) -> List[Dict]:
    """Return every ``create_clock`` directive found in the staged SDC
    files as ``{period_ns, port_name, name, source}``.

    Tcl variables (``set <var> <value>`` assignments earlier in the
    same file) referenced via ``$var`` / ``${var}`` are substituted
    before parsing, so OpenROAD-flow-scripts-style constraint files
    (``-period $clk_period ... [get_ports $clk_port_name]``) resolve
    to their literal values, not just hand-written literal SDCs."""
    out: List[Dict] = []
    for sdc in collect_sdc_files(project, extra_dirs=extra_dirs):
        try:
            text = sdc.read_text(errors="replace")
        except OSError:
            continue
        variables = _collect_tcl_vars(text)
        for line in text.splitlines():
            if "create_clock" not in line.lower():
                continue
            resolved = _substitute_vars(line, variables) if variables else line
            mp = _PERIOD_RE.search(resolved)
            if not mp:
                continue
            try:
                period_ns = float(mp.group(1))
            except ValueError:
                continue
            mport = _PORT_RE.search(resolved)
            mname = _NAME_RE.search(resolved)
            out.append({
                "period_ns": period_ns,
                "port_name": mport.group(1) if mport else None,
                "name": mname.group(1) if mname else None,
                "source": str(sdc),
            })
    return out


def primary_clock(project: Path,
                  extra_dirs: Optional[List[Path]] = None) -> Optional[Dict]:
    """Return the ``create_clock`` entry with the smallest period (the
    fastest / primary clock), or ``None`` if no SDC clocks are staged."""
    clocks = collect_create_clocks(project, extra_dirs=extra_dirs)
    if not clocks:
        return None
    return min(clocks, key=lambda c: c["period_ns"])


_GET_PORTS_RE = re.compile(r"get_ports\s+\{?\s*([A-Za-z_]\w*)", re.IGNORECASE)
# A `set <var> <value>` whose VAR names a clock/reset PORT (…_port / …_port_name),
# e.g. `set clk_port_name clk_i`, `set reset_port rst_n`. Distinct from
# `set clk_name core_clock` (a clock-OBJECT label, not a port).
_PORT_VAR_RE = re.compile(r"(?:clk|clock|rst|reset)\w*_?port(?:_name)?$",
                          re.IGNORECASE)
_BARE_TOKEN_RE = re.compile(r"^\{?\s*([A-Za-z_]\w*)")


def staged_constrained_ports(project: Path,
                             extra_dirs: Optional[List[Path]] = None) -> set:
    """ORGANIC #618 — return the SET (lowercased) of top-level port spellings
    the design's OWN staged constraint SDC explicitly references: every
    ``get_ports <name>`` identifier (after Tcl ``$var`` substitution) plus the
    value of any ``set <…>_port[_name] <name>`` clock/reset-port variable.

    This is the design's upstream-verified contract — the same ground-truth
    ranking as the period/port resolution in :func:`primary_clock` (#554) and
    the Phase-3 netlist-port binding (#623). A flow step that RENAMES a top
    port (e.g. ``reset_clock_variant_alias``) must not rename a spelling pinned
    here: doing so breaks the SDC's ``get_ports`` AND the
    ``l9_rtl_pin_consistency_check`` (the sole strict-structural gate). Returns
    an empty set when no staged SDC exists (so callers fall through to their
    existing behaviour unchanged). Chip-AGNOSTIC: standard-SDC syntax only,
    set-membership on port spellings, no chip-class literals."""
    pinned: set = set()
    for sdc in collect_sdc_files(project, extra_dirs=extra_dirs):
        try:
            text = sdc.read_text(errors="replace")
        except OSError:
            continue
        variables = _collect_tcl_vars(text)
        # (1) clock/reset port-name set-vars (the value may itself be a $ref).
        for var, val in variables.items():
            if _PORT_VAR_RE.search(var):
                resolved = _substitute_vars(val, variables).strip()
                m = _BARE_TOKEN_RE.match(resolved)
                if m:
                    pinned.add(m.group(1).lower())
        # (2) every get_ports identifier, after full var substitution so
        #     `[get_ports $clk_port_name]` resolves to the literal port.
        body = _substitute_vars(text, variables) if variables else text
        for m in _GET_PORTS_RE.finditer(body):
            pinned.add(m.group(1).lower())
    return pinned


def main(argv=None) -> int:
    """CLI smoke-check: print the primary clock JSON for <project_path>.
    Returns 0; prints ``null`` when no staged SDC clocks are found."""
    import argparse
    import json as _json
    import sys

    parser = argparse.ArgumentParser(
        description="Print primary create_clock from staged SDC files.")
    parser.add_argument("project", help="Project root directory")
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])
    clk = primary_clock(Path(args.project))
    print(_json.dumps(clk))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
