"""v0.1.49 — Submitter-facing waiver Markdown emitter.

Companion to `signoff_waiver_emit.py` (which produces the machine-
readable JSON entries that an automation pipeline consumes). This
program takes (a) a list of JSON waivers + (b) a project metadata
file, and emits the **chipignite-reviewer-facing Markdown document**
following the canonical 7-section template:

  § 1 Project identification
  § 2 Waived items (per JSON entry)
  § 3 Root cause analysis
  § 4 Independent verifications already performed
  § 5 Risk assessment (functional / timing / manufacturing / testability)
  § 6 Recommendation
  § 7 Attachments

Why this is a program and not a skill
=====================================

The 7-section TEMPLATE is fixed — every chipignite waiver submission
follows this skeleton. The CONTENT per-section comes from JSON inputs
or a project-meta file. So the emit is deterministic over (waivers,
meta) → markdown. A skill would re-author this layout each time with
LLM drift; a program emits it identically every time and pytest can
pin the structure.

Reference
=========

  - Template structure: chipignite / Open MPW submission convention,
    cross-referenced against commercial Calibre LVS waiver flow.
  - Concrete instance: `benchmark_clean/spm_pilot_v0144/caravel_integration/
    signoff/waivers/spm_chipignite_waiver.md` (generated by this program).
  - JSON inputs: `signoff_waiver_emit.py` (sister Bucket-A program).

Unit tests: `programs/tests/test_signoff_waiver_md_emit.py`.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional
import plugin_manifest_discovery as _pmd  # noqa: E402  (#800 ONE version reader)


@dataclass
class IndependentVerification:
    """One row of the § 4 independent-verification table."""
    item: str
    tool: str
    result: str       # PASS, e.g. "261 = 261 device classes match"
    report_path: str  # path/glob to the supporting log/report

    def as_md_row(self) -> str:
        return f"| {self.item} | {self.tool} | {self.result} | `{self.report_path}` |"


@dataclass
class RiskAssessment:
    """The § 5 four-axis risk assessment."""
    functional: str = ""    # e.g. "None — device-level LVS proves equivalence"
    timing: str = ""        # e.g. "None — WNS 0.0 ns, IR drop < 35 µV"
    manufacturing: str = "" # e.g. "None — DRC + antenna + latch-up clean"
    testability: str = ""   # e.g. "None — Logic Analyzer + GPIO functional"

    def is_complete(self) -> bool:
        return bool(self.functional and self.timing
                    and self.manufacturing and self.testability)


@dataclass
class ProjectMeta:
    """Fields the JSON waivers don't carry; supplied by the user once per
    submission (vs once per failure)."""
    project_name: str
    shuttle: str                     # e.g. "chipignite MPW-7, 2026-Q3"
    caravel_commit: str = ""         # e.g. "efabless/caravel@a1b2c3d"
    pdk: str = "sky130A"
    wrapper_loc: int = 0             # # of lines in user_project_wrapper.v
    submitter: str = ""              # e.g. "reyer@defintek.io"
    submission_date: str = ""        # ISO date

    root_cause_paragraph: str = ""   # § 3 free text
    recommendation_paragraph: str = ""  # § 6 free text

    independent_verifications: List[IndependentVerification] = field(
        default_factory=list)
    risk: RiskAssessment = field(default_factory=RiskAssessment)
    attachments: List[str] = field(default_factory=list)


PLACEHOLDER_TOKENS = ("TODO", "FIXME", "TBD", "tbd", "REPLACE-ME",
                      "{{", "}}", "<<", ">>")


def _check_no_placeholder(label: str, text: str, errors: List[str]) -> None:
    for tok in PLACEHOLDER_TOKENS:
        if tok in text:
            errors.append(
                f"{label} contains placeholder token '{tok}'; "
                "fill in the real value before submitting")
            return


def validate_meta(meta: ProjectMeta) -> List[str]:
    """Validate the project meta. Same honesty discipline as the JSON
    schema check: real values, no placeholders, complete risk axes.
    """
    errors: List[str] = []
    if not meta.project_name.strip():
        errors.append("project_name is required")
    if not meta.shuttle.strip():
        errors.append("shuttle is required")
    if not meta.submitter.strip() or meta.submitter.strip().lower() in (
            "ai", "claude", "agent", "self", "tbd"):
        errors.append(
            f"submitter '{meta.submitter}' must be a real reviewer id "
            "(not 'ai' / 'agent' / 'self' / 'tbd')")
    if not meta.root_cause_paragraph.strip():
        errors.append("root_cause_paragraph (§ 3) is required")
    if len(meta.root_cause_paragraph.strip()) < 80:
        errors.append(
            "root_cause_paragraph (§ 3) must be >= 80 chars; describe the "
            "tool/PDK convention difference that produced the failure")
    if not meta.recommendation_paragraph.strip():
        errors.append("recommendation_paragraph (§ 6) is required")
    if not meta.risk.is_complete():
        missing = [k for k, v in (
            ("functional", meta.risk.functional),
            ("timing", meta.risk.timing),
            ("manufacturing", meta.risk.manufacturing),
            ("testability", meta.risk.testability)) if not v]
        errors.append(
            f"risk assessment is incomplete; supply text for: {missing}")
    if len(meta.independent_verifications) < 3:
        errors.append(
            "independent_verifications must list >= 3 entries (the reviewer "
            "expects multiple orthogonal verifications, not a single tool)")

    for label, text in (
            ("root_cause_paragraph", meta.root_cause_paragraph),
            ("recommendation_paragraph", meta.recommendation_paragraph),
            ("risk.functional", meta.risk.functional),
            ("risk.timing", meta.risk.timing),
            ("risk.manufacturing", meta.risk.manufacturing),
            ("risk.testability", meta.risk.testability),
    ):
        _check_no_placeholder(label, text, errors)
    return errors


# ---------------------------------------------------------------------------
# Markdown emit
# ---------------------------------------------------------------------------
def emit_markdown(
    waivers: List[Dict[str, Any]],
    meta: ProjectMeta,
) -> str:
    """Emit the 7-section submitter-facing Markdown.

    `waivers` is the list of JSON waiver dicts (as produced by
    `signoff_waiver_emit.py`). `meta` is the project-level context.
    """
    out: List[str] = []

    # ---- Title + preamble ----
    out.append(f"# Waiver Request — {meta.project_name} on {meta.shuttle}")
    out.append("")
    out.append(
        "> Submitter-facing waiver document for the open-source-flow "
        "signoff failures that, by independent evidence, are documented "
        "tool/PDK limitations rather than design defects. Each entry "
        "references the machine-readable JSON waiver under `signoff/waivers/` "
        "and the pilot writeups under `benchmark_clean/.../caravel_integration/`.")
    out.append("")
    out.append(f"_Emitted by `signoff_waiver_md_emit.py` (Vibe-IC plugin "
               f"v{_pmd.running_plugin_version()}). "
               f"Do not edit by hand — regenerate from sources._")
    out.append("")

    # ---- § 1 Project identification ----
    out.append("## 1. Project identification")
    out.append("")
    out.append(f"- **Project**: `{meta.project_name}`")
    out.append(f"- **Shuttle**: {meta.shuttle}")
    if meta.caravel_commit:
        out.append(f"- **Caravel commit**: `{meta.caravel_commit}`")
    out.append(f"- **PDK**: `{meta.pdk}`")
    if meta.wrapper_loc:
        out.append(f"- **Wrapper RTL**: `verilog/rtl/user_project_wrapper.v` "
                   f"({meta.wrapper_loc} lines)")
    if meta.submitter:
        out.append(f"- **Submitter**: {meta.submitter}")
    if meta.submission_date:
        out.append(f"- **Submission date**: {meta.submission_date}")
    out.append("")

    # ---- § 2 Waived items (table) ----
    out.append("## 2. Waived items")
    out.append("")
    out.append("| # | Check | Reason class | Risk | JSON |")
    out.append("|---|---|---|---|---|")
    for i, w in enumerate(waivers, start=1):
        out.append(
            f"| {i} "
            f"| `{w.get('failed_check', '?')}` "
            f"{'(' + w.get('sub_check_detail', '') + ')' if w.get('sub_check_detail') else ''} "
            f"| `{w.get('reason_class', '?')}` "
            f"| {w.get('risk_assessment', 'low')} "
            f"| `signoff/waivers/{w.get('id', '?')}.json` |")
    out.append("")
    out.append(f"Total: {len(waivers)} waiver(s).")
    out.append("")

    # ---- § 3 Root cause ----
    out.append("## 3. Root cause analysis")
    out.append("")
    out.append(meta.root_cause_paragraph.strip())
    out.append("")

    # ---- Per-waiver mitigation expansion ----
    out.append("### 3.1 Per-waiver detail")
    out.append("")
    for w in waivers:
        out.append(f"#### `{w.get('failed_check', '?')}` — `{w.get('reason_class', '?')}`")
        if w.get("sub_check_detail"):
            out.append(f"_{w['sub_check_detail']}_")
        out.append("")
        out.append(w.get("mitigation", ""))
        out.append("")
        if w.get("evidence_files"):
            out.append("Supporting evidence:")
            for ev in w["evidence_files"]:
                out.append(f"- `{ev}`")
            out.append("")
        if w.get("expected_remediation_path"):
            out.append(f"**Expected remediation path**: "
                       f"{w['expected_remediation_path']}")
            out.append("")

    # ---- § 4 Independent verifications ----
    out.append("## 4. Independent verifications already performed")
    out.append("")
    out.append("| Verification | Tool | Result | Report |")
    out.append("|---|---|---|---|")
    for v in meta.independent_verifications:
        out.append(v.as_md_row())
    out.append("")

    # ---- § 5 Risk assessment ----
    out.append("## 5. Risk assessment")
    out.append("")
    out.append(f"- **Functional**: {meta.risk.functional}")
    out.append(f"- **Timing**: {meta.risk.timing}")
    out.append(f"- **Manufacturing**: {meta.risk.manufacturing}")
    out.append(f"- **Testability**: {meta.risk.testability}")
    out.append("")

    # ---- § 6 Recommendation ----
    out.append("## 6. Recommendation")
    out.append("")
    out.append(meta.recommendation_paragraph.strip())
    out.append("")

    # ---- § 7 Attachments ----
    out.append("## 7. Attachments")
    out.append("")
    if meta.attachments:
        for a in meta.attachments:
            out.append(f"- [ ] `{a}`")
    else:
        # Auto-derived from waiver evidence_files + JSON paths.
        seen = set()
        for w in waivers:
            for ev in w.get("evidence_files", []):
                if ev not in seen:
                    seen.add(ev)
                    out.append(f"- [ ] `{ev}`")
            jp = f"signoff/waivers/{w.get('id', '?')}.json"
            if jp not in seen:
                seen.add(jp)
                out.append(f"- [ ] `{jp}`")
    out.append("")

    out.append("---")
    out.append("")
    out.append(f"End of waiver package — {len(waivers)} entry(ies), "
               f"{len(meta.independent_verifications)} independent verification(s).")
    out.append("")
    return "\n".join(out)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _load_meta(meta_path: Path) -> ProjectMeta:
    """Load project metadata from a JSON file. The file may carry
    `independent_verifications` and `risk` as nested objects.
    """
    data = json.loads(meta_path.read_text(encoding="utf-8"))
    ivs = [IndependentVerification(**v) for v in
           data.pop("independent_verifications", [])]
    risk_d = data.pop("risk", {})
    risk = RiskAssessment(**risk_d)
    meta = ProjectMeta(**data)
    meta.independent_verifications = ivs
    meta.risk = risk
    return meta


#: Where a project keeps the machine-readable waiver pair and the one
#: submission-level metadata file the Markdown needs on top of them. Named here,
#: beside the emitter, because the emitter is what has to agree with it.
WAIVER_DIR = "signoff/waivers"
PROJECT_META_FILENAME = "project_meta.json"
WAIVER_MD_FILENAME = "signoff_waiver.md"


def emit_for_project(project: Path) -> Optional[Path]:
    """Emit the submitter-facing Markdown for `project`, or None if it has no
    submission to make. Returns the path written.

    THE PROJECT-LEVEL ENTRY, and the reason it lives here. This module owned an
    `emit_markdown(waivers, meta)` reachable only from its own `--meta/--waiver`
    CLI, so a run that HAD produced both inputs still had to be told by hand to
    turn them into the document a reviewer reads. Putting the path convention in
    the caller instead would have put it in a 45k-line runner, where it drifts
    from the emitter it has to agree with.

    NOTHING IS INVENTED. Two inputs must already be on disk — the JSON waivers
    `signoff_waiver_emit` writes, and the one submission-level
    `project_meta.json` a human supplies (shuttle, submitter, root cause,
    recommendation). Either one absent returns None and writes nothing: a
    fabricated waiver document is worse than none, and an absent one is an
    honest "this project has no waiver package".
    """
    wdir = Path(project) / WAIVER_DIR
    meta_path = wdir / PROJECT_META_FILENAME
    if not meta_path.is_file():
        return None
    waivers: List[Dict[str, Any]] = []
    for wp in sorted(wdir.glob("*.json")):
        if wp.name == PROJECT_META_FILENAME:
            continue
        try:
            waivers.append(json.loads(wp.read_text(encoding="utf-8")))
        except (OSError, ValueError):
            continue
    if not waivers:
        return None
    meta = _load_meta(meta_path)
    out = wdir / WAIVER_MD_FILENAME
    out.write_text(emit_markdown(waivers, meta), encoding="utf-8")
    return out


def _cli() -> int:
    p = argparse.ArgumentParser(
        description="Emit submitter-facing waiver Markdown from JSON inputs.")
    p.add_argument("--meta", type=Path, required=True,
                   help="Project metadata JSON")
    p.add_argument("--waiver", type=Path, action="append", default=[],
                   help="Path to a JSON waiver (repeatable)")
    p.add_argument("--out", type=Path, default=None,
                   help="Output Markdown path (default: stdout)")
    p.add_argument("--strict", action="store_true",
                   help="Exit non-zero if meta validation reports errors")
    args = p.parse_args()

    meta = _load_meta(args.meta)
    errs = validate_meta(meta)
    if errs:
        import sys as _sys
        for e in errs:
            print(f"WARN: {e}", file=_sys.stderr)
        if args.strict:
            return 1

    waivers = []
    for w_path in args.waiver:
        waivers.append(json.loads(w_path.read_text(encoding="utf-8")))

    md = emit_markdown(waivers, meta)
    if args.out:
        args.out.write_text(md, encoding="utf-8")
        import sys as _sys
        print(f"wrote: {args.out}", file=_sys.stderr)
    else:
        print(md, end="")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_cli())
