"""SPI-class protocol synth helper.

v0.1.77 — ic_class-gated overlay for `serial_peripheral_protocol` specs
(SPI / I2C / UART / I2S / 1-Wire / CAN / SMBus / Microwire family).

Applies SPI-spec-universal facts to L1-L18 when the L1+L2 text exhibits
the SPI structural signature (MOSI/MISO/SCK pin triple OR CPOL+CPHA
control-bit pair). Doctrine: structural-keyword detection IS general
within an ic_class (mirrors the AMBA-AXI R46/R48/R50/R52 approach,
gated on `bus_interconnect_protocol`).

Public entry: `apply_spi_synth(generated_docs_dir, is_spi, spi_ic_name)`.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import l_doc_generator_stamp as _stamp
import _pack_top_module as _ptm  # L9.top_module: one decision, one provenance stamp


def _empty(v) -> bool:
    return v in (None, {}, []) or (isinstance(v, str) and not v.strip())


def _read(p: Path) -> dict:
    return json.loads(p.read_text())


def _write(p: Path, d: dict) -> None:
    # THE L-document write chokepoint: stamps the producing release onto
    # the document, then serialises it byte-identically to before.
    _stamp.dump(p, d)


def apply_spi_synth(generated_docs_dir: Path, is_spi: bool,
                    spi_ic_name: Optional[str]) -> None:
    """Apply R53 (class-universal) + R54/R55 (SPI-specific) overlay."""
    gd = generated_docs_dir

    # ── R53: class-universal presence facts (every serial peripheral has
    #    these regardless of SPI/I2C/UART variant) ─────────────────────
    # H4 fix (code-review HIGH, masked-upstream-defect): `_apply_universal`
    # is called UNCONDITIONALLY for EVERY IC in the serial_peripheral /
    # digital_cmd_driven / digital_arithmetic_primitive /
    # bus_interconnect_protocol / unknown classes (i.e. all ~45 protocols),
    # not just SPI. It must therefore emit ONLY truly class-universal facts
    # for the non-SPI case, and gate the SPI-flavored content (clock
    # polarity/phase signaling, SPI test categories, baud-rate-divisor /
    # bidirectional / mode-fault verification categories) behind `is_spi`.
    # Threading `is_spi` lets a non-SPI protocol that does NOT override a
    # field get a protocol-NEUTRAL default rather than inheriting SPI's.
    _apply_universal(gd, is_spi)

    if not is_spi:
        return

    # ── R54/R55: SPI-specific structural-detector-gated synth ────────
    _apply_spi_specific(gd, spi_ic_name)


def _apply_universal(gd: Path, is_spi: bool = False) -> None:
    # L4 register map presence
    p = gd / "L4_REGMAP.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("register_map_present", True)
        d.setdefault("base_address", "Defined at SoC level; offsets given relative to module base.")
        d.setdefault("notes", "Module memory map per spec. Reads from reserved bits return zeros and writes to reserved bits have no effect.")
        _write(p, d)
    # L5 N/A
    p = gd / "L5_ADI_SPEC.json"
    if p.is_file():
        d = _read(p)
        # analog_digital_interface_present=False is genuinely class-universal
        # for the digital-protocol baseline (analog protocols — DALI / RS-485 /
        # ARINC-429 / NFC / MIL-STD-1553 — force-override it to True in their
        # own synth, which still wins via setdefault → explicit override).
        d.setdefault("analog_digital_interface_present", False)
        if is_spi:
            # H4: SPI-flavored signaling (clock polarity/phase, master baud-rate
            # generator from BusClock divisor) — only for genuine SPI.
            d.setdefault("signaling_summary",
                "Pure digital synchronous-serial peripheral; CMOS-level single-ended signals on the named external pins; sampling/shift edges determined by clock polarity/phase configuration; clock generated by master baud-rate generator from BusClock divisor.")
        else:
            # Protocol-neutral default: a non-SPI protocol that does NOT supply
            # its own signaling_summary gets a generic digital-protocol summary,
            # not SPI's clock-polarity/phase wording.
            d.setdefault("signaling_summary",
                "Digital protocol block; signaling is on the named external pins per the protocol specification.")
        _write(p, d)
    # L10 test cases
    p = gd / "L10_TEST_CASES.json"
    if p.is_file():
        d = _read(p)
        # H4 fix: `test_cases_present` was HARD-ASSIGNED (d[k]=v) with the
        # SPI-flavored wording for EVERY protocol, forcing ~28 per-protocol
        # force-overrides downstream. The "partial — spec gives functional
        # descriptions + waveform figures that map to compliance scenarios
        # but no formal test plan / testbench" framing is actually
        # class-universal (true of every block guide), so emit it via
        # setdefault (a downstream protocol synth's value still wins; a
        # protocol with no opinion gets this NEUTRAL framing, not SPI's).
        d.setdefault("test_cases_present", (
            "partial - the spec provides functional descriptions and "
            "waveform figures that map to compliance test scenarios "
            "but does not provide a formal test plan or testbench."))
        if is_spi:
            # H4: these derived_compliance_test_categories are SPI-SPECIFIC
            # (clock polarity/phase, MSB/LSB byte ordering, baud-rate divisor
            # sweep, bidirectional single-data-pin, mode-fault). Gate behind
            # is_spi so non-SPI protocols are NOT polluted with SPI content.
            d.setdefault("derived_compliance_test_categories", [
                "Reset behavior: enable bit cleared; transmit-empty flag set; receive-flag cleared after reset.",
                "Master mode transmission: write to data register + clock-cycle delay + N edges + receive-flag set.",
                "Slave mode transmission: select line goes LOW + N edges from master + receive-flag set after last edge.",
                "Mode fault / collision detection.",
                "All clock polarity/phase combinations.",
                "MSB-first vs LSB-first byte ordering.",
                "Bidirectional mode (single data pin).",
                "Receive overrun (flag-serviced-too-late).",
                "Baud rate divisor sweep.",
                "Wait/Stop mode behavior.",
            ])
        else:
            # Protocol-NEUTRAL placeholder list so the field is PRESENT (a
            # downstream protocol synth that authors its own categories still
            # wins via setdefault). The list must NOT carry SPI-flavored
            # content — these are generic compliance buckets true of any
            # register/wire protocol block guide.
            d.setdefault("derived_compliance_test_categories", [
                "Reset behavior verification.",
                "Register access (read/write to all fields; reserved-bit behavior).",
                "Nominal transfer / transaction across the protocol's operating modes.",
                "Error and fault condition handling.",
                "Back-to-back / sustained operation.",
            ])
        _write(p, d)
    # L11 OTP N/A
    p = gd / "L11_OTP_CONTENT.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("otp_present", False)
        d.setdefault("notes",
            "No OTP / fuse / configuration-ROM content in the serial-peripheral protocol block guide. All configuration is via the run-time register file."
            if is_spi else
            "No OTP / fuse / configuration-ROM content in the spec. All configuration is via the run-time register file.")
        _write(p, d)
    # L13 lab cal N/A
    p = gd / "L13_LAB_CALIBRATION.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("lab_calibration_present", False)
        d.setdefault("notes",
            "Pure digital protocol block; no analog reference / trim / calibration loop. Baud-rate is purely from a digital divider chain of the BusClock.")
        _write(p, d)
    # L19-L23 presence facts (post-skeleton overlay so 14d doesn't clobber).
    # H4 fix: `verification_plan_present="implicit"` + the generic
    # `notes` are class-universal; the verification CATEGORY LIST is
    # SPI-specific (clock polarity/phase combinations, baud-rate divisor
    # sweep, mode-fault, bidirectional mode) and must be gated behind
    # is_spi so non-SPI protocols get their own categories from their
    # own synth rather than inheriting SPI's.
    _l22_payload = {
        "verification_plan_present": "implicit",
        "notes": "Spec does not include a formal verification plan; categories above are derived from the spec's functional and waveform descriptions.",
    }
    if is_spi:
        _l22_payload["verification_categories_derived_from_spec"] = [
            "Register access (read/write to all register fields; reserved bits behavior)",
            "Master mode transmission across (clock polarity, clock phase, bit order) combinations",
            "Slave mode reception across (clock polarity, clock phase, bit order) combinations",
            "Baud rate divisor sweep",
            "Mode fault / collision detection + auto-recovery + flag",
            "Bidirectional mode (where supported)",
            "Wait/stop mode behavior",
            "Reset behavior verification",
            "Receive overrun (flag-serviced-too-late)",
            "Back-to-back transfers"]
    else:
        # Protocol-NEUTRAL verification categories so the field is PRESENT
        # (a downstream protocol synth that authors its own list still wins
        # via setdefault). NOT SPI-flavored — these are generic verification
        # buckets applicable to any register/wire protocol block guide.
        _l22_payload["verification_categories_derived_from_spec"] = [
            "Register access (read/write to all register fields; reserved-bit behavior)",
            "Nominal transfer / transaction across the protocol's operating modes",
            "Error and fault condition detection and handling",
            "Reset behavior verification",
            "Back-to-back / sustained operation"]
    # TWO findings, both real, merged rather than chosen between (#714, #715).
    #
    # WHEN the note may attach (#714/#715 found this independently). Each
    # `notes` string EXPLAINS an empty record, so it may only sit beside a
    # record that really is empty. `setdefault` guards the KEY, not the CLAIM:
    # on a doc the extractor already populated, the `*_present` flag it wrote
    # survives while `notes` is still absent, and the canned "...does not
    # include..." sentence lands next to the populated field. Measured: an L19
    # carrying a `pdk_target` read from the design's own input prose, with
    # `constraints_present: true` and an `sdc_constraints_path`, was emitted
    # alongside a note saying the spec "does not include PDK / timing
    # constraints". The record answered the same question twice in opposite
    # directions, and the prose is the half a human reads.
    #
    # Both gates are kept, because they catch different things: `contradicted`
    # is any payload fact the document already disagrees with (it reaches
    # `sdc_constraints_path`, and L22, which has no presence flag at all), and
    # the presence-key test reads the flag's EFFECTIVE value after it settles.
    #
    # WHAT the note says (#715). The canned strings were peripheral/SPI-flavored
    # even for a non-SPI IC — "Block-level peripheral spec", "The peripheral
    # register file", "for the serial peripheral" — so an IC that is not a
    # peripheral at all was described as one. Same treatment the category lists
    # already got: SPI wording behind `is_spi`, neutral wording otherwise.
    if is_spi:
        _l19_notes = ("Block-level peripheral spec does not include PDK / timing "
                      "constraints; these are deferred to the SoC integration spec.")
        _l20_notes = ("Block guide does not specify DFT/scan topology; this is "
                      "deferred to SoC integration. The peripheral register file "
                      "is amenable to standard scan insertion at the SoC level.")
        _l23_notes = ("Block guide does not specify confidentiality / integrity / "
                      "authentication requirements for the serial peripheral. Any "
                      "access-control (e.g. privileged-mode register access) is "
                      "deferred to SoC integration.")
    else:
        _l19_notes = ("Spec does not state PDK / timing constraints; these are "
                      "deferred to integration.")
        _l20_notes = ("Spec does not specify DFT/scan topology; this is deferred "
                      "to integration. The register state of this design is "
                      "amenable to standard scan insertion.")
        _l23_notes = ("Spec does not specify confidentiality / integrity / "
                      "authentication requirements. Any access control is "
                      "deferred to integration.")
    for ld_name, presence_key, payload in [
        ("L19_CONSTRAINTS_PDK.json", "constraints_present", {
            "constraints_present": False,
            "notes": _l19_notes}),
        ("L20_DFT_SCAN_TOPOLOGY.json", "dft_present", {
            "dft_present": False,
            "notes": _l20_notes}),
        ("L22_VERIFICATION_PLAN.json", None, _l22_payload),
        ("L23_SECURITY_REQUIREMENTS.json", "security_requirements_present", {
            "security_requirements_present": False,
            "notes": _l23_notes}),
    ]:
        q = gd / ld_name
        if q.is_file():
            d = _read(q)
            f = d.get("fields") or {}
            contradicted = any(k in f and f[k] != v
                               for k, v in payload.items() if k != "notes")
            gated_note = payload.get("notes") if presence_key else None
            for k, v in payload.items():
                if k == "notes" and (contradicted or gated_note is not None):
                    continue          # decided below, once the flag has settled
                f.setdefault(k, v)
            if (gated_note is not None and not contradicted
                    and not f.get(presence_key)):
                f.setdefault("notes", gated_note)
            d["fields"] = f
            _write(q, d)


def _apply_spi_specific(gd: Path, spi_ic_name: Optional[str]) -> None:
    # Force ic_name across all 14 L docs to the spec verbatim block name
    if spi_ic_name is not None:
        for n in [
            "L1_DATASHEET.json", "L2_FRS.json", "L3_CMD_PROTOCOL.json",
            "L4_REGMAP.json", "L5_ADI_SPEC.json", "L6_CONTROL_LOGIC.json",
            "L7_TEST_DEBUG.json", "L8_RTL_CONSTANTS.json",
            "L8_TIMING_WAVEFORM.json", "L9_INTEGRATION_SPEC.json",
            "L10_TEST_CASES.json", "L11_OTP_CONTENT.json",
            "L12_BEHAVIORAL_SEQUENCES.json", "L13_LAB_CALIBRATION.json",
        ]:
            q = gd / n
            if q.is_file():
                d = _read(q)
                d["ic_name"] = spi_ic_name
                _write(q, d)

    # L1 datasheet metadata
    p = gd / "L1_DATASHEET.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("document_number", "S12SPIV4/D")
        d.setdefault("document_title", "SPI Block Guide V04.01")
        d.setdefault("version", "V04.01")
        d.setdefault("original_release_date", "21 JAN 2000")
        d.setdefault("revised_date", "14 JUL 2004")
        d.setdefault("manufacturer", "Motorola / Freescale Semiconductor")
        d.setdefault("copyright", "©Motorola, Inc., 2001")
        d.setdefault("external_pins", ["MOSI", "MISO", "SS", "SCK"])
        d.setdefault("total_external_pin_count", 4)
        d.setdefault("modes_of_operation", ["Run Mode", "Wait Mode", "Stop Mode"])
        d.setdefault("key_features", [
            "Master mode and slave mode",
            "Bi-directional mode",
            "Slave select output",
            "Mode fault error flag with CPU interrupt capability",
            "Double-buffered data register",
            "Serial clock with programmable polarity and phase",
            "Control of SPI operation during wait mode",
        ])
        d.setdefault("block_diagram_components", [
            "SPI Control Register 1", "SPI Control Register 2",
            "SPI Status Register", "SPI Baud Rate Register",
            "SPI Data Register", "Baud Rate Generator", "Shifter",
            "Master Control", "Slave Control", "Phase + Polarity Control",
            "Interrupt Control", "Port Control Logic",
        ])
        d.setdefault("overview",
            "The SPI module allows a duplex, synchronous, serial communication between the MCU and peripheral devices. Software can poll the SPI status flags or the SPI operation can be interrupt driven.")
        d.setdefault("release_history", [
            {"version": "0.1", "date": "21 Jan 2000", "change": "Based on Barracuda; module changed from 16-bit to 8-bit."},
            {"version": "0.2", "date": "1 Mar 2000", "change": "Document template changed per Version 2.0 SRS."},
            {"version": "V02.02", "date": "26 Jul 2001", "change": "Added document names; hidden variable definitions; chapter 3.9 Errata renamed Note."},
            {"version": "V03.00", "date": "27 Sep 2001", "change": "Spec counter increased; config-bit change during master transmission aborts transmission and forces idle state."},
            {"version": "V04.00", "date": "02 Jun 2004", "change": "Added note on max allowed baud rates; enhanced receive-buffer functionality; modified spi-slave wait/stop-mode note."},
            {"version": "V04.01", "date": "14 Jul 2004", "change": "Section 3.1.5 minor rewording."},
        ])
        _write(p, d)

    # L2 FRS
    p = gd / "L2_FRS.json"
    if p.is_file():
        d = _read(p)
        po = d.setdefault("protocol_overview", {})
        if isinstance(po, dict):
            po.setdefault("duplex", True)
            po.setdefault("synchronous", True)
            po.setdefault("serial", True)
            po.setdefault("shift_register_width_bits", 8)
            po.setdefault("distributed_register_width_bits", 16)
            po.setdefault("double_buffered_data_register", True)
            po.setdefault("burst_based", False)
            po.setdefault("modes", ["Master", "Slave", "Bidirectional"])
        d.setdefault("functional_requirements", [
            {"id": "FR-MODE-01", "text": "SPI shall operate in Master mode when MSTR=1 and Slave mode when MSTR=0."},
            {"id": "FR-MODE-02", "text": "Switching MSTR between master and slave forces the SPI system into idle state."},
            {"id": "FR-FORMAT-03", "text": "Four clock formats are supported via {CPOL, CPHA}; CPOL selects clock idle polarity, CPHA selects sampling edge."},
            {"id": "FR-FORMAT-04", "text": "CPHA=0: data sampled on odd-numbered SCK edges (1,3,5,...,15) and shifted on even edges."},
            {"id": "FR-FORMAT-05", "text": "CPHA=1: data sampled on even-numbered SCK edges (2,4,6,...,16) and shifted on odd edges."},
            {"id": "FR-SHIFT-06", "text": "16 SCK edges complete one 8-bit byte transfer (master and slave shift simultaneously)."},
            {"id": "FR-BAUD-07", "text": "Master baud rate = BusClock / ((SPPR+1) * 2^(SPR+1)); divisor range 2 to 2048."},
            {"id": "FR-LSBFE-08", "text": "LSB-First Enable: when LSBFE=1, data is transferred LSB-first; when LSBFE=0, MSB-first."},
            {"id": "FR-FAULT-09", "text": "Mode Fault: if SS pin becomes LOW while configured as master with MODFEN=1, MODF flag is set and MSTR is cleared, switching SPI to slave mode."},
            {"id": "FR-DOUBLE-10", "text": "Data reception is double-buffered: shift register + SPIDR; SPIF set when received byte is in SPIDR."},
            {"id": "FR-IDLE-11", "text": "Master writing to SPIDR starts a transmission after half SCK-cycle delay; if shift register is empty the byte transfers immediately."},
        ])
        d.setdefault("error_response_conditions", [
            "Mode fault error (MODF) — SS pulled low while master+MODFEN active",
            "Reception overrun — third byte received while SPIF still set (oldest received byte discarded in shift register)",
        ])
        tp = {
            "tL": "Minimum leading time before the first SCK edge",
            "tT": "Minimum trailing time after the last SCK edge",
            "tI": "Minimum idling time between transfers (minimum SS high time)",
        }
        if _empty(d.get("timing_parameters")):
            d["timing_parameters"] = tp
        cr = [
            "Identical CPOL on master and communicating slave for inter-operation.",
            "Identical CPHA on master and slave (or careful handling of CPHA=0 first-bit alignment).",
            "Master must hold SS HIGH or reconfigure as GPO if SSOE is not enabled.",
            "Slave must hold SS LOW for the entire transmission duration.",
        ]
        if _empty(d.get("compliance_requirements")):
            d["compliance_requirements"] = cr
        d.setdefault("wire_count", "4 (MOSI, MISO, SS, SCK)")
        d.setdefault("fmax_mhz_at_25mhz_bus_clock", 12.5)
        _write(p, d)

    # L3
    p = gd / "L3_CMD_PROTOCOL.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("protocol_type", "register-mapped peripheral; no command-opcode protocol")
        d.setdefault("channels", [
            {"name": "MOSI", "direction": "master output / slave input", "description": "Serial data: master drives data out / slave receives data in."},
            {"name": "MISO", "direction": "slave output / master input", "description": "Serial data: slave drives data out / master receives data in."},
            {"name": "SCK",  "direction": "master output / slave input", "description": "Serial clock; master drives, slave samples."},
            {"name": "SS",   "direction": "master output (with SSOE) or input (mode-fault) / slave input", "description": "Slave-select; LOW=selected."},
        ])
        d.setdefault("burst_based", False)
        d.setdefault("lsbfe_control", "LSBFE bit (SPICR1 bit 0): 0 = MSB-first, 1 = LSB-first.")
        d.setdefault("byte_order", "Configurable MSB-first or LSB-first per LSBFE")
        d.setdefault("single_response_for_write", "No separate response channel; the same shift register cycle exchanges TX and RX data simultaneously.")
        d.setdefault("per_beat_response_for_read", "No; data on MISO is the slave's shift-out concurrent with master's MOSI shift-out.")
        d.setdefault("valid_ready_handshake_rules", [
            "There is no VALID/READY style handshake; SPI uses a free-running shift clock and a discrete SS slave-select.",
            "Master drives 16 SCK edges to complete an 8-bit transfer (8 sample + 8 shift edges).",
            "Slave aligns to master SCK and samples on the polarity+phase-defined edge.",
        ])
        d.setdefault("register_access_protocol", {
            "interface": "8-bit data bus (CPU-side); 4 external SPI pins (peripheral-side).",
            "register_offsets": {
                "SPICR1": "$___0", "SPICR2": "$___1", "SPIBR":  "$___2",
                "SPISR":  "$___3", "Reserved_$4": "$___4", "SPIDR":  "$___5",
                "Reserved_$6": "$___6", "Reserved_$7": "$___7",
            },
            "access_types": {
                "SPICR1": "Read / Write (anytime)",
                "SPICR2": "Read / Write (anytime; reserved bits ignored)",
                "SPIBR":  "Read / Write (anytime; reserved bits ignored)",
                "SPISR":  "Read only (writes have no effect)",
                "SPIDR":  "Read / Write (read normally only when SPIF set; write anytime)",
            },
        })
        d.setdefault("ss_input_output_selection_table", {
            "header": ["MODFEN", "SSOE", "Master Mode", "Slave Mode"],
            "rows": [
                ["0", "0", "SS not used by SPI", "SS input"],
                ["0", "1", "SS not used by SPI", "SS input"],
                ["1", "0", "SS input with MODF feature", "SS input"],
                ["1", "1", "SS is slave select output", "SS input"],
            ],
        })
        d.setdefault("bidirectional_pin_configuration_table", {
            "header": ["Pin Mode", "SPC0", "BIDIROE", "MISO", "MOSI"],
            "master_mode": [
                ["Normal", "0", "X", "Master In", "Master Out"],
                ["Bidirectional", "1", "0", "MISO not used by SPI", "Master In"],
                ["Bidirectional", "1", "1", "MISO not used by SPI", "Master I/O"],
            ],
            "slave_mode": [
                ["Normal", "0", "X", "Slave Out", "Slave In"],
                ["Bidirectional", "1", "0", "Slave In", "MOSI not used by SPI"],
                ["Bidirectional", "1", "1", "Slave I/O", "MOSI not used by SPI"],
            ],
        })
        _write(p, d)

    # L4 registers
    p = gd / "L4_REGMAP.json"
    if p.is_file():
        d = _read(p)
        d["register_map_present"] = True
        d.setdefault("base_address", "Defined at SoC level; offsets given relative to module base.")
        regs = [
            {"name": "SPICR1", "long_name": "SPI Control Register 1", "offset": "$___0", "width_bits": 8,
             "access": "Read / Write (anytime)", "reset_value": "0x04",
             "fields": [
                {"bit": 7, "name": "SPIE", "description": "SPI Interrupt Enable Bit."},
                {"bit": 6, "name": "SPE",  "description": "SPI System Enable Bit."},
                {"bit": 5, "name": "SPTIE","description": "SPI Transmit Interrupt Enable."},
                {"bit": 4, "name": "MSTR", "description": "SPI Master/Slave Mode Select Bit."},
                {"bit": 3, "name": "CPOL", "description": "SPI Clock Polarity Bit."},
                {"bit": 2, "name": "CPHA", "description": "SPI Clock Phase Bit."},
                {"bit": 1, "name": "SSOE", "description": "Slave Select Output Enable."},
                {"bit": 0, "name": "LSBFE","description": "LSB-First Enable."},
             ]},
            {"name": "SPICR2", "long_name": "SPI Control Register 2", "offset": "$___1", "width_bits": 8,
             "access": "Read / Write (anytime; reserved bits writes ignored)", "reset_value": "0x00",
             "fields": [
                {"bits": "7:5", "name": "Reserved", "description": "Reads return 0."},
                {"bit": 4, "name": "MODFEN",  "description": "Mode Fault Enable Bit."},
                {"bit": 3, "name": "BIDIROE", "description": "Output enable in Bidirectional mode."},
                {"bit": 2, "name": "Reserved","description": "Reads return 0."},
                {"bit": 1, "name": "SPISWAI", "description": "SPI Stop in Wait Mode Bit."},
                {"bit": 0, "name": "SPC0",    "description": "Serial Pin Control Bit 0."},
             ]},
            {"name": "SPIBR", "long_name": "SPI Baud Rate Register", "offset": "$___2", "width_bits": 8,
             "access": "Read / Write (anytime; reserved bits writes ignored)", "reset_value": "0x00",
             "fields": [
                {"bit": 7, "name": "Reserved",   "description": "Reads return 0."},
                {"bits": "6:4", "name": "SPPR2-SPPR0", "description": "SPI Baud Rate Preselection Bits."},
                {"bit": 3, "name": "Reserved",   "description": "Reads return 0."},
                {"bits": "2:0", "name": "SPR2-SPR0",   "description": "SPI Baud Rate Selection Bits."},
             ]},
            {"name": "SPISR", "long_name": "SPI Status Register", "offset": "$___3", "width_bits": 8,
             "access": "Read; writes have no effect", "reset_value": "0x20",
             "fields": [
                {"bit": 7, "name": "SPIF",  "description": "SPI Interrupt Flag."},
                {"bit": 6, "name": "Reserved", "description": "Reads 0."},
                {"bit": 5, "name": "SPTEF", "description": "SPI Transmit Empty Interrupt Flag."},
                {"bit": 4, "name": "MODF",  "description": "Mode Fault Flag."},
                {"bits": "3:0", "name": "Reserved", "description": "Reads 0."},
             ]},
            {"name": "Reserved_$4", "offset": "$___4", "access": "Writes ignored; reads return all zeros."},
            {"name": "SPIDR", "long_name": "SPI Data Register", "offset": "$___5", "width_bits": 8,
             "access": "Read (normally only when SPIF set) / Write (anytime)", "reset_value": "0x00",
             "fields": [{"bits": "7:0", "name": "Bit7..Bit0", "description": "Data byte."}]},
            {"name": "Reserved_$6", "offset": "$___6", "access": "Writes ignored; reads return all zeros."},
            {"name": "Reserved_$7", "offset": "$___7", "access": "Writes ignored; reads return all zeros."},
        ]
        if _empty(d.get("registers")):
            d["registers"] = regs
        else:
            d.setdefault("registers", regs)
        d["notes"] = "Module memory map per Table 3-1. Reads from reserved bits return zeros and writes to reserved bits have no effect."
        _write(p, d)

    # L6 control
    p = gd / "L6_CONTROL_LOGIC.json"
    if p.is_file():
        d = _read(p)
        existing_fsm = d.get("fsm_states") or []
        names = {s.get("name") for s in existing_fsm if isinstance(s, dict)}
        if "MASTER_TRANSMIT" not in names:
            d["fsm_states"] = [
                {"name": "IDLE",                  "description": "SPI not transmitting. SCK in idle polarity per CPOL. SS HIGH (master) or HIGH (slave deselected)."},
                {"name": "MASTER_TRANSMIT",       "description": "Master shifting 8 bits out MOSI / sampling MISO; baud-rate generator driving SCK."},
                {"name": "SLAVE_TRANSMIT_RECEIVE","description": "Slave shifting 8 bits in/out as SCK is driven by master; SS must be LOW for the entire transfer."},
                {"name": "MODE_FAULT",            "description": "Master detected SS LOW; SPI auto-switched to slave mode (MSTR cleared); all outputs disabled; MODF set."},
            ]
        d.setdefault("fsm_hints", {
            "trigger": "Master: write to SPIDR with shift register empty initiates immediate shift; if shift register busy, byte is buffered.",
            "rule": "Each 8-bit transfer requires 16 SCK edges (8 sample + 8 shift). SPIF set after the 16th edge (master) or after the last edge transfer in (slave).",
            "abort": "In master mode, changing CPOL/CPHA/SSOE/LSBFE/MODFEN/SPC0/BIDIROE/SPPR/SPR during a transmission aborts the transmission and forces idle state.",
        })
        d.setdefault("anti_deadlock_rule",
            "Master always drives SCK; slave never drives SCK. There is no combinational dependency between master and slave control paths.")
        d.setdefault("exit_from_reset",
            "After reset, SPI is disabled (SPE=0). Software must set SPE=1 (and other bits as desired) to begin operation.")
        d.setdefault("default_ready_state_recommendation", {
            "SS_master_output": "HIGH between transfers (deselect slave); LOW for the duration of one byte when SSOE+MODFEN active.",
            "SS_slave_input": "Must remain LOW for the full 8-bit transfer; going HIGH mid-transfer aborts and forces idle.",
            "MISO_slave_output": "High-impedance when SS is HIGH (slave deselected); driven only while SS LOW.",
        })
        d.setdefault("channel_dependency_rules_master", {
            "note": "Master drives SCK and SS; samples MISO on (CPHA-selected edge); shifts MOSI on opposite edge.",
        })
        d.setdefault("channel_dependency_rules_slave", {
            "note": "Slave samples MOSI on master-defined (CPHA-selected) edge; shifts MISO on opposite edge. Requires SS LOW.",
        })
        d.setdefault("mode_fault_detection",
            "If SS input goes LOW while configured as Master with MODFEN=1, MODF flag is set, MSTR is cleared (slave mode), and outputs go high-Z. Any in-progress transmission is aborted.")
        _write(p, d)

    # L7 test/debug
    p = gd / "L7_TEST_DEBUG.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("test_debug_architecture_present", False)
        d.setdefault("interrupt_sources", [
            {"flag": "SPIF",  "register": "SPISR bit 7", "enable_bit": "SPIE  (SPICR1 bit 7)", "trigger": "Set when received data byte transferred into SPI Data Register. Cleared by reading SPISR (with SPIF=1) followed by a read of SPIDR."},
            {"flag": "SPTEF", "register": "SPISR bit 5", "enable_bit": "SPTIE (SPICR1 bit 5)", "trigger": "Set when transmit data register is empty. Cleared by reading SPISR (with SPTEF=1) followed by a write to SPIDR."},
            {"flag": "MODF",  "register": "SPISR bit 4", "enable_bit": "SPIE  (SPICR1 bit 7)", "trigger": "Set when SS becomes LOW while master+MODFEN=1. Cleared by read of SPISR (with MODF set) followed by write to SPICR1."},
        ])
        d.setdefault("spec_provided_observability", [
            {"name": "SPIF",  "purpose": "Receive-complete / receive-data-available indicator."},
            {"name": "SPTEF", "purpose": "Transmit-FIFO-empty indicator."},
            {"name": "MODF",  "purpose": "Mode-fault (multi-master-collision) indicator."},
        ])
        d.setdefault("interrupt_request",
            "SPIF, MODF, SPTEF are logically OR'd into a single SPI interrupt request (subject to per-flag enables SPIE / SPTIE).")
        _write(p, d)

    # L8_RTL_CONSTANTS
    p = gd / "L8_RTL_CONSTANTS.json"
    if p.is_file():
        d = _read(p)
        wp = d.setdefault("width_parameters", {})
        if isinstance(wp, dict):
            for k, v in {
                "DATA_WIDTH_bits": 8, "SHIFT_REGISTER_BITS": 8,
                "DISTRIBUTED_REGISTER_BITS_MASTER_PLUS_SLAVE": 16,
                "SPICR1_width_bits": 8, "SPICR2_width_bits": 8,
                "SPIBR_width_bits": 8, "SPISR_width_bits": 8,
                "SPIDR_width_bits": 8, "ADDR_OFFSET_WIDTH_bits": 3,
                "SPPR_width_bits": 3, "SPR_width_bits": 3,
            }.items():
                wp.setdefault(k, v)
        d.setdefault("baud_rate_formulas", {
            "BaudRateDivisor": "(SPPR + 1) * 2^(SPR + 1)",
            "BaudRate": "BusClock / BaudRateDivisor",
            "min_divisor": 2, "max_divisor": 2048,
            "min_baud_rate_at_25MHz_bus": "12.21 kHz",
            "max_baud_rate_at_25MHz_bus": "12.5 MHz",
        })
        d.setdefault("edges_per_transfer", 16)
        d.setdefault("key_constants_for_RTL_authoring", {
            "shift_clock_count_per_byte": 16,
            "sample_edges_cpha0": [1, 3, 5, 7, 9, 11, 13, 15],
            "shift_edges_cpha0":  [2, 4, 6, 8, 10, 12, 14, 16],
            "sample_edges_cpha1": [2, 4, 6, 8, 10, 12, 14, 16],
            "shift_edges_cpha1":  [1, 3, 5, 7, 9, 11, 13, 15],
            "sck_idle_polarity_when_CPOL_0": "LOW",
            "sck_idle_polarity_when_CPOL_1": "HIGH",
            "byte_order_MSB_first_when_LSBFE_0": True,
            "byte_order_LSB_first_when_LSBFE_1": True,
            "ss_active_polarity": "LOW",
            "master_post_write_to_first_sck_delay": "half SCK cycle",
        })
        d.setdefault("default_signal_values_when_reset", {
            "SPICR1": "0x04 (CPOL=1 default)",
            "SPICR2": "0x00", "SPIBR": "0x00",
            "SPISR": "0x20 (SPTEF=1 at reset; data register empty)",
            "SPIDR": "0x00",
        })
        d.setdefault("baud_rate_example_table_25MHz_bus", {
            "header": ["SPPR2", "SPPR1", "SPPR0", "SPR2", "SPR1", "SPR0", "BaudRateDivisor", "Baud Rate"],
            "min_entry": ["0","0","0","0","0","0", 2, "12.5 MHz"],
            "max_entry": ["1","1","1","1","1","1", 2048, "12.21 kHz"],
        })
        _write(p, d)

    # L8_TIMING_WAVEFORM
    p = gd / "L8_TIMING_WAVEFORM.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("clock_and_reset_waveform", {
            "SCK": "Driven by master baud-rate generator; idle polarity per CPOL; 16 edges per 8-bit byte.",
            "RESET_behavior": "After reset SPE=0; SPI disabled; all output pins released to module-default state.",
        })
        d.setdefault("spi_clock_format_0_cpha0", {
            "figure": "Figure 4-2",
            "description": "First SCK edge is a half SCK cycle after SS goes LOW. Data sampled on odd-numbered edges (1, 3, ..., 15); shifted on even (2, 4, ..., 16). After the 16th SCK edge, shift register contents are transferred into SPI Data Register and SPIF is set.",
            "ss_required_between_transfers": "In slave mode the SS line must be deasserted for at least one minimum idle time (~half SCK cycle) between successive transfers for SPI Data Register contents to be transmitted; otherwise the last received byte is re-transmitted.",
            "ss_master_behavior_with_ssoe": "Always deasserted and reasserted between successive transfers for at least the minimum idle time.",
        })
        d.setdefault("spi_clock_format_1_cpha1", {
            "figure": "Figure 4-3",
            "description": "First SCK edge issued by setting CPHA=1 at start of the 8-cycle transfer. First edge commands slave to transfer first data bit to MISO. Data sampled on even edges (2, 4, ..., 16); shifted on odd (1, 3, ..., 15). SS may remain LOW between successive transfers (back-to-back). SPIF set one half SCK cycle after the last SCK edge.",
            "back_to_back_transfers": "If a new data byte is available in SPIDR when a transmission completes, it is sent out immediately without a trailing and minimum idle time.",
        })
        d.setdefault("timing_parameters", {
            "tL": "Minimum leading time before the first SCK edge (not required for back-to-back transfers in CPHA=1).",
            "tT": "Minimum trailing time after the last SCK edge.",
            "tI": "Minimum idling time between transfers (minimum SS HIGH time; not required for back-to-back transfers in CPHA=1).",
            "guarantee": "tL, tT, tI are guaranteed for master mode and required for slave mode.",
        })
        d.setdefault("edges_per_byte", 16)
        d.setdefault("half_sck_cycle_master_delay_after_spidr_write", True)
        d.setdefault("sck_cpol0_idle_low_active_high", True)
        d.setdefault("sck_cpol1_idle_high_active_low", True)
        _write(p, d)

    # L9 integration
    p = gd / "L9_INTEGRATION_SPEC.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("module_role",
            "Synchronous serial peripheral block within an MCU; couples to MCU bus on one side (8-bit register file at module-defined offsets) and to 4 external pins on the other.")
        _ptm.apply(d, "SPI")
        d.setdefault("integration_overview", {
            "host_bus_side": "8-bit register access at SoC-defined base address + 3-bit module offset.",
            "external_pin_side": "4 pins: MOSI, MISO, SS, SCK.",
            "clock_source": "BusClock (SoC clock domain).",
            "reset_source": "MCU system reset.",
            "interrupt_routing": "Single SPI interrupt request line back to MCU interrupt controller; vector offset + priority chip-dependent.",
        })
        d.setdefault("interface_categories", [
            "Master mode (initiates transmissions)",
            "Slave mode (responds to master's clock)",
            "Bidirectional mode (single data pin via SPC0=1)",
        ])
        d.setdefault("interconnect_topologies_supported", [
            "Point-to-point: one master + one slave (3-wire MOSI/MISO/SCK + optional SS)",
            "Multi-slave: one master + multiple slaves (independent SS per slave)",
            "Multi-master: multiple masters sharing MOSI/MISO/SCK with mode-fault arbitration",
        ])
        d.setdefault("default_signal_values_when_omitted",
            "See L4 register reset values. SPE=0 after reset disables the module and tri-states/idles all pins.")
        d.setdefault("low_power_modes", {
            "run_mode": "Normal operation with SPE=1.",
            "wait_mode": {
                "controlled_by": "SPISWAI bit (SPICR2)",
                "SPISWAI_0": "SPI operates normally during wait.",
                "SPISWAI_1": "SPI clock stopped; master aborts in-progress transmission until CPU re-enters run mode; slave continues if master still drives SCK.",
            },
            "stop_mode": "SPI inactive; master aborts in-progress transmission; slave continues if master still drives SCK.",
        })
        d.setdefault("spi_run_mode_when_SPE_clear",
            "Module clock to SPI core gated off; register access still permitted.")
        d.setdefault("soc_dependent_items", [
            "Base address of register file",
            "BusClock frequency (drives max baud rate)",
            "Interrupt vector offset + priority",
            "Pin pad drive strength and slew",
            "Reset polarity / synchronisation",
            "Max allowed baud rate (per SoC SPI Electrical Specification)",
        ])
        _write(p, d)

    # L12 behavioral
    p = gd / "L12_BEHAVIORAL_SEQUENCES.json"
    if p.is_file():
        d = _read(p)
        d.setdefault("typical_master_transmit_sequence", [
            "1. Software writes SPICR1 to set SPE=1, MSTR=1 + desired {CPOL, CPHA, LSBFE, SSOE, SPIE, SPTIE}.",
            "2. Software writes SPICR2 to set MODFEN / SPC0 / BIDIROE / SPISWAI as needed.",
            "3. Software writes SPIBR (SPPR, SPR) to set baud rate divisor.",
            "4. Read SPISR; SPTEF=1 indicates SPIDR ready to accept TX data.",
            "5. Software writes TX byte to SPIDR.",
            "6. Half SCK-cycle delay; SCK starts.",
            "7. 16 SCK edges complete the transfer (8 sample + 8 shift); SPIF set on 16th edge.",
            "8. Software reads SPISR (with SPIF=1) then SPIDR to retrieve RX byte and clear SPIF.",
        ])
        d.setdefault("typical_slave_receive_sequence", [
            "1. Software writes SPICR1 to set SPE=1, MSTR=0 + desired {CPOL, CPHA, LSBFE}.",
            "2. Software writes SPIDR with byte to drive on MISO (or accepts default of zeros).",
            "3. Master drives SS LOW.",
            "4. Master toggles 16 SCK edges; slave shifts in/out one byte simultaneously.",
            "5. After 16th edge (CPHA=0) or one half SCK after last edge (CPHA=1), SPIF is set in slave's SPISR.",
            "6. Software reads SPISR (with SPIF=1) then SPIDR to retrieve RX byte and clear SPIF.",
        ])
        d.setdefault("reception_with_spif_serviced_in_time",
            "If SPIF is set and a valid byte is in the receive shift register, and SPIF is serviced before the start of a third transmission, the byte in the receive shift register is transferred into the SPIDR and SPIF remains set (Figure 3-6).")
        d.setdefault("reception_with_spif_serviced_too_late",
            "If SPIF is set and a valid byte is in the receive shift register, and SPIF is serviced after the start of a third transmission, the byte in the receive shift register is lost and is not transferred into the SPIDR (Figure 3-7).")
        d.setdefault("mode_fault_recovery_sequence", [
            "1. Master detects SS LOW with MODFEN=1.",
            "2. MODF set; MSTR cleared (auto-switched to slave); SCK/MOSI/MISO outputs disabled; any in-progress transmission aborted.",
            "3. Software reads SPISR (with MODF=1) then writes SPICR1 to clear MODF and reconfigure as master or slave.",
        ])
        d.setdefault("low_power_mode_entry",
            "On entering wait/stop mode with SPISWAI=1, master aborts in-progress transmission; slave keeps shifting if master still drives SCK (continues to track master).")
        _write(p, d)

    # L14 versioning
    p = gd / "L14_PROTOCOL_VERSIONING.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f.setdefault("spec_version", "V04.01")
        if _empty(f.get("previous_versions")):
            f["previous_versions"] = ["0.1", "0.2", "0.3", "0.4", "0.5", "0.6", "0.7", "0.8", "V02.02", "V03.00", "V03.01", "V03.02", "V03.03", "V03.04", "V03.05", "V03.06", "V04.00"]
        if _empty(f.get("key_changes")):
            f["key_changes"] = [
                {"version": "V03.00", "summary": "Spec counter increased; config-bit change during master transmission now aborts the transmission and forces idle state."},
                {"version": "V03.01", "summary": "CPHA=0 slave-mode transfer description changed; CPHA=1 master-mode transfer description changed; bidirectional master-mode mode-fault note added."},
                {"version": "V04.00", "summary": "Enhanced receive-buffer functionality (SPIF / SPIDR handling on missed-read case); SPI-slave in wait/stop mode behavior clarified; max-allowed-baud-rate note added."},
                {"version": "V04.01", "summary": "Minor rewording of Section 3.1.5 (SPI Data Register)."},
            ]
        if _empty(f.get("backward_compat_traps")):
            f["backward_compat_traps"] = [
                {"trap_name": "config_bit_change_during_transmission",
                 "v0_2_x_and_earlier": "Behavior of changing CPOL/MSTR/etc. during an in-progress transmission was not specified.",
                 "v03_00_and_later": "Any change of a config bit during master-mode in-progress transmission aborts the transmission and forces idle state.",
                 "trap": "Drivers ported from pre-V03.00 may rely on changing CPOL on-the-fly during a transmission; after V03.00 this aborts the transfer."},
                {"trap_name": "receive_buffer_third_byte_handling",
                 "pre_V04_00": "Third-byte handling when SPIF still set was implementation-defined.",
                 "V04_00_and_later": "If SPIF still set and a second byte already buffered, a third byte's reception causes the second byte in shift register to be lost.",
                 "trap": "Polling loops that ignore SPIF latency may silently lose bytes after V04.00."},
            ]
        f.setdefault("version_naming_history_note",
            "Early dot-versions (0.1-0.8) became formal V02.02 in July 2001 (renamed for SRS2.0 template); subsequent versions follow V0Maj.Min scheme.")
        d["fields"] = f
        _write(p, d)

    # L15 encoding tables
    p = gd / "L15_ENCODING_TABLES.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f.setdefault("ss_input_output_selection", {
            "header_columns": ["MODFEN", "SSOE", "Master Mode", "Slave Mode"],
            "rows": [
                {"MODFEN": "0", "SSOE": "0", "Master_Mode": "SS not used by SPI", "Slave_Mode": "SS input"},
                {"MODFEN": "0", "SSOE": "1", "Master_Mode": "SS not used by SPI", "Slave_Mode": "SS input"},
                {"MODFEN": "1", "SSOE": "0", "Master_Mode": "SS input with MODF feature", "Slave_Mode": "SS input"},
                {"MODFEN": "1", "SSOE": "1", "Master_Mode": "SS is slave select output", "Slave_Mode": "SS input"},
            ],
        })
        f.setdefault("bidirectional_pin_configurations", {
            "header_columns": ["Pin Mode", "SPC0", "BIDIROE", "MISO", "MOSI"],
            "master_mode_rows": [
                {"Pin_Mode": "Normal",        "SPC0": "0", "BIDIROE": "X", "MISO": "Master In",            "MOSI": "Master Out"},
                {"Pin_Mode": "Bidirectional", "SPC0": "1", "BIDIROE": "0", "MISO": "MISO not used by SPI", "MOSI": "Master In"},
                {"Pin_Mode": "Bidirectional", "SPC0": "1", "BIDIROE": "1", "MISO": "MISO not used by SPI", "MOSI": "Master I/O"},
            ],
            "slave_mode_rows": [
                {"Pin_Mode": "Normal",        "SPC0": "0", "BIDIROE": "X", "MISO": "Slave Out",            "MOSI": "Slave In"},
                {"Pin_Mode": "Bidirectional", "SPC0": "1", "BIDIROE": "0", "MISO": "Slave In",             "MOSI": "MOSI not used by SPI"},
                {"Pin_Mode": "Bidirectional", "SPC0": "1", "BIDIROE": "1", "MISO": "Slave I/O",            "MOSI": "MOSI not used by SPI"},
            ],
        })
        f.setdefault("normal_vs_bidirectional_mode_table", {
            "header_columns": ["When SPE=1", "Master Mode (MSTR=1)", "Slave Mode (MSTR=0)"],
            "rows": [
                {"When_SPE_1": "Normal Mode SPC0=0",     "Master": "Serial Out on MOSI; Serial In on MISO",                  "Slave":  "Serial In on MOSI; Serial Out on MISO"},
                {"When_SPE_1": "Bidirectional SPC0=1",   "Master": "Serial Out + Serial In on MOMI (gated by BIDIROE)",      "Slave":  "Serial In + Serial Out on SISO (gated by BIDIROE)"},
            ],
        })
        f.setdefault("baud_rate_table_25MHz_bus_clock", {
            "header_columns": ["SPPR2", "SPPR1", "SPPR0", "SPR2", "SPR1", "SPR0", "BaudRateDivisor", "Baud Rate"],
            "row_count_total": 64,
            "example_rows": [
                {"SPPR": "000", "SPR": "000", "Divisor": 2,    "Baud": "12.5 MHz"},
                {"SPPR": "000", "SPR": "001", "Divisor": 4,    "Baud": "6.25 MHz"},
                {"SPPR": "000", "SPR": "111", "Divisor": 256,  "Baud": "97.66 kHz"},
                {"SPPR": "001", "SPR": "000", "Divisor": 4,    "Baud": "6.25 MHz"},
                {"SPPR": "111", "SPR": "111", "Divisor": 2048, "Baud": "12.21 kHz"},
            ],
        })
        tbl = [
            "Table 3-1 Module Memory Map",
            "Table 3-2 SS Input / Output Selection",
            "Table 3-3 Bidirectional Pin Configurations",
            "Table 3-4 Example SPI Baud Rate Selection (25 MHz Bus Clock)",
            "Table 4-1 Normal Mode and Bidirectional Mode",
        ]
        if _empty(f.get("tables")):
            f["tables"] = tbl
        d["fields"] = f
        _write(p, d)

    # L16 compliance
    p = gd / "L16_COMPLIANCE_PROPERTIES.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f.setdefault("must_have_properties", [
            "Identical CPOL on master and communicating slave",
            "Master must always drive SCK; slave must never drive SCK",
            "Slave SS must remain LOW for the entire 8-bit transfer (CPHA=0 strict; CPHA=1 may stay LOW back-to-back)",
            "In master mode, any change to {CPOL, CPHA, SSOE, LSBFE, MODFEN, SPC0, BIDIROE, SPPR, SPR} mid-transmission MUST abort the transmission and force the SPI into idle state",
            "In slave mode, any change to {CPOL, CPHA, SSOE, LSBFE, MODFEN, SPC0, BIDIROE} mid-transmission corrupts the transmission and MUST be avoided",
            "CPOL or MSTR bit change with a received byte pending in the receive shift register destroys the received byte and MUST be avoided",
            "SPIF clearing requires read of SPISR (with SPIF=1) followed by read of SPIDR",
            "SPTEF clearing requires read of SPISR (with SPTEF=1) followed by write to SPIDR; a SPIDR write without first reading SPTEF=1 is silently ignored",
            "MODF clearing requires read of SPISR (with MODF=1) followed by write to SPICR1",
        ])
        f.setdefault("must_not_have_properties", [
            "Two simultaneous masters driving MOSI/SCK without mode-fault arbitration",
            "Two slaves both selected on the same MISO line (output contention)",
        ])
        f.setdefault("compliance_failure_modes", [
            {"mode": "Lost RX byte", "trigger": "Third byte received while SPIF still set and not serviced before start of third transmission."},
            {"mode": "Aborted TX",   "trigger": "Config-bit change during master transmission."},
            {"mode": "Mode fault",   "trigger": "SS pulled LOW while configured master + MODFEN=1."},
        ])
        f.setdefault("min_baud_rate_constraint",
            "Implementation-defined per SoC; spec note: max allowed baud rate per SoC SPI Electrical Specification.")
        f.setdefault("reset_behavior_compliance",
            "After reset SPE=0, SPTEF=1, SPIF=0, MODF=0, MSTR=0, CPOL=1, CPHA=0, all data registers cleared.")
        d["fields"] = f
        _write(p, d)

    # L17 channel catalog (force-set SPI shape)
    p = gd / "L17_CHANNEL_SIGNAL_CATALOG.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f["channels"] = [
            {"name": "MOSI", "direction_master": "output", "direction_slave": "input",
             "purpose": "Master-Output Slave-Input serial data; in bidirectional master mode acts as MOMI (Master I/O); in bidirectional slave mode is not used by SPI.",
             "active_levels": "Push-pull CMOS"},
            {"name": "MISO", "direction_master": "input", "direction_slave": "output (tri-stated when SS HIGH)",
             "purpose": "Master-Input Slave-Output serial data; in bidirectional master mode is not used; in bidirectional slave mode acts as SISO (Slave I/O).",
             "active_levels": "Push-pull CMOS (slave output); high-impedance when slave deselected"},
            {"name": "SCK",  "direction_master": "output", "direction_slave": "input",
             "purpose": "Serial clock; 16 edges per 8-bit transfer; idle polarity per CPOL.",
             "active_levels": "Push-pull CMOS"},
            {"name": "SS",   "direction_master": "output (when MODFEN=1 + SSOE=1) or input (mode-fault detection when MODFEN=1 + SSOE=0) or unused (MODFEN=0)",
             "direction_slave": "input",
             "purpose": "Slave-Select; LOW = selected; HIGH = deselected (slave output tri-stated and SCK input ignored).",
             "active_levels": "Active-LOW"},
        ]
        f["global_signals"] = [
            {"name": "BusClock", "purpose": "MCU bus clock; source for baud-rate generator."},
            {"name": "Reset",    "purpose": "MCU system reset; resets all SPI registers."},
        ]
        f["channel_counts"] = {
            "channels": 4, "external_pins_total": 4,
            "register_count_at_module": 5, "register_addresses_in_map": 8,
        }
        f["handshake_pairs"] = [
            {"name": "BUS_WRITE_SPIDR", "from": "MCU bus", "to": "TX shift register", "rule": "SPTEF=1 → write to SPIDR queued for next transmission."},
            {"name": "RX_SHIFT_TO_SPIDR", "from": "RX shift register", "to": "SPIDR", "rule": "After last sample edge, RX byte copied to SPIDR + SPIF=1."},
        ]
        dg = f.setdefault("dependency_graph", {})
        if isinstance(dg, dict):
            dg["common_rule"] = (
                "Master drives SCK + (optionally) SS. Slave drives MISO (or "
                "MOMI/SISO under bidirectional gating). Slave samples on the "
                "CPHA-defined edge; master samples on the same CPHA-defined edge.")
            dg.setdefault("data_dependency",
                "MOSI/MISO data is sampled on the latching edge defined by {CPOL, CPHA} pair.")
            for kill in ("AXI_read", "AXI3_write", "AXI4_write"):
                dg.pop(kill, None)
        f.setdefault("ordering_rules", {
            "byte_ordering": "Configurable MSB-first (LSBFE=0) or LSB-first (LSBFE=1).",
            "tx_rx_simultaneity": "TX and RX are simultaneous on the same 16-SCK-edge transfer (full duplex).",
        })
        d["fields"] = f
        _write(p, d)

    # L18 interconnect
    p = gd / "L18_INTERCONNECT_TOPOLOGY.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f.setdefault("topology_type", "Point-to-point master-slave serial; extensible to one-master + N-slave with per-slave SS lines.")
        f.setdefault("supported_topologies", [
            {"name": "Point-to-point master-slave", "description": "One master + one slave; 3 wires (MOSI/MISO/SCK) + optional SS."},
            {"name": "Multi-slave",  "description": "One master + multiple slaves; master uses one SS per slave (GPO); only one slave selected at a time."},
            {"name": "Multi-master", "description": "Multiple masters share MOSI/MISO/SCK; mode-fault feature arbitrates bus access; SS doubles as collision-detect input."},
        ])
        f.setdefault("master_slave_role_summary", [
            {"role": "Master", "responsibilities": ["Drive SCK", "Drive SS LOW (when SSOE+MODFEN active) before each transfer", "Initiate transmissions by writing SPIDR"]},
            {"role": "Slave",  "responsibilities": ["Sample SCK", "Sample MOSI on (CPHA-selected) latching edge", "Drive MISO on shifting edge while SS is LOW", "Tri-state MISO when SS is HIGH"]},
        ])
        f.setdefault("bidirectional_mode", {
            "description": "When SPC0=1, single data pin is used; MOSI becomes MOMI (master) or MISO becomes SISO (slave). BIDIROE controls the direction of the chosen pin.",
            "master_mode_pin": "MOMI (was MOSI)",
            "slave_mode_pin": "SISO (was MISO)",
        })
        f.setdefault("interconnect_role",
            "There is no protocol-layer interconnect (no router/bridge). Multi-slave is realized by per-slave SS routing in the SoC integration; multi-master is realized by shared MOSI/MISO/SCK with mode-fault-based arbitration.")
        f.setdefault("ordering_guarantees", {
            "single_master_single_slave": "Bytes are transferred in the order the master writes SPIDR.",
            "multi_master": "No fairness guarantee; collision yields mode-fault and one master surrenders the bus.",
        })
        f.setdefault("ss_handling_per_topology", {
            "point_to_point_CPHA0": "SS must toggle HIGH between bytes (min tI high time).",
            "point_to_point_CPHA1": "SS may stay LOW continuously for back-to-back transfers.",
            "multi_slave": "Each slave's SS individually driven LOW only when addressed.",
        })
        f.setdefault("memory_vs_peripheral_regions",
            "Not applicable (no architectural memory map at the protocol layer).")
        f.setdefault("slave_classification", {
            "duplex_slave": "Capable of both transmit and receive; standard SPI slave.",
            "receive_only_slave": "Simpler slaves with no MISO output drive; master will not receive data from them.",
        })
        f.setdefault("default_signal_values_evidence_tables", [
            "Table 3-2 SS Input / Output Selection",
            "Table 3-3 Bidirectional Pin Configurations",
            "Table 4-1 Normal Mode and Bidirectional Mode",
        ])
        d["fields"] = f
        _write(p, d)

    # L21 power (SPI-specific key names)
    p = gd / "L21_POWER_INTENT.json"
    if p.is_file():
        d = _read(p)
        f = d.get("fields") or {}
        f.setdefault("power_intent_present", False)
        f.setdefault("low_power_modes_summary", {
            "run_mode_when_SPE_clear":   "Module clock to SPI core gated off; registers still accessible.",
            "wait_mode_with_SPISWAI_1":  "SPI clock generation turned off; in-progress transmission stops/resumes per master/slave role.",
            "stop_mode":                  "SPI inactive (module clock disabled); independent of SPISWAI; in-progress transmission stops (master) or continues if SCK driven (slave).",
        })
        f.setdefault("notes", "Power domain partitioning is deferred to SoC integration. The peripheral block has no internal voltage domains.")
        d["fields"] = f
        _write(p, d)


# ---------------------------------------------------------------------------
# Module-level importable detector (lifted from the inline detector in
# phase1_doc_one_shot_runner.py — ORGANIC-20260531). Byte-for-byte the same
# boolean the runner used inline (`_spi_blob` -> `blob`), so behaviour is
# identical; exposing it module-level lets the universal no-misfire guard
# (tests/test_protocol_detector_no_misfire.py) auto-cover this protocol.
# Reads ONLY the spec text `blob` — never a filename or benchmark name.
# ---------------------------------------------------------------------------
def _wb(tok: str, blob: str) -> bool:
    """Word-boundary token match (avoids substring false-positives)."""
    import re
    return re.search(r"\b" + re.escape(tok) + r"\b", blob) is not None


def is_spi(blob: str) -> bool:
    """Content-only `spi` detector (importable, lifted from the runner) WITH a
    FOREIGN-PRIMARY DEFER.

    Empty-safe. Reads ONLY ``blob`` (spec text). The structural signature
    below (MOSI+MISO+SCK pin triple, OR CPOL+CPHA control-bit pair) is the
    byte-for-byte original the runner used inline, but it is necessary and NOT
    sufficient: several neighbouring protocols either ride directly on top of
    the SPI bus (TPM has an SPI-FIFO transport, the JEDEC xSPI/QSPI/OSPI flash
    interface is an EXPANSION of classic SPI) or cite SPI signals in passing
    (the EtherCAT slave's PDI / a LoRa transceiver's host SPI / an MDIO
    register-access example), so their generated L-docs carry MOSI/MISO/SCK or
    CPOL/CPHA tokens and would otherwise trip the bare branches below — and the
    generic SPI synth would then FORCE-OVERWRITE that foreign spec's L-docs
    with SPI identity.

    Guard (mirrors `is_mipi`'s foreign-primary defer doctrine and the AHB+APB
    `_axi_primary` doctrine — GENERAL, content-only, density / structural
    signatures only, NEVER a benchmark-name / chip / SKU literal as detection
    logic): if the blob's DOMINANT subject is one of these foreign protocols,
    defer (return False) so the generic SPI synth never runs on it:

      - TPM (TCG Trusted Platform Module 2.0): dense Trusted-Platform-Module /
        TPM2_-command / PCR naming. A TPM doc names TPM2_* commands and PCRs
        thousands of times; an SPI bus doc names neither.
      - QSPI / OSPI / xSPI (JEDEC JESD251 Expanded SPI): the SPI-FAMILY flash
        expansion — multi-IO data lines + the JEDEC xSPI / SFDP / dummy-cycle /
        DDR-DQS vocabulary. This is a genuine derived-CHILD of SPI, so the
        defer is a sibling-MUTEX on its distinctive xSPI/flash discriminator
        (NOT shared by a plain single-IO SPI doc), which is correct hardening.
      - EtherCAT (IEC 61158 Industrial Ethernet): dense EtherCAT naming + an
        EtherCAT-only structural feature (the EtherType 0x88A4, the datagram /
        FMMU / SyncManager / ESC slave-controller model).
      - LoRa / LoRaWAN: the Chirp-Spread-Spectrum PHY (CSS + spreading factor
        SF7..SF12) and/or the dense LoRaWAN MAC naming. An SPI bus carries
        none of the LPWAN PHY/MAC structures.
      - MDIO (IEEE 802.3 Clause 22/45 Management Data Input/Output): the
        MDC+MDIO two-wire pair + the MDIO frame-field model (PHYAD / REGAD /
        turnaround) and/or the Clause-22/45 management vocabulary.

    The real `spi` benchmark trips NONE of these defers (it carries 0 TPM2_ /
    xSPI / JESD251 / SFDP / EtherCAT / LoRaWAN / MDIO / PHYAD tokens) and stays
    True; each foreign benchmark trips its own foreign-primary defer and is
    suppressed. See test_protocol_detector_no_misfire.py.
    """
    if not blob:
        return False
    low = blob.lower()

    # --- FOREIGN-PRIMARY DEFER (the blob's true subject is NOT SPI). ---
    # TPM 2.0: dense Trusted-Platform-Module / TPM2_-command / PCR naming.
    tpm_primary = (
        blob.count("TPM2_") >= 20
        or blob.count("Trusted Platform Module") >= 20
        or (low.count("tpm") >= 50 and "pcr" in low
            and ("tcg" in low or "commandcode" in low
                 or "trusted platform module" in low)))
    # QSPI / OSPI / xSPI (JEDEC JESD251 Expanded SPI): the SPI-family flash
    # EXPANSION — require at least TWO independent xSPI/flash-only structural
    # features so a plain single-IO SPI doc (which has none) stays True.
    _xspi_feats = sum(bool(x) for x in (
        "jesd251" in low or _wb("xSPI", blob) or "expanded spi" in low,
        "sfdp" in low or "serial flash discoverable parameter" in low,
        "dummy cycle" in low or "dummy cycles" in low,
        ("dqs" in low and ("ddr" in low or "dtr" in low
                           or "double data rate" in low)),
        (("octal" in low and ("io" in low or "data lines" in low
                              or "flash" in low))
         or ("quad i/o" in low or "quad-io" in low
             or "io0" in low and "io3" in low)),
    ))
    qspi_ospi_primary = _xspi_feats >= 2
    # EtherCAT: dense EtherCAT naming + an EtherCAT-only structural feature.
    ethercat_primary = (
        low.count("ethercat") >= 20
        and ("0x88a4" in low
             or "fmmu" in low or "syncmanager" in low
             or "sync manager" in low
             or ("datagram" in low and ("esc" in low or "slave" in low))))
    # LoRa / LoRaWAN: the Chirp-Spread-Spectrum PHY and/or dense LoRaWAN MAC.
    _css = ("chirp spread spectrum" in low
            or ("chirp" in low and "spread spectrum" in low))
    _sf = ("spreading factor" in low
           or any(_wb("SF" + str(n), blob) for n in range(7, 13)))
    lora_primary = (
        (_css and _sf)
        or (low.count("lorawan") >= 20
            and ("deveui" in low or "appkey" in low or "otaa" in low
                 or "network server" in low)))
    # MDIO: the MDC+MDIO two-wire pair + the Clause-22/45 frame-field model.
    mdio_primary = (
        ("mdc" in low and "mdio" in low)
        and (("phyad" in low or "regad" in low)
             or ("clause 22" in low or "clause 45" in low)
             or low.count("mdio") >= 20))
    if (tpm_primary or qspi_ospi_primary or ethercat_primary
            or lora_primary or mdio_primary):
        return False

    # --- STRUCTURAL SPI signature (unchanged byte-for-byte from the runner's
    #     inline detector). ---
    return bool(
        ("MOSI" in blob and "MISO" in blob
            and "SCK" in blob)
        or ("CPOL" in blob and "CPHA" in blob))
