#!/usr/bin/env python3
"""
tristate_bus_check.py — Generate general tristate / open-drain bus assertions.

Given a bus description (list of drivers + readback timing), emits SystemVerilog
Assertions (SVA) and a SymbiYosys (.sby) spec that formally verify:

  (A) Single-driver invariant:
      forall time t:  sum_i(driver_oe[i]) <= 1
      (at most one driver active at any time — prevents bus contention)

  (B) Readback sample delay tolerance:
      driver_oe[i] |=> (after N cycles) readback == driven_value
      (readback becomes valid only AFTER N-cycle sync; sampling earlier → stale value)

  (C) Mutual exclusion of driver groups (e.g., wake_gen vs TX vs RX):
      user-provided pairs like [(wake_oe, tx_busy), (wake_oe, rx_active)]
      asserts wake_oe && (tx_busy || rx_active) == 0

Why this skill exists:
  <half-duplex-tester> debug (2026-04-16) found:
    Bug #5: wake_gen drove bus simultaneously with host RX → corrupted bits
    Bug #8: tx_phy sampled id_bus_rx at cycle 3 but sync latency is ~3-4
             cycles → read STALE bus value → false collision detection
  Both bugs are bus-arbitration issues detectable by formal assertions.

Usage:
    python3 tristate_bus_check.py --bus-name id_bus \\
        --drivers mac_tx_oe,wake_oe \\
        --sync-depth 3 \\
        --mutex wake_oe:tx_busy,wake_oe:rx_active \\
        --out-dir /tmp/bus_check

Generality: works for ANY tristate/open-drain bus in ANY IC. Parameterized by
driver list, sync depth, and mutex pairs. Not tied to any protocol.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path
from typing import List, Tuple


def gen_sva(bus_name: str, drivers: List[str], sync_depth: int,
            mutex_pairs: List[Tuple[str, str]]) -> str:
    lines = []
    lines.append(f"// Generated by tristate_bus_check.py — bus: {bus_name}")
    lines.append("// Properties:")
    lines.append("//   (A) Single-driver invariant")
    lines.append(f"//   (B) Readback sample delay >= {sync_depth} cycles")
    lines.append(f"//   (C) Driver mutex pairs ({len(mutex_pairs)})")
    lines.append("")
    lines.append(f"module {bus_name}_check_assertions (")
    lines.append("    input wire clk,")
    lines.append("    input wire rst_n,")
    for d in drivers:
        lines.append(f"    input wire {d},")
    lines.append(f"    input wire {bus_name}_driven_value,   // What drivers are driving")
    lines.append(f"    input wire {bus_name}_readback        // Synchronized bus sample")
    lines.append(");")
    lines.append("")

    # (A) Single-driver
    lines.append("    // (A) At most one driver active at any time")
    sum_expr = " + ".join(d for d in drivers)
    lines.append(f"    a_single_driver: assert property (")
    lines.append(f"        @(posedge clk) disable iff (!rst_n)")
    lines.append(f"        ({sum_expr}) <= 1")
    lines.append(f"    );")
    lines.append("")

    # (B) Readback sample delay
    lines.append(f"    // (B) After any driver asserts, readback matches after {sync_depth} cycles")
    for d in drivers:
        lines.append(f"    a_readback_{d}: assert property (")
        lines.append(f"        @(posedge clk) disable iff (!rst_n)")
        lines.append(f"        ({d} ##{sync_depth} $stable({d})) |->")
        lines.append(f"        ({bus_name}_readback == {bus_name}_driven_value)")
        lines.append(f"    );")
    lines.append("")
    lines.append(f"    // (B') Cover: catch the anti-pattern — sampling readback <{sync_depth} cycles after drive change")
    lines.append(f"    property p_premature_sample;")
    lines.append(f"        @(posedge clk) disable iff (!rst_n)")
    d0 = drivers[0]
    lines.append(f"        $rose({d0}) ##1 ({bus_name}_readback != {bus_name}_driven_value);")
    lines.append(f"    endproperty")
    lines.append(f"    cov_premature_sample: cover property (p_premature_sample);")
    lines.append("")

    # (C) Mutex
    if mutex_pairs:
        lines.append("    // (C) Driver mutex (drivers that must never be asserted together)")
        for a, b in mutex_pairs:
            lines.append(f"    a_mutex_{a}_{b}: assert property (")
            lines.append(f"        @(posedge clk) disable iff (!rst_n)")
            lines.append(f"        !({a} && {b})")
            lines.append(f"    );")
        lines.append("")
    lines.append("endmodule")
    return '\n'.join(lines)


def gen_sby(bus_name: str) -> str:
    return f"""\
; Formal verification for {bus_name} bus arbitration

[options]
mode bmc
depth 50

[engines]
smtbmc

[script]
read -sv {bus_name}_check_assertions.sv
prep -top {bus_name}_check_assertions

[files]
{bus_name}_check_assertions.sv
"""


def gen_readme(bus_name: str, drivers: List[str], sync_depth: int,
               mutex_pairs: List[Tuple[str, str]]) -> str:
    return f"""\
# {bus_name} Bus Check

Auto-generated assertions for the `{bus_name}` tristate / open-drain bus.

## Configuration

- **Drivers**: {', '.join(drivers)}
- **Readback sync depth**: {sync_depth} cycles
- **Mutex pairs**: {', '.join(f'{a}/{b}' for a, b in mutex_pairs) or 'none'}

## Files

- `{bus_name}_check_assertions.sv` — SystemVerilog Assertions (SVA) module
- `{bus_name}_check.sby` — SymbiYosys formal spec

## How to run

```bash
sby -f {bus_name}_check.sby
```

## Properties verified

1. **Single-driver invariant** — at any cycle, at most one OE is high.
2. **Readback sample timing** — sampling before `sync_depth` cycles after drive
   change returns a stale value; only sampling after `sync_depth` is valid.
3. **Driver mutex** — specific pairs of drivers (e.g., wake vs TX) must never
   be simultaneously active.

## Covered bugs

From the <half-duplex-tester> debug session (2026-04-16):
- Bug #5 (wake_gen vs RX contention) → mutex pair
- Bug #8 (TX collision detect on stale readback) → sync depth property

## Integration

Bind this module to your top-level:

```systemverilog
bind top_module {bus_name}_check_assertions {bus_name}_check_inst (
    .clk(clk), .rst_n(rst_n),
    {', '.join(f'.{d}({d}_signal)' for d in drivers)},
    .{bus_name}_driven_value(your_drive_value),
    .{bus_name}_readback(your_synchronized_readback)
);
```
"""


def parse_mutex(s: str) -> List[Tuple[str, str]]:
    if not s:
        return []
    out = []
    for pair in s.split(','):
        pair = pair.strip()
        if ':' not in pair:
            continue
        a, b = pair.split(':', 1)
        out.append((a.strip(), b.strip()))
    return out


def main():
    ap = argparse.ArgumentParser(description='Generate tristate bus assertions')
    ap.add_argument('--bus-name', required=True,
                    help='name of the bus (used for file prefix, e.g. "id_bus")')
    ap.add_argument('--drivers', required=True,
                    help='comma-separated driver OE signal names')
    ap.add_argument('--sync-depth', type=int, default=2,
                    help='number of sync flop stages between bus and readback')
    ap.add_argument('--mutex', default='',
                    help='mutex pairs as a:b,c:d (must not be simultaneously high)')
    ap.add_argument('--out-dir', required=True)
    args = ap.parse_args()

    drivers = [d.strip() for d in args.drivers.split(',') if d.strip()]
    if len(drivers) < 1:
        print("ERROR: need at least 1 driver", file=sys.stderr)
        return 2
    if args.sync_depth < 1:
        print("ERROR: sync-depth must be >= 1", file=sys.stderr)
        return 2
    mutex = parse_mutex(args.mutex)

    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    sva_file = out / f"{args.bus_name}_check_assertions.sv"
    sby_file = out / f"{args.bus_name}_check.sby"
    readme = out / f"README_{args.bus_name}.md"
    sva_file.write_text(gen_sva(args.bus_name, drivers, args.sync_depth, mutex))
    sby_file.write_text(gen_sby(args.bus_name))
    readme.write_text(gen_readme(args.bus_name, drivers, args.sync_depth, mutex))
    print(f"Generated in {out}:")
    print(f"  {sva_file.name}")
    print(f"  {sby_file.name}")
    print(f"  {readme.name}")
    print(f"\nTo formally verify: cd {out} && sby -f {sby_file.name}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
