#!/usr/bin/env python3
"""XOR layout sign-off gate — computed GDS-vs-golden XOR, not a hardcoded floor.

TAPEOUT-SIGNOFF P0#3 (XOR half). A Caravel / Open-MPW shuttle submission must
XOR-match the assembled GDS (e.g. `user_project_wrapper`, or the full-chip
`caravel`) against the golden reference geometry with ZERO residual delta —
EXCEPT deltas that live entirely inside a *documented* blackbox hard-macro
(whose internal geometry is legitimately abstracted away in the reference, so a
delta there is expected and reviewer-waivable).

Why this program exists
=======================
Today `programs/caravel_integration_runner.py` ASSERTS a "2/7 floor" by
comparing the precheck fail-set to a HARDCODED memory constant
(`KNOWN_2_OF_7_FLOOR = {"Consistency", "XOR"}`). That constant is a *memory* of
what one pilot happened to see — it is never actually COMPUTED against the
submission's own geometry, so it cannot tell a legitimate blackbox-macro XOR
delta from a real one. This program REPLACES that assumption with a real,
per-layer KLayout XOR:

  (a) EMIT the KLayout XOR script — the standard `pya`/DRC-style layer-by-layer
      boolean XOR: read both layouts, per-layer `Region ^ Region`, report the
      residual geometry area + polygon count per layer, and ATTRIBUTE each
      residual to the enclosing top-level macro instance so the verdict step can
      apply a documented waiver.
  (b) PARSE a completed XOR report → verdict:
        - PASS               when there is ZERO residual delta, OR every residual
                             bucket lies inside a macro cell that the caller
                             EXPLICITLY put on the blackbox-macro allow-list
                             (`PASS_WITH_WAIVER`).
        - FAIL               listing the per-layer residual (layer + area + which
                             cell) for any residual that is NOT inside an
                             allow-listed macro — including residual outside every
                             macro (the sentinel bucket `__outside_macros__`) and
                             residual the report could not attribute at all.
        - INCOMPLETE (§4.05) when the report (or a GDS) is absent / unparseable /
                             the emit script reported it could not find the top
                             cell. Absent evidence is NEVER a fabricated PASS.

§4.05 honesty invariants (enforced + unit-tested)
=================================================
  * The blackbox-macro allow-list is an EXPLICIT input — a list of macro CELL
    names the submitter documents as legitimately abstracted. It is NEVER a
    hardcoded count / floor. An empty allow-list means every residual is a real
    delta.
  * A waiver may ONLY swallow residual the report ATTRIBUTES to an allow-listed
    macro. Residual outside every macro, residual attributed to a
    non-allow-listed cell, and residual with no attribution at all ALL still
    FAIL. A waiver can never launder a real, out-of-macro delta into a PASS.
  * Missing report / missing GDS / unparseable report → INCOMPLETE, never PASS.

Chip-AGNOSTIC: pure geometry + a caller-supplied cell-name allow-list; no
design-specific literal appears anywhere in this file.

CLI
===
  # (a) emit the KLayout XOR script for a live run
  python3 xor_layout_check.py --emit-script xor.py \
      --top user_project_wrapper \
      --layout assembled.gds --golden golden_caravel.gds \
      --report-out xor_report.json
  # then, live:  klayout -zz -b -r xor.py    (writes xor_report.json)

  # (b) parse the completed report into a verdict
  python3 xor_layout_check.py --report xor_report.json \
      --allow-macro sram_1kbyte_1rw_1kbyte_32x256_8 \
      --allow-macro <another_documented_blackbox_macro>

Exit codes:  0 = PASS / PASS_WITH_WAIVER,  1 = FAIL,  2 = INCOMPLETE.

Unit tests: `programs/tests/test_xor_layout_check.py`.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

EMITTED_BY = "vibe-ic plugin xor_layout_check v1"

# Sentinel bucket for residual geometry that lies inside NO named macro
# instance. It can never appear on a legitimate allow-list (it is not a real
# cell name), so residual here is ALWAYS a real, unwaivable delta.
OUTSIDE_SENTINEL = "__outside_macros__"


# ---------------------------------------------------------------------------
# (a) KLayout XOR script emitter
# ---------------------------------------------------------------------------
# Standard pya layer-by-layer boolean XOR. Runs live under
# `klayout -zz -b -r <script>` (same batch pattern as the DEF→GDS streamout in
# phase3_one_shot_runner._GDS_STREAMOUT_PY). Paths are embedded as literals for
# reproducibility; an env override is honoured so a harness can re-point them.
_XOR_SCRIPT_TEMPLATE = '''\
# Auto-generated by {emitted_by} — KLayout layer-by-layer XOR.
# Compares the assembled layout-under-test against the golden reference GDS,
# per-layer boolean XOR (Region ^ Region), and writes a JSON residual report
# attributing each residual to the enclosing top-level macro instance so a
# downstream gate can apply an EXPLICIT blackbox-macro waiver allow-list.
import os, sys, json
import pya

TOP = os.environ.get("XOR_TOP", {top!r})
LUT = os.environ.get("XOR_LAYOUT", {layout!r})     # layout under test (assembled GDS)
GOLD = os.environ.get("XOR_GOLDEN", {golden!r})    # golden reference GDS
REPORT = os.environ.get("XOR_REPORT", {report!r})
OUTSIDE = {outside!r}


def _write(obj):
    with open(REPORT, "w") as fh:
        json.dump(obj, fh, indent=2)


def _load(path):
    ly = pya.Layout()
    ly.read(path)
    return ly


def _topcell(ly, name):
    c = ly.cell(name)
    if c is None:
        tops = ly.top_cells()
        c = tops[0] if tops else None
    return c


lut = _load(LUT)
gold = _load(GOLD)
dbu = lut.dbu or 0.001

lut_top = _topcell(lut, TOP)
gold_top = _topcell(gold, TOP)
if lut_top is None or gold_top is None:
    # Honest failure: no anchor top cell → cannot XOR. The verdict step reads
    # `error` and returns INCOMPLETE (§4.05), never a fabricated PASS.
    _write({{"tool": "klayout-xor", "top": TOP,
             "layout_under_test": LUT, "golden_reference": GOLD,
             "error": "top cell not found in one/both layouts",
             "lut_top": lut_top.name if lut_top else None,
             "gold_top": gold_top.name if gold_top else None}})
    print("XOR_ERROR top-cell-not-found")
    sys.exit(3)

# Merged instance-bbox region per direct child cell of the layout-under-test
# top. Residual inside one of these boxes is ATTRIBUTED to that macro; the
# verdict step decides (from the explicit allow-list) whether it is waivable.
macro_boxes = {{}}
for inst in lut_top.each_inst():
    cn = inst.cell.name
    macro_boxes.setdefault(cn, pya.Region()).insert(inst.bbox())

# Union of (layer, datatype) present in EITHER layout.
layer_infos = {{}}
for ly in (lut, gold):
    for idx in ly.layer_indexes():
        info = ly.get_info(idx)
        layer_infos[(info.layer, info.datatype)] = info


def _region(ly, top_cell, info):
    idx = ly.find_layer(info)
    if idx is None:
        return pya.Region()
    return pya.Region(top_cell.begin_shapes_rec(idx))


report_layers = []
total_count = 0
total_area_dbu2 = 0
for key in sorted(layer_infos.keys()):
    info = layer_infos[key]
    ra = _region(lut, lut_top, info)
    rb = _region(gold, gold_top, info)
    xor = ra ^ rb
    xor.merge()
    cnt = xor.count()
    if cnt == 0:
        continue
    name = info.name if info.name else ("%d/%d" % (info.layer, info.datatype))
    by_cell = []
    remaining = xor.dup()
    for cn in sorted(macro_boxes.keys()):
        inside = xor.dup() & macro_boxes[cn]
        ic = inside.count()
        if ic:
            by_cell.append({{"cell": cn, "count": ic,
                             "area_um2": inside.area() * dbu * dbu}})
            remaining = remaining - macro_boxes[cn]
    rc = remaining.count()
    if rc:
        by_cell.append({{"cell": OUTSIDE, "count": rc,
                         "area_um2": remaining.area() * dbu * dbu}})
    total_count += cnt
    total_area_dbu2 += xor.area()
    report_layers.append({{"layer": name, "residual_count": cnt,
                           "residual_area_um2": xor.area() * dbu * dbu,
                           "by_cell": by_cell}})

report = {{"tool": "klayout-xor", "top": TOP,
          "layout_under_test": LUT, "golden_reference": GOLD, "dbu": dbu,
          "total_residual_count": total_count,
          "total_residual_area_um2": total_area_dbu2 * dbu * dbu,
          "layers": report_layers}}
_write(report)
print("XOR_REPORT_WRITTEN " + REPORT)
print("XOR_TOTAL_RESIDUAL_COUNT " + str(total_count))
'''


def emit_xor_script(top: str,
                    layout_under_test: str,
                    golden_reference: str,
                    report_out: str) -> str:
    """Return the pya KLayout XOR script text (chip-AGNOSTIC).

    The script reads both layouts, computes a per-layer boolean XOR, attributes
    each residual to the enclosing top-level macro instance, and writes a JSON
    report at `report_out`. Run it with `klayout -zz -b -r <script>`.
    """
    return _XOR_SCRIPT_TEMPLATE.format(
        emitted_by=EMITTED_BY,
        top=str(top),
        layout=str(layout_under_test),
        golden=str(golden_reference),
        report=str(report_out),
        outside=OUTSIDE_SENTINEL,
    )


def klayout_command_hint(script_path: str) -> str:
    """The shell command a wrapper runs to execute the emitted XOR script."""
    return (f"export QT_QPA_PLATFORM=offscreen && "
            f"klayout -zz -b -r {script_path}")


# ---------------------------------------------------------------------------
# (b) Completed-report parser → verdict
# ---------------------------------------------------------------------------
def classify_report(report: Dict[str, Any],
                    allow_macros: Optional[List[str]] = None,
                    ) -> Tuple[str, List[Dict[str, Any]], List[Dict[str, Any]]]:
    """Classify a parsed XOR report dict into (verdict, waived, failing).

    verdict ∈ {PASS, PASS_WITH_WAIVER, FAIL}. `waived` lists residual buckets
    covered by the EXPLICIT allow-list; `failing` lists every real delta.

    §4.05 rules baked in:
      * only residual attributed to an allow-listed macro cell is waivable;
      * residual in the `__outside_macros__` sentinel bucket, residual on a
        non-allow-listed cell, and residual with NO `by_cell` attribution ALL
        fail — a waiver can never swallow an out-of-macro / unattributed delta;
      * a positive `total_residual_count` with no per-layer breakdown fails
        (conservatively: a delta we cannot attribute is not waivable).
    """
    allow = set(allow_macros or [])
    waived: List[Dict[str, Any]] = []
    failing: List[Dict[str, Any]] = []

    layers = report.get("layers") or []
    accounted = 0
    for layer in layers:
        lname = layer.get("layer", "<unknown-layer>")
        lcount = int(layer.get("residual_count", 0) or 0)
        larea = float(layer.get("residual_area_um2", 0.0) or 0.0)
        if lcount == 0:
            continue
        accounted += lcount
        by_cell = layer.get("by_cell") or []
        if not by_cell:
            # Residual with no attribution can NEVER be waived (§4.05).
            failing.append({
                "layer": lname, "cell": None,
                "count": lcount, "area_um2": larea,
                "reason": ("unattributed residual — report gives no by_cell "
                           "attribution, so no waiver can apply")})
            continue
        for bucket in by_cell:
            cell = bucket.get("cell")
            bcount = int(bucket.get("count", 0) or 0)
            barea = float(bucket.get("area_um2", 0.0) or 0.0)
            if bcount == 0:
                continue
            if cell and cell != OUTSIDE_SENTINEL and cell in allow:
                waived.append({"layer": lname, "cell": cell,
                               "count": bcount, "area_um2": barea})
            else:
                if cell == OUTSIDE_SENTINEL or not cell:
                    reason = ("residual outside every allow-listed blackbox "
                              "macro — a real geometry delta")
                else:
                    reason = (f"cell '{cell}' is not on the blackbox-macro "
                              "allow-list — a real geometry delta")
                failing.append({"layer": lname, "cell": cell,
                                "count": bcount, "area_um2": barea,
                                "reason": reason})

    # Guard: a report that CLAIMS a positive total but breaks nothing down is
    # a real delta we cannot attribute → fail (never silently PASS it).
    total = report.get("total_residual_count")
    if total is not None and int(total) > 0 and accounted == 0 and not failing:
        failing.append({
            "layer": "<unknown-layer>", "cell": None,
            "count": int(total), "area_um2":
                float(report.get("total_residual_area_um2", 0.0) or 0.0),
            "reason": ("report declares a positive total_residual_count but "
                       "no per-layer breakdown — cannot attribute or waive")})

    if failing:
        verdict = "FAIL"
    elif waived:
        verdict = "PASS_WITH_WAIVER"
    else:
        verdict = "PASS"
    return verdict, waived, failing


def _attributed_cells(report: Dict[str, Any]) -> set:
    """The set of macro CELL names the report attributed any residual to.

    Used to detect an INERT allow-list entry -- a macro the submitter put on the
    waiver allow-list that the report never attributed residual to (so the waiver
    matched nothing). The most common cause is running the XOR at a `--top` above
    the macro: the emit-script macro-bbox attribution keys on the DIRECT child
    instances of the XOR top cell, so an allow-listed macro that is nested deeper
    (e.g. `spm` inside `user_project_wrapper` inside `caravel_core` when the XOR
    top is `caravel`) never appears in any `by_cell` bucket and the `--allow-macro`
    is silently a no-op. Surfacing this keeps a submitter from believing a waiver
    applied when it did not (§4.05: never let an inert waiver look effective)."""
    seen: set = set()
    for layer in report.get("layers") or []:
        for bucket in layer.get("by_cell") or []:
            cell = bucket.get("cell")
            if cell and cell != OUTSIDE_SENTINEL:
                seen.add(cell)
    return seen


def _incomplete(top: Optional[str], layout: Optional[str],
                golden: Optional[str], allow_macros: List[str],
                reason: str) -> Dict[str, Any]:
    return {
        "verdict": "INCOMPLETE",
        "top": top,
        "layout_under_test": layout,
        "golden_reference": golden,
        "allow_macros": list(allow_macros or []),
        "incomplete_reason": reason,
        "emitted_by": EMITTED_BY,
    }


def evaluate(report_path: Optional[Path],
             allow_macros: Optional[List[str]] = None,
             top: Optional[str] = None,
             layout_under_test: Optional[Path] = None,
             golden_reference: Optional[Path] = None) -> Dict[str, Any]:
    """Load a completed XOR report and return the verdict dict.

    INCOMPLETE (never PASS) when the report is absent / unparseable, when the
    emit script recorded an `error` (e.g. top cell not found), or when a GDS
    the report references was supplied but is missing.
    """
    allow_macros = list(allow_macros or [])
    lut_s = str(layout_under_test) if layout_under_test else None
    gold_s = str(golden_reference) if golden_reference else None

    # A supplied-but-absent GDS is honest INCOMPLETE, not a PASS.
    for label, p in (("layout-under-test", layout_under_test),
                     ("golden-reference", golden_reference)):
        if p is not None and not Path(p).is_file():
            return _incomplete(top, lut_s, gold_s, allow_macros,
                               f"{label} GDS absent: {p}")

    if report_path is None or not Path(report_path).is_file():
        return _incomplete(top, lut_s, gold_s, allow_macros,
                           f"XOR report absent: {report_path}")
    try:
        data = json.loads(Path(report_path).read_text(encoding="utf-8"))
    except Exception as e:  # noqa: BLE001 — any parse failure is INCOMPLETE
        return _incomplete(top, lut_s, gold_s, allow_macros,
                           f"XOR report unparseable: {e}")
    if not isinstance(data, dict):
        return _incomplete(top, lut_s, gold_s, allow_macros,
                           "XOR report is not a JSON object")
    if data.get("error"):
        return _incomplete(top, data.get("layout_under_test", lut_s),
                           data.get("golden_reference", gold_s), allow_macros,
                           f"XOR script reported error: {data.get('error')}")

    verdict, waived, failing = classify_report(data, allow_macros)

    # Advisory (never changes the verdict, §4.05): flag any allow-list entry the
    # report attributed NO residual to. When there IS residual, an inert entry is
    # almost always a --top-level mismatch -- the allow-listed macro is nested
    # below the XOR top cell, so the macro-bbox attribution (which keys on the
    # DIRECT children of --top) never produced a `by_cell` bucket for it and the
    # waiver silently matched nothing. Surfacing it stops a submitter believing a
    # waiver applied when it did not.
    attributed = _attributed_cells(data)
    inert_allow_macros = [m for m in allow_macros if m not in attributed]
    has_residual = int(data.get("total_residual_count") or 0) > 0 or bool(failing) \
        or bool(waived)
    advisories: List[str] = []
    if inert_allow_macros and has_residual:
        advisories.append(
            "allow-macro(s) matched no residual bucket: "
            + ", ".join(inert_allow_macros)
            + f" -- the XOR top cell is '{data.get('top', top)}' and macro-bbox "
            "attribution only sees its DIRECT child instances, so a macro nested "
            "deeper is never attributable/waivable at this --top (re-run the XOR "
            "with --top set to the cell that DIRECTLY instantiates the macro).")

    return {
        "verdict": verdict,
        "top": data.get("top", top),
        "layout_under_test": data.get("layout_under_test", lut_s),
        "golden_reference": data.get("golden_reference", gold_s),
        "allow_macros": allow_macros,
        "inert_allow_macros": inert_allow_macros,
        "advisories": advisories,
        "total_residual_count": data.get("total_residual_count"),
        "total_residual_area_um2": data.get("total_residual_area_um2"),
        "waived_residual": waived,
        "failing_residual": failing,
        "emitted_by": EMITTED_BY,
    }


def verdict_exit_code(verdict: str) -> int:
    """0 = PASS / PASS_WITH_WAIVER, 1 = FAIL, 2 = INCOMPLETE."""
    if verdict in ("PASS", "PASS_WITH_WAIVER"):
        return 0
    if verdict == "FAIL":
        return 1
    return 2  # INCOMPLETE (or anything unexpected) is never a success


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def _cli(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        description="XOR layout sign-off gate — computed GDS-vs-golden XOR "
                    "with an explicit blackbox-macro waiver allow-list.")
    mode = p.add_argument_group("mode (choose one)")
    mode.add_argument("--emit-script", type=Path,
                      help="Emit the KLayout XOR pya script to this path.")
    mode.add_argument("--report", type=Path,
                      help="Parse a COMPLETED XOR report JSON into a verdict.")

    p.add_argument("--top", default="",
                   help="Top cell to XOR (e.g. user_project_wrapper / caravel).")
    p.add_argument("--layout", type=Path, default=None,
                   help="Assembled layout-under-test GDS.")
    p.add_argument("--golden", type=Path, default=None,
                   help="Golden reference GDS.")
    p.add_argument("--report-out", type=Path, default=Path("xor_report.json"),
                   help="[emit] Where the emitted script will write its report.")
    p.add_argument("--allow-macro", action="append", default=[], dest="allow_macros",
                   help="[report] A blackbox-macro CELL name whose internal "
                        "geometry is documented as abstracted (repeatable). "
                        "NEVER a count — an explicit, per-submission waiver.")
    p.add_argument("--out-json", type=Path, default=None,
                   help="Write the verdict/emit summary JSON here (else stdout).")
    args = p.parse_args(argv)

    if args.emit_script:
        if not args.top:
            print("ERROR: --emit-script requires --top", file=sys.stderr)
            return 2
        for label, gp in (("--layout", args.layout), ("--golden", args.golden)):
            if gp is not None and not Path(gp).is_file():
                print(f"WARN: {label} GDS not present yet: {gp} "
                      "(script still emitted; run it once the GDS exists)",
                      file=sys.stderr)
        script = emit_xor_script(
            args.top,
            str(args.layout) if args.layout else "assembled.gds",
            str(args.golden) if args.golden else "golden.gds",
            str(args.report_out))
        args.emit_script.parent.mkdir(parents=True, exist_ok=True)
        args.emit_script.write_text(script, encoding="utf-8")
        summary = {
            "mode": "emit",
            "script": str(args.emit_script),
            "top": args.top,
            "layout_under_test": str(args.layout) if args.layout else None,
            "golden_reference": str(args.golden) if args.golden else None,
            "report_out": str(args.report_out),
            "command_hint": klayout_command_hint(str(args.emit_script)),
            "emitted_by": EMITTED_BY,
        }
        out = json.dumps(summary, indent=2)
        if args.out_json:
            args.out_json.write_text(out + "\n", encoding="utf-8")
        else:
            print(out)
        return 0

    if args.report:
        result = evaluate(
            args.report, args.allow_macros,
            top=args.top or None,
            layout_under_test=args.layout,
            golden_reference=args.golden)
        out = json.dumps(result, indent=2)
        if args.out_json:
            args.out_json.write_text(out + "\n", encoding="utf-8")
        else:
            print(out)
        return verdict_exit_code(result["verdict"])

    p.error("choose a mode: --emit-script <path> or --report <path>")
    return 2  # pragma: no cover — argparse.error exits


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_cli())
