services:

  xrun:
    build: .
    volumes:
      - ./src/:/src/:ro
    env_file : ./src/.env
    working_dir: /code/rundir
    command: pytest -s --log-cli-level=INFO -o cache_dir=/rundir/harness/.cache /src/test_runner.py -v
    networks:
      - licnetwork

networks:
  licnetwork:
      name: licnetwork
      external: true