# Bucket A — program-rule sketches for programs/ppa_search_run.py
# Corpus-sweep REQUIRED before merging into programs/ppa_search_run.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A placeholder implementation carries an explanatory string saying WHY it cannot answer, and that string names a module or artefact as not yet present. The named thing lands later, in a different change, and the string is never revisited — it is a literal in a file nobody had reason to reopen. The stale claim is then copied verbatim into every document the placeholder publishes, where it reads as a current statement about the tree and is believed, because a provenance note is exactly the field a reader does not audit.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_published_absence_claim_is_rechecked_against_the_tree(sample_text, ports):
    """A published explanation that asserts a named artefact is ABSENT must be re-evaluated against the tree at the moment it is published, not written as a literal. Two qualifications decide the whole rule and both are structural. The absence verb must attach to THAT path — sharing a docstring with it is not attachment. And the claim must be UNCONDITIONAL: a message emitted only on the branch where the artefact was found missing is correct by construction and must never be flagged. What is refused is a claim that is published whatever the tree says, which is the only form that can go stale silently."""
    # Expected signal: ERROR
    # Suggested fix action: Walk the string literals of the program layer. For each absence verb, take only paths within a short window of it, so the verb attaches to the path rather than merely sharing a docstring. Resolve each path; keep the ones that EXIST. Then discard every remaining hit whose literal is reachable only through a branch whose test mentions that artefact — those are correct messages on the not-found path. Refuse what is left: a claim of absence that is published unconditionally about something present. CORPUS-SWEPT ON THIS TREE, AND THE SWEEP IS WHERE BOTH QUALIFICATIONS CAME FROM. Matching a verb and a path anywhere in one literal gives 560 hits over 119,359 literals, all of them a module docstring naming a file in one paragraph and using an absence phrase in another. Requiring proximity gives 85 at a wide window, 14 at a medium one and 6 at a tight one. Reading those 6: four attach the verb to a different noun in the same sentence, and two are messages on a not-found branch. ZERO real defects remain, so this rule runs CLEAN on the tree today — the instance that motivated it has since been fixed at its one site. It is the only rule in this set that meets the run-clean bar outright, and it is worth having anyway: the fixed site was guarded by hand for one string, and nothing stops the next stub from carrying the next one.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A sweep turns a lever and records an objective on each arm. One axis of the objective is computed by a session whose inputs the lever cannot reach — it reads an upstream intermediate rather than the artefact the lever rewrote. The axis then returns the SAME value on every arm while every arm's actual artefacts differ. No individual number looks wrong, no gate fires, and the sweep publishes the axis as searched. A reader concludes the lever does not affect that axis, which is the exact opposite of what happened.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_metric_constant_across_arms_that_differ_is_not_measured_under_that_lever(sample_text, ports):
    """Across a set of arms whose implementations provably differ, an axis taking ONE distinct value on every arm is a candidate for not having been measured downstream of the lever. It is only a CANDIDATE: a clean design is clean on every arm, so a zero-valued count that is invariant is usually correct and flagging it is noise. The discriminator is a SIBLING measuring the same quantity from the same artefact: when one reading of a quantity moves across the arms and another reading of that same quantity does not, the frozen one is not describing the arms. That test needs no reference measurement and no knowledge of what the right value would be, which is what lets it run inside the flow."""
    # Expected signal: ERROR
    # Suggested fix action: At sweep publication, for each axis over the arms that RAN: count distinct values and distinct implementation identities. Group axes into families sharing their leading name segments. Report an axis when the arms carry two or more implementation identities, the axis carries exactly one value, AND some sibling in its family carries more than one. Name the axis, the frozen value, the sibling and its spread. Raise the severity when the frozen value is a numeric sentinel, because a sentinel is what an un-analysed report prints. Two arms make it non-vacuous, so do not gate it behind a minimum sweep size; a one-arm sweep is skipped and SAYS it was skipped. CORPUS-SWEPT ON A REAL 21-ARM PUBLISHED SWEEP, AND NARROWED BY IT: the invariance test alone flags 24 of 54 axes, which is unusable — most are a clean design being clean on every arm. Adding the varying-sibling condition gives 8; requiring the frozen value to be a sentinel as well gives 4. Ship the two-condition form and report the sentinel as severity, not as a filter, because a legitimately-zero count with a varying sibling is a real pattern too. THE TOP HIT IS A LIVE DEFECT AND IT WAS FOUND INDEPENDENTLY BY ANOTHER ROUTE: a timing summary frozen at the sentinel on all 21 arms while its sibling reading of the same quantity spreads over 20 distinct values, from a multi-corner report whose corner key the comparison gate separately refuses as null. Two methods with nothing in common converging on one record is the strongest evidence either can give, and this method adds what the other cannot: the number itself does not move when the thing it measures does.
    return []  # list of findings — TODO implement
