# Bucket A — program-rule sketches for programs/ppa_head_to_head_check.py
# Corpus-sweep REQUIRED before merging into programs/ppa_head_to_head_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A comparison gate declares, per axis, the set of measurement-condition keys two numbers must both carry before they may be compared. The module that emits that axis fills the keys it happens to have. Nothing relates the two sets. A producer short of one key makes every comparison over its numbers refuse, on both arms at once, before any value is looked at — and the refusal names a key, not a producer, so it reads as a caller mistake rather than as the emitting module's gap.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_required_scope_keys_are_emitted_by_their_producer(sample_text, ports):
    """Each key a comparison gate requires of an axis must be emitted by the module that produces that axis, or that module must record, beside the scope it did not fill, the reason it could not. The two-sided rule matters: a key filled with an empty or null placeholder is worse than an absent one, because two placeholders compare equal and two numbers taken under conditions nobody recorded then pass as taken under the same conditions."""
    # Expected signal: ERROR
    # Suggested fix action: For each axis of the comparison gate's required-keys table, construct the producing module's scope on a fixture and diff the key sets. Refuse when a required key is neither emitted nor accounted for by a recorded gap reason. Refuse separately, and with a distinct code, when a required key is present with a null or empty value. THE PREDICATE WAS RUN on the power axis by building the producer's real records and diffing their scope against the consumer's table: 5 of 6 required keys satisfied, the sixth missing. That is the whole check, on one axis, in a few lines — which is the argument for it. It must be driven per axis over the whole required table rather than per producer, because a producer emits scope for more than one axis and satisfying one says nothing about the next. THE RULE ALREADY HAS A WORKING REFERENCE IMPLEMENTATION IN A SIBLING MODULE OF THE SAME LAYER, and the implementing lane should copy it rather than invent one. The timing producer declares a fixed key set that is ALWAYS PRESENT — 7 of the 7 its axis requires — and its suite refuses both a missing key and an UNDECLARED EXTRA, on the stated ground that a key nobody declared makes a record incomparable to every other record. The two producers between them evidence both clauses of this rule: one is short a key, and the other has been seen writing a key that is present and null, which the comparison refuses under a different code precisely because two nulls compare equal. Absent, present-and-null, and undeclared-extra are three distinct verdicts and the check owes all three.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A tool grows a second way to name its input — a directory of many alongside the single positional one — and the two are wired as independent options rather than as alternatives. Given both, the later branch wins and the other input is never opened. Nothing is printed about the input that was dropped, so a caller who names a failing record and adds the directory flag is told the directory's verdict and never learns the record was not read. The exit code changes with it, from a finding to a could-not-check, which reads as an improvement.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_two_input_selectors_given_together_must_refuse(sample_text, ports):
    """Two selectors that name the same input in different ways are ALTERNATIVES and must be declared as such: given both, refuse as a bad invocation and name both. Silently letting one shadow the other converts a real verdict into a different verdict on an unrelated population, and the caller has no way to tell — the output is well-formed and describes work that was genuinely done, just not on the thing they named."""
    # Expected signal: ERROR
    # Suggested fix action: Put the single-target and the collection selectors in one mutually exclusive group so the argument parser itself refuses both, and return the bad-invocation exit code rather than the could-not-check one. Where an existing caller depends on passing both, adjudicate BOTH populations and aggregate under the most-severe rule; never pick one silently. Add the both-given case to the layer's bad-invocation arm so every tool in the layer is covered by the same test rather than this one. CORPUS-SWEPT: the population is 9 commands taking BOTH a positional target and a real collection selector, and NOT ONE declares a mutual-exclusion group — so the rule has no false positives to narrow away here, and 9 sites to fix. The case proven to change its verdict silently is one of the 9. Beware the obvious screen: matching selector names by prefix pulls in every permission flag that begins the same way and reports 34, of which 25 are not selectors at all. Match the names exactly.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A gate finds its inputs with a filename glob carrying a semantic token. The complaint the glob was written to answer is that a conforming record filed under another name goes unjudged — and a filename glob answers that complaint with a smaller version of itself. It fails in both directions at once: a conforming document whose name lacks the token is never read, and a NON-input whose name carries the token is read as an input, which for a gate that names its own output report after itself means the gate adjudicates its own verdict. The disclosed denominator does not save it, because the denominator is counted over the already-name-filtered population.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_discovery_selects_on_the_parsed_document_not_on_the_filename(sample_text, ports):
    """Discovery of typed input must select on the PARSED DOCUMENT — its declared schema, or where none is declared a structural predicate stated in the code — and never on the file's name. A name is a convention the producer may not have been told about, and it is chosen by the same author whose mistake the gate exists to catch. The output-document case must be excluded explicitly rather than by hoping its name differs: a gate that reads its own verdict as an input reports the pass it already wrote."""
    # Expected signal: ERROR
    # Suggested fix action: Walk every candidate file under the root, parse it, and select on the declared schema identifier; where a document class declares none, select on a structural predicate and state that predicate in the code beside the selector. Exclude the gate's own output schemas by name of SCHEMA, not by name of file, and add a test that builds a real report with the real command, drops it in the corpus and asserts the vacuous refusal. Disclose three numbers on every run, not one: files opened, records selected, and files that could not be parsed — a file nobody could read is not a file that held no record, and it must raise the verdict rather than shrink the denominator quietly. Measured on the two committed record trees of this layer: 582 documents of which 15 declare the comparison schema, name-glob selects 0; and 496 documents of which 2 declare it, name-glob selects 4 — two records and two of the gate's own reports. A SECOND INSTANCE, IN THE SAME LAYER AND SHARPER: the timing module selects sign-off reports by a name pattern under three named directories, and its own comment claims that a new corner report is therefore picked up without a change to the module. Measured against the report names the flow's own runner writes, the pattern reaches 8 of 13 timing-shaped reports — and one of the five it misses is a report the SAME runner deliberately stamps with the basis marker this module reads. Some of the five may be out of scope on purpose; nothing in the selector says which, and that is the defect rather than the count. A structural selector states the intent it is currently leaving to a prefix. CORPUS-SWEPT, AND THE POPULATION IS NOT WHAT IT LOOKS LIKE. Applied to every filename pattern in the program layer the rule flags 362 of 1584, and the overwhelming majority are correct: a layer reading artefacts it wrote itself, under names it chose, in a directory it owns. There is no two-author problem there and flagging it is noise. The population where the rule holds is a scan over a CALLER-SUPPLIED corpus, whose documents may have been written by a producer this layer never saw — measured here as 12 programs, not 362 sites, which makes the check per-scanner and tractable. Scope it that way. AND FOLLOW CONSTANTS: a screen that reads only the literal argument of the discovery call finds 4 of the 12 and MISSES THE CASE THAT MOTIVATED THIS RULE, whose pattern is a module-level constant. That is the third time in this batch a naive screen has failed on the very case it was written for. SPLIT OFF THE SECOND INSTANCE: the timing-report case is a different rule wearing the same clothes. It is same-layer, so the corpus argument does not apply; what is wrong there is that the module's own comment CLAIMS a new report is picked up without a change and the pattern does not deliver that. That belongs with the documented-claim family, not here.
    return []  # list of findings — TODO implement
