# Bucket A — program-rule sketches for programs/enhancement_emit.py
# Corpus-sweep REQUIRED before merging into programs/enhancement_emit.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: One tool WRITES a document and a second tool VALIDATES it. The writer's own schema documents a field as free text; the validator requires that field to match a fixed prefixed form. Each side is self-consistent and each side's tests pass. The writer accepts and emits the malformed document with no complaint, so the refusal arrives later, from a different tool, in a different run, and only if somebody thinks to run it — by which time the document has been filed and the author has moved on.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_writer_enforces_the_field_shapes_its_declared_consumer_requires(sample_text, ports):
    """A writer that produces a document for a declared validator must apply that validator's field-shape rules AT WRITE TIME, not leave them to be discovered downstream. The two rule sets must come from one place: a shape restated in a second file is a shape that will disagree with the first. Measured cost of the split: the writer's own documentation gave no hint the field was constrained at all, so the natural reading produced a document its sibling refused."""
    # Expected signal: ERROR
    # Suggested fix action: Import the validator's field-shape rules into the writer and apply them to every field the validator constrains, before the file is written; refuse with the validator's own message so the two tools cannot disagree about what is wrong. State the constrained shape in the writer's schema documentation as well, since an author reads the writer's contract and never the validator's. Add a two-directional test: a well-shaped field writes and validates, and a free-text field is refused BY THE WRITER rather than only by the validator. MEASURED: 6 of the 29 backlog records already filed in this tree fail the shape rule their own validator enforces, and both records this lane emitted were refused on first write — by an author reading the writer's contract, which documents the field as free text.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: The whole purpose of turning a recovery into a deterministic rule is that the next run recovers it with no agent present. That holds only if something invokes the program the rule lands in. Routing is chosen by naming the program that OWNS the subject, which is the right criterion for correctness and says nothing about whether anything runs it — and the tree separately tracks gates that no automatic verdict consults. Nothing joins the two, so a capture can be perfectly routed, perfectly implemented, and silent forever, while the record and the routing table both read as complete.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_distilled_rule_must_be_routed_into_a_program_some_verdict_consults(sample_text, ports):
    """Routing a rule to the program that owns its subject is necessary and not sufficient: the program must also be one that something invokes. A rule in a program no verdict consults is indistinguishable, from every artefact the capture produces, from a rule that fires and finds nothing — and it is worse than an unwritten rule, because the record asserts the class is now covered. Join the routing table to the wiring census at emit time and refuse the pairing, rather than discovering it when a later run does not catch the thing the record promised."""
    # Expected signal: ERROR
    # Suggested fix action: At emit time, resolve each record's target program through the routing table and check it against the wiring census the tree already maintains — the one that lists gates no automatic verdict consults, together with its standing baseline. Refuse a record whose target is unwired, naming both the record and the program, and say which of the two must change: wire the program, or route the rule to one that runs. MEASURED on this batch, and RE-MEASURED after it grew: 26 Bucket-A records resolve to 16 distinct programs and NONE of them is unwired (it was 21 into 15 when the rule was written; re-running the check is the rule applying to itself), so the batch passes the check it is proposing — which is the result to want and not the one to assume, because I did not verify it until I wrote this rule. The census on this tree reports 619 gates with 61 unwired against a baseline of 59, and names three as newly unwired; one of those three is a program of the very layer this batch is about, so the pairing was reachable rather than hypothetical.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A rule is distilled from a defect, and to size it the author writes a screen over the tree and quotes what it returns. The screen is written from the same understanding that produced the rule, so it inherits the same blind spot: it matches something ADJACENT to the subject. Nothing catches this, because a population count has no expected value to compare against — the number is the answer, so any number looks like the answer. The failure is silent in both directions, and the direction that survives review is the LOW one: a screen returning a small tidy number reads as a well-scoped rule, while a screen returning an absurd number at least invites suspicion.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_quoted_population_count_must_name_the_known_instance_its_screen_was_validated_(sample_text, ports):
    """A count over a population is a measurement, and a measurement whose apparatus was never checked against a known reading is not evidence. Before quoting what a screen returns, run it against an instance already known to be in the population — the defect the rule came from is always available and costs nothing — and state that it was found. A screen that cannot find the case it was written for is not narrow, it is wrong, and its number is unusable in either direction."""
    # Expected signal: ERROR
    # Suggested fix action: At emit time, require a record that quotes a population count to also name the known instance the screen located, and refuse the record when it does not. The control is free: the motivating defect is by construction a member. Prefer two runs in opposite directions — a broad form and a narrow one — because a single number is unfalsifiable while a pair that disagree by an order of magnitude localises the error immediately. MEASURED ON THIS BATCH, WHICH IS THE EVIDENCE: twelve screens I wrote returned a number I could not use. A prefix match pulled in every permission flag, 34 for 9. A verb matched a path three paragraphs away, 560 for 0. A no-argument probe measured the argument parser, 18 of 19 and worthless. Module-stem matching counted in-repo packages as third-party, 216 for 51. An exit code read after a pipe reported the status of the last command in it. One matched a pattern literal inside a regex and reported a document that does not exist. AND THREE OF THE TWELVE FAILED TO FIND THE VERY CASE THEY WERE WRITTEN FOR — a pattern held in a constant, a command spanning continuation lines, and a name composed by a format string — which a positive control would have caught in one run each. The warnings are currently scattered across five records under five headings, so a reader of any one of them sees only their local instance; this record is the class.
    return []  # list of findings — TODO implement
