# Bucket A — program-rule sketches for programs/_ppa/schema_validation.py
# Corpus-sweep REQUIRED before merging into programs/_ppa/schema_validation.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: An interface states that every instance document declares its type and that each type has a schema. Producers duly stamp the type into every document they write. Nothing checks that the schema exists, so types accumulate faster than schema files and most documents end up self-declaring a type nothing can validate them against. The gap is silent by construction: the document is well-formed, it names its type, and a consumer that validates only when a schema is found reports success on the ones where none is.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_every_emitted_document_type_must_have_the_schema_its_own_interface_promises(sample_text, ports):
    """A document type that nothing can validate is a promise the interface makes and the tree does not keep. Enumerate the type identifiers producers emit and require a schema for each, because the missing schema is not a documentation debt — it is the reason downstream fields go unenforced. Two defects already recorded in this batch reduce to it: a field that should be mandatory whenever a verdict names a tool, and a provenance convention that two producers resolve in opposite directions. Neither can be fixed where it was found; both need the type to be describable first."""
    # Expected signal: ERROR
    # Suggested fix action: Collect the document-type identifiers producers stamp into their output, collect the schema files present, and refuse a type with no schema — reporting the identifier and the producer that emits it. Run it in the direction that also catches the reverse: a schema file for a type nothing emits is a document class that has gone away and left its contract behind. MEASURED: 29 document-type identifiers are emitted and 14 schema files exist, leaving AT LEAST 17 types with no schema — at least, because the file-matching used here is by name fragment and errs toward reporting a schema as present. The type the originating lane asked about is among them, and so are the bundle, the sign-off record set, the frontier and the evidence manifest. THIS IS AN UPSTREAM CAUSE, NOT A PEER: two other records in this batch describe fields nobody enforces, and the reason nobody enforces them is that the document type carrying them cannot be described.
    return []  # list of findings — TODO implement
