# Bucket A — program-rule sketches for programs/crosslayer_search_space.py
# Corpus-sweep REQUIRED before merging into programs/crosslayer_search_space.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A search space decides, per lever, whether the specification permits turning it, and publishes the admitted set with a count. Permission is a property of the SPECIFICATION; having somewhere to apply it is a property of the DESIGN, and the document conflates them. A lever that is permitted but has no applicable site on this design is admitted, counted, and indistinguishable in the published record from one with many sites — so the space advertises a dimensionality it does not have, a reader plans a sweep against it, and the shortfall only appears when somebody tries to author a candidate and finds there is nothing to change.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_admitted_lever_must_report_its_applicable_site_count(sample_text, ports):
    """Admission answers whether a lever MAY be turned; it does not answer whether there is anything here to turn. Both belong in the published space, per lever, because a consumer sizing a search reads the admitted count as the number of dimensions available to it. A lever admitted with zero applicable sites is not a search dimension, and a space that cannot say so overstates itself in the one field a planner uses. Report the count rather than dropping the lever: zero sites on this design is a measurement about the design, and silently withholding an admitted lever would hide it."""
    # Expected signal: WARN
    # Suggested fix action: Give each lever an applicable-site counter over the design's own sources — for a state-encoding lever the number of state-holding control structures, for a hierarchy lever the number of module boundaries eligible to move, and so on — and publish the count beside `admitted` on every lever. Report a lever admitted with a count of zero as a distinct, non-fatal finding, and subtract it from the count a planner reads, or publish both totals so the difference is visible. Where a lever's sites cannot be counted deterministically, emit the count as not-measured with the reason rather than as zero: an uncounted lever and an inapplicable one must not look alike, which is the same sentinel rule the record layer already enforces. MEASURED on the published space document: `admitted_count` is 5, every one of the 5 admitted levers carries the same ten keys, and NONE of those keys is a site count — while on that design one of the 5 had no applicable site at all, being a pure datapath with no control state to re-encode. The lane that hit this authored no candidate for it and said so in prose; nothing in the machine-readable space records it.
    return []  # list of findings — TODO implement
