# Bucket A — program-rule sketches for programs/plugin_change_pytest_gate.py
# Corpus-sweep REQUIRED before merging into programs/plugin_change_pytest_gate.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A suite parametrises over a population it DISCOVERS (a glob, a package walk) but drives each member with an invocation it DECLARES (a hand-maintained table or a literal tuple). The guard against an empty population is written as a floor — at least N — with N frozen at the count on the day the two numbers happened to agree. The floor then passes forever while the two sets drift apart, so a member added later is silently uncovered, and an entry left behind for a member since deleted is invisible in the other direction. The class is not confined to test files and it is not confined to invocation tables: any place a literal list stands in for a population the code could enumerate has it, INCLUDING inside a census written to fix this very defect, which is where it is hardest to see because the file's subject is the rule it breaks.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_population_guard_asserts_equality_not_a_floor(sample_text, ports):
    """A population guard over a discovered set must assert EQUALITY against the declared set and print the symmetric difference, never a lower bound. A lower bound answers a question nobody asked — is the population non-empty — while the question that matters is whether every discovered member is declared and every declared member still exists. A floor cannot see either drift, and it reads as coverage while holding neither."""
    # Expected signal: ERROR
    # Suggested fix action: Replace the floor assertion with a set-equality assertion between the discovered population and the declared table, whose message prints both counts and both directions of the difference. Emit it ONCE for the whole population rather than once per member, so the reader gets the list instead of N single names. THE OBVIOUS WRONG GUARD, and one is already in the tree: asserting the declared table against ITS OWN length. That is self-consistency; it passes for any table and can never see the population. Assert against the POPULATION. Where several declared tables cover one discovered population, assert each against it and assert the tables agree with one another — the defect is not confined to invocation tables: the same shape sits on the present-but-empty input table and on the hand-listed producer set, whose discovered counterpart is an importable package. NOTE ON WHERE THIS LIVES: no program in this tree audits a test suite's own population arithmetic, so this routes to the gate that stands between a plugin change and a completion claim. Its natural home is a new member of the meta-gate family that already audits the program population for wiring and for a disclosed denominator; build it there and this gate calls it. COUNT THE OTHER SITES BEFORE BUILDING: measured on this tree the same shape sits on SIX tables of one layer — two invocation tables at 15 of 19, a present-but-empty input table at 8 of 19, a hand-named producer trio, a literal backend tuple whose package is importable, and the envelope-producer direction of the census at three literals. Only the first was known when this record was written; the other five came from asking the question once per table. A fix that repairs one table and leaves five is the floor again at a different altitude.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: A suite that enforces a LAYER-wide property selects its population with a filename-prefix glob, because in the layer's first week the prefix and the layer were the same set. They stop being the same set as soon as the layer gains a module inside its own package, or a program that imports the layer under a different name. Every such executable is outside the population, so the layer property is unenforced on it — and the defect the suite exists to catch survives there untouched, with the suite green.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_layer_membership_is_declared_not_inferred_from_a_filename_prefix(sample_text, ports):
    """Membership of a layer is a RELATION — the executable imports the layer's package, or cites the layer's interface document — and it must be computed from that relation, never from how the file happens to be named. A naming convention standing in for a boundary silently shrinks the population every time the layer grows in a direction the convention did not anticipate, and the shrinkage is invisible because the members that fell out were never counted."""
    # Expected signal: ERROR
    # Suggested fix action: Define the population as every executable that imports the layer's package or cites the layer's interface document, and take the prefix glob as one contributor rather than as the definition. Assert that the relation-derived population is a superset of the glob-derived one, and drive every arm of the layer property over the relation-derived set. NOTE ON WHERE THIS LIVES: same home as the population-equality rule, and they share a helper — the relation-derived population is the input both need, so computing it twice is how the two answers start to disagree.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.66
# Pattern: Two modules agree on a document shape: one writes it, the other reads and validates it. Neither imports the other — the writer builds a plain mapping and the reader receives one — so the relation exists in the SHARED VOCABULARY and nowhere in the code. Dependency analysis cannot see it, the module graph shows the two as unrelated, and each side's suite exercises only its own reading of the shape. Both suites pass. The disagreement is reachable only by driving the two together, which nothing does, so the defect ships and is found by whoever first runs the layer end to end.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_contract_relation_is_not_an_import_edge_and_owes_a_pair_test(sample_text, ports):
    """Where two modules share a document-shape identifier and neither imports the other, they have a contract with no code relation, and that pair owes a test that exercises BOTH sides — the real producer's output handed to the real consumer. This is the seam class that per-module suites cannot reach by construction, not by oversight: a suite that imports one module is testing one reading of a two-sided agreement, and a second reading it never loads cannot contradict it. Exclude the vocabulary token that most modules carry before counting, or the pair set explodes into every combination and the real seams drown in it."""
    # Expected signal: ERROR
    # Suggested fix action: Collect, per module, the document-shape identifiers it names as string literals. Drop any identifier carried by more than two modules — that is the layer's universal record type, not a contract between a pair. Every remaining identifier shared by exactly two modules is a producer/consumer contract: require a test file whose imports include BOTH modules, and report each pair that has none. MEASURED ON THIS LAYER: 6 contract pairs; 0 of 6 have an import edge, so a dependency-graph check finds none of them; 5 of 6 now have a pair test, all added by the lanes that repaired the seam defects; and 1 of 6 has NEITHER — a live seam of exactly the shape that produced four of the eighteen findings. Guard the detector's own denominator: without the generic-token exclusion the same layer reports 47 pairs, and the 6 that matter are indistinguishable from the 41 that do not.
    return []  # list of findings — TODO implement
