#!/usr/bin/env python3
"""Generate candidate integration fixtures for critical skills (full_markdown tier).

For each critical skill, walks its compliance.yaml and emits a markdown
fixture that satisfies every `pattern` requirement. Algorithm:

  1. If requirement has `positive_sample`, use it verbatim.
  2. Else, decompose the regex alternation and pick the first literal token,
     expanding `##\s+Foo` → `## Foo`.

The resulting fixture is committed as a golden reference. When the skill
spec changes, run this script to refresh; review the diff; commit.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required", file=sys.stderr); sys.exit(2)

HERE    = Path(__file__).resolve().parent
SKILLS  = HERE.parent / "skills"
OUT     = HERE / "integration_fixtures"
OUT.mkdir(parents=True, exist_ok=True)

CRITICAL = [
    "spec-to-rtl",
    "integration-spec-gen",
    "flow-orchestrate",
    "phase1-orchestrate",
    "tapeout-checklist",
    "datasheet-gen",
    "rtl-review",
    "testbench-gen",
]


def pattern_to_fixture(pat: str) -> str:
    """Turn regex into a string containing a match. Uses re iterative
    simplification similar to gen_compliance_tests._pattern_to_satisfier
    but operates on RAW pattern strings (not escape-laden YAML literals)."""
    s = pat
    # Strip anchors
    s = s.replace("^", "").replace("$", "")
    # (?:A|B|C) or (A|B|C) → first branch
    def pick_first(m):
        inner = m.group(1)
        first = inner.split("|")[0]
        return first
    # Non-capturing groups with alternation
    s = re.sub(r"\(\?:([^()]+?)\)", pick_first, s)
    # Capturing groups with alternation
    s = re.sub(r"\(([^()]+?\|[^()]+?)\)", pick_first, s)
    # Remaining capture groups (no alternation) — drop parens
    s = re.sub(r"\(([^()]*)\)", r"\1", s)
    # Whitespace metachars
    s = s.replace(r"\s+", " ").replace(r"\s*", " ").replace(r"\s", " ")
    # Other metachars
    s = s.replace(r"\d+", "1").replace(r"\d", "1")
    s = s.replace(r"\w+", "foo").replace(r"\w", "x")
    # Optional group quantifier `?` following a word: drop
    s = re.sub(r"([A-Za-z0-9_]+)\?", r"\1", s)
    # Character classes
    s = re.sub(r"\[([^\]]+)\]\+", lambda m: m.group(1)[0], s)
    s = re.sub(r"\[([^\]]+)\]",   lambda m: m.group(1)[0], s)
    # Dots
    s = s.replace(r".+?", "x").replace(r".+", "x").replace(r".*?", "x").replace(r".*", "x").replace(r".", " ")
    # Remaining escapes
    s = re.sub(r"\\([^a-zA-Z0-9])", r"\1", s)
    # Collapse whitespace
    s = re.sub(r"\s+", " ", s).strip()
    return s or "XXX"


def build_fixture(skill: str) -> tuple[str, list[str], list[str]]:
    """Return (markdown_text, req_ids, req_ids_missing_positive_sample).
    Missing-positive-sample list tells the caller which patterns the
    naive decomposer had to guess at — those are the likely Layer-3
    fail points that need hand-written positive_sample in the yaml."""
    yml = SKILLS / skill / "compliance.yaml"
    data = yaml.safe_load(yml.read_text()) or {}
    parts = [f"# Integration fixture for {skill}",
             "#",
             "# AUTO-GENERATED by _shared/gen_integration_fixtures.py",
             "# Each requirement's text is either its `positive_sample` (preferred)",
             "# or a best-effort regex decomposition (fragile — add positive_sample).",
             "# Regenerate when compliance.yaml requirements change.",
             ""]
    expected_ids = []
    missing_pos = []
    # #2048. This generator used to append the RTL post-check header to ANY
    # fixture whose yaml selected `postcheck_pass_only`, which meant the
    # repo's own tooling manufactured the unmeasured claim that made those
    # cross-checks green. Measured on origin/main: regenerating the
    # `rtl-review` and `tapeout-checklist` fixtures turned all seven of their
    # named audit cross-checks from FAIL to PASS with zero receipts on disk.
    # A fixture for an `output_type: report` skill must not carry a header
    # that document could never have earned.
    output_type = str(data.get("output_type") or "").strip().lower()
    needs_postcheck_header = False
    for section in ("requirements", "cross_checks", "postchecks"):
        for req in data.get(section) or []:
            if not isinstance(req, dict):
                continue
            if (req.get("rule") == "postcheck_pass_only"
                    and output_type != "report"):
                needs_postcheck_header = True
            if "pattern" not in req:
                continue
            rid = req.get("id", "?")
            expected_ids.append(rid)
            pos = req.get("positive_sample")
            if pos:
                text = pos
            else:
                text = pattern_to_fixture(req["pattern"])
                missing_pos.append(rid)
            parts.append(f"<!-- {rid} -->")
            parts.append(text)
            parts.append("")
    if needs_postcheck_header:
        parts.append("<!-- postcheck_pass_only header -->")
        parts.append("// Post-checks: rtl_hygiene_lint=PASS, fsm_error_invariant=PASS")
        parts.append("")
    return "\n".join(parts) + "\n", expected_ids, missing_pos


def main():
    for skill in CRITICAL:
        fx, ids, missing = build_fixture(skill)
        (OUT / f"{skill}.md").write_text(fx)
        flag = f"  [MISSING positive_sample: {missing}]" if missing else ""
        print(f"WROTE: integration_fixtures/{skill}.md  ({len(ids)} reqs){flag}")


if __name__ == "__main__":
    main()
