"""Layer 3 of the v0.50 testing strategy (_shared/TESTING_STRATEGY.md).

For each critical skill (testability: full_markdown), run its golden
fixture under `integration_fixtures/<skill>.md` through the compliance
engine and assert PASS. Fixtures are generated by
`gen_integration_fixtures.py` and committed; when a skill's spec changes
the fixture is regenerated + reviewed + re-committed.

Unlike Layer 1 (engine-correctness against known-bad) and Layer 2
(pattern validity with positive/negative samples), this layer validates
the END-TO-END pipeline: real (but hand-curated) markdown → engine →
PASS. Failure here means either the skill spec drifted from reality or
the fixture is stale. Either way, gatekeeper skills get human attention
before the fixture is updated.
"""
from __future__ import annotations
import json, subprocess, sys
from pathlib import Path

import pytest

HERE       = Path(__file__).resolve().parent
FIXTURES   = HERE / "integration_fixtures"
DRIVER     = HERE / "skill_compliance_check.py"
SKILLS     = HERE.parent / "skills"

# Critical skills, each with a flag saying whether its yaml has enough
# positive_sample annotations for the naive fixture to fully PASS. When
# the flag is True, the test is strict; when False, xfail (strict=False)
# tracks progress without blocking.
# v0.59 H1: list updated after the v0.58 phase-1 fact-graph refactor moved
# 11 layer-doc-gen skills (datasheet-gen / frs-gen / cmd-protocol-gen /
# regmap-gen / adi-spec-gen / control-logic-gen / test-debug-gen /
# timing-waveform-gen / rtl-constants-gen / integration-spec-gen) and
# phase1-orchestrate to legacy/skills_phase1_v051/. They're replaced by
# the single `phase1` skill backed by tools/phase1_engine/.
CRITICAL = [
    ("spec-to-rtl",           True),    # fully annotated
    ("phase1",                False),   # v0.58 single Phase-1 skill (replaces 11+1 legacy)
    ("flow-orchestrate",      False),
    ("tapeout-checklist",     False),
    ("rtl-review",            False),
    ("testbench-gen",         False),
]


@pytest.mark.xfail(strict=False, reason="regression-from-v2-rename — extraction/walker behaviour drift exposed by public CI when full pytest replaced root's curated regression_suite.py; tracked in MAINTAINER_GITHUB_SETTINGS")
@pytest.mark.parametrize("skill,fully_annotated",
                         CRITICAL,
                         ids=[s for s, _ in CRITICAL])
def test_golden_fixture_passes_compliance(skill, fully_annotated, tmp_path):
    if not fully_annotated:
        pytest.xfail(
            f"{skill}: yaml needs positive_sample added to every pattern before "
            "the naive integration fixture can PASS compliance. "
            "See _shared/TESTING_STRATEGY.md §Layer 3.")
    fx = FIXTURES / f"{skill}.md"
    yml = SKILLS / skill / "compliance.yaml"

    assert fx.exists(), (
        f"Missing integration fixture: {fx}. "
        f"Run `python3 _shared/gen_integration_fixtures.py` to regenerate.")
    assert yml.exists(), f"Missing compliance.yaml: {yml}"

    report = tmp_path / f"{skill}.json"
    r = subprocess.run(
        [sys.executable, str(DRIVER),
         "--requirements", str(yml),
         "--json", str(report),
         str(fx)],
        capture_output=True, text=True,
    )
    # driver exit: 0 = PASS, 1 = FAIL
    if r.returncode != 0:
        details = report.read_text() if report.exists() else r.stdout
        pytest.fail(
            f"{skill} golden fixture failed compliance:\n"
            f"  fixture: {fx}\n"
            f"  compliance: {yml}\n"
            f"  driver stdout:\n{r.stdout[:1000]}\n"
            f"  driver stderr:\n{r.stderr[:500]}\n"
            f"  report:\n{details[:1500]}")
