"""Generate programs/adversarial_findings.json from a LIVE campaign. argv: <plugin>"""
import json
import subprocess
import sys
from pathlib import Path

PLUGIN = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(PLUGIN / "programs"))
sys.path.insert(0, str(PLUGIN / "programs" / "tests"))
import adversarial_agent as AA  # noqa: E402
from _published_corpus import CORPUS_ENV, corpus_root  # noqa: E402

# `PLUGIN.parents[2] / "benchmark-data" / "ic"` until the corpus left this
# repository at `c5d7f2d00`. After that this generator could not reach a single
# cell on any host, so the one supported way to re-measure the ratchet's own
# finding set was broken for as long as the ratchet was — a finding could not be
# closed even by a fix that closed it, because closing requires re-generating
# this file and the generator had nothing to read.
_ROOT = corpus_root()
if _ROOT is None:
    sys.exit(f"[REFUSED] gen_adversarial_findings: no published corpus. Point "
             f"${CORPUS_ENV} at a clone of vibeic/benchmark-data. Regenerating "
             f"this file from a corpus that is not there would publish an EMPTY "
             f"finding set, which reads as 'every finding closed'.")
IC = _ROOT / "ic"
CELL = "spm/v1.9.96_gf180mcuD"
DONOR = "sha256/clean_run_v1427_20260715"
OLDER = "sha256/clean_run_v1422_20260715"

# MEASURED_ON WAS A TYPED LITERAL and stayed "a38902d1" across every
# regeneration after it. A finding set whose subject commit is hand-carried
# says whatever it said last time somebody remembered, and this file exists
# precisely because a finding must not be negotiable. Derived now.
try:
    MEASURED_ON = subprocess.run(
        ["git", "-C", str(PLUGIN), "rev-parse", "--short=8", "HEAD"],
        capture_output=True, text=True, timeout=30, check=True).stdout.strip()
except (OSError, subprocess.SubprocessError):
    MEASURED_ON = "NOT DETERMINED"

rows = []
for attack, fn, kwargs in (
    ("A3_CROSS_DESIGN", AA.attack_cross_design, {"donor": IC / DONOR}),
    ("A2_STALE_REPLAY", AA.attack_stale_replay, {"older": IC / OLDER}),
    ("A1_TAMPER_DESTRUCTIVE", AA.attack_tamper_destructive, {}),
):
    if attack == "A3_CROSS_DESIGN":
        got = fn(PLUGIN, IC / CELL, kwargs["donor"])
    elif attack == "A2_STALE_REPLAY":
        got = fn(PLUGIN, IC / CELL, kwargs["older"])
    else:
        got = fn(PLUGIN, IC / CELL)
    for a in got:
        rows.append({"attack": attack, "target": a.target, "verdict": a.verdict})

forging = sorted({(r["attack"], r["target"]) for r in rows
                  if r["verdict"] == AA.SUCCEEDED})
doc = {
    "schema": "vibe-ic/adversarial-findings/v1",
    "_comment": [
        "The gates that CURRENTLY produce a green from evidence that is not",
        "theirs. Generated by tools/gen_adversarial_findings.py from a live",
        "campaign -- never hand-edited, because a hand-edited finding list is an",
        "allowlist and #1119 exists to stop findings being negotiable.",
        "",
        "This file is a RATCHET, checked in both directions by",
        "test_adversarial_agent.py:",
        "  a NEW (attack, gate) pair here      -> a gate started forging a green",
        "  a listed pair that now DEFENDS      -> the finding CLOSED; say which",
        "                                         fix closed it and re-generate",
        "  a listed pair that goes UNAVAILABLE -> the cell it needed is gone. The",
        "                                         finding is UNPROVEN, not fixed,",
        "                                         and must not read as progress.",
        "",
        "That third case is the one that matters: without it a corpus prune would",
        "silently 'close' every finding and the ratchet would measure the",
        "publication schedule instead of the gates.",
    ],
    "measured_on": MEASURED_ON,
    "cell": CELL,
    "donor": DONOR,
    "older_run": OLDER,
    "forging": [{"attack": a, "target": t} for a, t in forging],
}
out = PLUGIN / "programs" / "adversarial_findings.json"
out.write_text(json.dumps(doc, indent=2) + "\n", encoding="utf-8")
print(f"wrote {out} with {len(forging)} forging pair(s)")
for a, t in forging:
    print(f"  {a:24} {t}")
