#!/usr/bin/env python3
"""step_pnr must resolve the design's SDC from the tree's SHARED contract.

The defect: `step_pnr` globbed `constraints/*.sdc` (project ROOT) and
`phase2/stage2/constraints/*.sdc` to decide whether the design staged an SDC.
Neither is the ground truth. `sdc_constraints.collect_sdc_files` — the shared
accessor used by every OTHER staged-SDC consumer in the same file — defines it
as `input/constraints/*.sdc` then `input/reference_flow/**/*.sdc`, and
documents `extra_dirs` as appending AFTER that ground truth.

Measured on the authoring host: the project-root probe matched on 0 of 10
projects, while `phase2/stage2/constraints/<top>.sdc` matched because
`step_canonicalize_artefacts` writes the runner's OWN auto-SDC there — so the
miss laundered a fabricated SDC into "design-staged" on every later run, and a
design's real `create_clock -name core_clock` never reached PnR or STA.

BIDIRECTIONAL NEGATIVE CONTROL: the first two tests FAIL against the pre-fix
code (the input-dir SDC is not resolved; the auto-SDC is emitted instead). The
remaining tests pass BOTH ways — they are the guards that pin the blast radius:
the legacy directories still resolve, and honoring a staged SDC must not leave
the I/O boundary untimed.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import phase3_one_shot_runner as p3  # noqa: E402
import sdc_constraints as _sdc  # noqa: E402


def _mkproj(tmp_path: Path, where: str, text: str) -> Path:
    proj = tmp_path / "proj"
    d = proj / where
    d.mkdir(parents=True, exist_ok=True)
    (d / "clock.sdc").write_text(text)
    return proj


DESIGN_SDC = (
    "# design-authored\n"
    "set_units -time ns\n"
    "create_clock [get_ports clk] -name core_clock -period 10.0\n"
)


AUTO_SDC = (
    "# Auto-generated minimal SDC for silicon top "
    "(no constraints/*.sdc supplied; clk_period_ns=10.0 clk_port=clk)\n"
    "create_clock -name clk -period 10.0 [get_ports clk]\n"
)

SDC_GEN_OUTPUT = (
    "# Auto-generated by sdc_gen.py (Wave 72/73)\n"
    "# Top entity: top\n"
    "# Clock: clk period=10 ns\n"
    "create_clock -name clk -period 10 [get_ports clk]\n"
)


def _prefix_probe(project: Path):
    """The EXACT probe step_pnr used before this fix, kept verbatim so the
    defect is characterised by behaviour and not only by a missing symbol."""
    return (
        next(iter(sorted(project.glob("constraints/*.sdc"))), None)
        or next(iter(sorted((project / "phase2/stage2/constraints").glob("*.sdc")
                            if (project / "phase2/stage2/constraints").is_dir()
                            else [])), None)
    )


# ---------------------------------------------------------------- the defect

def test_input_constraints_sdc_is_resolved(tmp_path):
    """FAILS PRE-FIX (no such resolver). The canonical input location resolves."""
    proj = _mkproj(tmp_path, "input/constraints", DESIGN_SDC)
    found = p3._resolve_staged_silicon_sdc(proj)
    assert found is not None, "the design's staged SDC was not resolved at all"
    assert found.parts[-3:] == ("input", "constraints", "clock.sdc")
    # ...and the pre-fix probe demonstrably could NOT find it. This is the
    # behavioural half of the negative control: same fixture, old logic, miss.
    assert _prefix_probe(proj) is None


def test_input_constraints_outranks_the_flows_own_output(tmp_path):
    """FAILS PRE-FIX. The ground truth must OUTRANK the flow's own output dir.

    The laundering case: `step_canonicalize_artefacts` writes the runner's own
    auto-SDC into phase2/stage2/constraints, and the pre-fix probe preferred it
    over the design's real file.
    """
    proj = _mkproj(tmp_path, "input/constraints", DESIGN_SDC)
    stage2 = proj / "phase2/stage2/constraints"
    stage2.mkdir(parents=True, exist_ok=True)
    (stage2 / "top.sdc").write_text(AUTO_SDC)

    found = p3._resolve_staged_silicon_sdc(proj)
    assert found is not None
    assert "input" in found.parts, (
        "the flow's OWN auto-SDC outranked the design's staged SDC — the "
        "fabricated constraint is being laundered as design-staged")
    assert "core_clock" in found.read_text()

    # Behavioural negative control: the pre-fix probe picked the runner's own
    # fabrication, and its first line says so in the runner's own words.
    stale = _prefix_probe(proj)
    assert stale is not None and stale.name == "top.sdc"
    assert "no constraints/*.sdc supplied" in stale.read_text()
    assert "core_clock" not in stale.read_text()


@pytest.mark.parametrize("generated", [AUTO_SDC, SDC_GEN_OUTPUT])
def test_a_prior_flow_generated_sdc_is_not_design_staged(tmp_path, generated):
    """The flow's output cannot become higher-authority input on a rerun.

    Both producer banners exist in real run trees.  In particular, an old
    auto-SDC may name ``clk`` while the current top exposes ``i_clk``; sourcing
    it produces OpenSTA's ``No paths found`` and a false-looking 0.00 slack.
    """
    proj = _mkproj(tmp_path, "phase2/stage2/constraints", generated)
    assert p3._resolve_staged_silicon_sdc(proj) is None


def test_a_hand_authored_legacy_sdc_still_resolves(tmp_path):
    """Producer attribution, not directory retirement, bounds the fix."""
    proj = _mkproj(tmp_path, "phase2/stage2/constraints", DESIGN_SDC)
    found = p3._resolve_staged_silicon_sdc(proj)
    assert found is not None and found.read_text() == DESIGN_SDC


# ------------------------------------------------- guards (pass BOTH ways)

@pytest.mark.parametrize("legacy", ["constraints",
                                    "phase2/stage2/constraints"])
def test_legacy_dirs_still_resolve_when_they_are_the_only_source(tmp_path,
                                                                 legacy):
    """Blast radius: a project that resolved an SDC before still resolves it."""
    proj = _mkproj(tmp_path, legacy, DESIGN_SDC)
    found = next(iter(_sdc.collect_sdc_files(
        proj, extra_dirs=[proj / "constraints",
                          proj / "phase2/stage2/constraints"])), None)
    assert found is not None, f"legacy dir {legacy} stopped resolving"


def test_io_parity_supplies_absent_delays_against_the_designs_own_clock(tmp_path):
    """Honoring the staged SDC must not leave the I/O boundary untimed."""
    proj = _mkproj(tmp_path, "input/constraints", DESIGN_SDC)
    out, info = p3._ensure_staged_sdc_io_delay(DESIGN_SDC, proj)
    assert "set_input_delay" in out and "set_output_delay" in out, (
        "a staged SDC declaring only create_clock left every primary I/O "
        "UNCONSTRAINED — a violation would vanish by subtraction")
    # referenced to the DESIGN's clock object, not an invented one
    assert "-clock core_clock" in out
    assert info["clock_name"] == "core_clock"
    assert "clk]" not in out.split("I/O-delay parity")[1].replace(
        "[all_inputs]", "").replace("[all_outputs]", "")


def test_io_parity_never_overrides_a_design_declared_delay(tmp_path):
    """A design that declares its own I/O delays is left byte-identical."""
    proj = _mkproj(tmp_path, "input/constraints", DESIGN_SDC)
    declared = (DESIGN_SDC
                + "set_input_delay 1.5 -clock core_clock [all_inputs]\n"
                + "set_output_delay 1.5 -clock core_clock [all_outputs]\n")
    out, info = p3._ensure_staged_sdc_io_delay(declared, proj)
    assert out == declared, "a design-declared I/O delay was overridden"
    assert info["added_input_delay"] is None
    assert info["added_output_delay"] is None


def test_io_parity_fabricates_nothing_without_a_resolvable_clock(tmp_path):
    """No create_clock anywhere ⇒ no invented clock reference (§4.05)."""
    proj = tmp_path / "bare"
    proj.mkdir()
    out, info = p3._ensure_staged_sdc_io_delay("# nothing here\n", proj)
    assert out == "# nothing here\n"
    assert info["added_input_delay"] is None
    assert info["clock_name"] is None
