"""v1.0.47 — ORGANIC #678: deterministic Shape-B sample-export preserves the
runner's reset/clock variant-alias wrapper (gate↔scorer discrepancy).

PATTERN: the runner fires `reset_clock_variant_alias` (#518) — it renames the
TB-facing top to `<top>__rcvar_inner` IN PLACE and appends a wrapper `<top>`
exposing the canonical reset/clock spelling, wired 1:1. BOTH modules live in ONE
RTL file, and only the COMPLETE file PASSES the hidden TB (which binds the
canonical port). The prose-only Shape-B export hand-copied just the un-wrapped
inner core → standalone compile (no TB) passes the inner → gate GREEN, but the
host scorer binds the hidden TB against the canonical port → COMPILE-ERROR. The
deterministic fix never reached the scorer (gate-as-sole-emit-path failure).

FIX: `programs/shape_b_sample_export.py` is the SOLE emit path (analogous to
`gates_atomic.py` for Shape C). It copies the runner's COMPLETE TB-facing-top
RTL FILE verbatim (preserving every wrapper + inner) and a post-export guard
(standalone iverilog compile + variant-alias completeness) REJECTS any export
missing a wrapper or a wrapper's inner.

POSITIVE — a runner work-dir RTL holding `<top>__rcvar_inner` + wrapper `<top>`
exports the COMPLETE file, standalone-compiles, wrapper present.

§4.05 NEGATIVE no-leak:
  * a single-module design with no alias wrapper still exports correctly;
  * an export MISSING the wrapper is REJECTED by the guard;
  * a `*__rcvar_inner` WITHOUT its wrapper fails the guard.

Fixtures embed the real repro shape: reset_n inner + rst_n wrapper.
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

import pytest

PLUGIN = Path(__file__).resolve().parent.parent.parent
PROGRAMS = PLUGIN / "programs"
if str(PROGRAMS) not in sys.path:
    sys.path.insert(0, str(PROGRAMS))

import shape_b_sample_export as sbx  # noqa: E402
import reset_clock_variant_alias as _rcv  # noqa: E402


_HAVE_IVERILOG = shutil.which("iverilog") is not None


def _port_names(txt: str, module: str) -> set:
    """Set of `module`'s port names — used to assert a PURE reorder (#707):
    the exported sample reorders ports to the genre convention, so it is no
    longer byte-identical to the source, but the port SET (and every module)
    must be preserved — nothing added / dropped / renamed."""
    return {n for _d, _w, n in _rcv.parse_module_ports(txt, module)}


# ── the real repro shape: reset_n inner + rst_n wrapper (one file) ──────────
# This is exactly what step_reset_clock_variant_aliases emits: the leaf renamed
# to `<leaf>__rcvar_inner` (ports use the prompt spelling `reset_n`) plus a
# wrapper taking the leaf name (`<leaf>`) exposing canonical `rst_n`, wired 1:1.
def _rcvar_complete_file(leaf: str) -> str:
    inner = f"{leaf}__rcvar_inner"
    return f"""\
// {leaf}__rcvar_inner — original core (prompt spelling reset_n)
module {inner} (
    input  wire clk,
    input  wire reset_n,
    input  wire [7:0] din,
    output reg  [7:0] dout
);
    always @(posedge clk or negedge reset_n)
        if (!reset_n) dout <= 8'd0;
        else          dout <= din;
endmodule

// {leaf} — reset/clock NAME-VARIANT alias wrapper for `{inner}`
// Generated by reset_clock_variant_alias.py (#518).
module {leaf} (
    input wire clk,
    input wire rst_n,
    input wire [7:0] din,
    output wire [7:0] dout
);
    {inner} u_{inner} (
        .clk(clk),
        .reset_n(rst_n),
        .din(din),
        .dout(dout)
    );
endmodule
"""


# only the inner (the prose-export bug: wrapper DROPPED)
def _inner_only_file(leaf: str) -> str:
    inner = f"{leaf}__rcvar_inner"
    return f"""\
module {inner} (
    input  wire clk,
    input  wire reset_n,
    input  wire [7:0] din,
    output reg  [7:0] dout
);
    always @(posedge clk or negedge reset_n)
        if (!reset_n) dout <= 8'd0;
        else          dout <= din;
endmodule
"""


# only the wrapper (instantiates an inner that is NOT shipped)
def _wrapper_only_file(leaf: str) -> str:
    inner = f"{leaf}__rcvar_inner"
    return f"""\
module {leaf} (
    input wire clk,
    input wire rst_n,
    input wire [7:0] din,
    output wire [7:0] dout
);
    {inner} u_{inner} (
        .clk(clk),
        .reset_n(rst_n),
        .din(din),
        .dout(dout)
    );
endmodule
"""


# a plain single-module design with no alias wrapper at all
def _single_module_file(leaf: str) -> str:
    return f"""\
module {leaf} (
    input  wire [7:0] a,
    input  wire [7:0] b,
    output wire [7:0] y
);
    assign y = a + b;
endmodule
"""


def _mk_rtl_dir(tmp_path: Path, leaf: str, content: str,
                fname: str | None = None) -> Path:
    rtl = tmp_path / "phase2" / "stage1" / "rtl"
    rtl.mkdir(parents=True, exist_ok=True)
    (rtl / (fname or f"{leaf}.v")).write_text(content)
    return rtl


# ── POSITIVE ────────────────────────────────────────────────────────────────
def test_positive_rcvar_wrapper_exported_complete(tmp_path: Path):
    """A runner work-dir RTL holding `<top>__rcvar_inner` + wrapper `<top>`
    exports the COMPLETE file; standalone-compiles; wrapper present."""
    leaf = "data_reg"
    rtl = _mk_rtl_dir(tmp_path, leaf, _rcvar_complete_file(leaf))
    samples = tmp_path / "samples"

    res = sbx.export(rtl, leaf, samples, spec_module=leaf)
    assert res["verdict"] == "PASS", res
    # TB-facing top is the WRAPPER (canonical rst_n), not the inner.
    assert res["tb_facing_top"] == leaf

    out = samples / f"{leaf}.v"
    assert out.is_file()
    txt = out.read_text()
    # COMPLETE file: BOTH the wrapper AND the inner core are present.
    assert f"module {leaf}__rcvar_inner" in txt
    assert f"module {leaf}\n" in txt or f"module {leaf} (" in txt
    # The canonical TB-facing port survives (rst_n) AND the inner spelling.
    assert "rst_n" in txt and "reset_n" in txt
    # #707 — the wrapper's ports are reordered to the genre convention (no longer
    # byte-identical), but it is a PURE reorder: the COMPLETE file is preserved
    # (both modules present, checked above) and the wrapper's port SET is intact.
    src = _rcvar_complete_file(leaf)
    assert _port_names(txt, leaf) == _port_names(src, leaf)
    assert f"module {leaf}__rcvar_inner" in txt  # inner core not mutated/dropped


def test_positive_guard_passes_on_complete_file(tmp_path: Path):
    leaf = "data_reg"
    out = tmp_path / "samples" / f"{leaf}.v"
    out.parent.mkdir(parents=True)
    out.write_text(_rcvar_complete_file(leaf))
    ok, problems = sbx.guard_export(out)
    # No blocking problems (NOTEs allowed when iverilog is absent).
    blocking = [p for p in problems if not p.startswith("NOTE:")]
    assert ok and not blocking, problems


# ── §4.05 NEGATIVE no-leak ────────────────────────────────────────────────
def test_negative_single_module_no_wrapper_still_exports(tmp_path: Path):
    """A single-module design with NO alias wrapper still exports correctly —
    the fix must not regress the common case."""
    leaf = "add8"
    rtl = _mk_rtl_dir(tmp_path, leaf, _single_module_file(leaf))
    samples = tmp_path / "samples"
    res = sbx.export(rtl, leaf, samples, spec_module=leaf)
    assert res["verdict"] == "PASS", res
    assert res["tb_facing_top"] == leaf
    out = samples / f"{leaf}.v"
    assert out.is_file()
    # #707 — ports reordered to the genre convention (no longer byte-identical),
    # but a PURE reorder: same module, same port SET (nothing added/dropped).
    txt = out.read_text()
    assert f"module {leaf}" in txt
    assert _port_names(txt, leaf) == _port_names(_single_module_file(leaf), leaf)


def test_negative_export_missing_wrapper_is_rejected(tmp_path: Path):
    """An export that shipped ONLY the inner core (wrapper DROPPED) — the exact
    prose-export bug — is REJECTED by the guard, and no broken sample is left."""
    leaf = "data_reg"
    # Simulate the prose bug directly: a samples/<leaf>.v with only the inner.
    out = tmp_path / "samples" / f"{leaf}.v"
    out.parent.mkdir(parents=True)
    out.write_text(_inner_only_file(leaf))
    ok, problems = sbx.guard_export(out)
    assert not ok
    assert any("DROPPED" in p or "alias wrapper" in p for p in problems), problems


def test_negative_inner_without_wrapper_via_export_rejected(tmp_path: Path):
    """End-to-end: when the runner's rtl/ somehow holds ONLY the inner module
    (no wrapper), export REJECTS it and removes the half-shipped sample so the
    scorer reports honest no_sample rather than a false-green compile error."""
    leaf = "data_reg"
    inner = f"{leaf}__rcvar_inner"
    rtl = _mk_rtl_dir(tmp_path, leaf, _inner_only_file(leaf),
                      fname=f"{inner}.v")
    samples = tmp_path / "samples"
    # spec_module/leaf point at the wrapper name, which is absent → resolver
    # falls to the single instantiation-root (the inner) and exports it; the
    # guard then rejects (inner without its wrapper).
    res = sbx.export(rtl, leaf, samples, spec_module=leaf)
    assert res["verdict"] == "FAIL", res
    assert res["reason"] == "guard_rejected", res
    # the broken sample must NOT be left on disk.
    assert not (samples / f"{leaf}.v").is_file()


def test_negative_wrapper_without_inner_fails_guard(tmp_path: Path):
    """A `*__rcvar_inner`-instantiating wrapper shipped WITHOUT its inner fails
    the guard (scorer would hit 'Unknown module type: <inner>')."""
    leaf = "data_reg"
    out = tmp_path / "samples" / f"{leaf}.v"
    out.parent.mkdir(parents=True)
    out.write_text(_wrapper_only_file(leaf))
    ok, problems = sbx.guard_export(out)
    assert not ok
    assert any("Unknown module type" in p or "NOT in the exported file" in p
               for p in problems), problems


@pytest.mark.skipif(not _HAVE_IVERILOG, reason="iverilog not installed")
def test_standalone_compile_distinguishes_complete_from_dropped(tmp_path: Path):
    """With iverilog present, the COMPLETE file compiles standalone but the
    wrapper-without-inner file does NOT (the real silicon signature)."""
    leaf = "data_reg"
    good = tmp_path / "good.v"
    good.write_text(_rcvar_complete_file(leaf))
    ok_good, _ = sbx.guard_export(good)
    assert ok_good

    bad = tmp_path / "bad.v"
    bad.write_text(_wrapper_only_file(leaf))
    ok_bad, problems = sbx.guard_export(bad)
    assert not ok_bad, problems


# ── resolver selection-rule unit checks ─────────────────────────────────────
def test_resolver_prefers_wrapper_over_inner(tmp_path: Path):
    leaf = "data_reg"
    rtl = _mk_rtl_dir(tmp_path, leaf, _rcvar_complete_file(leaf))
    src, top, note = sbx.resolve_tb_facing_file(rtl, leaf, spec_module=leaf)
    assert top == leaf  # the wrapper, NOT data_reg__rcvar_inner
    assert "variant-alias wrapper" in note


def test_resolver_falls_to_spec_module_when_no_alias(tmp_path: Path):
    leaf = "dirtypo"          # dir leaf differs from the spec module name
    spec = "adder8"
    rtl = _mk_rtl_dir(tmp_path, leaf, _single_module_file(spec),
                      fname=f"{spec}.v")
    src, top, note = sbx.resolve_tb_facing_file(rtl, leaf, spec_module=spec)
    assert top == spec
