"""CLOCK PORT MUST BE RESOLVED BY CONNECTIVITY, NOT BY NAME (chip/PDK-AGNOSTIC).

PROVE-FIRST floor (measured 2026-07-25 on a real 155k-cell campaign design,
sky130A, against its own 20 MB post-synth netlist):

  * The design declares TWO clock-looking top ports. The first is an unused
    alternate/decoy pin; the second is the real core clock that every flop
    is connected to.
  * SHIPPED name-based resolver:
        _v1_6_623_clock_port_in_netlist_text(...) -> "<decoy>"
    CONNECTIVITY resolver:
        _clock_port_by_sequential_fanin(...)      -> ("<real>", 14625, 14625)
    i.e. 14625 of 14625 clock-pin connections (100%) go to the REAL port and
    ZERO go to the decoy the shipped resolver picked.
  * Consequence measured in the live PnR log:
        [INFO  CTS-0007] Net "<decoy>" found for clock "<decoy>".
        [WARNING CTS-0041] Net "<decoy>" has 0 sinks. Skipping...
        [INFO  CTS-0008] TritonCTS found 0 clock nets.
        [WARNING CTS-0082] No valid clock nets in the design.
        [INFO  CTS-0500] Runtime: 1.15s
        [INFO  RSZ-0033] No hold violations found.
    CTS built NO clock tree in 1.15 s on a 155k-cell synchronous design, and
    the very next line reports hold clean. That "clean" is VACUOUS: there are
    no hold violations because no real path is constrained, not because the
    design is hold-correct. The design would route and sign off having timed
    nothing.
  * #623 already established the right doctrine ("keyed on the netlist's own
    clock port") but implemented it as a NAME regex over the port list, so
    declaration order decides. This closes that gap: the netlist states
    unambiguously which port reaches sequential clock pins.

Fix under test: `_clock_port_by_sequential_fanin` — pure string analysis of
the post-synth netlist, ranked BEFORE the name-based chain. Returns None when
the netlist carries no clock-pin connections or none of them trace to a top
input, so every existing resolution path is preserved unchanged.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

import phase3_one_shot_runner as p3


_DECL_RE = re.compile(r"^\s*input\s+(?:wire\s+)?(?:\[[^\]]*\]\s*)?(\w+)\s*;",
                      re.MULTILINE)


def _netlist(ports_decl: str, insts: str, top: str = "dut") -> str:
    """A yosys-shaped flat gate netlist: header port list, then the
    `input x; wire x;` declaration pairs, then instances."""
    header = ", ".join(_DECL_RE.findall(ports_decl))
    return (f"/* Generated by a synthesis tool */\n"
            f"module {top}({header});\n{ports_decl}\n{insts}\nendmodule\n")


# A decoy clock port declared BEFORE the real core clock -- the exact shape
# that defeated the name-based resolver.
DECOY_PORTS = """  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input core_clk_i;
  wire core_clk_i;
"""


def _dffs(net: str, n: int, cell: str = "scl__dfxtp_1") -> str:
    return "\n".join(
        f"  {cell} _inst{i}_ (\n    .CLK({net}),\n    .D(d{i}),\n"
        f"    .Q(q{i})\n  );" for i in range(n))


# ---------------------------------------------------------------------------
# THE BUG.
# ---------------------------------------------------------------------------
def test_decoy_clock_port_declared_first_loses_to_the_real_one():
    """The exact shape that produced a vacuous sign-off: a decoy clock port
    declared BEFORE the real one, with every flop on the real one."""
    nl = _netlist(DECOY_PORTS, _dffs("core_clk_i", 40))
    got = p3._clock_port_by_sequential_fanin(nl, top="dut")
    assert got is not None
    port, hits, total = got
    assert port == "core_clk_i"
    assert hits == 40 and total == 40

    # And witness the shipped name-based behaviour on the SAME netlist:
    # it picks the decoy, which is what built no clock tree.
    assert p3._v1_6_623_clock_port_in_netlist_text(nl, top="dut") == "clk"


def test_top_input_ports_are_read_in_declaration_order():
    nl = _netlist(DECOY_PORTS, _dffs("core_clk_i", 3))
    assert p3._netlist_top_input_ports(nl, top="dut") == [
        "clk", "rst_n", "core_clk_i"]


@pytest.mark.parametrize("pin", ["CLK", "CK", "GCLK", "CLKN", "CLOCK"])
def test_standard_clock_pin_names_are_all_recognised(pin):
    """chip-AGNOSTIC: keyed on standard sequential clock PIN names."""
    insts = (f"  scl__dff_1 _i0_ (\n    .{pin}(core_clk_i),\n"
             f"    .D(d0),\n    .Q(q0)\n  );")
    nl = _netlist(DECOY_PORTS, insts)
    got = p3._clock_port_by_sequential_fanin(nl, top="dut")
    assert got is not None and got[0] == "core_clk_i"


def test_dominant_domain_wins_on_a_multi_clock_netlist():
    insts = _dffs("core_clk_i", 90) + "\n" + _dffs("clk", 10)
    nl = _netlist(DECOY_PORTS, insts)
    port, hits, total = p3._clock_port_by_sequential_fanin(nl, top="dut")
    assert port == "core_clk_i"
    assert hits == 90 and total == 100


# ---------------------------------------------------------------------------
# FALL-THROUGH: never make things worse than the existing chain.
# ---------------------------------------------------------------------------
def test_combinational_netlist_falls_through():
    """No sequential cells -> no opinion; the existing chain must be used."""
    nl = _netlist(DECOY_PORTS, "  scl__and2_1 _i0_ (.A(a), .B(b), .X(y));")
    assert p3._clock_port_by_sequential_fanin(nl, top="dut") is None


def test_internally_generated_clock_falls_through():
    """When flops are clocked by an INTERNAL net (gated/divided clock) rather
    than a top port, this resolver must abstain rather than guess."""
    nl = _netlist(DECOY_PORTS, _dffs("gated_clk_net", 25))
    assert p3._clock_port_by_sequential_fanin(nl, top="dut") is None


def test_empty_or_unparseable_text_falls_through():
    assert p3._clock_port_by_sequential_fanin("", top="dut") is None
    assert p3._clock_port_by_sequential_fanin("not a netlist", top="dut") is None


def test_escaped_net_names_are_normalised():
    insts = ("  scl__dfxtp_1 _i0_ (\n    .CLK(\\\\core_clk_i ),\n"
             "    .D(d0),\n    .Q(q0)\n  );")
    nl = _netlist(DECOY_PORTS, insts)
    got = p3._clock_port_by_sequential_fanin(nl, top="dut")
    # Either resolves to the port or abstains -- it must never crash or
    # return a name carrying the escape character.
    if got is not None:
        assert not got[0].startswith("\\\\")


def test_resolver_is_pure_and_deterministic():
    nl = _netlist(DECOY_PORTS, _dffs("core_clk_i", 12))
    a = p3._clock_port_by_sequential_fanin(nl, top="dut")
    b = p3._clock_port_by_sequential_fanin(nl, top="dut")
    assert a == b
    assert nl == _netlist(DECOY_PORTS, _dffs("core_clk_i", 12))


def test_new_code_is_chip_agnostic():
    src = Path(p3.__file__).read_text()
    start = src.index("_CLOCK_PIN_TOKENS =")
    end = src.index("def _v1_6_623_extract_clock_port_from_netlist")
    body = src[start:end]
    banned = re.compile(
        r"\b(sky130\w*|gf180\w*|nangate\w*|freepdk\w*|asap7|skywater|"
        r"globalfoundries|tsmc|wb_clk_i|edge_llm\w*|wishbone)\b",
        re.IGNORECASE)
    hit = banned.search(body)
    assert hit is None, f"chip-specific literal: {hit.group(0)!r}"
