#!/usr/bin/env python3
"""Wave 77 — INDEX.md freshness CI.

Re-runs `tools/gen_programs_index.py --check` and FAILs if the
committed INDEX.md drifts from what the generator would produce.

This is the lock that keeps the auto-generated catalog from rotting:
any new gate, renamed gate, or _APPLICABLE_CLASSES change forces the
author to regenerate the INDEX before the PR can land.

Skip behaviour: when running from the opensource_repo/ mirror tree,
the generator itself may not be present — skip rather than FAIL since
the mirror is a derived artefact (the source-of-truth tree always has
the generator + an up-to-date INDEX).
"""
from __future__ import annotations
import subprocess
import sys
from pathlib import Path
import pytest

from _plugin_tree import plugin_path, repo_path_or_missing

# flow #486: INDEX.md is a SHIPPED in-plugin artefact (resolve via the
# plugin-root resolver); the generator tools/gen_programs_index.py is a
# repo-root-only tool NOT shipped in the flattened cache (resolve to a
# non-existent path there so the existing `if not GEN.exists(): skip`
# branch fires — no IndexError from a hard-coded parents[5]).
GEN = repo_path_or_missing("tools", "gen_programs_index.py")
INDEX = plugin_path("programs", "INDEX.md")


def test_index_md_exists():
    assert INDEX.exists(), (
        f"INDEX.md missing at {INDEX}; run "
        f"`python3 tools/gen_programs_index.py`"
    )


def test_index_carries_auto_generated_marker():
    """Belt-and-braces: a hand-edited INDEX would lose the marker
    and break this test even if the content happened to match."""
    text = INDEX.read_text()
    assert "AUTO-GENERATED by tools/gen_programs_index.py" in text


def test_index_is_fresh():
    if not GEN.exists():
        pytest.skip(
            f"generator not present at {GEN} (mirror tree); freshness "
            f"is enforced in the source-of-truth tree only"
        )
    r = subprocess.run(
        [sys.executable, str(GEN), "--check"],
        capture_output=True, text=True, timeout=60,
    )
    assert r.returncode == 0, (
        f"INDEX.md is stale — re-run `python3 tools/gen_programs_index.py`."
        f"\nstderr:\n{r.stderr}\nstdout:\n{r.stdout}"
    )


def test_index_lists_every_non_helper_program():
    """Sanity: every *.py under programs/ that isn't a helper / shim
    must appear in the alphabetical listing. Catches a future
    generator regression that forgets a row."""
    progs = plugin_path("programs")
    text = INDEX.read_text()
    missing = []
    for p in sorted(progs.glob("*.py")):
        name = p.stem
        if name.startswith("_"):
            continue
        head = p.read_text(errors="replace")[:2000]
        if "DEPRECATION SHIM" in head.upper():
            continue
        if f"`{name}`" not in text:
            missing.append(name)
    assert not missing, (
        f"INDEX.md missing {len(missing)} program(s): {missing[:10]}"
        f"{'...' if len(missing) > 10 else ''}"
    )


# --- the title rule: an em-dash is not always a name separator

def _title_fn():
    """Import `_title` out of the generator, which lives in the repo's tools/
    rather than in the plugin, so it is skipped where only the plugin ships."""
    if GEN is None or not Path(GEN).is_file():
        pytest.skip("tools/gen_programs_index.py is not in this checkout")
    import importlib.util
    spec = importlib.util.spec_from_file_location("gpi", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod._title


def test_a_punctuation_dash_does_not_eat_the_description():
    """INDEX.md is how a reader navigates 1003 programs, and four rows told them
    nothing.

    The rule was an unconditional positional split on the first em-dash, which
    assumes every docstring's first line is `<module> — <description>`. 816 of
    them are. The ones that use an em-dash as ORDINARY PUNCTUATION lost their
    description to it:

        "A committed pointer to a file that does not exist — anywhere."
             indexed as:  anywhere.

    Found while regenerating a stale INDEX.md, not by anything failing.
    """
    title = _title_fn()
    assert title("A committed pointer to a file that does not exist — anywhere.",
                 "tracked_symlink_target_present_check") == \
        "A committed pointer to a file that does not exist — anywhere."


def test_a_module_name_prefix_is_still_dropped():
    """The 816-case majority, pinned — the fix must not stop stripping the name
    it was written to strip."""
    title = _title_fn()
    assert title("arbiter_starvation_check.py — BACKLOG-v11 P0.6.",
                 "arbiter_starvation_check") == "BACKLOG-v11 P0.6."
    assert title("programs/acceptance_evidence_in_fix_comment_check.py — v0.2.97",
                 "acceptance_evidence_in_fix_comment_check") == "v0.2.97"


def test_a_version_prefix_is_still_dropped():
    """The third branch, and the reason the rule is not simply "keep prose".

    `phase1_post_process` leads with a version, not its own name, and the
    description is genuinely after the dash. A rule that only recognised the
    module name would index it as "v0.1.51 — phase1 output post-processor.",
    which is worse than what it replaced.
    """
    title = _title_fn()
    assert title("v0.1.51 — phase1 output post-processor.",
                 "phase1_post_process") == "phase1 output post-processor."
