"""tests/test_analog_a1_a4_block_coverage_and_substance.py

Behavioural discriminators for three defects in the A1-A4 deterministic
gates, plus direction-1 guards for every carve-out that must NOT change.

DEFECT 1 — partial block coverage absorbed into PASS (A1/d5, A2/d5, A4/d2,
           and the same shape in A3).
  The project-mode tail of each gate was:

      if findings:                        -> FAIL
      if missing_seen and blocks_pass==0: -> VACUOUS_PASS
      return emit_pass(...)               # <- mixed PASS + missing

  so a run where the upstream skill produced an artefact for 1 of N
  declared blocks exited 0 with verdict PASS. The flow declaration cannot
  compensate: each A-step declares ONE glob (`phase2/analog/*/topology.md`)
  and `flow_compliance_check` satisfies a glob entry on its FIRST match, so
  per-block coverage is knowable only inside the gate.

DEFECT 2 — A3 certified an empty `.subckt` shell.
  `analog_a3_netlist_gen_check`'s only substance rules were "size >= 200B"
  and "contains .subckt". A placeholder padded with header comments clears
  both. `analog_netlist_pdk_check` (A3's gate of record) cannot catch it
  either: its rules iterate DEVICE cards, so zero devices == zero findings
  == NETLIST_PDK_OK.

DEFECT 3 — the A3 gates never read the flow-declared path.
  `flow/phase1_phase2_phase3.yaml` declares A3's required_output as
  `phase2/analog/*/*.sp` (and A1's as `phase1/analog/*/spec.json`), matching
  `_path_layout.phase2_analog_block_dir` / `phase1_analog_block_dir` and what
  `migrate_to_layout_p.py` produces. Every A1-A4 gate hardcoded
  `phase3/analog/` (where the analog RUNNER writes), so a project laid out
  exactly as its own flow declares self-skipped and measured nothing.

Run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 python3 -m pytest tests/<this file>
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

PROGRAMS = Path(__file__).resolve().parent.parent
PLUGIN = PROGRAMS.parent
FLOW_YAML = PLUGIN / "flow" / "phase1_phase2_phase3.yaml"

A1 = PROGRAMS / "analog_a1_spec_extract_check.py"
A2 = PROGRAMS / "analog_a2_topology_select_check.py"
A3 = PROGRAMS / "analog_a3_netlist_gen_check.py"
A4 = PROGRAMS / "analog_a4_corner_sweep_check.py"
PDK = PROGRAMS / "analog_netlist_pdk_check.py"

# (gate program, canonical artefact filename, flow-declared phase root)
GATES = [
    pytest.param(A1, "spec.json", "phase1/analog", id="A1"),
    pytest.param(A2, "topology.md", "phase2/analog", id="A2"),
    pytest.param(A3, "{block}.sp", "phase2/analog", id="A3"),
    pytest.param(A4, "corner_results.json", "phase2/analog", id="A4"),
]

_REAL_TOPOLOGY = (
    "# Topology\n\n"
    "Two-stage differential amplifier: an NMOS differential pair with a PMOS "
    "current mirror load, a common-source output stage, and Miller feedback "
    "compensation. Tail bias comes from a widlar reference. The dominant pole "
    "sits at the first stage; the right-half-plane zero is cancelled by a "
    "nulling resistor sized against the load capacitor.\n"
)
_REAL_NETLIST = (
    "* block netlist\n"
    ".subckt {block} VDD VSS VOUT VREF EN\n"
    + "M1 net1 VREF VSS VSS nmos w=2u l=0.18u\n" * 6
    + ".ends {block}\n.end\n"
)
# >200 bytes, has .subckt, has ZERO device cards: the placeholder shape that
# cleared every A3 rule before A3_NETLIST_NO_DEVICES existed.
_EMPTY_SHELL = (
    "* {block} — SPICE netlist\n"
    "* Generated by the analog-netlist-gen skill.\n"
    "* PDK model library include:\n"
    '.include "design.ngspice"\n'
    "*\n"
    "* Interface: vdd (supply), vss (ground), vin (input), vout (output)\n"
    "*\n"
    ".subckt {block} vdd vss vin vout\n"
    "* --- device instantiations go here ---\n"
    ".ends {block}\n"
    ".end\n"
)
_REAL_CORNERS = {
    "_provenance": "real_ngspice",
    # `_provenance` is true of the SIMULATOR and says nothing about the
    # SUBJECT. Six of this file's coverage fixtures assert a certified A4, and
    # an artefact that declares simulated corners while refusing to say what
    # circuit produced them no longer certifies one — so the record of WHAT was
    # simulated sits beside the netlist `_artefact` already writes. Coverage,
    # not disclosure, stays the property under test.
    "design_content": "structure_and_geometry",
    "best_corner": {"name": "tt_27"},
    "corners": [
        {"name": "tt_27", "simulator_run": True, "vout_v": 1.2},
        {"name": "ss_125", "simulator_run": True, "vout_v": 1.21},
        {"name": "ff_m40", "simulator_run": True, "vout_v": 1.19},
    ],
    "spec_results": [
        {"name": "vout", "status": "PASS", "target": 1.2,
         "tolerance_pct": 0.05},
    ],
}


# ── fixture helpers ────────────────────────────────────────────────────────

def _block_list(project: Path, blocks: list, root: str = "phase3/analog"
                ) -> None:
    d = project / root
    d.mkdir(parents=True, exist_ok=True)
    (d / "analog_block_list.json").write_text(json.dumps({"blocks": blocks}))


def _artefact(project: Path, block: str, filename: str,
              root: str = "phase3/analog") -> None:
    """Write a substantive artefact for `block` under `root`."""
    name = filename.format(block=block)
    d = project / root / block
    d.mkdir(parents=True, exist_ok=True)
    if name == "spec.json":
        (d / name).write_text(json.dumps(
            {"specs": [{"name": "vout", "typ": 1.2, "min": 1.1,
                        "max": 1.3}]}))
    elif name == "topology.md":
        (d / name).write_text(_REAL_TOPOLOGY)
    elif name == "corner_results.json":
        (d / name).write_text(json.dumps(_REAL_CORNERS))
        # A4's declared upstream input. A block that has corner results also
        # has the netlist those corners were run on; without it the A4 gate's
        # A4_NETLIST_ABSENT rule (correctly) declines to certify the sweep,
        # which is not the property these coverage fixtures are exercising.
        (d / f"{block}.sp").write_text(_REAL_NETLIST.format(block=block))
    elif name.endswith(".sp"):
        (d / name).write_text(_REAL_NETLIST.format(block=block))
        _netlist_record(d, block)
    else:                                       # pragma: no cover
        raise AssertionError(f"unhandled artefact {name}")


def _netlist_record(d: Path, block: str) -> None:
    """The producer's record BESIDE the netlist, for the same reason
    `_REAL_CORNERS` carries `design_content`: several of this file's coverage
    fixtures assert a CERTIFIED A3, and a deck that refuses to say what circuit
    is in it no longer certifies one. Coverage, not disclosure, stays the
    property under test — so the deck discloses, and the fixtures keep
    measuring what they were written to measure.

    A fixture that asserted a certified step on a SILENT artefact would be a
    small standing statement that omission is fine, which is the incentive the
    disclosure tier exists to remove."""
    (d / "netlist_provenance.json").write_text(json.dumps({
        "block": block,
        "_provenance": {"producer": "test-fixture",
                        "design_content": "structure_and_geometry"}}))


def _run(prog: Path, project: Path, *args: str,
         report: str = "report.json") -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(prog), str(project),
         "--json", str(project / report), *args],
        capture_output=True, text=True)


def _report(project: Path, report: str = "report.json") -> dict:
    return json.loads((project / report).read_text())


# ══════════════════════════════════════════════════════════════════════════
# DEFECT 1 — discriminators: partial block coverage must not certify a step
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_partial_block_coverage_is_incomplete(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """1 of 2 declared blocks has the artefact → rc=1 INCOMPLETE.

    On the base tree every one of these exits 0 with verdict PASS.
    """
    _block_list(tmp_path, ["blk_ok", "blk_missing"])
    _artefact(tmp_path, "blk_ok", filename)
    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "INCOMPLETE", rpt
    assert rpt["blocks_pass"] == 1
    assert rpt["blocks_missing"] == 1
    # The uncovered block must be NAMED — a count alone is not actionable.
    assert rpt["incomplete_blocks"] == ["blk_missing"], rpt
    assert "blk_missing" in r.stderr


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_partial_block_coverage_scales_to_many_blocks(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """5 declared blocks, 1 covered → INCOMPLETE naming the other 4."""
    blocks = [f"blk{i}" for i in range(5)]
    _block_list(tmp_path, blocks)
    _artefact(tmp_path, "blk0", filename)
    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "INCOMPLETE"
    assert rpt["blocks_checked"] == 5
    assert rpt["blocks_pass"] == 1
    assert sorted(rpt["incomplete_blocks"]) == blocks[1:]


# ══════════════════════════════════════════════════════════════════════════
# DEFECT 2 — discriminator: an empty `.subckt` shell is not a netlist
# ══════════════════════════════════════════════════════════════════════════

def test_a3_empty_subckt_shell_fails(tmp_path: Path) -> None:
    """>200B + `.subckt` + zero device cards → A3_NETLIST_NO_DEVICES.

    On the base tree this exits 0 with verdict PASS.
    """
    _block_list(tmp_path, ["testblock"])
    d = tmp_path / "phase3/analog/testblock"
    d.mkdir(parents=True, exist_ok=True)
    body = _EMPTY_SHELL.format(block="testblock")
    (d / "testblock.sp").write_text(body)
    assert len(body.encode()) > 200, "fixture must clear the size rule"
    assert ".subckt" in body, "fixture must clear the .subckt rule"

    r = _run(A3, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "FAIL"
    assert any(f["rule"] == "A3_NETLIST_NO_DEVICES"
               for f in rpt["findings"]), rpt


def test_a3_comment_only_body_is_not_a_device(tmp_path: Path) -> None:
    """Comment / continuation lines inside the body do not count as devices."""
    _block_list(tmp_path, ["testblock"])
    d = tmp_path / "phase3/analog/testblock"
    d.mkdir(parents=True, exist_ok=True)
    (d / "testblock.sp").write_text(
        "* testblock netlist\n"
        '.include "design.ngspice"\n'
        ".subckt testblock vdd vss vin vout\n"
        + "* Mn: the input pair goes here (a comment, not a card)\n" * 6
        + "+ continuation of nothing\n"
        "; Rload placeholder\n"
        ".ends testblock\n.end\n")
    r = _run(A3, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    assert any(f["rule"] == "A3_NETLIST_NO_DEVICES"
               for f in _report(tmp_path)["findings"])


def test_a3_devices_outside_subckt_do_not_count(tmp_path: Path) -> None:
    """Cards in the top-level deck do not substantiate an empty `.subckt`."""
    _block_list(tmp_path, ["testblock"])
    d = tmp_path / "phase3/analog/testblock"
    d.mkdir(parents=True, exist_ok=True)
    (d / "testblock.sp").write_text(
        "* testblock deck\n"
        '.include "design.ngspice"\n'
        + "R_probe out 0 1meg\n" * 8          # top level, OUTSIDE the subckt
        + ".subckt testblock vdd vss vin vout\n"
        "* empty\n"
        ".ends testblock\n.end\n")
    r = _run(A3, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    assert any(f["rule"] == "A3_NETLIST_NO_DEVICES"
               for f in _report(tmp_path)["findings"])


# ══════════════════════════════════════════════════════════════════════════
# DEFECT 3 — discriminators: the flow-declared path must actually be read
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_artefact_at_flow_declared_path_is_read(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Artefact ONLY at the path the flow declares → PASS, not a self-skip.

    On the base tree each gate reports the block MISSING (all-missing →
    VACUOUS_PASS), i.e. it certifies the step having opened no file.
    """
    _block_list(tmp_path, ["blk_ok"])
    _artefact(tmp_path, "blk_ok", filename, root=declared_root)
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "PASS", rpt
    assert rpt["blocks_pass"] == 1
    assert rpt["blocks_missing"] == 0


def test_a3_defect_at_flow_declared_path_is_caught(tmp_path: Path) -> None:
    """A BAD netlist at the declared path must FAIL, not vanish into a skip.

    This is the load-bearing half of the path fix: reading the declared
    path only matters if a defect there is reported.
    """
    _block_list(tmp_path, ["blk"])
    d = tmp_path / "phase2/analog/blk"
    d.mkdir(parents=True, exist_ok=True)
    (d / "blk.sp").write_text(_EMPTY_SHELL.format(block="blk"))
    r = _run(A3, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "FAIL"
    finding = next(f for f in rpt["findings"]
                   if f["rule"] == "A3_NETLIST_NO_DEVICES")
    assert finding["rel_path"].startswith("phase2/analog/"), finding


def test_pdk_check_reads_flow_declared_phase2_decks(tmp_path: Path) -> None:
    """`analog_netlist_pdk_check` must audit decks under phase2/analog.

    On the base tree it globs `_pl.analog_dir` (phase3/analog) only and
    returns `{"skipped": true}` with `passed: true`.
    """
    d = tmp_path / "phase2/analog/blk"
    d.mkdir(parents=True, exist_ok=True)
    (d / "blk.sp").write_text(
        "* blk netlist\n"
        '.include "design.ngspice"\n'
        ".subckt blk vdd vss vin vout\n"
        "XM1 vout vin vss vss sg13_lv_nmos w=1u l=0.13u\n"
        ".ends blk\n")
    r = _run(PDK, tmp_path)
    rpt = _report(tmp_path)
    assert rpt["summary"].get("skipped") is not True, rpt["summary"]
    assert rpt["summary"]["files_checked"] == 1, rpt["summary"]
    assert r.returncode == 0, (r.stdout, r.stderr)


def test_pdk_check_reports_defect_in_phase2_deck(tmp_path: Path) -> None:
    """A deck under phase2/analog with no model source must FAIL the audit."""
    d = tmp_path / "phase2/analog/blk"
    d.mkdir(parents=True, exist_ok=True)
    (d / "blk.sp").write_text(
        "* blk netlist with NO .include / .lib model source\n"
        ".subckt blk vdd vss vin vout\n"
        "XM1 vout vin vss vss sky130_fd_pr__nfet_01v8 w=1 l=0.15\n"
        ".ends blk\n"
        ".tran 1n 1u\n.end\n")
    r = _run(PDK, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["summary"]["files_checked"] == 1
    assert any(f["severity"] == "ERROR" for f in rpt["findings"]), rpt


def test_a3_substance_gate_is_wired_into_the_flow(tmp_path: Path) -> None:
    """A3's declared substance program must be a member of A3's gate.

    Before this change `analog_a3_netlist_gen_check` appeared nowhere in
    flow/phase1_phase2_phase3.yaml — it was an orphan program, so nothing
    in the flow ever executed its ruleset.
    """
    text = FLOW_YAML.read_text(encoding="utf-8")
    assert "analog_a3_netlist_gen_check" in text, \
        "A3's substance gate is not referenced by the flow at all"
    # It must sit inside step A3's gate, next to analog_netlist_pdk_check.
    a3_start = text.index("\n  - id: A3\n")
    a4_start = text.index("\n  - id: A4\n")
    a3_block = text[a3_start:a4_start]
    assert "program_exit_zero" in a3_block
    assert "analog_a3_netlist_gen_check" in a3_block, a3_block
    assert "analog_netlist_pdk_check" in a3_block, a3_block


def test_pdk_check_audits_each_deck_exactly_once(tmp_path: Path) -> None:
    """Both roots are audited, and no deck is audited twice.

    NOT a direction-1 guard — it fails on the base tree, which sees only
    the phase3 deck (files_checked == 1). It is a discriminator for the
    path fix that also pins the de-duplication invariant the multi-root
    glob introduces.
    """
    for root in ("phase3/analog", "phase2/analog"):
        d = tmp_path / root / "blk"
        d.mkdir(parents=True, exist_ok=True)
        (d / "blk.sp").write_text(
            "* blk\n"
            '.include "design.ngspice"\n'
            ".subckt blk vdd vss vin vout\n"
            "XM1 vout vin vss vss sg13_lv_nmos w=1u l=0.13u\n"
            ".ends blk\n")
    r = _run(PDK, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    # Two distinct files → exactly two audits, no duplicates.
    assert _report(tmp_path)["summary"]["files_checked"] == 2


# ══════════════════════════════════════════════════════════════════════════
# DIRECTION-1 GUARDS — behaviour that must NOT change (pass on BOTH trees)
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_all_blocks_missing_stays_vacuous_pass(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """No block has the artefact → VACUOUS_PASS rc=0 (defer to the skill).

    This is the "the skill has not run yet" contract. INCOMPLETE must NOT
    swallow it, or a project that has not started the step would block the
    whole flow audit.
    """
    _block_list(tmp_path, ["a", "b", "c"])
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "VACUOUS_PASS"


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_no_block_list_stays_vacuous_pass(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Pure-digital project (no analog_block_list.json) → VACUOUS_PASS."""
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "VACUOUS_PASS"


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_block_mode_missing_stays_waived_rc2(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """`--block <missing>` keeps exit 2 → analog_one_shot_runner WAIVED.

    The new rc=1 lives ONLY in the no---block tail; converting these
    legitimate deferrals into hard failures would break the runner.
    """
    _block_list(tmp_path, ["blk_ok", "blk_missing"])
    _artefact(tmp_path, "blk_ok", filename)
    r = _run(prog, tmp_path, "--block", "blk_missing")
    assert r.returncode == 2, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "WAIVED"
    assert rpt["suggested_skill"]


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_block_mode_covered_block_still_passes(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """`--block <covered>` still PASSes even while a sibling is uncovered."""
    _block_list(tmp_path, ["blk_ok", "blk_missing"])
    _artefact(tmp_path, "blk_ok", filename)
    r = _run(prog, tmp_path, "--block", "blk_ok")
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "PASS"


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_full_coverage_still_passes(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Every declared block covered → PASS rc=0. A real green stays green."""
    _block_list(tmp_path, ["blk_a", "blk_b"])
    _artefact(tmp_path, "blk_a", filename)
    _artefact(tmp_path, "blk_b", filename)
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "PASS"
    assert rpt["blocks_pass"] == 2
    assert rpt["blocks_missing"] == 0


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_canonical_runner_path_still_wins(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """With the artefact at BOTH roots, the canonical runner path is used."""
    _block_list(tmp_path, ["blk"])
    _artefact(tmp_path, "blk", filename)                        # phase3
    _artefact(tmp_path, "blk", filename, root=declared_root)    # declared
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "PASS"
    for f in rpt.get("findings", []):
        assert not f.get("rel_path", "").startswith(declared_root)


def test_guard_a3_real_netlist_still_passes(tmp_path: Path) -> None:
    """A netlist with real device cards keeps PASSing the new device rule."""
    _block_list(tmp_path, ["ldo"])
    _artefact(tmp_path, "ldo", "{block}.sp")
    r = _run(A3, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "PASS"


def test_guard_a3_runner_deterministic_stub_still_passes(
        tmp_path: Path) -> None:
    """The analog runner's OWN deterministic-stub `.sp` must not newly FAIL.

    `analog_one_shot_runner._emit_deterministic_stub` writes a marked
    `.subckt` carrying `r_stub vin vout 1k`. That IS a device card, so the
    PASS_WITH_STUB benchmark tier survives the new rule — this guard pins
    that, so a future stub template that drops the card is caught here
    rather than in the field.
    """
    _block_list(tmp_path, ["ldo"])
    d = tmp_path / "phase3/analog/ldo"
    d.mkdir(parents=True, exist_ok=True)
    (d / "ldo.sp").write_text(
        "* deterministic_stub extraction_strategy=deterministic_stub "
        "block=ldo step=A3_netlist_gen — replace with real analog output\n"
        "* ldo — SPICE netlist (stub)\n"
        ".subckt ldo vdd vss vin vout\n"
        "* replace with extracted netlist when analog-netlist-gen skill runs\n"
        "r_stub vin vout 1k\n"
        ".ends ldo\n")
    r = _run(A3, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "PASS"


def test_guard_a3_x_instance_only_body_passes(tmp_path: Path) -> None:
    """A hierarchical block whose body is only `X` sub-instances is real."""
    _block_list(tmp_path, ["top"])
    d = tmp_path / "phase3/analog/top"
    d.mkdir(parents=True, exist_ok=True)
    (d / "top.sp").write_text(
        "* hierarchical block\n"
        '.include "design.ngspice"\n'
        ".subckt top vdd vss vin vout\n"
        + "Xstage1 vdd vss vin mid amp_core\n" * 4
        + "Xstage2 vdd vss mid vout amp_core\n"
        ".ends top\n.end\n")
    _netlist_record(d, "top")       # the DEVICE-CARD rule is what is under test
    r = _run(A3, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "PASS"


def test_guard_a3_existing_substance_rules_survive(tmp_path: Path) -> None:
    """A3_NETLIST_TOO_SMALL and A3_NETLIST_NO_SUBCKT still fire, unchanged."""
    _block_list(tmp_path, ["ldo"])
    d = tmp_path / "phase3/analog/ldo"
    d.mkdir(parents=True, exist_ok=True)
    (d / "ldo.sp").write_text("* netlist stub\n.end\n")
    r = _run(A3, tmp_path, report="small.json")
    assert r.returncode == 1
    assert any(f["rule"] == "A3_NETLIST_TOO_SMALL"
               for f in _report(tmp_path, "small.json")["findings"])

    (d / "ldo.sp").write_text(
        "* simulation script (no .subckt)\n"
        + "M1 net1 VREF VSS VSS nmos w=2u l=0.18u\n" * 12 + ".end\n")
    r = _run(A3, tmp_path, report="nosub.json")
    assert r.returncode == 1
    assert any(f["rule"] == "A3_NETLIST_NO_SUBCKT"
               for f in _report(tmp_path, "nosub.json")["findings"])


@pytest.mark.parametrize("mutate,rule", [
    (lambda d: d.update({"_provenance": "deterministic_stub"}),
     "A4_DETERMINISTIC_STUB"),
    (lambda d: [c.update({"simulator_run": False}) for c in d["corners"]],
     "A4_NO_SIMULATOR_RUN"),
    (lambda d: d.update({"spec_results": [{"name": "vout",
                                           "status": "FAIL"}]}),
     "A4_NO_PASS_SPEC"),
    (lambda d: d["corners"].append({"name": "ss_125_bad",
                                    "simulator_run": True, "vout_v": 1.9}),
     "A4_CORNER_MARGIN_FAIL"),
])
def test_guard_a4_real_findings_still_fail(tmp_path: Path, mutate,
                                           rule: str) -> None:
    """A genuinely BAD block still reads FAIL, never the softer INCOMPLETE.

    INCOMPLETE is for unmeasured work; a measured defect must keep landing
    in the `findings` bucket via emit_fail.
    """
    _block_list(tmp_path, ["blk_bad", "blk_ok"])
    _artefact(tmp_path, "blk_ok", "corner_results.json")
    data = json.loads(json.dumps(_REAL_CORNERS))
    mutate(data)
    d = tmp_path / "phase3/analog/blk_bad"
    d.mkdir(parents=True, exist_ok=True)
    (d / "corner_results.json").write_text(json.dumps(data))
    r = _run(A4, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "FAIL", rpt
    assert any(f["rule"] == rule for f in rpt["findings"]), rpt


def test_guard_fail_outranks_incomplete(tmp_path: Path) -> None:
    """A measured defect + an uncovered block → FAIL (the stronger verdict)."""
    _block_list(tmp_path, ["blk_bad", "blk_ok", "blk_absent"])
    _artefact(tmp_path, "blk_ok", "spec.json")
    d = tmp_path / "phase3/analog/blk_bad"
    d.mkdir(parents=True, exist_ok=True)
    (d / "spec.json").write_text("{}")
    r = _run(A1, tmp_path)
    assert r.returncode == 1
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "FAIL", rpt
    assert any(f["rule"] == "A1_SPEC_EMPTY" for f in rpt["findings"])


def test_guard_pdk_check_no_analog_dir_still_skips(tmp_path: Path) -> None:
    """A pure-digital project keeps its cost-free skip on analog_netlist_pdk.

    #521 — the skip is unchanged; what changed is that it is now REPORTED as
    one. rc 2 is the vacuous tier, not a failure: this guard exists to prove
    a digital project is never turned red, and rc 2 does not turn it red.
    """
    (tmp_path / "phase2/stage2").mkdir(parents=True, exist_ok=True)
    r = _run(PDK, tmp_path)
    assert r.returncode == 2, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["summary"] == {"skipped": True, "reason": "no_analog_dir"}
    assert rpt["passed"] is True


def test_guard_pdk_check_analog_dir_without_decks_still_skips(
        tmp_path: Path) -> None:
    """An analog dir carrying no `.sp` keeps SKIP_NO_SP_FILES (#521: rc 2)."""
    (tmp_path / "phase3/analog").mkdir(parents=True, exist_ok=True)
    r = _run(PDK, tmp_path)
    assert r.returncode == 2, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["summary"] == {"skipped": True, "reason": "no_sp_files"}


def test_guard_pdk_check_stub_tier_preserved(tmp_path: Path) -> None:
    """PASS_WITH_STUB tier survives — benchmark stub runs must not flip."""
    d = tmp_path / "phase3/analog/blk"
    d.mkdir(parents=True, exist_ok=True)
    (d / "blk.sp").write_text(
        "* deterministic_stub extraction_strategy=deterministic_stub\n"
        ".subckt blk vdd vss vin vout\n"
        "r_stub vin vout 1k\n"
        ".ends blk\n")
    r = _run(PDK, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["summary"]["verdict_tier"] == "PASS_WITH_STUB", rpt["summary"]


def test_guard_runner_only_uses_block_mode(tmp_path: Path) -> None:
    """analog_one_shot_runner must keep invoking the A-gates with --block.

    The new INCOMPLETE rc=1 lives in the no---block tail. If the runner ever
    dropped `--block`, a partially-covered project would turn the runner's
    per-block WAIVED deferral into a hard failure. Pin the invocation shape.
    """
    src = (PROGRAMS / "analog_one_shot_runner.py").read_text(encoding="utf-8")
    marker = 'cmd = [sys.executable, str(det), str(project), "--block", bname]'
    assert marker in src, \
        "analog_one_shot_runner no longer invokes the A-gates in --block mode"


def test_guard_analog_class_na_predicate_unchanged(tmp_path: Path) -> None:
    """ORGANIC #676 class-N/A predicate in the shared helper still behaves.

    The helper file is edited by this change; the P0 gates
    (analog_flow_compliance_check / analog_digital_interface_check /
    analog_a6_block_pv_check) depend on this predicate.
    """
    sys.path.insert(0, str(PROGRAMS))
    import _analog_a_check_common as aac

    # Nothing declared → not N/A (fail-closed).
    assert aac.analog_class_is_na(tmp_path) is False
    # Non-analog class + every block low_confidence → N/A.
    (tmp_path / "reports").mkdir(parents=True, exist_ok=True)
    (tmp_path / "reports/ic_class.json").write_text(
        json.dumps({"has_analog": False}))
    (tmp_path / "phase3/analog").mkdir(parents=True, exist_ok=True)
    (tmp_path / "phase3/analog/analog_block_list.json").write_text(
        json.dumps({"blocks": [{"name": "por", "low_confidence": True}]}))
    assert aac.analog_class_is_na(tmp_path) is True
    # A confident (spec-backed) block is still gated.
    (tmp_path / "phase3/analog/analog_block_list.json").write_text(
        json.dumps({"blocks": [{"name": "ldo", "low_confidence": False}]}))
    assert aac.analog_class_is_na(tmp_path) is False
