#!/usr/bin/env python3
"""The auto-SDC must not assert the design supplied no constraints.

THE DEFECT. ``_build_auto_silicon_sdc`` opens the sign-off deck with

    # Auto-generated minimal SDC for silicon top (no constraints/*.sdc supplied; ...)

That is a statement about the DESIGN, printed on the strength of one glob
returning nothing. #742 corrected WHERE the glob looks (``input/constraints``
then ``input/reference_flow``) but left the sentence an assertion rather than a
measurement, so a design that stages its constraints anywhere else — the
``input/design_src/`` tree a Path-A run stages into, for instance — gets a deck
whose first line says it staged none.

MEASURED, all 7 projects with an ``input/`` tree on the authoring host: 4 stage
at least one ``.sdc`` under ``input/`` that the resolver cannot see, and on all
4 the emitted deck asserts none was supplied.

BIDIRECTIONAL NEGATIVE CONTROL, measured both ways: 6 FAIL / 1 PASS against
the pre-fix producer, 7/7 PASS after. The ONE that passes both ways is
``test_header_is_byte_identical_when_the_design_staged_nothing`` — the blast-
radius guard, which asserts a property this change deliberately does NOT move.
The rest fail pre-fix either because the survey does not exist or because the
header states the falsehood.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import phase3_one_shot_runner as p3  # noqa: E402

# An OpenLane-style flow-templated SDC: every number comes from a variable the
# STA engine never sets. Reading it standalone aborts the deck.
TEMPLATED_SDC = (
    "# generated by get_cup_sdc.py\n"
    "set ::env(IO_SYNC) 0\n"
    "create_clock [get_ports $::env(CLOCK_PORT)] -name clk "
    "-period $::env(CLOCK_PERIOD)\n"
    "set_max_transition $::env(MAX_TRANSITION_CONSTRAINT) [current_design]\n"
    "set_max_fanout $::env(MAX_FANOUT_CONSTRAINT) [current_design]\n"
    "set_input_delay -max 3.89 -clock [get_clocks {clk}] [get_ports {adr[*]}]\n"
)

# A self-contained SDC: no flow variables at all.
STANDALONE_SDC = (
    "# design-authored\n"
    "create_clock [get_ports clk] -name core_clock -period 10.0\n"
)


def _mk(tmp_path: Path, rel: str, text: str) -> Path:
    proj = tmp_path / "proj"
    p = proj / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return proj


# ------------------------------------------------------------- the defect

def test_staged_sdc_outside_the_resolved_dirs_is_surveyed(tmp_path):
    """FAILS PRE-FIX (no such function). The design's file is SEEN even where
    the resolver does not read."""
    proj = _mk(tmp_path, "input/design_src/openlane/top/signoff.sdc",
               TEMPLATED_SDC)
    rows = p3._staged_sdc_survey(proj)
    assert len(rows) == 1, "a staged SDC under input/ was not surveyed at all"
    row = rows[0]
    assert row["path"] == "input/design_src/openlane/top/signoff.sdc"
    assert row["consumed"] is False
    assert row["reason_not_consumed"], "not-consumed without a stated reason"
    # the resolver itself is UNCHANGED — it still consumes nothing here
    assert p3._resolve_staged_silicon_sdc(proj) is None


def test_header_stops_claiming_none_was_supplied(tmp_path):
    """FAILS PRE-FIX. The deck must not assert a falsehood about the design."""
    proj = _mk(tmp_path, "input/design_src/openlane/top/signoff.sdc",
               TEMPLATED_SDC)
    (proj / "phase1/generated_docs").mkdir(parents=True, exist_ok=True)
    text = p3._build_auto_silicon_sdc(proj, top="top")
    first = text.splitlines()[0]
    assert "no constraints/*.sdc supplied" not in first, (
        "the deck states the design supplied no constraints while its own "
        "input/ tree holds one")
    assert "VIBEIC_STAGED_SDC_NOT_CONSUMED" in text
    assert "input/design_src/openlane/top/signoff.sdc" in text, (
        "the unconsumed file is not NAMED — a count is not a disclosure")


def test_templated_sdc_is_reported_with_the_variables_it_needs(tmp_path):
    """FAILS PRE-FIX. WHY it cannot be consumed must be stated, not implied."""
    proj = _mk(tmp_path, "input/design_src/openlane/top/signoff.sdc",
               TEMPLATED_SDC)
    row = p3._staged_sdc_survey(proj)[0]
    refs = row["unevaluable_env_refs"]
    assert "CLOCK_PERIOD" in refs and "CLOCK_PORT" in refs
    assert "MAX_TRANSITION_CONSTRAINT" in refs
    # IO_SYNC IS assigned inside the same file — it is not an unmet dependency
    assert "IO_SYNC" not in refs, (
        "an ::env var the file itself sets was reported as unresolvable")


# --------------------------------------------- guards (pass BOTH ways)

def test_header_is_byte_identical_when_the_design_staged_nothing(tmp_path):
    """Blast radius: the overwhelming majority of projects stage no SDC at all
    and their deck must not change by one byte."""
    proj = tmp_path / "bare"
    (proj / "input" / "docs").mkdir(parents=True)
    text = p3._build_auto_silicon_sdc(proj, top="top")
    assert text.splitlines()[0].startswith(
        "# Auto-generated minimal SDC for silicon top "
        "(no constraints/*.sdc supplied;")
    assert "VIBEIC_STAGED_SDC_NOT_CONSUMED" not in text


def test_the_consumed_file_is_never_reported_as_unconsumed(tmp_path):
    """A design that stages in the canonical location is consumed as before,
    and the survey says so rather than disclosing a phantom gap."""
    proj = _mk(tmp_path, "input/constraints/clock.sdc", STANDALONE_SDC)
    consumed = p3._resolve_staged_silicon_sdc(proj)
    assert consumed is not None and consumed.name == "clock.sdc"
    rows = p3._staged_sdc_survey(proj)
    assert len(rows) == 1 and rows[0]["consumed"] is True
    assert p3._staged_sdc_not_consumed_note(proj) == ""


def test_survey_does_not_change_which_file_is_consumed(tmp_path):
    """The one thing this change must NOT do: move the resolver. A templated
    file staged outside the ground truth is surveyed and still not consumed;
    the canonical file still wins."""
    proj = _mk(tmp_path, "input/design_src/openlane/top/signoff.sdc",
               TEMPLATED_SDC)
    (proj / "input/constraints").mkdir(parents=True, exist_ok=True)
    (proj / "input/constraints/clock.sdc").write_text(STANDALONE_SDC)
    consumed = p3._resolve_staged_silicon_sdc(proj)
    assert consumed is not None
    assert consumed.parts[-3:] == ("input", "constraints", "clock.sdc")
    rows = {r["path"]: r for r in p3._staged_sdc_survey(proj)}
    assert rows["input/constraints/clock.sdc"]["consumed"] is True
    assert rows["input/design_src/openlane/top/signoff.sdc"]["consumed"] is False


def test_unevaluable_detection_ignores_ordinary_tcl_variables(tmp_path):
    """The runner's OWN auto-SDC binds `$_vibeic_p` with `foreach`. Flagging
    plain `$var` would refuse valid decks, so only ::env() is considered."""
    deck = ("create_clock -name clk -period 10.0 [get_ports clk]\n"
            "set _vibeic_data_in {}\n"
            "foreach _vibeic_p [all_inputs] { lappend _vibeic_data_in "
            "$_vibeic_p }\n"
            "set_input_delay 2 -clock clk $_vibeic_data_in\n")
    assert p3._sdc_unevaluable_env_refs(deck) == []
