"""The common-mode reference must not track the thing being compared.

MEASURED (round 26, OSR 64, five inputs, one full conversion window each,
after the latch was made to resolve (v1.16.18) and its strobe moved off the
clock edge (v1.16.41)). At the instant the quantiser decides:

    vin       0.30    0.40    0.50    0.60    0.70
    vcm     0.5024  0.5336  0.5643  0.5934  0.6220

`vcm` moves 0.1196 V across the input range -- a slope of 0.299 V/V --
against a declared value of (vrefp+vrefn)/2 = 0.600 V, while the signal
differential's whole variation is 0.004 to 0.024 V. The comparator's
REFERENCE tracks the input six times harder than the signal does, so its
decision cannot carry information however good the latch is: measured, the
differential now changes sign with the input (16..32 of 63) and the output
still never flips.

The node is generated by a matched resistive divider and loaded by TEN
switched device terminals -- counted in the EMITTED netlist, because they live
in the per-stage group and expand with the declared order, so counting the
entry's top level alone undercounts them (it says 2, and my first version of
the control below asserted against that wrong number and failed). A divider
alone cannot hold that.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import analog_a2_topology_emit as m  # noqa: E402


def _entry():
    for name in dir(m):
        v = getattr(m, name)
        if isinstance(v, dict) and "delta_sigma" in v:
            c = v["delta_sigma"]
            if isinstance(c, dict) and "circuit_class_citation" in c:
                return c
    raise AssertionError("delta_sigma entry not found")


def _dev(name):
    for d in _entry()["devices"]:
        if d.get("name") == name:
            return d
    return None


def test_the_common_mode_node_is_decoupled_at_all():
    c = _dev("c_vcm")
    assert c is not None, "vcm has no decoupling; a divider alone cannot hold it"
    assert c["role"] == "cap"
    assert set(c["nets"]) == {"vcm", "vss"}


def test_the_decoupling_is_SIZED_from_the_declaration_not_a_constant():
    # a hand number here would go stale the moment enob/osr/vref move, which
    # is the same defect this repo fixed for the bias resistor
    exprs = {e["device"]: e for e in _entry()["device_param_exprs"]}
    assert "c_vcm" in exprs, "c_vcm carries no derived size"
    assert exprs["c_vcm"]["param"] == "l"
    assert "40.0" in exprs["c_vcm"]["expr"]
    # and it must be expressed against the sampling capacitor, not typed out
    assert "enob" in exprs["c_vcm"]["expr"] and "osr" in exprs["c_vcm"]["expr"]


def test_the_decoupling_dominates_the_charge_that_disturbs_it():
    """Four unit sampling/DAC capacitors commutate onto vcm every clock. The
    decoupling has to be much larger than that, or it is decorative."""
    exprs = {e["device"]: e for e in _entry()["device_param_exprs"]}
    import re
    mult = float(re.match(r"\s*([0-9.]+)\s*\*", exprs["c_vcm"]["expr"]).group(1))
    assert mult >= 10.0, (
        f"decoupling is {mult}x a unit sampling cap; four of them switch onto "
        f"this node every clock")


def test_the_switched_load_this_is_sized_against_really_exists():
    """The control that keeps the number honest: if the switched paths were
    removed the sizing argument would be void, so count them -- across the
    STAGE expansion, because that is where most of them live."""
    top = [d["name"] for d in _entry()["devices"]
           if "vcm" in (d.get("nets") or [])
           and d.get("name", "").startswith(("mn_smpb", "mp_smpb",
                                             "mn_dacr", "mp_dacr",
                                             "mn_azq", "mp_azq"))]
    per_stage = [d["name"] for g in m._stage_groups(_entry())
                 for d in (g.get("devices") or [])
                 if "vcm" in (d.get("nets") or [])
                 and d.get("name", "").startswith(("mn_smpb", "mp_smpb",
                                                   "mn_dacr", "mp_dacr"))]
    # 2 at the top (the auto-zero clamp) + 4 per stage
    assert len(top) == 2, top
    assert len(per_stage) == 4, per_stage


def test_the_shipped_library_still_holds_its_own_invariants():
    assert m.library_invariants() == []
