#!/usr/bin/env python3
"""TDF ATPG — `--top` must name a module of the netlist the run ACTUALLY reads.

MEASURED on a real cell run (subservient x sky130A, plugin 1.9.82, project
`converge/`), Step DT1 = FAIL with this recorded reason:

    "producer recorded ERROR (ATPG could not run): gate-levelise failed
     (exit 1): ... Executing Verilog-2005 frontend:
     /work/phase2/stage2/dft/cut_netlist.v ...
     Generating RTLIL representation for module `\\subservient'.
     ... 3. Executing HIERARCHY pass (managing design hierarchy).
     ERROR: Module `chip_top' not found!"

The two halves of that message name two DIFFERENT modules. Reproduced
deterministically against the byte-identical pre-fix file, in-project:

    discover_mapped_netlist -> phase2/stage2/synth/chip_top_synth.v
    derived --top           -> chip_top
    cut_netlist top         -> subservient
    MISMATCH: True

Cause: `--top` was derived from the MAPPED netlist, but when
`phase2/stage2/dft/cut_netlist.v` already exists the run REUSES it verbatim
and never reads the mapped netlist at all. A project that emits more than one
`*_synth.v` (a chip-top wrapper beside the core — routine) picks the wrong one
by glob order, so yosys is asked `hierarchy -top <wrapper>` about a file that
only contains <core>. The TDF run then dies, and the step reports "ATPG could
not run" — i.e. NO transition-coverage statement about the design at all,
which is not the same thing as a coverage FAIL.

This is the adjacent-measurement shape: the top name is resolved against one
artefact and applied to another.

The three cases below are deliberately bidirectional. `test_reuses_cut_netlist_top`
FAILS against the pre-fix file and passes after. `test_no_cut_netlist_still_uses_mapped_netlist`
and `test_unambiguous_project_is_unchanged` must pass BOTH before and after —
they are what stops the fix from "just always read the cut netlist", which
would break the build-the-cut-netlist-from-scratch path, and what stops it
from being narrowed until it fires on nothing.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROGRAMS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROGRAMS))

import transition_fault_atpg_run as tdf  # noqa: E402


def _mk_project(tmp_path: Path, *, with_cut: bool, with_wrapper: bool) -> Path:
    """A project whose CUT netlist top differs from the mapped-netlist top.

    Chip-AGNOSTIC: the module names here are fixtures, not any real design.
    'aa_wrapper' sorts BEFORE 'zz_core' so the mapped-netlist glob picks the
    wrapper — the same ordering accident the real run hit.
    """
    proj = tmp_path / "proj"
    synth = proj / "phase2" / "stage2" / "synth"
    dft = proj / "phase2" / "stage2" / "dft"
    synth.mkdir(parents=True)
    dft.mkdir(parents=True)

    (synth / "zz_core_synth.v").write_text(
        "module zz_core(input i_clk, output o_q);\nendmodule\n")
    if with_wrapper:
        (synth / "aa_wrapper_synth.v").write_text(
            "module aa_wrapper(input i_clk, output o_q);\nendmodule\n")
    if with_cut:
        # What `fault cut` emits: the CORE, cut — never the wrapper.
        (dft / "cut_netlist.v").write_text(
            "/* Automatically generated by Fault */\n"
            "module zz_core(i_clk, o_q, _0001_, \\_0001_.d );\nendmodule\n")
    return proj


def _derived_top(proj: Path, monkeypatch) -> str:
    """Run main() far enough to capture the `top` it hands the ATPG."""
    seen = {}

    def _fake_run(project, **kw):
        seen.update(kw)
        return 0, {"verdict": "PASS"}

    monkeypatch.setattr(tdf, "run_tdf_atpg", _fake_run)
    # Liberty resolution runs before top derivation and needs a PDK we do not
    # have here; it is not what this test is about.
    monkeypatch.setattr(tdf, "_resolve_design_liberty",
                        lambda project, explicit: "/pdk/dummy.lib")
    rc = tdf.main([str(proj), "--clock", "i_clk",
                   "--json", str(proj / "out.json")])
    assert rc == 0, f"main() exited {rc}; expected the patched run to return 0"
    assert "top" in seen, "run_tdf_atpg was never reached"
    return seen["top"]


def test_reuses_cut_netlist_top(tmp_path, monkeypatch):
    """THE DEFECT. Cut netlist present -> it is the subject; top comes from it.

    Pre-fix this returns 'aa_wrapper' (from the mapped-netlist glob) while the
    file yosys will read declares only 'zz_core' -> "Module `aa_wrapper' not
    found!". Post-fix it returns 'zz_core'.
    """
    proj = _mk_project(tmp_path, with_cut=True, with_wrapper=True)
    cut = proj / "phase2" / "stage2" / "dft" / "cut_netlist.v"
    assert "module zz_core" in cut.read_text()
    assert "aa_wrapper" not in cut.read_text()

    top = _derived_top(proj, monkeypatch)
    assert top == "zz_core", (
        f"--top={top!r} names a module absent from the netlist this run "
        f"actually reads ({cut}); yosys `hierarchy -top {top}` cannot resolve "
        f"it and the whole TDF run dies with no coverage statement")


def test_no_cut_netlist_still_uses_mapped_netlist(tmp_path, monkeypatch):
    """REVERSE CASE — must pass BOTH before and after the fix.

    With no cut netlist, `fault cut` will BUILD one from the mapped netlist,
    so the mapped netlist is the subject and the old derivation is correct.
    A fix that unconditionally reads the cut netlist breaks this path.
    """
    proj = _mk_project(tmp_path, with_cut=False, with_wrapper=True)
    assert not (proj / "phase2" / "stage2" / "dft" / "cut_netlist.v").exists()

    top = _derived_top(proj, monkeypatch)
    mapped = tdf.discover_mapped_netlist(proj)
    expected = Path(mapped).stem[: -len("_synth")]
    assert top == expected, (
        f"with no cut netlist the mapped netlist {mapped} is the subject; "
        f"expected top {expected!r}, got {top!r}")


def test_unambiguous_project_is_unchanged(tmp_path, monkeypatch):
    """REVERSE CASE — the ordinary single-netlist project must be untouched.

    Guards against narrowing the fix until it fires on nothing: here both
    derivations agree, and the answer must still be the real top (not None,
    not the literal 'top' fallback).
    """
    proj = _mk_project(tmp_path, with_cut=True, with_wrapper=False)
    top = _derived_top(proj, monkeypatch)
    assert top == "zz_core"


def test_escaped_identifier_cut_top(tmp_path, monkeypatch):
    """Yosys writes escaped identifiers as `module \\name`; strip the backslash.

    A leading backslash left on the name would produce a top that resolves no
    better than the wrong name did — a silent re-introduction of the defect.
    """
    proj = _mk_project(tmp_path, with_cut=True, with_wrapper=True)
    cut = proj / "phase2" / "stage2" / "dft" / "cut_netlist.v"
    cut.write_text("module \\zz_core (i_clk, o_q);\nendmodule\n")
    top = _derived_top(proj, monkeypatch)
    assert top == "zz_core", f"escaped identifier not normalised: {top!r}"
