"""Step 14's netlist audit is not blind — and nothing pinned that.

D9 published step 14 as RULER-BLIND on the criterion "delete the step's own
declared output and the verdict does not move". The deletion half REPRODUCES:
on isolated copies of 4 published runs
(`cvdp/run_v0153_runner/fixed_priority_arbiter`, `phase1_parity/espi`,
`phase1_parity/interlaken`, `phase1_parity/lpc/phase2`), removing
`phase2/stage2/synth/netlist.v` left `yosys_hilomap_required_check` and
`yosys_script_template_check` at rc=0 in both arms.

The DIAGNOSIS does not survive the next arm. `phase2/stage2/synth/netlist.v` is
STEP 9's declared output, re-declared by step 14, and step 9's gate carries
`files_exist: phase2/stage2/synth/netlist.v` while step 14 `blocks_on: [9, 13]`.
Absence is already blocked upstream, deliberately, and `audit_handoff_netlist`
says so in prose. What step 14 owns is whether the artefact PnR receives is a
netlist at all — and it reads it:

    MEASURED on isolated copies of 6 published runs carrying the artefact
    (cvdp/fixed_priority_arbiter, phase1_parity/{espi,interlaken,lpc,lpc/phase2,
    mdio}) — replacing `netlist.v` with a one-line comment moved
    `yosys_script_template_check` rc 0 -> 1 on 6 of 6.

That property had NO test. This file is that test, because a measurement
nobody pinned is a measurement that decays. It adds no new decision to the
gate; every assertion here passes on origin/main unchanged.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

SCRIPT = Path(__file__).resolve().parent.parent / "yosys_script_template_check.py"
assert SCRIPT.exists(), f"Script not found: {SCRIPT}"

sys.path.insert(0, str(SCRIPT.parent))
import yosys_script_template_check as ystc  # noqa: E402

_REAL_NETLIST = """\
/* Generated by Yosys */
module top(input clk, input a, output y);
  wire n1;
  sky_cell _0_ (.A(a), .Y(n1));
  assign y = n1;
endmodule
"""


def _synth_dir(tmp_path: Path) -> Path:
    d = tmp_path / "phase2" / "stage2" / "synth"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _netlist(tmp_path: Path, text: str) -> Path:
    p = _synth_dir(tmp_path) / "netlist.v"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)
    return p


def test_a_real_netlist_is_credited_and_the_denominator_is_disclosed(tmp_path):
    rc, report, _msgs = ystc.audit_handoff_netlist(tmp_path, [])
    assert rc == 0, "no netlist at all is step 9's block, not step 14's"
    assert report["present"] is False

    _netlist(tmp_path, _REAL_NETLIST)
    rc, report, _msgs = ystc.audit_handoff_netlist(tmp_path, [])
    assert rc == 0
    assert report["present"] is True
    assert report["has_module"] is True
    assert report["bytes"] == len(_REAL_NETLIST.encode())


@pytest.mark.parametrize("stub,why", [
    ("// netlist\n", "comment-only"),
    ("", "empty"),
    ("   \n\n", "whitespace-only"),
    ("wire n1;\nassign y = n1;\n", "no module declaration"),
])
def test_a_stub_at_the_handoff_path_moves_the_verdict(tmp_path, stub, why):
    """THE ARM D9's deletion probe cannot reach: the file is THERE and is not
    a netlist. This is what step 14 is for, and it bites."""
    _netlist(tmp_path, _REAL_NETLIST)
    assert ystc.audit_handoff_netlist(tmp_path, [])[0] == 0

    _netlist(tmp_path, stub)
    rc, report, msgs = ystc.audit_handoff_netlist(tmp_path, [])
    assert rc == 1, f"a {why} handoff artefact must not certify a tape-out path"
    assert report["present"] is True, (
        "the control: the file EXISTS, so this rc is the CONTENT talking and "
        "not the absence step 9 already blocks")
    assert msgs, "a refusal must say what it refused on"


def test_a_netlist_older_than_its_declared_producer_moves_the_verdict(tmp_path):
    """Staleness — the second decision this gate owns. A netlist that predates
    the script claiming to write it is the previous run's ghost."""
    d = _synth_dir(tmp_path)
    nl = d / "netlist.v"
    nl.write_text(_REAL_NETLIST)
    ys = d / "synth.ys"
    ys.write_text("read_verilog top.v\nsynth\nwrite_verilog netlist.v\n")

    import os
    os.utime(nl, (1_000_000, 1_000_000))
    os.utime(ys, (2_000_000, 2_000_000))
    rc, report, _msgs = ystc.audit_handoff_netlist(tmp_path, [str(ys)])
    assert rc == 1
    assert report["producer_scripts"] == [str(ys)]
    assert report["stale_vs_scripts"] == [str(ys)]

    # The control on the same fixture: make the netlist NEWER and it passes,
    # so the failure above is the timestamp and not the producer detection.
    os.utime(nl, (3_000_000, 3_000_000))
    rc, report, _msgs = ystc.audit_handoff_netlist(tmp_path, [str(ys)])
    assert rc == 0
    assert report["stale_vs_scripts"] == []


def test_a_script_that_writes_elsewhere_is_not_treated_as_a_producer(tmp_path):
    """PRECISION. A `phase3/**/*.ys` post-synthesis equivalence script is newer
    than the phase-2 handoff BY CONSTRUCTION, so treating every discovered
    script as a producer reported staleness on trees where there was none."""
    d = _synth_dir(tmp_path)
    nl = d / "netlist.v"
    nl.write_text(_REAL_NETLIST)
    lec = tmp_path / "phase3" / "lec"
    lec.mkdir(parents=True)
    ys = lec / "lec_post_top.ys"
    ys.write_text("read_verilog a.v\nwrite_verilog lec_out.v\n")

    import os
    os.utime(nl, (1_000_000, 1_000_000))
    os.utime(ys, (2_000_000, 2_000_000))
    rc, report, msgs = ystc.audit_handoff_netlist(tmp_path, [str(ys)])
    assert rc == 0
    assert report["producer_scripts"] == []
    assert any("staleness not compared" in m for m in msgs), (
        "unmeasured must be recorded as unmeasured, never as agreement")
