"""sdc_gen names its output `{top}.sdc`, so a change in TOP RESOLUTION orphans
the previous run's file in the directory the Step-8 validator globs.

The generator resolves `top` per-run: `--top-name`, else a board wrapper, else
L9's `top_module`, else the literal `chip_top` fallback. A project whose L9 does
not yet carry `top_module` therefore gets `chip_top.sdc` — and because no ports
are classifiable at that point, the `if inputs:` / `if outputs:` render guards
emit NO `set_input_delay` / `set_output_delay`. Once L9 resolves, the next run
writes a COMPLETE SDC under a DIFFERENT filename and the earlier one is left
behind. `sdc_validator_check` globs `*.sdc` over that directory and grades every
file it finds, so the orphan — constraining a top module that no longer exists
anywhere in the project — reports "missing set_input_delay / set_output_delay"
and FAILs Step 8 forever, voiding every step that depends on it, while the
design's own constraints are complete.

BIDIRECTIONAL negative control:
  * FORWARD  — `test_stale_sdc_for_a_superseded_top_is_removed` FAILs against
    the byte-identical pre-fix generator (the orphan survives) and PASSes after.
  * REVERSE 1 — `test_a_foreign_sdc_is_never_touched`: an SDC the generator did
    not write must SURVIVE. The fix must not become "delete siblings".
  * REVERSE 2 — `test_a_genuinely_incomplete_current_top_sdc_still_fails`: the
    real defect underneath must STILL be caught. A CURRENT-top SDC that really
    lacks I/O delays must still make the validator exit non-zero. This is the
    guard against "fixed" meaning "made Step 8 unfailable".
"""
import json
import subprocess
import sys
from pathlib import Path

PROGRAMS = Path(__file__).resolve().parent.parent
SDC_GEN = PROGRAMS / "sdc_gen.py"
VALIDATOR = PROGRAMS / "sdc_validator_check.py"

# Exactly what the pre-fix generator left on disk in the field: its own banner,
# a top entity that no longer exists, and no I/O delays at all.
STALE_CHIP_TOP_SDC = """\
# =========================================================================
# Auto-generated by sdc_gen.py (Wave 72/73)
# Top entity: chip_top
# Clock: clk period=20 ns
# DO NOT hand-edit; regenerate via sdc_gen.py.
# =========================================================================

create_clock -name clk_main -period 20 [get_ports {clk}]
derive_pll_clocks
derive_clock_uncertainty
"""


def _scaffold(tmp_path: Path, top: str = "widget_core") -> Path:
    """A project whose L9 DOES resolve a top — i.e. the second run, the one
    that emits `{top}.sdc` and orphans whatever the first run wrote."""
    proj = tmp_path / "proj"
    (proj / "phase1" / "generated_docs").mkdir(parents=True)
    (proj / "phase2" / "stage1" / "rtl").mkdir(parents=True)
    (proj / "phase1" / "generated_docs" / "L8_RTL_CONSTANTS.json").write_text(
        json.dumps({"clock_mhz": 50}))
    (proj / "phase1" / "generated_docs" / "L9_INTEGRATION_SPEC.json").write_text(
        json.dumps({
            "top_module": top,
            "top_module_pins": [
                {"name": "clk", "mode": "input"},
                {"name": "reset_n", "mode": "input"},
                {"name": "data_i", "mode": "input"},
                {"name": "data_o", "mode": "output"},
            ],
        }))
    (proj / "phase2" / "stage1" / "rtl" / f"{top}.v").write_text(
        f"module {top}(input wire clk, input wire reset_n, "
        f"input wire [7:0] data_i, output wire [7:0] data_o); endmodule\n")
    return proj


def _fpga_dir(proj: Path) -> Path:
    d = proj / "phase2" / "stage1" / "fpga"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _run_gen(proj: Path):
    return subprocess.run([sys.executable, str(SDC_GEN), str(proj)],
                          capture_output=True, text=True, timeout=60)


def test_stale_sdc_for_a_superseded_top_is_removed(tmp_path):
    """FORWARD control — fails against the pre-fix generator."""
    proj = _scaffold(tmp_path)
    stale = _fpga_dir(proj) / "chip_top.sdc"
    stale.write_text(STALE_CHIP_TOP_SDC)

    cp = _run_gen(proj)
    assert cp.returncode == 0, cp.stderr

    current = _fpga_dir(proj) / "widget_core.sdc"
    assert current.is_file(), "the run's own SDC must still be written"
    assert "set_input_delay" in current.read_text()

    assert not stale.exists(), (
        "sdc_gen left its own superseded output for top 'chip_top' beside the "
        "SDC for the resolved top 'widget_core'; sdc_validator_check globs "
        "*.sdc over this directory and will FAIL Step 8 on the orphan")
    # Degrade loudly: the removal must be announced, not silent.
    assert "SUPERSEDED" in cp.stdout, cp.stdout

    # And the end-to-end consequence: Step 8 is clean.
    v = subprocess.run([sys.executable, str(VALIDATOR), str(proj)],
                       capture_output=True, text=True, timeout=60)
    assert v.returncode == 0, f"{v.stdout}\n{v.stderr}"


def test_the_orphan_is_shed_even_when_the_run_skips_if_exists(tmp_path):
    """FORWARD control, self-heal path — also fails against the pre-fix file.

    A project that ALREADY carries the orphan (because the offending run
    happened before this fix) must be able to shed it. sdc_gen skips when the
    current top's SDC exists, so the cleanup has to run on that path too or the
    directory stays poisoned forever.
    """
    proj = _scaffold(tmp_path)
    fpga = _fpga_dir(proj)
    stale = fpga / "chip_top.sdc"
    stale.write_text(STALE_CHIP_TOP_SDC)
    # A COMPLETE current-top SDC already on disk => sdc_gen takes the skip path.
    _run_gen(proj)
    assert (fpga / "widget_core.sdc").is_file()
    stale.write_text(STALE_CHIP_TOP_SDC)          # re-introduce the orphan

    cp = _run_gen(proj)
    assert cp.returncode == 0, cp.stderr
    assert "SKIP:" in cp.stdout, "precondition: this run must take the skip path"
    assert not stale.exists(), (
        "an already-orphaned directory must shed the stale SDC on the "
        "skip-if-exists path too")


def test_a_foreign_sdc_is_never_touched(tmp_path):
    """REVERSE 1 — the fix must supersede only the generator's OWN output."""
    proj = _scaffold(tmp_path)
    fpga = _fpga_dir(proj)

    # No sdc_gen banner => not ours, whatever it is named.
    hand = fpga / "board_extra.sdc"
    hand.write_text("# hand-authored by the board team\n"
                    "# Top entity: some_other_top\n"
                    "set_false_path -from [get_ports rst_n]\n")
    # Banner present but attributable to THIS run's top => not superseded.
    same_top = fpga / "widget_core_backup.sdc"
    same_top.write_text(STALE_CHIP_TOP_SDC.replace("Top entity: chip_top",
                                                   "Top entity: widget_core"))

    cp = _run_gen(proj)
    assert cp.returncode == 0, cp.stderr

    assert hand.is_file(), "a hand-authored SDC must never be removed"
    assert "hand-authored" in hand.read_text()
    assert same_top.is_file(), (
        "an sdc_gen file attributed to the CURRENT top is not superseded")


def test_a_genuinely_incomplete_current_top_sdc_still_fails(tmp_path):
    """REVERSE 2 — the real defect underneath must STILL be caught.

    If the fix were 'stop grading files until the count reaches zero', this
    would go green and Step 8 would become unfailable. The validator must still
    reject a CURRENT-top SDC that genuinely carries no I/O delays.
    """
    proj = _scaffold(tmp_path)
    fpga = _fpga_dir(proj)
    # The resolved top's OWN SDC, incomplete. sdc_gen skips-if-exists, so this
    # is what the validator grades.
    (fpga / "widget_core.sdc").write_text(
        STALE_CHIP_TOP_SDC.replace("Top entity: chip_top",
                                   "Top entity: widget_core"))

    cp = _run_gen(proj)
    assert cp.returncode == 0, cp.stderr
    assert (fpga / "widget_core.sdc").is_file()

    v = subprocess.run([sys.executable, str(VALIDATOR), str(proj)],
                       capture_output=True, text=True, timeout=60)
    assert v.returncode != 0, (
        "a current-top SDC with no set_input_delay/set_output_delay must STILL "
        "FAIL — the supersede fix must not swallow the defect it sits on top of")
    assert "set_input_delay" in (v.stdout + v.stderr)
