"""`fault chain` cannot parse an `inout` port; the scan-insert program strips
UNCONNECTED inout ports for fault and restores them into fault's output.

Root cause (measured on caravel_user_project x sky130A, fault 0.9.4): the
synthesised `user_project_wrapper` carries `inout [28:0] analog_io;` — the only
bidirectional port. AUCOHL/Fault's `Module.Port.extract` classifies every port
as strictly `.input` or `.output` (its `Port.Polarity` enum has no `inout`
case), so the invariant `ports == inputs + outputs` fails and `fault chain`
aborts at port classification BEFORE building any chain::

    chain.swift: Fatal error: ... RuntimeError("Some ports in
    user_project_wrapper are not properly declared as an input or output.")

`fault chain` produced no scan netlist, so Step 11 (DFT) and Step 12 (post-DFT)
self-skipped as a "disclosed capability gap" — but the ATPG engine was never the
problem; scan INSERTION never ran. Every pad-ring / wrapper / analog-bearing top
with a bidirectional port hits this.

An inout port that carries NO scannable logic (an analog pass-through, an
unbonded pad) can be removed from the netlist fault reads and restored
byte-for-byte into fault's output — lossless, because the chain never touches
it. These tests exercise the SHIPPED pure helpers and assert BEHAVIOUR (the
inout port survives a strip→restore round trip; a connected inout is refused; a
no-inout netlist is untouched), never a source literal. The executed end-to-end
`fault chain` run on the real caravel netlist is the acceptance evidence for the
change; these keep the transform honest without needing Docker.
"""
import re
import sys
from pathlib import Path

SCRIPT = Path(__file__).parent.parent / "fault_scan_chain_insert.py"
assert SCRIPT.exists()

sys.path.insert(0, str(SCRIPT.parent))
import fault_scan_chain_insert as fsci  # noqa: E402


# A caravel-wrapper-shaped yosys NON-ANSI netlist: one unconnected inout
# (analog_io) between two ordinary ports, plus a scalar input/output.
NETLIST_WITH_INOUT = (
    "/* Generated by Yosys */\n"
    "module top(wb_clk_i, io_oeb, analog_io, user_clock2, user_irq);\n"
    "  input wb_clk_i;\n"
    "  wire wb_clk_i;\n"
    "  output io_oeb;\n"
    "  wire io_oeb;\n"
    "  inout [28:0] analog_io;\n"
    "  wire [28:0] analog_io;\n"
    "  input user_clock2;\n"
    "  wire user_clock2;\n"
    "  output user_irq;\n"
    "  wire user_irq;\n"
    "  assign user_irq = wb_clk_i & user_clock2;\n"
    "endmodule\n"
)

NETLIST_NO_INOUT = (
    "module top(a, b);\n"
    "  input a;\n  wire a;\n"
    "  output b;\n  wire b;\n"
    "  assign b = a;\n"
    "endmodule\n"
)

# A CONNECTED inout: the port drives a real cell pin, so it must NOT be stripped.
NETLIST_CONNECTED_INOUT = (
    "module top(clk, pad);\n"
    "  input clk;\n  wire clk;\n"
    "  inout pad;\n  wire pad;\n"
    "  BUF u0 (.A(clk), .Y(pad));\n"
    "endmodule\n"
)


def test_find_inout_ports_locates_the_bidirectional_port():
    found = fsci.find_inout_ports(NETLIST_WITH_INOUT)
    assert set(found) == {"analog_io"}
    assert found["analog_io"] == "inout [28:0] analog_io;"


def test_find_inout_ports_empty_when_none():
    assert fsci.find_inout_ports(NETLIST_NO_INOUT) == {}


def test_port_is_connected_false_for_passthrough_true_for_driven():
    # analog_io appears only in the port list + inout/wire decls -> unconnected
    assert fsci.port_is_connected(NETLIST_WITH_INOUT, "analog_io") is False
    # pad is driven by a cell -> connected
    assert fsci.port_is_connected(NETLIST_CONNECTED_INOUT, "pad") is True


def test_port_list_successor():
    assert fsci.port_list_successor(NETLIST_WITH_INOUT, "analog_io") == \
        "user_clock2"
    assert fsci.port_list_successor(NETLIST_WITH_INOUT, "user_irq") is None
    assert fsci.port_list_successor(NETLIST_WITH_INOUT, "nope") is None


def test_strip_removes_port_from_header_and_decls():
    stripped = fsci.strip_inout_ports(NETLIST_WITH_INOUT, ["analog_io"])
    # gone from the module header port list
    hdr = re.search(r"^module\s+\w+\s*\((.*?)\)\s*;", stripped, re.M | re.S)
    names = [p.strip() for p in hdr.group(1).split(",")]
    assert "analog_io" not in names
    # the surviving ports keep their order
    assert names == ["wb_clk_i", "io_oeb", "user_clock2", "user_irq"]
    # inout declaration line is gone; the other ports' decls are intact
    assert "inout [28:0] analog_io;" not in stripped
    assert "input wb_clk_i;" in stripped
    # fault would now accept it: no inout port remains
    assert fsci.find_inout_ports(stripped) == {}


def test_strip_is_a_noop_when_no_inout():
    assert fsci.strip_inout_ports(NETLIST_NO_INOUT, []) == NETLIST_NO_INOUT


def test_strip_then_restore_round_trips_the_inout_port():
    decls = fsci.find_inout_ports(NETLIST_WITH_INOUT)
    successors = {n: fsci.port_list_successor(NETLIST_WITH_INOUT, n)
                  for n in decls}
    stripped = fsci.strip_inout_ports(NETLIST_WITH_INOUT, list(decls))
    # Simulate `fault chain` output: it appends DFT ports to the header. The
    # important property is that our restore puts analog_io back regardless.
    faultish = stripped.replace(
        "module top(wb_clk_i, io_oeb, user_clock2, user_irq);",
        "module top(wb_clk_i, io_oeb, user_clock2, user_irq, sin, sout);")
    restored = fsci.restore_inout_ports(faultish, decls, successors)
    # the inout port is back in the header, at its original position (before its
    # successor user_clock2), and declared as inout with its exact width
    hdr = re.search(r"^module\s+\w+\s*\((.*?)\)\s*;", restored, re.M | re.S)
    names = [p.strip() for p in hdr.group(1).split(",")]
    assert names.index("analog_io") == names.index("user_clock2") - 1
    assert fsci.find_inout_ports(restored) == {"analog_io":
                                               "inout [28:0] analog_io;"}


def test_restore_ignores_identifier_inside_a_metadata_comment():
    # `fault chain` emits a /* FAULT METADATA ... */ comment that mentions every
    # port name (incl. the successor). Header surgery must not be hit there.
    decls = {"analog_io": "inout [28:0] analog_io;"}
    successors = {"analog_io": "user_clock2"}
    chained = (
        '/* FAULT METADATA: {"order":[{"name":"user_clock2"}]} '
        'END FAULT METADATA */\n'
        "module top(wb_clk_i, user_clock2);\n"
        "  input wb_clk_i;\n  wire wb_clk_i;\n"
        "  input user_clock2;\n  wire user_clock2;\n"
        "endmodule\n"
    )
    restored = fsci.restore_inout_ports(chained, decls, successors)
    # exactly ONE header insertion — the comment's user_clock2 is untouched
    hdr = re.search(r"^module\s+\w+\s*\((.*?)\)\s*;", restored, re.M | re.S)
    names = [p.strip() for p in hdr.group(1).split(",")]
    assert names == ["wb_clk_i", "analog_io", "user_clock2"]
    # the metadata comment still reads exactly as fault wrote it
    assert '{"name":"user_clock2"}' in restored
    assert restored.count("analog_io") == 2  # header entry + inout decl only
