"""tests/test_analog_a1_a4_flow_declared_layout.py

PR #465 follow-up. #465 taught the A1-A4 gates to resolve a per-block
ARTEFACT under more than one analog root, but left the BLOCK LIST that gates
access to those artefacts readable at exactly one path — so on the only two
layouts a real producer creates, every one of #465's three fixes was
unreachable.

MEASURED on main @ bd2e11520 (v1.7.58), project laid out exactly as
flow/phase1_phase2_phase3.yaml declares (block list at
`phase1/analog/analog_block_list.json` — the path EVERY A-step's
`condition:` pins — A1's spec at `phase1/analog/<blk>/`, A2-A4's artefacts at
`phase2/analog/<blk>/`, a second block declared with nothing):

    analog_a1_spec_extract_check <proj>  -> rc=0 VACUOUS_PASS
      "phase3/analog/analog_block_list.json missing or empty;
       gate inapplicable."
    ... identical for a2 / a3 / a4.

i.e. the flow ACTIVATED A1-A4 (their condition reads the phase1 copy) and
then accepted a rc=0 from four gates that had loaded no block list at all.
#465's newly wired blocking A3 sub-gate was tautological there: it cannot
reach a non-zero exit on the layout the flow declares.

The second real layout is the one `migrate_to_layout_p.py` produces. MEASURED
by running the production migrator on a pre-v2 project: it emits exactly two
moves — `analog/analog_block_list.json -> phase1/analog/...` and
`analog/<block> -> phase2/analog/<block>`. `_classify_analog_block` picks ONE
most-backend destination for the WHOLE block dir, so A1's spec.json lands
under `phase2/analog/`, NOT the `phase1/analog/` the flow declares as A1's
required_output — which #465's {canonical, declared-phase} candidate pair
also missed.

These tests build both layouts with the block list where its OWN producer
puts it (the migrator layout is built by INVOKING the production migrator),
never the phase3-list / phase1-artefact hybrid that no producer creates.

Run: PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 python3 -m pytest tests/<this file>
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

PROGRAMS = Path(__file__).resolve().parent.parent

A1 = PROGRAMS / "analog_a1_spec_extract_check.py"
A2 = PROGRAMS / "analog_a2_topology_select_check.py"
A3 = PROGRAMS / "analog_a3_netlist_gen_check.py"
A4 = PROGRAMS / "analog_a4_corner_sweep_check.py"
MIGRATE = PROGRAMS / "migrate_to_layout_p.py"

# (gate program, artefact filename, root the flow declares for that step)
GATES = [
    pytest.param(A1, "spec.json", "phase1/analog", id="A1"),
    pytest.param(A2, "topology.md", "phase2/analog", id="A2"),
    pytest.param(A3, "{block}.sp", "phase2/analog", id="A3"),
    pytest.param(A4, "corner_results.json", "phase2/analog", id="A4"),
]

_TOPOLOGY = (
    "# Topology\n\n"
    "Two-stage differential amplifier: an NMOS differential pair with a PMOS "
    "current mirror load, a common-source output stage, and Miller feedback "
    "compensation. Tail bias comes from a widlar reference. The dominant pole "
    "sits at the first stage; the right-half-plane zero is cancelled by a "
    "nulling resistor sized against the load capacitor.\n"
)
_NETLIST = (
    "* block netlist\n"
    '.include "design.ngspice"\n'
    ".subckt {block} VDD VSS VOUT VREF EN\n"
    + "M1 net1 VREF VSS VSS nmos w=2u l=0.18u\n" * 6
    + ".ends {block}\n.end\n"
)
# >200 bytes, has `.subckt`, ZERO device cards inside the body: the
# placeholder shape A3_NETLIST_NO_DEVICES exists to reject.
_EMPTY_SHELL = (
    "* {block} — SPICE netlist\n"
    "* Generated by the analog-netlist-gen skill.\n"
    "* PDK model library include:\n"
    '.include "design.ngspice"\n'
    "*\n"
    "* Interface: vdd (supply), vss (ground), vin (input), vout (output)\n"
    "*\n"
    ".subckt {block} vdd vss vin vout\n"
    "* --- device instantiations go here ---\n"
    ".ends {block}\n"
    ".end\n"
)
_CORNERS = {
    "_provenance": "real_ngspice",
    "best_corner": {"name": "tt_27"},
    "corners": [
        {"name": "tt_27", "simulator_run": True, "vout_v": 1.2},
        {"name": "ss_125", "simulator_run": True, "vout_v": 1.21},
        {"name": "ff_m40", "simulator_run": True, "vout_v": 1.19},
    ],
    "spec_results": [
        {"name": "vout", "status": "PASS", "target": 1.2,
         "tolerance_pct": 0.05},
    ],
}


# ── fixture helpers ────────────────────────────────────────────────────────

def _write_block_list(project: Path, blocks: list, root: str) -> None:
    d = project / root
    d.mkdir(parents=True, exist_ok=True)
    (d / "analog_block_list.json").write_text(json.dumps({"blocks": blocks}))


def _write_artefact(project: Path, block: str, filename: str,
                    root: str) -> None:
    name = filename.format(block=block)
    d = project / root / block
    d.mkdir(parents=True, exist_ok=True)
    if name == "spec.json":
        (d / name).write_text(json.dumps(
            {"specs": [{"name": "vout", "typ": 1.2, "min": 1.1, "max": 1.3}]}))
    elif name == "topology.md":
        (d / name).write_text(_TOPOLOGY)
    elif name == "corner_results.json":
        (d / name).write_text(json.dumps(_CORNERS))
    elif name.endswith(".sp"):
        (d / name).write_text(_NETLIST.format(block=block))
    else:                                       # pragma: no cover
        raise AssertionError(f"unhandled artefact {name}")


def _all_artefacts(project: Path, block: str, root: str) -> None:
    """Every A1-A4 artefact for one block under a SINGLE root — the shape a
    pre-v2 `analog/<block>/` dir has, and therefore the shape
    `migrate_to_layout_p.py` relocates as one unit."""
    for _prog, filename, _declared in [(p.values[0], p.values[1], p.values[2])
                                       for p in GATES]:
        _write_artefact(project, block, filename, root)


def _run(prog: Path, project: Path, *args: str,
         report: str = "report.json") -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(prog), str(project),
         "--json", str(project / report), *args],
        capture_output=True, text=True)


def _report(project: Path, report: str = "report.json") -> dict:
    return json.loads((project / report).read_text())


def _flow_declared_project(project: Path) -> None:
    """The layout flow/phase1_phase2_phase3.yaml declares: block list where
    every A-step's `condition:` pins it, A1's spec at phase1/analog, A2-A4's
    artefacts at phase2/analog. `blk_none` is declared and produces nothing."""
    _write_block_list(project, ["blk_ok", "blk_none"], "phase1/analog")
    for param in GATES:
        _prog, filename, declared_root = param.values
        _write_artefact(project, "blk_ok", filename, declared_root)


def _migrated_project(project: Path, blocks: list) -> None:
    """A pre-v2 project put through the PRODUCTION migrator. Only the FIRST
    block gets artefacts; the rest are declared and empty."""
    _write_block_list(project, blocks, "analog")
    _all_artefacts(project, blocks[0], "analog")
    cp = subprocess.run(
        [sys.executable, str(MIGRATE), str(project), "--no-git"],
        capture_output=True, text=True)
    assert cp.returncode == 0, (cp.stdout, cp.stderr)


# ══════════════════════════════════════════════════════════════════════════
# DISCRIMINATORS — the block list must be found where its producers write it
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_flow_declared_layout_reaches_the_incomplete_verdict(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Flow-declared layout, 1 of 2 declared blocks covered → rc=1 INCOMPLETE.

    On main every one of these is rc=0 VACUOUS_PASS "phase3/analog/
    analog_block_list.json missing or empty; gate inapplicable" — the gate
    certifies the step having loaded no block list.
    """
    _flow_declared_project(tmp_path)
    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "INCOMPLETE", rpt
    assert rpt["blocks_checked"] == 2, rpt
    assert rpt["incomplete_blocks"] == ["blk_none"], rpt
    assert "blk_none" in r.stderr


def test_a3_substance_gate_is_not_tautological_on_the_declared_layout(
        tmp_path: Path) -> None:
    """The blocking A3 sub-gate must have a reachable non-zero exit on the
    layout the flow declares.

    Step A3 IS active there (its `condition:` reads
    `phase1/analog/analog_block_list.json`) and its `files_exist` leg IS
    satisfied (`phase2/analog/*/*.sp` matches), so the wired-in
    `program_exit_zero: analog_a3_netlist_gen_check` runs — and on main it
    returns 0 no matter what the deck contains. Here a device-free `.subckt`
    shell sitting at exactly the path A3's `required_outputs` names must FAIL
    with A3_NETLIST_NO_DEVICES.
    """
    _write_block_list(tmp_path, ["blk_ok"], "phase1/analog")
    d = tmp_path / "phase2/analog/blk_ok"
    d.mkdir(parents=True, exist_ok=True)
    body = _EMPTY_SHELL.format(block="blk_ok")
    (d / "blk_ok.sp").write_text(body)
    assert len(body.encode()) > 200, "fixture must clear the size rule"

    r = _run(A3, tmp_path)
    assert r.returncode == 1, (r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "FAIL", rpt
    finding = next(f for f in rpt["findings"]
                   if f["rule"] == "A3_NETLIST_NO_DEVICES")
    assert finding["rel_path"].startswith("phase2/analog/"), finding


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_migrator_produced_layout_is_measured(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """A project put through the PRODUCTION `migrate_to_layout_p.py` is
    measured, not skipped.

    The migrator moves the block list to `phase1/analog/` and the WHOLE block
    dir to `phase2/analog/` — including A1's spec.json, which the flow
    declares at `phase1/analog/`. Both halves have to be tolerated or A1
    reads its own migrated spec as MISSING.
    """
    _migrated_project(tmp_path, ["blk_ok", "blk_none"])
    assert (tmp_path / "phase1/analog/analog_block_list.json").is_file()
    assert (tmp_path / "phase2/analog/blk_ok/spec.json").is_file(), \
        "migrator no longer lands the spec under phase2 — re-derive this test"

    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "INCOMPLETE", rpt
    assert rpt["blocks_pass"] == 1, rpt
    assert rpt["incomplete_blocks"] == ["blk_none"], rpt


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_migrator_produced_layout_full_coverage_passes(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Same migrated layout, every declared block covered → rc=0 PASS with
    the block actually MEASURED (blocks_pass == 1), not a VACUOUS_PASS.

    Direction check on the widening: it must not turn a complete migrated
    project red, and it must not leave it certified-without-reading either.
    """
    _migrated_project(tmp_path, ["blk_ok"])
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "PASS", rpt
    assert rpt["blocks_pass"] == 1, rpt
    assert rpt["blocks_missing"] == 0, rpt


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_legacy_pre_v2_analog_root_is_read(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """A pre-v2 project that has NOT been migrated (everything under the
    top-level `analog/`) is measured too — the third location
    `analog_block_list_emit_check._PROJECT_GLOBS` already probes."""
    _write_block_list(tmp_path, ["blk_ok", "blk_none"], "analog")
    _all_artefacts(tmp_path, "blk_ok", "analog")
    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "INCOMPLETE", rpt
    assert rpt["incomplete_blocks"] == ["blk_none"], rpt


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_block_mode_still_defers_on_the_declared_layout(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """`--block <uncovered>` on the flow-declared layout → rc=2 WAIVED.

    On main this is rc=0 VACUOUS_PASS: the block list was not found, so the
    gate never even got to the deferral. rc=2 is what
    `analog_one_shot_runner` translates into a deferral, so the runner's
    contract is preserved on this layout rather than replaced by a silent
    green.
    """
    _flow_declared_project(tmp_path)
    r = _run(prog, tmp_path, "--block", "blk_none")
    assert r.returncode == 2, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "WAIVED", rpt
    assert rpt["suggested_skill"]


def test_vacuous_reason_names_every_location_probed(tmp_path: Path) -> None:
    """The VACUOUS_PASS reason must not claim a single path was the only one
    looked at. On main it reads
    "phase3/analog/analog_block_list.json missing or empty" while the gate's
    own step condition pins the phase1 copy — a message that told the reader
    the gate had checked somewhere it had not."""
    r = _run(A1, tmp_path)
    assert r.returncode == 0, (r.stdout, r.stderr)
    reason = _report(tmp_path)["reason"]
    for rel in ("phase3/analog/analog_block_list.json",
                "phase1/analog/analog_block_list.json",
                "analog/analog_block_list.json"):
        assert rel in reason, (rel, reason)


# ══════════════════════════════════════════════════════════════════════════
# DIRECTION-1 GUARDS — must pass on BOTH trees
# ══════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_canonical_runner_layout_unchanged(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """The layout `analog_one_shot_runner` writes (block list AND every
    artefact under `phase3/analog/`) keeps its exact verdict."""
    _write_block_list(tmp_path, ["blk_ok"], "phase3/analog")
    _write_artefact(tmp_path, "blk_ok", filename, "phase3/analog")
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    rpt = _report(tmp_path)
    assert rpt["verdict"] == "PASS", rpt
    assert rpt["blocks_pass"] == 1


# What each gate names as the `rel_path` of an artefact that exists at NO
# candidate. Byte-identical to what the pre-#465 tree reported: A1-A3 name the
# canonical runner path, A4 keeps its own legacy `analog/<block>/...` literal
# (predates #465 — `analog_a4_corner_sweep_check.py:139`). Pinned per gate so
# widening the candidate list cannot silently change what an operator is told
# to go create.
_MISSING_REL_PREFIX = {
    "analog_a1_spec_extract_check.py": "phase3/analog/",
    "analog_a2_topology_select_check.py": "phase3/analog/",
    "analog_a3_netlist_gen_check.py": "phase3/analog/",
    "analog_a4_corner_sweep_check.py": "analog/",
}


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_missing_artefact_rel_path_is_unchanged(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """When NO candidate exists the reported `rel_path` is exactly what these
    gates have always named. Widening the candidate list must not change what
    an operator is told to go create."""
    _write_block_list(tmp_path, ["blk_ok", "blk_none"], "phase3/analog")
    _write_artefact(tmp_path, "blk_ok", filename, "phase3/analog")
    r = _run(prog, tmp_path)
    assert r.returncode == 1, (prog.name, r.stdout, r.stderr)
    findings = _report(tmp_path)["findings"]
    miss = [f for f in findings if f.get("block") == "blk_none"]
    assert miss, findings
    want = _MISSING_REL_PREFIX[prog.name]
    assert all(f["rel_path"] == f"{want}blk_none/{filename.format(block='blk_none')}"
               for f in miss), (want, miss)


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_explicit_empty_canonical_list_wins_over_a_stale_sibling(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """An explicit `[]` at the CANONICAL path is the runner's documented
    "pure-digital, skip on purpose" signal (`_load_block_list_with_status`
    status=="empty"). A stale sibling copy at `phase1/analog` must NOT
    resurrect it — first EXISTING file wins, not first non-empty."""
    _write_block_list(tmp_path, [], "phase3/analog")
    _write_block_list(tmp_path, ["ghost_a", "ghost_b"], "phase1/analog")
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "VACUOUS_PASS"


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_no_analog_anywhere_stays_vacuous_pass(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Pure-digital project — no block list under ANY probed root."""
    (tmp_path / "phase2/stage3").mkdir(parents=True, exist_ok=True)
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "VACUOUS_PASS"


@pytest.mark.parametrize("prog,filename,declared_root", GATES)
def test_guard_all_blocks_missing_on_declared_layout_stays_vacuous_pass(
        tmp_path: Path, prog: Path, filename: str, declared_root: str
) -> None:
    """Block list present at the flow-declared path but NO block has any
    artefact → VACUOUS_PASS rc=0, the "the skill has not run yet, defer to
    it" contract. Finding the list must not convert a not-yet-started step
    into a blocking INCOMPLETE."""
    _write_block_list(tmp_path, ["a", "b"], "phase1/analog")
    r = _run(prog, tmp_path)
    assert r.returncode == 0, (prog.name, r.stdout, r.stderr)
    assert _report(tmp_path)["verdict"] == "VACUOUS_PASS"
