"""test_lec_functional_mode_scan.py — controls for the step-13 scan comparison.

Step 13 is `RTL == post-DFT netlist`, and its artefact is shared by EVERY IC.
So the property that matters most here is not that a scan netlist can pass —
it is that the constraints which let it pass CANNOT make a broken netlist pass,
and that a design with no scan chain is byte-unchanged.

MEASURED FACTS these tests encode (spm x sky130A, yosys 0.67+, image 0.2.45):

  * `equiv_make` HARD-ERRORS on a gate port with no gold counterpart:
    "ERROR: Can't match gate port `test_gate' to a gold port."  So the DFT
    ports must be REMOVED, not merely tied off.
  * `fault chain` resynthesises and prefixes every internal wire (`__uuf__.`),
    which drops the miter from 97 compared points to 1 and sends equiv_induct
    into a non-converging wall.  Mirroring the prefix onto the gold restores
    it: 63 points, all proven, "Equivalence successfully proven!", 0.48 s.
  * Tying `test` to 1 instead of 0 → 0 of 63 proven.  Tying `shift` to 1 →
    32 unproven.  A one-gate `nor2_1`→`nand2_1` corruption → 1 unproven.
    None of the three passes, so the constraints are not vacuous.

Every test below is written to FAIL against a specific way of getting this
wrong; the mutation each one kills is named in its docstring.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROGRAMS = Path(__file__).resolve().parents[1]
if str(PROGRAMS) not in sys.path:
    sys.path.insert(0, str(PROGRAMS))

import lec_run                                  # noqa: E402


SCAN_NETLIST = """\
/* Generated by Yosys */
module spm(clk, rst, x, y, p, sin, shift, sout, tck, test);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [31:0] x;
  wire [31:0] x;
  input y;
  wire y;
  output p;
  wire p;
  input sin;
  input shift;
  output sout;
  input tck;
  input test;
  wire \\__uuf__.creg[0] ;
endmodule
"""

GOOD_META = {
    "published": True,
    "functional_mode_tieoff": {"sin": 0, "shift": 0, "test": 0, "tck": 0},
    "scan_out_port": "sout",
    "internal_wire_prefix": "__uuf__",
}


class TestScanModeOnlyFiresOnAPublishedChain:
    """KILLS: wrapping a netlist that has no DFT ports.

    A wrapper emitted over a non-scan netlist would tie off ports that do not
    exist and drop an output that does not exist — the yosys read would fail,
    or worse, succeed against something that is not the artefact named in the
    report.  `published` is the scan producer's own MEASURED flag; it is the
    only thing allowed to turn this on.
    """

    def test_published_chain_is_accepted(self):
        sm = lec_run.scan_mode_from_meta(GOOD_META)
        assert sm is not None
        assert sm["tieoff"] == {"sin": 0, "shift": 0, "test": 0, "tck": 0}
        assert sm["scan_out_port"] == "sout"
        assert sm["internal_prefix"] == "__uuf__"

    @pytest.mark.parametrize("mutate", [
        lambda m: {**m, "published": False},
        lambda m: {k: v for k, v in m.items() if k != "published"},
        lambda m: {**m, "functional_mode_tieoff": {}},
        lambda m: {k: v for k, v in m.items() if k != "scan_out_port"},
    ], ids=["unpublished", "no-published-key", "empty-tieoff", "no-sout"])
    def test_incomplete_metadata_never_wraps(self, mutate):
        assert lec_run.scan_mode_from_meta(mutate(GOOD_META)) is None

    def test_non_dict_never_wraps(self):
        assert lec_run.scan_mode_from_meta(None) is None
        assert lec_run.scan_mode_from_meta([]) is None

    def test_unmeasurable_prefix_is_none_not_a_guess(self):
        """A missing prefix must NOT be substituted.  It costs compared points,
        which is visible; a wrong one is silent."""
        sm = lec_run.scan_mode_from_meta(
            {**GOOD_META, "internal_wire_prefix": None})
        assert sm is not None and sm["internal_prefix"] is None


class TestInterfaceComesFromTheNetlist:
    """KILLS: guessing the wrapper's port list.

    The wrapper must present exactly the gold's interface.  It is derived from
    the scan netlist's own header minus the DFT ports, which is that interface
    by construction, because `fault chain` only ADDS ports.
    """

    def test_dft_ports_are_dropped_and_the_rest_kept_in_order(self):
        ports = lec_run.netlist_top_ports(
            SCAN_NETLIST, "spm",
            exclude=["sin", "shift", "test", "tck", "sout"])
        assert [n for _, _, n in ports] == ["clk", "rst", "x", "y", "p"]
        assert dict((n, d) for d, _, n in ports) == {
            "clk": "input", "rst": "input", "x": "input",
            "y": "input", "p": "output"}

    def test_vector_range_is_preserved(self):
        ports = lec_run.netlist_top_ports(SCAN_NETLIST, "spm")
        rng = {n: r.strip() for _, r, n in ports}
        assert rng["x"] == "[31:0]"
        assert rng["clk"] == ""

    def test_unknown_top_yields_nothing_rather_than_a_guess(self):
        assert lec_run.netlist_top_ports(SCAN_NETLIST, "not_the_top") == []


class TestWrappersRestoreTheComparison:
    """KILLS the two measured obstacles, each independently."""

    def _wrappers(self, meta=None):
        sm = lec_run.scan_mode_from_meta(meta or GOOD_META)
        ports = lec_run.netlist_top_ports(
            SCAN_NETLIST, "spm", exclude=["sin", "shift", "test", "tck", "sout"])
        return lec_run.build_scan_wrappers("spm", ports, sm)

    def test_gate_wrapper_ties_every_control_and_drops_sout(self):
        """KILLS: leaving a DFT port in the gate's port list.  MEASURED: yosys
        aborts with "Can't match gate port `test_gate' to a gold port"."""
        gate, _ = self._wrappers()
        assert "module spm(clk, rst, x, y, p);" in gate
        for port in ("sin", "shift", "test", "tck"):
            assert f".{port}(1'b0)" in gate, port
        assert ".sout()" in gate               # dangling, not compared
        assert "spm__scan" in gate

    def test_gate_wrapper_uses_the_metadatas_values_not_hardcoded_zeros(self):
        """KILLS: hard-coding 0.  The negative controls flip a value to 1 and
        require the comparison to FAIL; if the builder ignored the metadata
        those controls would silently test nothing."""
        gate, _ = self._wrappers(
            {**GOOD_META,
             "functional_mode_tieoff": {"sin": 0, "shift": 0,
                                        "test": 1, "tck": 0}})
        assert ".test(1'b1)" in gate
        assert ".shift(1'b0)" in gate

    def test_gold_wrapper_reproduces_the_gates_flatten_prefix(self):
        """KILLS: omitting the prefix mirror.  MEASURED: without it the miter
        drops from 63 proven points to 1 unproven one and never converges."""
        _, gold = self._wrappers()
        assert f"\\{lec_run._LEC_WRAP_INST}.__uuf__ (" in gold
        assert "spm__rtl" in gold

    def test_gold_wrapper_without_a_prefix_still_wraps(self):
        """An unmeasurable prefix costs points, it does not disable the DFT
        port removal — which is the part that is not optional."""
        _, gold = self._wrappers({**GOOD_META, "internal_wire_prefix": None})
        assert f"\\{lec_run._LEC_WRAP_INST} (" in gold
        assert "__uuf__" not in gold

    def test_both_wrappers_present_the_same_interface(self):
        gate, gold = self._wrappers()
        head = "module spm(clk, rst, x, y, p);"
        assert head in gate and head in gold


class TestNoScanRunIsByteUnchanged:
    """KILLS: any change to the script a NON-scan design gets.

    Step 13's artefact is shared by every IC.  A scan feature that perturbs the
    script for designs with no scan chain would move verdicts across the whole
    fleet.  Byte-equality is the only assertion strong enough here — measured
    against stock `origin/main` lec_run as well (md5 4bca3eff6d96b35adacc51f1a4010c9d).
    """

    def _script(self, **kw):
        return lec_run.build_equiv_script(
            ["/w/rtl/spm.v"], "/w/synth/netlist.v", "spm",
            "/pdk/sky130_fd_sc_hd__tt_025C_1v80.lib", **kw)

    def test_default_call_emits_no_wrapper_commands(self):
        s = self._script()
        for token in ("__scan", "__rtl", "lec_scan_gate_wrapper",
                      "lec_scan_gold_wrapper", "rename spm"):
            assert token not in s, token

    def test_scan_mode_without_wrapper_files_changes_nothing(self):
        """All three inputs are required together.  A gold wrapper without a
        gate wrapper would compare the RTL against nothing; a gate wrapper
        without a gold one would leave the prefixes unmirrored."""
        base = self._script()
        assert self._script(scan_mode=lec_run.scan_mode_from_meta(GOOD_META)) \
            == base
        assert self._script(gate_wrapper_v="/w/g.v") == base
        assert self._script(scan_mode=lec_run.scan_mode_from_meta(GOOD_META),
                            gate_wrapper_v="/w/g.v") == base

    def test_scan_mode_with_both_wrappers_does_change_the_script(self):
        """The counter-control: if this passed too, every assertion above would
        be vacuous."""
        s = self._script(scan_mode=lec_run.scan_mode_from_meta(GOOD_META),
                         gate_wrapper_v="/w/g.v", gold_wrapper_v="/w/gd.v")
        assert s != self._script()
        assert "rename spm spm__rtl" in s
        assert "rename spm spm__scan" in s
        assert "read_verilog -sv /w/g.v" in s
        assert "read_verilog -sv /w/gd.v" in s

    def test_the_gate_netlist_read_is_never_replaced(self):
        """KILLS the one shortcut that must never be taken: making step 13 pass
        by comparing a DIFFERENT netlist.  The scan path only ADDS a wrapper
        around the same file."""
        s = self._script(scan_mode=lec_run.scan_mode_from_meta(GOOD_META),
                         gate_wrapper_v="/w/g.v", gold_wrapper_v="/w/gd.v")
        assert "/w/synth/netlist.v" in s
        assert "_synth.v" not in s.replace("/w/synth/netlist.v", "")

    def test_wrapper_reads_are_ordered_after_their_renames(self):
        """The rename must precede the wrapper read on each side, or the
        wrapper's `module spm` collides with the netlist's."""
        s = self._script(scan_mode=lec_run.scan_mode_from_meta(GOOD_META),
                         gate_wrapper_v="/w/g.v", gold_wrapper_v="/w/gd.v")
        assert s.index("rename spm spm__rtl") < s.index("/w/gd.v")
        assert s.index("rename spm spm__scan") < s.index("/w/g.v")
        assert s.index("/w/gd.v") < s.index("prep -top spm")
        assert s.index("/w/g.v") < s.index("hierarchy -check -top spm")
