#!/usr/bin/env python3
"""Tests for generated_artifact_conflict_resolve.py (vibe-ic#1363).

BOTH DIRECTIONS, and the red one is the one that matters
========================================================
The green direction — a conflict on nothing but a derived artefact is resolved
by regenerating it — is the cheap half. The half that has to hold is the RED
one: a resolver that resolves everything is not a fix, it is a silent
`checkout --theirs` with better manners. So the negative controls are:

    a foreign path conflicts alone          REFUSE
    a foreign path conflicts ALONGSIDE the  REFUSE, and the derived file is left
      derived one                             UNTOUCHED — no partial resolution
    the regenerator exits non-zero          UNMEASURABLE, never RESOLVED
    the regenerator's own --check stays red UNMEASURABLE
    markers survive regeneration            UNMEASURABLE
    nothing is conflicted at all            UNMEASURABLE

Each drives a REAL git repository with a REAL conflict — none of them assert
about source text.

The synthetic artefact is deliberately NOT `programs/INDEX.md`: the real
generator measures 25-28s warm and over 60s cold, and the freshness of the real
INDEX is already pinned by `test_programs_index_freshness.py` in the SMOKE
floor. Duplicating that cost here would buy nothing. What IS asserted about the
real registry entry is that it points at the real file and the real generator —
`test_real_registry_entry_is_coherent`.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from _plugin_tree import plugin_path, repo_path_or_missing

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import generated_artifact_conflict_resolve as G  # noqa: E402

TIMEOUT = 60


# ─── a synthetic derived artefact, so the tests stay fast ───────────
GEN_SRC = '''#!/usr/bin/env python3
"""Synthetic generator: CATALOG.md is the sorted list of items/*.txt."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "CATALOG.md"


def render() -> str:
    names = sorted(p.stem for p in (ROOT / "items").glob("*.txt"))
    lines = ["<!-- AUTO-GENERATED by gen.py - DO NOT EDIT BY HAND -->", ""]
    lines += [f"- {n}" for n in names]
    lines += ["", f"Total: {len(names)}"]
    return "\\n".join(lines) + "\\n"


def main() -> int:
    want = render()
    if "--check" in sys.argv:
        have = OUT.read_text() if OUT.exists() else ""
        if have != want:
            print("CATALOG.md is stale", file=sys.stderr)
            return 1
        print("[PASS] CATALOG.md fresh")
        return 0
    OUT.write_text(want)
    print(f"wrote CATALOG.md ({len(want.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

ART = G.DerivedArtifact(
    path="CATALOG.md",
    generator="gen.py",
    regenerate=("python3", "gen.py"),
    check=("python3", "gen.py", "--check"),
)
FAKE_REGISTRY = (ART,)


def _run(repo: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ("git", "-C", str(repo)) + args,
        capture_output=True, text=True, timeout=TIMEOUT,
    )


def _regen(repo: Path) -> None:
    cp = subprocess.run(
        ("python3", "gen.py"), cwd=str(repo),
        capture_output=True, text=True, timeout=TIMEOUT,
    )
    assert cp.returncode == 0, cp.stderr


def _commit(repo: Path, msg: str) -> None:
    assert _run(repo, "add", "-A").returncode == 0
    cp = _run(repo, "commit", "-q", "-m", msg)
    assert cp.returncode == 0, cp.stderr


@pytest.fixture
def repo(tmp_path: Path) -> Path:
    """A repo whose CATALOG.md is derived, plus a hand-written file.

    `main` already holds one item, so the two branches below add
    ALPHABETICALLY ADJACENT items — which is what actually collides. Two
    far-apart additions 3-way-merge cleanly and would make this test pass
    for the wrong reason.
    """
    r = tmp_path / "repo"
    (r / "items").mkdir(parents=True)
    (r / "gen.py").write_text(GEN_SRC)
    (r / "hand_written.txt").write_text("base line\n")
    (r / "items" / "aaa.txt").write_text("aaa\n")
    _regen(r)
    assert _run(r, "init", "-q", "-b", "main").returncode == 0
    _run(r, "config", "user.email", "t@localhost")
    _run(r, "config", "user.name", "t")
    _commit(r, "base")
    return r


def _branch_adding(repo: Path, branch: str, item: str, *,
                   also_edit_hand_written: str | None = None) -> None:
    assert _run(repo, "checkout", "-q", "-B", branch, "main").returncode == 0
    (repo / "items" / f"{item}.txt").write_text(f"{item}\n")
    if also_edit_hand_written is not None:
        (repo / "hand_written.txt").write_text(also_edit_hand_written)
    _regen(repo)
    _commit(repo, f"add {item}")
    assert _run(repo, "checkout", "-q", "main").returncode == 0


def _markers(p: Path) -> int:
    return sum(
        1 for line in p.read_text().splitlines() if line.startswith("<<<<<<< ")
    )


# ─── the decision, with no side effects ─────────────────────────────
def test_decide_empty_is_unmeasurable_not_resolved():
    """A resolver invoked with nothing conflicted has NOT resolved anything."""
    v = G.decide([], FAKE_REGISTRY)
    assert v.code == 2
    assert "no conflicted path" in v.reason


def test_decide_only_registered_is_resolvable():
    v = G.decide(["CATALOG.md"], FAKE_REGISTRY)
    assert v.code == 0
    assert v.derived == ("CATALOG.md",) and v.foreign == ()


def test_decide_foreign_alone_refuses_and_names_it():
    v = G.decide(["src/real.py"], FAKE_REGISTRY)
    assert v.code == 1
    assert v.foreign == ("src/real.py",)


def test_decide_mixed_refuses_the_whole_resolution():
    """The derived half must NOT be reported resolvable when a real conflict
    rides along — that is the shape that hides the real one."""
    v = G.decide(["CATALOG.md", "src/real.py"], FAKE_REGISTRY)
    assert v.code == 1
    assert v.foreign == ("src/real.py",)
    assert v.derived == ("CATALOG.md",)   # seen, and deliberately not resolved


# ─── end to end, on real git conflicts ──────────────────────────────
def test_green_derived_only_conflict_is_resolved(repo: Path):
    _branch_adding(repo, "b1", "aab")
    _branch_adding(repo, "b2", "aac")
    assert _run(repo, "merge", "--no-edit", "b1").returncode == 0

    m = _run(repo, "merge", "--no-edit", "b2")
    assert m.returncode != 0, "the repro must actually conflict"
    conflicted = G.conflicted_paths(repo)
    assert conflicted == ("CATALOG.md",), conflicted
    assert _markers(repo / "CATALOG.md") == 1

    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 0, v.reason
    assert v.staged == ["CATALOG.md"]
    assert _markers(repo / "CATALOG.md") == 0
    assert G.conflicted_paths(repo) == ()
    # both sides' items survived — regeneration recomputed, it did not pick
    body = (repo / "CATALOG.md").read_text()
    assert "- aab" in body and "- aac" in body
    # and the merge can now be completed
    assert _run(repo, "commit", "-q", "--no-edit").returncode == 0
    chk = subprocess.run(("python3", "gen.py", "--check"), cwd=str(repo),
                         capture_output=True, text=True, timeout=TIMEOUT)
    assert chk.returncode == 0, chk.stderr


def test_red_foreign_conflict_alone_is_refused(repo: Path):
    """The negative control for the whole program."""
    assert _run(repo, "checkout", "-q", "-B", "h1", "main").returncode == 0
    (repo / "hand_written.txt").write_text("branch one says this\n")
    _commit(repo, "h1")
    assert _run(repo, "checkout", "-q", "main").returncode == 0
    (repo / "hand_written.txt").write_text("main says something else\n")
    _commit(repo, "main edit")

    m = _run(repo, "merge", "--no-edit", "h1")
    assert m.returncode != 0
    assert G.conflicted_paths(repo) == ("hand_written.txt",)

    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 1, v.reason
    assert v.foreign == ("hand_written.txt",)
    # untouched: still conflicted, still marked
    assert G.conflicted_paths(repo) == ("hand_written.txt",)
    assert _markers(repo / "hand_written.txt") == 1


def test_red_mixed_conflict_leaves_the_derived_file_untouched(repo: Path):
    """A real conflict alongside the derived one must refuse BOTH — a
    half-resolved tree makes the real conflict look smaller than it is."""
    _branch_adding(repo, "b1", "aab", also_edit_hand_written="from b1\n")
    _branch_adding(repo, "b2", "aac", also_edit_hand_written="from b2\n")
    assert _run(repo, "merge", "--no-edit", "b1").returncode == 0

    m = _run(repo, "merge", "--no-edit", "b2")
    assert m.returncode != 0
    assert set(G.conflicted_paths(repo)) == {"CATALOG.md", "hand_written.txt"}

    before = (repo / "CATALOG.md").read_bytes()
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 1, v.reason
    assert v.foreign == ("hand_written.txt",)
    assert v.regenerated == [] and v.staged == []
    assert (repo / "CATALOG.md").read_bytes() == before
    assert set(G.conflicted_paths(repo)) == {"CATALOG.md", "hand_written.txt"}


def test_dry_run_reports_the_verdict_and_changes_nothing(repo: Path):
    _branch_adding(repo, "b1", "aab")
    _branch_adding(repo, "b2", "aac")
    assert _run(repo, "merge", "--no-edit", "b1").returncode == 0
    assert _run(repo, "merge", "--no-edit", "b2").returncode != 0

    before = (repo / "CATALOG.md").read_bytes()
    v = G.resolve(repo, FAKE_REGISTRY, dry_run=True)
    assert v.code == 0
    assert v.regenerated == [] and v.staged == []
    assert (repo / "CATALOG.md").read_bytes() == before
    assert G.conflicted_paths(repo) == ("CATALOG.md",)


# ─── every degradation degrades toward refusing ─────────────────────
def _conflict_on_catalog(repo: Path) -> None:
    _branch_adding(repo, "b1", "aab")
    _branch_adding(repo, "b2", "aac")
    assert _run(repo, "merge", "--no-edit", "b1").returncode == 0
    assert _run(repo, "merge", "--no-edit", "b2").returncode != 0


def test_absent_generator_is_unmeasurable_not_resolved(repo: Path):
    _conflict_on_catalog(repo)
    (repo / "gen.py").unlink()
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 2
    assert "not present" in v.reason


def test_failing_regenerator_is_unmeasurable_not_resolved(repo: Path):
    _conflict_on_catalog(repo)
    (repo / "gen.py").write_text(
        "import sys\nprint('boom', file=sys.stderr)\nraise SystemExit(3)\n"
    )
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 2
    assert "exited 3" in v.reason
    assert v.staged == []


def test_regeneration_that_leaves_markers_is_unmeasurable(repo: Path):
    """A registry entry that is WRONG about a file being fully derived must
    not be able to stage conflict markers."""
    _conflict_on_catalog(repo)
    (repo / "gen.py").write_text("raise SystemExit(0)\n")  # writes nothing
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 2
    assert "SURVIVED regeneration" in v.reason
    assert v.staged == []
    assert _markers(repo / "CATALOG.md") == 1


def test_check_still_red_after_regeneration_is_unmeasurable(repo: Path):
    """Regenerating is not enough: the bytes written must be the bytes the
    freshness gate demands, or staging them only moves the failure."""
    _conflict_on_catalog(repo)
    (repo / "gen.py").write_text(
        "import sys\n"
        "from pathlib import Path\n"
        "if '--check' in sys.argv:\n"
        "    print('stale', file=sys.stderr); raise SystemExit(1)\n"
        "Path(__file__).resolve().parent.joinpath('CATALOG.md')"
        ".write_text('not what the gate wants\\n')\n"
    )
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 2
    assert "still" in v.reason and "rc=1" in v.reason
    assert v.staged == []


def test_no_conflict_in_progress_is_unmeasurable(repo: Path):
    v = G.resolve(repo, FAKE_REGISTRY)
    assert v.code == 2
    assert "no conflicted path" in v.reason


def test_not_a_git_worktree_is_unmeasurable(tmp_path: Path):
    d = tmp_path / "plain"
    d.mkdir()
    rc = G.main(["--repo", str(d)])
    assert rc == 2


# ─── the CLI carries the verdict, not someone else's rc ─────────────
def test_cli_exit_codes_and_json(repo: Path, tmp_path: Path):
    _conflict_on_catalog(repo)
    out = tmp_path / "v.json"
    # The real REGISTRY does not know CATALOG.md, so the CLI must REFUSE —
    # which is also a direct check that the shipped registry is not a
    # catch-all.
    rc = G.main(["--repo", str(repo), "--json", str(out)])
    assert rc == 1
    import json
    rec = json.loads(out.read_text())
    assert rec["verdict"] == "REFUSED"
    assert rec["foreign"] == ["CATALOG.md"]


# ─── the shipped registry entry points at the real thing ────────────
def test_every_real_registry_entry_is_coherent():
    """Cheap coherence over EVERY entry, not a second freshness test.

    Each registered artefact must exist, name a generator that exists, and
    carry PROVENANCE naming that generator in its own bytes. Written as a loop
    rather than against `REGISTRY[0]`: the previous form pinned
    `len(REGISTRY) == 1` and indexed the first entry, so registering a second
    derived artefact made it red for the population having grown rather than
    for anything being wrong. A coherence rule should cover the entry added
    tomorrow without being edited.

    Provenance is matched on the generator's BASENAME because the two artefacts
    state it in different shapes, both legitimate:
        INDEX.md              `<!-- AUTO-GENERATED by tools/gen_programs_index.py ...`
        PROGRAM_INVENTORY.json `"_comment": "... generated from the tree by
                                programs/gen_program_inventory.py ..."`
    """
    assert G.REGISTRY, "an empty registry would make every test here vacuous"
    for art in G.REGISTRY:
        gen = repo_path_or_missing(*art.generator.split("/"))
        if not gen.exists():
            pytest.skip(
                f"generator not present at {gen} (mirror tree); the repo-root "
                f"tools are not shipped in the flattened cache")
        root = gen.parents[len(art.generator.split("/")) - 1]
        artefact = (root / art.path)
        assert artefact.exists(), f"{art.path} missing at {artefact}"

        head = artefact.read_text(encoding="utf-8", errors="replace")[:2000]
        base = art.generator.rsplit("/", 1)[-1]
        assert base in head, (
            f"{art.path} carries no provenance naming {base}; registry says "
            f"{art.generator}")

        assert art.regenerate and art.check, art.path
        assert art.regenerate[0] == "python3" and art.check[0] == "python3"


# --- the REAL registry, not the fake one: what it actually covers -----------

_INDEX = "vibe-ic-marketplace/plugins/vibe-ic/programs/INDEX.md"
_INVENTORY = "vibe-ic-marketplace/plugins/vibe-ic/programs/PROGRAM_INVENTORY.json"


def test_the_inventory_is_registered_beside_the_index():
    """Both files every program-adding branch rewrites are derived.

    Measured on a real merge of `jdistmat/matrix-distil` into main a4caccefe:
    four paths conflicted, and INDEX.md and PROGRAM_INVENTORY.json were two of
    them. With only INDEX.md registered the inventory was named as a FOREIGN
    path, which refuses the WHOLE resolution -- including the half that was
    resolvable -- so the merge had to be finished by hand.
    """
    known = {a.path for a in G.REGISTRY}
    assert _INDEX in known
    assert _INVENTORY in known, (
        "PROGRAM_INVENTORY.json is derived, has a generator and a check, and "
        "conflicts on the same merges as INDEX.md")


def test_both_derived_paths_together_are_resolvable():
    v = G.decide([_INDEX, _INVENTORY])
    assert v.code == 0, f"{v.code}: {v.reason}"
    assert set(v.derived) == {_INDEX, _INVENTORY}
    assert not v.foreign


def test_a_foreign_path_still_refuses_the_whole_resolution():
    """The registry grew; the refusal must not have weakened."""
    v = G.decide([_INDEX, _INVENTORY, "vibe-ic-marketplace/README.md"])
    assert v.code == 1, f"{v.code}: {v.reason}"
    assert "vibe-ic-marketplace/README.md" in v.foreign


def test_the_inventory_is_checked_artefact_only_and_that_is_deliberate():
    """`--check` also binds README PROSE, which regeneration cannot fix.

    Registered with full --check this entry would stay red after a correct
    regeneration, and the resolver turns a still-red check into rc 2
    UNMEASURABLE -- reporting an unmeasurable tree where the artefact is
    provably correct.
    """
    entry = next(a for a in G.REGISTRY if a.path == _INVENTORY)
    assert "--check-artifact" in entry.check, entry.check
    assert "--check" not in entry.check[2:] or "--check-artifact" in entry.check
