"""Guards for `flow_output_substance` — the D3 decider.

EVERY TEST HERE HAS TWO POLES. A predicate that only ever demonstrates its
refusal is indistinguishable from one that refuses everything, and a detector
that fires on every target it is pointed at is as broken as the silence it
replaced. So each rule is shown refusing the vacuous artefact AND accepting the
healthy one that most resembles it.

The fixtures are the REAL bytes, not paraphrases: the vacuous STA transcript is
what OpenROAD wrote on
ghcr.io/vibeic/vibeic-eda@sha256:4ece6c01cddc99903af4f027326f7624b069311f2073a5a0b565d5a9cf649a16
when `eda_sta` handed it a netlist with no technology, and the zero-cell netlist
is what yosys wrote for `assign zero = 1'b0` on the same image.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

PROGRAMS = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROGRAMS))

import flow_output_substance as S  # noqa: E402


# ── The real defect, verbatim ───────────────────────────────────────────────
VACUOUS_STA = """OpenROAD 26Q3-1797-g1c09d62b96 
Features included (+) or not (-): -GPU +GUI -Python
This program is licensed under the BSD-3 license. See the LICENSE file for details.
[ERROR ORD-2010] no technology has been read.
ORD-2010
[ERROR STA-1570] No network has been linked.
STA-1570
[ERROR STA-1571] No network has been linked.
STA-1571
"""

GOOD_STA = """OpenROAD 26Q3-1797-g1c09d62b96 
Startpoint: _38_ (rising edge-triggered flip-flop clocked by clk)
Endpoint: _38_ (rising edge-triggered flip-flop clocked by clk)
Path Type: max
   0.95    0.95 v _38_/Q (gf180mcu_fd_sc_mcu7t5v0__dffrnq_1)
           1.27   slack (MET)

tns max 0.00
wns max 0.00
"""

# yosys, `assign zero = 1'b0`, 0 cells. A REAL netlist for a constant design.
ZERO_CELL_NETLIST = """/* Generated by Yosys 0.68+ */

module constzero(zero);
  output zero;
  wire zero;
  assign zero = 1'h0;
endmodule
"""


# ── TOOL_SELF_REPORT: the rule that catches the STA defect ──────────────────
def test_a_transcript_recording_the_tools_own_error_is_vacuous(tmp_path):
    """THE REAL CASE. Present, non-empty, not a symlink — and hollow."""
    p = tmp_path / "pre_pnr_timing.rpt"
    p.write_text(VACUOUS_STA)
    assert p.stat().st_size > 0, "the fixture must defeat the byte-count rule"

    v = S.classify_artefact(p)
    assert v["state"] == S.VACUOUS, v
    assert v["code"] == "TOOL_REPORTED_ERROR", v
    for diag in ("ORD-2010", "STA-1570", "STA-1571"):
        assert diag in v["detail"], (diag, v["detail"])


def test_a_transcript_from_a_run_that_worked_is_substantive(tmp_path):
    """THE OTHER POLE. Same kind, same tool, same shape — and real."""
    p = tmp_path / "pre_pnr_timing.rpt"
    p.write_text(GOOD_STA)
    v = S.classify_artefact(p)
    assert v["state"] == S.SUBSTANTIVE, v


def test_the_byte_count_rule_alone_cannot_separate_the_two(tmp_path):
    """Why the old predicate had to be replaced rather than tightened.

    Both files exist, both are non-empty, neither is a symlink. Every property
    the repository already tested is IDENTICAL across them; only the content
    rule tells them apart. If this ever stops being true the fixtures have
    drifted and the test above is proving nothing.
    """
    bad = tmp_path / "bad.rpt"; bad.write_text(VACUOUS_STA)
    good = tmp_path / "good.rpt"; good.write_text(GOOD_STA)
    for p in (bad, good):
        assert p.is_file() and not p.is_symlink() and p.stat().st_size > 0
    assert S.classify_artefact(bad)["state"] != S.classify_artefact(good)["state"]


def test_a_warning_is_not_an_error_and_does_not_make_a_run_vacuous(tmp_path):
    """A run that warns is a run that ran.

    `tool_diagnostic_id_gate` already owns the separate question of whether a
    warning is NEW. Treating WARNING as vacuity here would red most healthy
    artefacts in this repository.
    """
    p = tmp_path / "sta.rpt"
    p.write_text("[WARNING STA-0366] port 'clk' not found\n" + GOOD_STA)
    assert S.classify_artefact(p)["state"] == S.SUBSTANTIVE


# ── The carve-out that stops the detector firing on everything ──────────────
def test_a_structured_artefact_may_legitimately_CONTAIN_an_error_string(tmp_path):
    """MEASURED: `programs/pdk_registry.json` ships containing `[ERROR ...]`,
    and the MCP server records a failed tool's `stdoutTail` into provenance
    JSON — a CORRECT record of a failure. Applying the transcript rule to
    structured kinds would fire on healthy artefacts.
    """
    p = tmp_path / "provenance.json"
    p.write_text('{"tool": "openroad", "exitCode": 1, '
                 '"stdoutTail": "[ERROR STA-1570] No network has been linked."}')
    v = S.classify_artefact(p)
    assert v["state"] == S.SUBSTANTIVE, v


def test_the_same_error_text_in_a_transcript_IS_read(tmp_path):
    """The opposite pole of the carve-out: the rule is per-kind, not disabled."""
    p = tmp_path / "sta.log"
    p.write_text("[ERROR STA-1570] No network has been linked.\n")
    assert S.classify_artefact(p)["state"] == S.VACUOUS


# ── The netlist rule: zero cells is CORRECT, no module is not ───────────────
def test_a_design_that_legitimately_synthesises_to_zero_cells_is_not_flagged(tmp_path):
    """THE CONTROL. `assign zero = 1'b0` has no cells and is a real netlist.

    Requiring cells would be the adjacent-measurement trap, and it would red a
    correct design. This is the test that proves D3 is not a detector that fires
    on everything.
    """
    p = tmp_path / "netlist.v"
    p.write_text(ZERO_CELL_NETLIST)
    assert "0 cells" not in p.read_text()          # the count is not in the file
    v = S.classify_artefact(p)
    assert v["state"] == S.SUBSTANTIVE, v


def test_a_netlist_with_no_module_declaration_is_vacuous(tmp_path):
    p = tmp_path / "netlist.v"
    p.write_text("/* Generated by Yosys 0.68+ */\n\n")
    v = S.classify_artefact(p)
    assert v["state"] == S.VACUOUS and v["code"] == "NO_MODULE", v


# ── Sentinels: zero bytes is the message ────────────────────────────────────
def test_an_empty_marker_file_is_substantive_because_that_is_its_format(tmp_path):
    """`pdn.done` / `pass.flag` carry no content BY DESIGN. 11 of the flow's 198
    output alternatives are of this shape; a size rule reds every one.
    """
    for name in ("pdn.done", "pass.flag"):
        p = tmp_path / name
        p.write_bytes(b"")
        v = S.classify_artefact(p)
        assert v["state"] == S.SUBSTANTIVE and v["rule"] == S.SENTINEL, (name, v)


def test_an_empty_file_of_any_OTHER_kind_is_vacuous(tmp_path):
    """The sentinel carve-out is per-kind, not a general amnesty for 0 bytes."""
    p = tmp_path / "drc.rpt"
    p.write_bytes(b"")
    v = S.classify_artefact(p)
    assert v["state"] == S.VACUOUS and v["code"] == "ZERO_BYTES", v


# ── STRUCTURAL rules ────────────────────────────────────────────────────────
@pytest.mark.parametrize("body,code", [
    ("{}", "EMPTY_CONTAINER"),
    ("[]", "EMPTY_CONTAINER"),
    ("null", "EMPTY_CONTAINER"),
    ("{not json", "MALFORMED"),
])
def test_a_json_output_that_holds_nothing_is_vacuous(tmp_path, body, code):
    p = tmp_path / "summary.json"
    p.write_text(body)
    v = S.classify_artefact(p)
    assert v["state"] == S.VACUOUS and v["code"] == code, (body, v)


def test_a_json_output_reporting_a_measured_zero_is_substantive(tmp_path):
    """A report saying "0 violations" is a MEASUREMENT, not an absence. An
    empty list INSIDE the document is legitimate; only an empty document is not.
    """
    p = tmp_path / "drc.json"
    p.write_text('{"violations": [], "checked": true}')
    assert S.classify_artefact(p)["state"] == S.SUBSTANTIVE


def test_a_truncated_def_is_vacuous_and_a_complete_one_is_not(tmp_path):
    trunc = tmp_path / "a.def"
    trunc.write_text("VERSION 5.8 ;\nDESIGN top ;\nCOMPONENTS 2 ;\n")
    v = S.classify_artefact(trunc)
    assert v["state"] == S.VACUOUS and v["code"] == "TRUNCATED", v

    whole = tmp_path / "b.def"
    whole.write_text("VERSION 5.8 ;\nDESIGN top ;\nCOMPONENTS 0 ;\nEND COMPONENTS\nEND DESIGN\n")
    assert S.classify_artefact(whole)["state"] == S.SUBSTANTIVE


def test_whitespace_only_content_is_vacuous_though_its_byte_count_is_positive(tmp_path):
    """The weakest rule is still strictly stronger than "non-empty"."""
    p = tmp_path / "report.md"
    p.write_text("   \n\n\t\n")
    assert p.stat().st_size > 0
    v = S.classify_artefact(p)
    assert v["state"] == S.VACUOUS and v["code"] == "WHITESPACE_ONLY", v


# ── NOT_DECIDABLE is neither a pass nor a fail ──────────────────────────────
def test_an_opaque_bitstream_is_not_decidable_and_never_a_verdict(tmp_path):
    p = tmp_path / "top.sof"
    p.write_bytes(b"\x00\x01\x02\x03" * 64)
    v = S.classify_artefact(p)
    assert v["state"] == S.NOT_DECIDABLE, v
    assert v["state"] not in S.FAILING
    assert v["state"] != S.SUBSTANTIVE
    assert v["state"] in S.NO_VERDICT


# ── The whole-flow contract ─────────────────────────────────────────────────
def _steps():
    import yaml
    doc = yaml.safe_load((PROGRAMS.parent / "flow" /
                          "phase1_phase2_phase3.yaml").read_text())
    out = []

    def walk(o):
        if isinstance(o, dict):
            if "id" in o and "name" in o:
                out.append(o)
            for v in o.values():
                walk(v)
        elif isinstance(o, list):
            for v in o:
                walk(v)

    walk(doc)
    return [s for s in out if not str(s.get("id", "")).startswith("stage")]


def test_with_no_run_every_cell_is_NOT_MEASURED_and_none_is_a_pass():
    """The whole lesson: an absent measurement must not be renderable as a good
    one — and must not be rendered as a bad one either.
    """
    rec = S.classify_flow(None, _steps())
    assert rec["state"] == S.NOT_MEASURED
    assert rec["cells"], "an empty cell list would make the assertion vacuous"
    for c in rec["cells"]:
        assert c["state"] == S.NOT_MEASURED, c
        assert c["state"] != S.SUBSTANTIVE
        assert c["state"] not in S.FAILING


def test_a_step_the_run_never_reached_is_NOT_MEASURED_not_a_failure(tmp_path):
    """A phase-1 project has no phase-3 outputs, and that is not a defect.

    Without this, D3 reds every unreached step of every partial run — measured
    at 64 of 68 on a two-step run tree while this was being built. A dimension
    that reds everything gets ignored, which costs exactly what silence costs.
    """
    steps = {str(s["id"]): s for s in _steps()}
    r = S.classify_step(tmp_path, steps["10"])
    assert r["state"] == S.NOT_MEASURED, r
    assert r["code"] == "STEP_NOT_EVIDENCED", r
    assert r["state"] not in S.FAILING


def test_but_a_HALF_written_step_is_still_a_finding(tmp_path):
    """The exemption above is not a blanket amnesty for absence.

    The moment ANY declared output resolves, the step demonstrably ran, and a
    missing SIBLING output becomes a real finding again.
    """
    steps = {str(s["id"]): s for s in _steps()}
    (tmp_path / "phase3" / "stage3" / "sta").mkdir(parents=True)
    (tmp_path / "phase3" / "stage3" / "sta" / "pre_pnr_timing.rpt").write_text(GOOD_STA)
    # step 10's OTHER declared output, reports/phase3/sta/pre_pnr_summary.json,
    # is deliberately not written.
    r = S.classify_step(tmp_path, steps["10"])
    assert r["state"] == S.ABSENT, r
    assert r["state"] in S.FAILING


def test_the_real_case_end_to_end_on_the_flows_own_sta_step(tmp_path):
    """Step 10, both poles, through the same code path the grid uses."""
    steps = {str(s["id"]): s for s in _steps()}
    sta = tmp_path / "phase3" / "stage3" / "sta"
    sta.mkdir(parents=True)
    summ = tmp_path / "reports" / "phase3" / "sta"
    summ.mkdir(parents=True)
    (summ / "pre_pnr_summary.json").write_text('{"wns_ns": 1.27}')

    (sta / "pre_pnr_timing.rpt").write_text(VACUOUS_STA)
    bad = S.classify_step(tmp_path, steps["10"])
    assert bad["state"] == S.VACUOUS and bad["code"] == "TOOL_REPORTED_ERROR", bad

    (sta / "pre_pnr_timing.rpt").write_text(GOOD_STA)
    good = S.classify_step(tmp_path, steps["10"])
    assert good["state"] == S.SUBSTANTIVE, good


# ── The anti-D8 guard ───────────────────────────────────────────────────────
def test_this_module_never_reads_a_steps_gate(tmp_path):
    """D3 must not be D8 wearing a new name.

    Mechanical, not a promise: give a step a gate that would satisfy any
    declaration-based predicate and NO substantive output, and the verdict must
    still come from the bytes. The gate is also removed entirely in the second
    half — if any verdict moved, something read it.
    """
    steps = {str(s["id"]): s for s in _steps()}
    sta = tmp_path / "phase3" / "stage3" / "sta"
    sta.mkdir(parents=True)
    (sta / "pre_pnr_timing.rpt").write_text(VACUOUS_STA)
    summ = tmp_path / "reports" / "phase3" / "sta"
    summ.mkdir(parents=True)
    (summ / "pre_pnr_summary.json").write_text('{"wns_ns": 1.27}')

    import copy
    with_gate = copy.deepcopy(steps["10"])
    with_gate["gate"] = {"all_of": [{"files_exist": ["phase3/stage3/sta/pre_pnr_timing.rpt"]}]}
    without_gate = copy.deepcopy(steps["10"])
    without_gate.pop("gate", None)

    a = S.classify_step(tmp_path, with_gate)
    b = S.classify_step(tmp_path, without_gate)
    assert a["state"] == b["state"] == S.VACUOUS, (a["state"], b["state"])


def test_the_module_source_names_no_gate_key():
    """The same guard at the source level, so a future edit that starts reading
    the declaration turns this red instead of quietly changing what D3 means.
    """
    src = (PROGRAMS / "flow_output_substance.py").read_text()
    body = src.split('"""', 2)[2]        # strip the module docstring
    for forbidden in ('"gate"', "'gate'", '.get("gate"', "step['gate']"):
        assert forbidden not in body, (
            f"{forbidden} appears in the executable body; D3 must reach every "
            f"verdict from bytes a run wrote, never from what the flow declares")


# ── Every vacuity code the module can emit is enumerated ────────────────────
def test_every_emitted_code_is_in_the_declared_vocabulary():
    """A code invented at a return site and absent from the table is prose with
    a capital letter. Both directions: the table must also not rot.
    """
    src = (PROGRAMS / "flow_output_substance.py").read_text()
    import re
    emitted = set(re.findall(r'code="([A-Z_]+)"', src))
    emitted.discard("")
    known = set(S.VACUITY_CODES) | set(S.NO_VERDICT_CODES) | {"ABSENT"}
    assert emitted <= known, sorted(emitted - known)
    assert emitted, "no codes found — the regex has drifted from the source"


# ── The CLI contract ────────────────────────────────────────────────────────
def _cli(*args):
    p = subprocess.run([sys.executable, str(PROGRAMS / "flow_output_substance.py"), *args],
                       capture_output=True, text=True, timeout=600)
    return p.returncode, p.stdout + p.stderr


def test_the_cli_with_no_run_says_NOT_MEASURED_in_those_words():
    rc, out = _cli()
    assert rc == 0, out
    assert "NOT MEASURED" in out, out
    assert "neither a pass nor a fail" in out, out
