"""vibe-ic#1043 — vendored Apache-2.0 was attributed by habit, not by a check.

Apache-2.0 §4(b)/§4(d) attach to distributing the WORK, not to publishing a run
that used it. So withdrawing a run does not withdraw the duty: while the
vendored file is in the tree, the record naming its origin has to be too.

#1043's SPECIFIC claim does not reproduce — measured on `a38902d16` and on
`withdraw/nonpassing-published-runs@a8e254ad`, that branch deletes 2 manifests,
0 Apache-2.0 files survive under either, and all 330 it ships are covered.
#1027, whose restores the issue measured against, is CLOSED.

What reproduced is why nobody could tell: **nothing checked.** The gate's first
run on `a38902d16` found 493 shipped files declaring Apache-2.0, 491 covered,
and 2 third-party PDK cell models with no record at all.

THE FIXTURES BUILD REAL GIT REPOSITORIES because the predicate is "what we
distribute", and that is what git tracks. A file present on one machine and in
no commit is not something this repo ships, and
`test_an_untracked_vendored_file_is_out_of_scope` is what keeps that honest.
"""

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

_PROGRAMS = Path(__file__).resolve().parents[1]
_REPO = _PROGRAMS.parents[3]
_CHECK = _PROGRAMS / "vendored_attribution_present_check.py"

_APACHE_HEADER = (
    "// Copyright 2020 The Example PDK Authors\n"
    "//\n"
    "// Licensed under the Apache License, Version 2.0 (the \"License\");\n"
    "// you may not use this file except in compliance with the License.\n"
)
_SPDX = "// SPDX-License-Identifier: Apache-2.0\n"
_NO_LICENCE = "// generated by this flow; no third-party content\n"


def _load():
    spec = importlib.util.spec_from_file_location("vap", _CHECK)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["vap"] = mod
    spec.loader.exec_module(mod)
    return mod


M = _load()


def _repo(tmp_path: Path, files: dict, commit: bool = True) -> Path:
    root = tmp_path / "repo"
    (root / "benchmark-data").mkdir(parents=True, exist_ok=True)
    for rel, body in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body)
    subprocess.run(["git", "init", "-q"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.email", "t@t"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=root, check=True)
    if commit:
        subprocess.run(["git", "add", "-A"], cwd=root, check=True)
        subprocess.run(["git", "commit", "-qm", "corpus"], cwd=root, check=True)
    return root


def _cli(root: Path):
    p = subprocess.run([sys.executable, str(_CHECK), str(root)],
                       capture_output=True, text=True, timeout=170)
    return p.returncode, p.stdout + p.stderr


_VENDORED = "benchmark-data/ic/thing/rtl/cell_models.v"


# ==========================================================================
# 1. THE DEFECT
# ==========================================================================
def test_a_vendored_apache_file_with_no_manifest_is_refused(tmp_path):
    root = _repo(tmp_path, {_VENDORED: _APACHE_HEADER + "module m; endmodule\n"})
    rc, out = _cli(root)
    assert rc == 1, out
    assert "NO_ATTRIBUTION" in out and _VENDORED in out, out


def test_the_spdx_tag_alone_is_enough_to_be_in_scope(tmp_path):
    """Both spellings are required: SPDX alone misses every vendored PDK file
    (they carry the long header and no tag), and the header alone would miss
    modern SPDX-only sources."""
    root = _repo(tmp_path, {_VENDORED: _SPDX + "module m; endmodule\n"})
    rc, out = _cli(root)
    assert rc == 1, out
    assert "NO_ATTRIBUTION" in out, out


# ==========================================================================
# 2. THE FIX, AND ITS DIRECTION
# ==========================================================================
def test_a_manifest_at_or_above_covers_the_file(tmp_path):
    root = _repo(tmp_path, {
        _VENDORED: _APACHE_HEADER + "module m; endmodule\n",
        "benchmark-data/ic/thing/SOURCE_MANIFEST.md": "# origin\n",
    })
    rc, out = _cli(root)
    assert rc == 0, out
    assert "0 uncovered" in out, out


def test_a_manifest_BELOW_the_file_does_not_cover_it(tmp_path):
    """Attribution is inherited downward, not upward. Without this, dropping a
    manifest anywhere in the tree would silence the whole corpus."""
    root = _repo(tmp_path, {
        "benchmark-data/ic/thing/cell_models.v":
            _APACHE_HEADER + "module m; endmodule\n",
        "benchmark-data/ic/thing/sub/deeper/SOURCE_MANIFEST.md": "# origin\n",
    })
    rc, out = _cli(root)
    assert rc == 1, out


# ==========================================================================
# 3. NO FALSE POSITIVES — the half an always-fires mutant breaks
# ==========================================================================
def test_a_file_that_declares_no_licence_is_not_in_scope(tmp_path):
    """The population is the file's OWN declaration. Our own generated RTL is
    the overwhelming majority of the tree and must not be dragged in."""
    root = _repo(tmp_path, {
        "benchmark-data/ic/thing/rtl/generated.v": _NO_LICENCE + "module m; endmodule\n",
    })
    rc, out = _cli(root)
    # No Apache-declaring file at all -> an honest empty population, rc 2.
    assert rc == 2, out
    assert "NONE declaring Apache-2.0" in out, out


def test_an_untracked_vendored_file_is_out_of_scope(tmp_path):
    """The duty attaches to DISTRIBUTION. A file in no commit is not shipped."""
    root = _repo(tmp_path, {
        "benchmark-data/ic/thing/kept.v": _NO_LICENCE,
    })
    stray = root / _VENDORED
    stray.parent.mkdir(parents=True, exist_ok=True)
    stray.write_text(_APACHE_HEADER)          # never added
    rc, out = _cli(root)
    assert rc == 2, out
    assert "NONE declaring Apache-2.0" in out, out


def test_a_non_source_suffix_is_not_scanned(tmp_path):
    root = _repo(tmp_path, {
        "benchmark-data/ic/thing/notes.md": _APACHE_HEADER,
        "benchmark-data/ic/thing/keep.v": _NO_LICENCE,
    })
    rc, out = _cli(root)
    assert rc == 2, out


# ==========================================================================
# 4. NOT A VACUOUS PASS
# ==========================================================================
def test_an_empty_tree_is_rc_2_and_says_it_examined_nothing(tmp_path):
    root = _repo(tmp_path, {"benchmark-data/.keep": ""})
    rc, out = _cli(root)
    assert rc == 2, out
    assert "NOT a pass" in out or "NONE declaring" in out, out


def test_a_pass_states_its_denominator(tmp_path):
    root = _repo(tmp_path, {
        _VENDORED: _APACHE_HEADER + "module m; endmodule\n",
        "benchmark-data/ic/thing/SOURCE_MANIFEST.md": "# origin\n",
    })
    rc, out = _cli(root)
    assert rc == 0
    assert "declare Apache-2.0" in out and "tracked file(s) examined" in out, out


# ==========================================================================
# 5. THE SHIPPED TREE — the assertion no fixture can make
# ==========================================================================
@pytest.mark.skipif(not (_REPO / "benchmark-data").is_dir(),
                    reason="no benchmark-data in this tree")
def test_the_shipped_tree_attributes_every_apache_file_it_distributes():
    """The one that would have caught #1043's class. It is red on `a38902d16`
    (2 uncovered PDK cell models) and green with this branch's manifest."""
    res = M.audit(_REPO, "benchmark-data")
    assert res["apache_declared"] > 0, (
        "no shipped file declares Apache-2.0 — the predicate has stopped "
        "matching and this test is now vacuous")
    assert not res["uncovered"], (
        f"{len(res['uncovered'])} shipped Apache-2.0 file(s) have no "
        f"SOURCE_MANIFEST.md at or above them: {res['uncovered'][:5]}")
