"""vibe-ic#731 — the three declaration scans that read text nobody blanked.

`hdl_declaration_scan_strips_comments_check` reads the DATAFLOW into every
declaration scan and blocks on a new call site whose scanned value never passed
a stripper. On v1.14.75 it named three, and each one is a REAL defect with its
own failure, not a lint:

    _runner_measurement::_verilog_netlist::_V_MODULE_RE(text)
    benchmark_io_adapter::cvdp_package_response::_MODULE_BLOCK_RE(combined)
    design_one_shot_runner::_v1956_dut_instance_conns::pat(text)

On v1.16.85 it named three more, from the vector-TB generators:

    known_answer_vector_tb_gen::_bus_ports_from_rtl::pat_h(hdr)
    known_answer_vector_tb_gen::_bus_ports_from_rtl::pat_d(hdr)
    register_bus_driver_gen::find_host_intg_gen::pat(text)

Every test below drives the SHIPPED function on input a real design can carry
and asserts the behaviour, so it fails against the pre-fix sources for the
reason the gate names rather than because a helper is missing.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

PROGRAMS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROGRAMS))

import _hdl_code_text as B                      # noqa: E402
import benchmark_io_adapter as IO               # noqa: E402
import design_one_shot_runner as DR             # noqa: E402
import _runner_measurement as RM                # noqa: E402
import known_answer_vector_tb_gen as KTB        # noqa: E402
import register_bus_driver_gen as RBD           # noqa: E402


# ── the blanker's own contract ────────────────────────────────────────────
def test_blanking_preserves_length_and_every_code_character():
    """A span may be taken from the blanked text and used on the original."""
    text = ('module top;\n'
            '  // module ghost (\n'
            '  wire w;  /* module\n'
            '              phantom */\n'
            '  initial $display("module liar %s", w);\n'
            'endmodule\n')
    out = B.strip_hdl_comments_and_strings(text)
    assert len(out) == len(text)
    assert out.count("\n") == text.count("\n")
    for i, ch in enumerate(out):
        assert ch == text[i] or ch == " ", (i, ch, text[i])
    # The three phantoms are gone; the two real declarations survive.
    assert "ghost" not in out
    assert "phantom" not in out
    assert "liar" not in out
    assert "module top;" in out
    assert "endmodule" in out


def test_one_alternation_decides_the_nesting_both_ways():
    """A `//` inside a string is not a comment; a `"` inside a comment is not
    a string opener. Two sequential passes get exactly these two backwards."""
    assert B.strip_hdl_comments_and_strings('x = "a // b"; wire w;').endswith(
        "; wire w;")
    # An unbalanced quote inside a line comment must not swallow the next line.
    out = B.strip_hdl_comments_and_strings('a; // he said "hi\nwire w;\n')
    assert "wire w;" in out


def test_an_unterminated_opener_is_left_alone():
    """Blanking to EOF on a stray `/*` would erase a whole design."""
    text = "module top;\n/* never closed\nwire w;\n"
    assert B.strip_hdl_comments_and_strings(text) == text


# ── site 1: the netlist TELL ──────────────────────────────────────────────
def test_a_commented_module_does_not_make_a_file_a_netlist(tmp_path):
    """PRE-FIX: `_V_MODULE_RE` matched the banner and the file was handed to
    the cell counter, which reported `0 cell instances` — a TOOL_DID_NOT_RUN
    finding published about a file that is not a netlist at all."""
    p = tmp_path / "notes.v"
    p.write_text(
        "/*\n"
        "module ghost (input a);\n"
        "endmodule\n"
        "*/\n"
        "// nothing was synthesised here\n"
    )
    assert RM._verilog_netlist(p, "notes.v", "yosys") is None


def test_a_real_netlist_is_still_measured(tmp_path):
    """The NEGATIVE control: blanking must not cost a genuine measurement."""
    p = tmp_path / "netlist.v"
    p.write_text(
        "/* Generated by yosys */\n"
        "module top(input a, output y);\n"
        "  INV_X1 _0_ (.A(a), .Y(y));\n"
        "endmodule\n"
    )
    rec = RM._verilog_netlist(p, "netlist.v", "yosys")
    assert rec is not None and rec.get("measured") is True
    assert "1 cell instance" in rec["operation"]


# ── site 2: the packaged RTL bytes ────────────────────────────────────────
def _cvdp(tmp_path, sources: "dict[str, str]", response_paths):
    paths = []
    for name, body in sources.items():
        f = tmp_path / name
        f.write_text(body)
        paths.append(f)
    return json.loads(
        IO.cvdp_package_response(paths, paths, response_paths))["code"]


def test_a_commented_endmodule_does_not_truncate_the_packaged_rtl(tmp_path):
    """PRE-FIX: the non-greedy `[\\s\\S]*?` stopped at the COMMENTED
    `endmodule`, so the RTL handed to CVDP's scorer lost every line after it —
    including the real `endmodule`. The scorer receives a file that does not
    parse, and the contract of this function is EXACT accepted bytes."""
    alpha = ("module alpha;\n"
             "  wire w;\n"
             "  // endmodule  <- a reviewer's note\n"
             "  assign w = 1'b0;\n"
             "endmodule\n")
    code = _cvdp(tmp_path, {"src0.v": alpha, "src1.v": "module beta;\nendmodule\n"},
                 ["rtl/alpha.sv", "rtl/beta.sv"])
    packaged = code[0]["rtl/alpha.sv"]
    assert "assign w = 1'b0;" in packaged
    assert packaged.rstrip().endswith("endmodule")
    # EXACT bytes: the comment is still there, not blanked out.
    assert "// endmodule  <- a reviewer's note" in packaged


def test_a_module_named_only_inside_a_comment_is_not_packaged(tmp_path):
    """The other direction — a commented-out module must not become a mapping
    target the accepted RTL never declared."""
    src = ("// module ghost;\n"
           "// endmodule\n"
           "module real_top;\n"
           "endmodule\n")
    code = _cvdp(tmp_path, {"a.v": src, "b.v": "module beta;\nendmodule\n"},
                 ["rtl/real_top.sv", "rtl/beta.sv"])
    assert "module real_top;" in code[0]["rtl/real_top.sv"]
    assert "ghost" not in code[0]["rtl/real_top.sv"]


# ── site 3: the DUT connection list ───────────────────────────────────────
def test_an_unbalanced_paren_in_a_comment_does_not_hide_the_instantiation():
    """PRE-FIX: the `(` in the comment left `depth` never returning to 0, the
    walk fell off the end of the text and the function returned None — which
    its caller reports as "DUT module is not instantiated by this TB" about a
    testbench that instantiates it correctly."""
    tb = ("module tb;\n"
          "  dut_mod u_dut ( // drive reset first (see spec section 2\n"
          "    .clk(clk),\n"
          "    .rst_n(rst_n)\n"
          "  );\n"
          "endmodule\n")
    conns = DR._v1956_dut_instance_conns(tb, "dut_mod")
    assert conns is not None
    import re
    assert set(re.findall(r"\.\s*([A-Za-z_]\w*)\s*\(", conns)) == {"clk", "rst_n"}


def test_a_commented_out_instantiation_is_not_read_as_the_real_one():
    """The other direction — a connection list the design does not have."""
    tb = ("module tb;\n"
          "  // dut_mod u_old ( .legacy_pin(x) );\n"
          "  dut_mod u_dut ( .clk(clk) );\n"
          "endmodule\n")
    conns = DR._v1956_dut_instance_conns(tb, "dut_mod")
    assert conns is not None and "legacy_pin" not in conns
    assert "clk" in conns


# ── the gate itself ───────────────────────────────────────────────────────
def _load_gate():
    """The gate module, imported from the programs dir this file already uses."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "hdl_declaration_scan_gate_for_tests",
        PROGRAMS / "hdl_declaration_scan_strips_comments_check.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def test_the_declaration_scan_gate_is_green_on_this_tree():
    """The gate BLOCKS on a new unstripped scan, and what "green" HONESTLY means
    here is a RATCHET.

    Driven here so the repairs above are held by the gate, not only by their own
    unit tests. The verdict asked for is `--ratchet`: `offenders == the
    register`. That is the true statement — three scans DO still read unstripped
    text, each with a named owning lane — where "no scan reads unstripped text"
    would be false, and where the plain count is not an instrument at all: this
    population went 166 -> 165 -> 163 across a handful of landings while
    offenders were both entering and leaving, so the number moved DOWN in the
    same window that three new ones arrived.
    """
    proc = subprocess.run(
        [sys.executable,
         str(PROGRAMS / "hdl_declaration_scan_strips_comments_check.py"),
         "--ratchet"],
        capture_output=True, text=True, timeout=900)
    assert proc.returncode == 0, proc.stdout + proc.stderr
    assert "[PASS]" in proc.stdout


def test_the_ratchet_blocks_a_landing_that_ADDS_an_unstripped_scan():
    """DIRECTION 1: an offender not in the register fails the gate.

    THE OFFENDER IS PLANTED, NOT BORROWED FROM THE REGISTER. This test used to
    empty `_OFFENDER_REGISTER` and hand its former contents back as the
    observed population, which was exact while the register had entries and went
    VACUOUS the moment it emptied: v1.18.24 fixed every offender this gate
    named, `sorted(kept)` became `[]`, and a gate asked about NO offenders
    correctly answered rc 0 — a green test proving nothing. The population a
    ratchet judges is not the register's own contents, so the fixture must not
    be either. Both arms are asserted here: the same name UNREGISTERED blocks
    and REGISTERED does not, so the refusal is about membership and not about
    the name.
    """
    G = _load_gate()
    root = PROGRAMS.parent
    planted = "canonical_primitive_synth::_rtl_input_port_widths::_HDR(rtl)"
    kept = dict(G._OFFENDER_REGISTER)
    assert planted not in kept, (
        "the planted name must not already be registered, or the first arm "
        "below asks nothing")
    try:
        G._OFFENDER_REGISTER.clear()
        rc_unregistered = G._ratchet_verdict([planted], root)
        G._OFFENDER_REGISTER[planted] = "planted by this test"
        rc_registered = G._ratchet_verdict([planted], root)
    finally:
        G._OFFENDER_REGISTER.clear()
        G._OFFENDER_REGISTER.update(kept)
    assert rc_unregistered == 1, "an unregistered offender must BLOCK"
    assert rc_registered == 0, "the SAME offender, registered, must not block"


def test_the_ratchet_refuses_an_entry_that_outlived_its_offender():
    """DIRECTION 2: an entry whose offender is gone is itself an offender.

    Uses `canonical_primitive_synth::_rtl_input_port_widths`, which WAS an
    offender until the repair above stripped comments on the value reaching the
    scan — so this is the exact shape of fixing one and forgetting the entry.
    """
    G = _load_gate()
    root = PROGRAMS.parent
    kept = dict(G._OFFENDER_REGISTER)
    try:
        G._OFFENDER_REGISTER[
            "canonical_primitive_synth::_rtl_input_port_widths::_HDR(rtl)"] = (
            "planted for this test")
        rc = G._ratchet_verdict(sorted(kept), root)
    finally:
        G._OFFENDER_REGISTER.clear()
        G._OFFENDER_REGISTER.update(kept)
    assert rc == 1, "a stale register entry must BLOCK"


def test_the_ratchet_is_scoped_to_the_tree_it_is_aimed_at(tmp_path):
    """An entry naming a function this checkout does not define is out of scope,
    not stale — otherwise the verdict depends on which tree the gate was aimed
    at, which is the one property a gate must not have."""
    G = _load_gate()
    (tmp_path / "programs").mkdir()
    kept = dict(G._OFFENDER_REGISTER)
    try:
        rc = G._ratchet_verdict([], tmp_path)
    finally:
        G._OFFENDER_REGISTER.clear()
        G._OFFENDER_REGISTER.update(kept)
    assert rc == 0, "an out-of-tree entry is not stale"


# ── site 4: the struct-typed bus ports read off the DUT header ────────────
def test_a_commented_out_port_is_not_read_as_the_dut_bus_port(tmp_path):
    r"""PRE-FIX: `\binput\s+[\w:]*tl_h2d_t\s+(\w+)` matched the port line a
    revision had commented out, so the generated TB drove `legacy_h2d_i` — a
    name the DUT does not declare, and the testbench does not elaborate."""
    rtl = tmp_path / "phase2" / "stage1" / "rtl"
    rtl.mkdir(parents=True)
    (rtl / "dut.sv").write_text(
        "module dut (\n"
        "  // input  tl_h2d_t legacy_h2d_i,   <- removed in rev B\n"
        "  // output tl_d2h_t legacy_d2h_o,\n"
        "  input  tl_h2d_t tl_i,\n"
        "  output tl_d2h_t tl_o\n"
        ");\n"
        "endmodule\n")
    assert KTB._bus_ports_from_rtl(
        tmp_path, "dut", "tl_h2d_t", "tl_d2h_t") == ("tl_i", "tl_o")


def test_the_real_bus_ports_are_still_found(tmp_path):
    """The NEGATIVE control: blanking must not cost a genuine port pair."""
    rtl = tmp_path / "phase2" / "stage1" / "rtl"
    rtl.mkdir(parents=True)
    (rtl / "dut.sv").write_text(
        "module dut (\n"
        "  input  tlul_pkg::tl_h2d_t tl_i,\n"
        "  output tlul_pkg::tl_d2h_t tl_o\n"
        ");\n"
        "endmodule\n")
    assert KTB._bus_ports_from_rtl(
        tmp_path, "dut", "tl_h2d_t", "tl_d2h_t") == ("tl_i", "tl_o")


# ── site 5: the host-side integrity generator ─────────────────────────────
def test_a_module_name_taken_from_a_comment_is_not_instantiated():
    r"""PRE-FIX: `\bmodule\s+(\w+)` matched the COMMENTED header first, so the
    named module was `ghost_intg_gen` while the ports and the encoder came
    from the real one below it — a driver instantiating a module that no
    staged source declares."""
    src = ("// module ghost_intg_gen (\n"
           "module real_intg_gen (\n"
           "  input  tl_h2d_t tl_i,\n"
           "  output tl_h2d_t tl_o\n"
           ");\n"
           "  prim_secded_enc u_enc ();\n"
           "endmodule\n")
    mod, why = RBD.find_host_intg_gen([("rtl/gen.sv", src)],
                                      "tlul_pkg::tl_h2d_t")
    assert mod is not None, why
    assert mod["module"] == "real_intg_gen"
    assert mod["in"] == "tl_i" and mod["out"] == "tl_o"


def test_a_generator_that_exists_only_in_a_comment_is_not_reported():
    """The other direction — a whole commented-out generator must not be
    reported as a generator the design ships."""
    src = ("/*\n"
           "module ghost_intg_gen (\n"
           "  input  tl_h2d_t tl_i,\n"
           "  output tl_h2d_t tl_o\n"
           ");\n"
           "  prim_secded_enc u_enc ();\n"
           "endmodule\n"
           "*/\n")
    mod, why = RBD.find_host_intg_gen([("rtl/gen.sv", src)],
                                      "tlul_pkg::tl_h2d_t")
    assert mod is None
    assert "pass-through" in why
