#!/usr/bin/env python3
"""Step 21 — the clock-vs-signal disclosure that could not find the SDC.

THE DEFECT. `route_congestion_trade_disclosure` exists to say WHICH nets global
routing stripped a non-default rule from, and specifically whether any of them
is a CLOCK net — the whole point being that a clock net routed at default
width/spacing has traded R / skew / crosstalk margin away. It classified from
"the design's OWN clock evidence" read out of the SDC — but probed three
hardcoded FILENAMES:

    phase3/stage3/pnr/constraints.sdc
    phase3/stage3/sdc/design.sdc
    reports/phase3/constraints.sdc

The phase-3 runner writes `phase3/stage3/pnr/constraint.sdc` — SINGULAR
(`_ATPG_SDC_REL`, and the `read_sdc {pnr}/constraint.sdc` line in every OpenROAD
script it emits). Not one of the three names a file the flow produces, so the
classification could never be made on real data.

MEASURED on the real completed run `campaign_pr427/spm/converge_ihp-sg13g2`
(pure-digital standard cell; SDC and PnR log are digital artefacts):

    ground truth   3 *.sdc under the project, between them
                   `create_clock -name clk      ... [get_ports clk]`
                   `create_clock -name clk_main ... [get_ports {clk}]`
    origin/main    clock_nets = []          clock_evidence_available = False
    this branch    clock_nets = [clk, clk_main]   clock_evidence_available = True

The data was there and the regexes already matched it; only the filename guess
was wrong. Discovery is now by DIRECTORY + `*.sdc`, using `clock_plan_check`'s
`_SDC_DIR_CANDIDATES` — the plugin's existing convention for this same question.

WHAT IT COSTS. Nothing in rc: this gate is wired `advisory_program_exit_zero`
and returns 0 whether or not it finds evidence. It costs a directory glob per
run, and it turns "clock classification UNKNOWN — treat every trade as
potentially on a clock net" into a real answer. Where a trade IS on a clock net
the disclosure now says so, which is louder, not quieter.

WHAT THE WIDENING DRAGS IN — disclosed, not silently accepted. Measured over
every tracked project snapshot (119 of them across `benchmark-data`),
`clock_nets()` goes from `set()` to non-empty on 25. TWENTY-TWO of those 25
draw part of the answer from `phase2/stage1/fpga/*.sdc` — the FPGA-prototype
constraint file, whose template clock is `clk_main` — so a PHASE-3 routing
question harvests a clock name from the FPGA flow. That includes
`benchmark-data/ic/ibex` (real clock `clk_i`) and `.../subservient` (real clock
`i_clk`), each of which gets `clk_main` added ALONGSIDE the right answer.
`clock_nets()` returns a name SET used only to label nets the router already
reported a trade on, so an extra name can only OVER-report; it cannot hide a
clock trade and it cannot move a verdict tier. `phase2/stage1/fpga` stays
because it is what `clock_plan_check._SDC_DIR_CANDIDATES` lists, and the parity
is what stops the two from drifting apart again. See the source comment on
`_SDC_DIR_CANDIDATES` for the same numbers.

DIRECTION-1 GUARDS (`test_d1_*`) hold on the pre-fix tree too.
"""
from __future__ import annotations

import sys
from pathlib import Path

_PROGRAMS = Path(__file__).resolve().parents[1]
if str(_PROGRAMS) not in sys.path:
    sys.path.insert(0, str(_PROGRAMS))

import route_congestion_trade_disclosure as R  # noqa: E402

# The real run's constraint.sdc, verbatim in shape.
_PNR_SDC = (
    "# generated by phase3_one_shot_runner\n"
    "create_clock -name clk -period 10.0 [get_ports clk]\n"
    "set_clock_uncertainty 0.1 [get_clocks clk]\n"
)
_FPGA_SDC = "create_clock -name clk_main -period 10 [get_ports {clk}]\n"

# The real GRT-0273 message shape.
_LOG_CLOCK_TRADE = (
    "[INFO GRT-0020] Global routing.\n"
    "[WARNING GRT-0273] Disabled NDR (to reduce congestion) for net: clk\n"
    "[INFO GRT-0096] Final congestion report:\n"
)
_LOG_SIGNAL_TRADE = (
    "[INFO GRT-0020] Global routing.\n"
    "[WARNING GRT-0273] Disabled NDR (to reduce congestion) for net: dat_o[3]\n"
)


def _project(tmp: Path, *, sdc_rel="phase3/stage3/pnr/constraint.sdc",
             sdc_text=_PNR_SDC, log_text=_LOG_CLOCK_TRADE) -> Path:
    proj = tmp / "proj"
    pnr = proj / "phase3" / "stage3" / "pnr"
    pnr.mkdir(parents=True)
    (pnr / "pnr.log").write_text(log_text)
    sdc = proj / sdc_rel
    sdc.parent.mkdir(parents=True, exist_ok=True)
    sdc.write_text(sdc_text)
    return proj


# ===========================================================================
# The SDC the flow actually writes is found
# ===========================================================================
def test_the_runners_own_sdc_filename_is_found(tmp_path):
    """`constraint.sdc`, singular — the name the runner writes and the one
    none of the three hardcoded candidates matched."""
    proj = _project(tmp_path)
    assert R.clock_nets(proj) == {"clk"}, (
        "the disclosure still cannot read the SDC the flow produces")


def test_a_clock_trade_is_classified_as_a_clock_trade(tmp_path):
    """The observable property the gate exists for, end to end."""
    rep = R.audit(_project(tmp_path))
    assert rep["clock_evidence_available"] is True
    assert rep["trades"] == ["clk"]
    assert rep["clock_trades"] == ["clk"], rep


def test_sdc_in_any_known_constraint_directory_is_found(tmp_path):
    """Real runs carry several SDCs; the evidence is their union, not
    whichever one a hardcoded path happened to name."""
    proj = _project(tmp_path)
    fpga = proj / "phase2" / "stage1" / "fpga"
    fpga.mkdir(parents=True)
    (fpga / "spm.sdc").write_text(_FPGA_SDC)
    assert R.clock_nets(proj) == {"clk", "clk_main"}


def test_discovery_is_by_extension_not_by_filename(tmp_path):
    """A filename rule is what broke this. Any `*.sdc` in a constraint
    directory must count."""
    proj = _project(tmp_path, sdc_rel="phase3/stage3/constraints/whatever.sdc")
    assert R.clock_nets(proj) == {"clk"}


# ===========================================================================
# Two-sided control
# ===========================================================================
def test_a_signal_trade_is_not_called_a_clock_trade(tmp_path):
    """Finding the SDC must not turn every trade into a clock trade."""
    proj = _project(tmp_path, log_text=_LOG_SIGNAL_TRADE)
    rep = R.audit(proj)
    assert rep["trades"] == ["dat_o[3]"]
    assert rep["clock_trades"] == [], rep


def test_no_sdc_at_all_still_reports_unknown(tmp_path):
    """The honest no-evidence branch must survive: with nothing to read, the
    gate says UNKNOWN rather than inventing a classification."""
    proj = tmp_path / "p"
    pnr = proj / "phase3" / "stage3" / "pnr"
    pnr.mkdir(parents=True)
    (pnr / "pnr.log").write_text(_LOG_CLOCK_TRADE)
    rep = R.audit(proj)
    assert rep["clock_evidence_available"] is False
    assert rep["clock_trades"] == []


def test_an_sdc_with_no_create_clock_is_not_evidence(tmp_path):
    proj = _project(tmp_path, sdc_text="set_units -time ns\nset_load 0.1 [all_outputs]\n")
    assert R.clock_nets(proj) == set()


# ===========================================================================
# DIRECTION-1 GUARDS — hold on the pre-fix tree too
# ===========================================================================
def test_d1_the_real_grt0273_message_is_still_parsed():
    assert R.parse_trades(_LOG_CLOCK_TRADE) == ["clk"]


def test_d1_the_message_verb_is_still_never_taken_as_a_net_name():
    """`GRT-0273] Disabled NDR ...` once yielded the net name "Disabled"."""
    assert "Disabled" not in R.parse_trades(_LOG_CLOCK_TRADE)
    assert "disabled" not in [n.lower() for n in R.parse_trades(_LOG_CLOCK_TRADE)]


def test_d1_no_trade_stays_no_trade(tmp_path):
    proj = _project(tmp_path, log_text="[INFO GRT-0020] Global routing.\n")
    rep = R.audit(proj)
    assert rep["disclosed"] is False
    assert rep["trades"] == []


def test_d1_a_missing_pnr_log_is_still_reported_not_crashed(tmp_path):
    rep = R.audit(tmp_path / "nothing")
    assert rep["disclosed"] is False
    assert rep["reason"] == "no PnR log found"


def test_d1_the_gate_stays_advisory(tmp_path):
    """§4.05: DISCLOSURE ONLY — the verdict tier is unchanged."""
    proj = _project(tmp_path)
    assert R.main([str(proj)]) == 0
    assert "DISCLOSURE ONLY" in R.audit(proj)["note"]
