#!/usr/bin/env python3
"""Wave 77 — INDEX.md freshness CI.

Re-runs `tools/gen_programs_index.py --check` and FAILs if the
committed INDEX.md drifts from what the generator would produce.

This is the lock that keeps the auto-generated catalog from rotting:
any new gate, renamed gate, or _APPLICABLE_CLASSES change forces the
author to regenerate the INDEX before the PR can land.

Skip behaviour: when running from the opensource_repo/ mirror tree,
the generator itself may not be present — skip rather than FAIL since
the mirror is a derived artefact (the source-of-truth tree always has
the generator + an up-to-date INDEX).
"""
from __future__ import annotations
import subprocess
import sys
from pathlib import Path
import pytest

# parents[5] = AI_IC_design/ (real tree) or opensource_repo/ (mirror).
ROOT = Path(__file__).resolve().parents[5]
GEN = ROOT / "tools" / "gen_programs_index.py"
INDEX = (
    ROOT
    / "vibe-ic-marketplace"
    / "plugins"
    / "vibe-ic"
    / "programs"
    / "INDEX.md"
)


def test_index_md_exists():
    assert INDEX.exists(), (
        f"INDEX.md missing at {INDEX}; run "
        f"`python3 tools/gen_programs_index.py`"
    )


def test_index_carries_auto_generated_marker():
    """Belt-and-braces: a hand-edited INDEX would lose the marker
    and break this test even if the content happened to match."""
    text = INDEX.read_text()
    assert "AUTO-GENERATED by tools/gen_programs_index.py" in text


def test_index_is_fresh():
    if not GEN.exists():
        pytest.skip(
            f"generator not present at {GEN} (mirror tree); freshness "
            f"is enforced in the source-of-truth tree only"
        )
    r = subprocess.run(
        [sys.executable, str(GEN), "--check"],
        capture_output=True, text=True, timeout=60,
    )
    assert r.returncode == 0, (
        f"INDEX.md is stale — re-run `python3 tools/gen_programs_index.py`."
        f"\nstderr:\n{r.stderr}\nstdout:\n{r.stdout}"
    )


def test_index_lists_every_non_helper_program():
    """Sanity: every *.py under programs/ that isn't a helper / shim
    must appear in the alphabetical listing. Catches a future
    generator regression that forgets a row."""
    progs = (
        ROOT
        / "vibe-ic-marketplace"
        / "plugins"
        / "vibe-ic"
        / "programs"
    )
    text = INDEX.read_text()
    missing = []
    for p in sorted(progs.glob("*.py")):
        name = p.stem
        if name.startswith("_"):
            continue
        head = p.read_text(errors="replace")[:2000]
        if "DEPRECATION SHIM" in head.upper():
            continue
        if f"`{name}`" not in text:
            missing.append(name)
    assert not missing, (
        f"INDEX.md missing {len(missing)} program(s): {missing[:10]}"
        f"{'...' if len(missing) > 10 else ''}"
    )
