"""`sdc_gen` names its output `{top}.sdc` from a top it resolves PER RUN, so a
change in that resolution orphans the previous run's deck in the directory
`sdc_validator_check` globs — and step 8 then FAILs forever on a file
constraining a module the design does not declare.

Measured on the tracked corpus: 4 roots carry >=2 generated decks under
different `# Top entity:` names, and the validator grades every one of them
(`espi` FAIL(6), `mdio` FAIL(4), `usb_pd` FAIL(4) before any regeneration).

WHY THE FIX IS IN THE CONSUMER — AND WHAT THAT COSTS TO GET WRONG
==================================================================
The obvious fix is for the generator to delete its own superseded siblings.
It cannot: the only top it knows is the one IT resolved this run, which is
exactly the unstable quantity, and the resolution ladder (`--top-name`, else
a board wrapper, else `L9.top_module`, else the literal `chip_top`) can
resolve to a module the design does not contain at all. On the corpus's
`usb_pd`, `L9.top_module` is `usb_pd_engine` and `grep -rn "module
usb_pd_engine"` over the whole project returns nothing; the only staged tops
are `chip_top` and `usb_pd_bmc_phy`. A resolution-keyed deletion therefore
destroys `chip_top.sdc` — the deck for the module that EXISTS — and keeps the
deck for the phantom. On `ibex` the same inversion destroys a COMPLETE 56-line
deck (its own `create_clock` on the real top's `clk_i`, 36 `set_input_delay`).

So the survivor's IDENTITY is the property under test here, not the file
count. `test_the_deck_for_the_module_that_exists_survives_a_phantom_l9_top`
is the control that pins it: it goes RED against any fix that keys on the
per-run resolution instead of on what the project DECLARES.

BIDIRECTIONAL CONTROLS
======================
FORWARD (RED against the byte-identical pre-fix `sdc_validator_check`,
GREEN after):
  * `test_a_superseded_generator_deck_is_not_graded` — the base case.
  * `test_the_second_search_root_is_covered_too` — the SAME orphan under
    `phase2/stage2/constraints`. `_SEARCH_ROOTS` is TWO directories; a
    generator-side cleanup walks only `fpga_early_dir`, so it leaves this one
    exactly where it found it and step 8 still FAILs.
  * `test_every_deck_superseded_is_not_checked_never_pass` — the filter's
    empty-set case lands in the exit-2 tier. This one is dual-role: it is
    RED pre-fix (which reports exit 1), and it is also the guard that goes
    RED against any fix that lets an emptied set certify step 8 at exit 0.
  * `test_the_generator_banner_the_consumer_looks_for_is_the_one_it_writes`
    — drives `sdc_gen` and parses its real output with the checker's own
    reader, so emitter and checker cannot drift into two spellings of "is
    this file ours?". Necessarily post-fix-only: the shared reader is what
    the fix introduces.

REVERSE (GREEN pre-fix; they go RED only if the fix OVER-reaches — i.e. if
it becomes "grade fewer files until step 8 goes green", or "delete"):
  * `test_the_deck_for_the_module_that_exists_survives_a_phantom_l9_top` —
    the IDENTITY control described above. RED against a resolution-keyed fix.
  * `test_a_foreign_sdc_is_never_set_aside` — no generator banner, no
    ownership, no licence to ignore it.
  * `test_the_declared_top_deck_is_graded_even_if_the_rtl_lacks_that_module`
    — the deck this run is producing is graded whatever the module set says,
    so an incomplete current deck still FAILs.
  * `test_nothing_is_removed_from_disk` — RED against any fix that resolves
    this by deleting the orphan rather than declining to grade it.
"""
import json
import subprocess
import sys
from pathlib import Path

# The gatekeeper harness runs pytest under `--timeout=180` (tools/gatekeeper-land.sh),
# and `ci_harness_timeout_ceiling_check` requires every inner blocking call to be
# bounded at or under 180 // 3 = 60s. A larger inner bound can outlive the harness,
# and what then dies is the SESSION, not the test. Named so the ceiling is visible
# at authoring time -- this defect was written five separate times in one session.
_GATE_TIMEOUT_S = 60

PROGRAMS = Path(__file__).resolve().parent.parent
VALIDATOR = PROGRAMS / "sdc_validator_check.py"
SDC_GEN = PROGRAMS / "sdc_gen.py"

_BANNER = "Auto-generated by sdc_gen.py"


def _generated_deck(top: str, *, complete: bool) -> str:
    """A deck in exactly the shape `sdc_gen._render_sdc` writes one."""
    text = (
        "# =========================================================================\n"
        f"# {_BANNER} (Wave 72/73)\n"
        f"# Top entity: {top}\n"
        "# Clock: clk period=20 ns\n"
        "# DO NOT hand-edit; regenerate via sdc_gen.py.\n"
        "# =========================================================================\n"
        "\n"
        "create_clock -name clk_main -period 20 [get_ports {clk}]\n"
        "derive_clock_uncertainty\n"
    )
    if complete:
        text += ("set_input_delay  -clock clk_main -max 4.0 [get_ports {data_i}]\n"
                 "set_output_delay -clock clk_main -max 4.0 [get_ports {data_o}]\n")
    return text


def _foreign_deck() -> str:
    """Hand-authored / third-party: no banner, so nobody owns it."""
    return ("# board team's extra constraints -- do not regenerate\n"
            "# Top entity: some_bench_harness\n"
            "create_clock -name clk50 -period 20.000 [get_ports {CLOCK_50}]\n")


def _scaffold(tmp_path: Path, *, l9_top: str,
              rtl_modules=("chip_top",)) -> Path:
    proj = tmp_path / "proj"
    (proj / "phase1" / "generated_docs").mkdir(parents=True)
    rtl = proj / "phase2" / "stage1" / "rtl"
    rtl.mkdir(parents=True)
    (proj / "phase1" / "generated_docs" / "L8_RTL_CONSTANTS.json").write_text(
        json.dumps({"clock_mhz": 50}))
    (proj / "phase1" / "generated_docs" / "L9_INTEGRATION_SPEC.json").write_text(
        json.dumps({
            "top_module": l9_top,
            "top_module_pins": [
                {"name": "clk", "mode": "input"},
                {"name": "reset_n", "mode": "input"},
                {"name": "data_i", "mode": "input"},
                {"name": "data_o", "mode": "output"},
            ],
        }))
    for mod in rtl_modules:
        (rtl / f"{mod}.v").write_text(
            f"module {mod}(input wire clk, input wire reset_n, "
            f"input wire [7:0] data_i, output wire [7:0] data_o);\n"
            f"endmodule\n")
    return proj


def _fpga(proj: Path) -> Path:
    d = proj / "phase2" / "stage1" / "fpga"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _constraints(proj: Path) -> Path:
    d = proj / "phase2" / "stage2" / "constraints"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _validate(proj: Path, report: Path = None):
    cmd = [sys.executable, str(VALIDATOR), str(proj)]
    if report is not None:
        cmd += ["--json", str(report)]
    return subprocess.run(cmd, capture_output=True, text=True, timeout=_GATE_TIMEOUT_S)


# ----- FORWARD -------------------------------------------------------

def test_a_superseded_generator_deck_is_not_graded(tmp_path):
    """RED pre-fix: the orphan's missing I/O delays FAIL step 8."""
    proj = _scaffold(tmp_path, l9_top="chip_top")
    fpga = _fpga(proj)
    (fpga / "chip_top.sdc").write_text(_generated_deck("chip_top",
                                                       complete=True))
    orphan = fpga / "ghost_top.sdc"
    orphan.write_text(_generated_deck("ghost_top", complete=False))

    report = tmp_path / "sdc_validator.json"
    cp = _validate(proj, report)

    assert cp.returncode == 0, (
        "a deck this generator wrote for 'ghost_top' — a module the design "
        f"does not declare — must not be graded:\n{cp.stdout}\n{cp.stderr}")
    # DISCLOSED, not silently dropped.
    assert "superseded" in cp.stdout and "ghost_top" in cp.stdout, cp.stdout
    doc = json.loads(report.read_text())
    assert [Path(e["path"]).name for e in doc["sdc_files_superseded"]] == [
        "ghost_top.sdc"], doc
    assert doc["sdc_files_superseded"][0]["top_entity"] == "ghost_top", doc
    assert [Path(p).name for p in doc["sdc_files_checked"]] == [
        "chip_top.sdc"], doc


def test_the_second_search_root_is_covered_too(tmp_path):
    """RED pre-fix, and RED for any generator-side cleanup.

    `_SEARCH_ROOTS` is `phase2/stage1/fpga` AND `phase2/stage2/constraints`.
    A cleanup that walks the generator's own output directory never reaches
    this orphan, so step 8 keeps failing on the identical file one directory
    over. The consumer sees both roots by construction.
    """
    proj = _scaffold(tmp_path, l9_top="chip_top")
    (_fpga(proj) / "chip_top.sdc").write_text(
        _generated_deck("chip_top", complete=True))
    orphan = _constraints(proj) / "ghost_top.sdc"
    orphan.write_text(_generated_deck("ghost_top", complete=False))

    cp = _validate(proj)
    assert cp.returncode == 0, (
        "the orphan under phase2/stage2/constraints is the same defect as the "
        f"one under phase2/stage1/fpga:\n{cp.stdout}\n{cp.stderr}")
    assert "ghost_top" in cp.stdout, cp.stdout
    assert orphan.is_file()


# ----- REVERSE: the IDENTITY of the survivor -------------------------

def test_the_deck_for_the_module_that_exists_survives_a_phantom_l9_top(tmp_path):
    """THE identity control (the corpus `usb_pd` / `ibex` shape).

    `L9.top_module` names `usb_pd_engine`, which the design does not declare;
    the module it DOES declare is `chip_top`. Both decks are on disk. The one
    for the module that EXISTS must be graded — so its missing I/O delays must
    still FAIL step 8 and must still be NAMED.

    Any fix keyed on the run's resolved top (`--top-name` > board wrapper >
    `L9.top_module` > `chip_top`) discards `chip_top.sdc` here and reports
    PASS. That is the inversion this test exists to catch, and it is why the
    predicate keys on the design's own module set instead.
    """
    proj = _scaffold(tmp_path, l9_top="usb_pd_engine",
                     rtl_modules=("chip_top", "usb_pd_bmc_phy"))
    fpga = _fpga(proj)
    survivor = fpga / "chip_top.sdc"
    survivor.write_text(_generated_deck("chip_top", complete=False))
    (fpga / "usb_pd_engine.sdc").write_text(
        _generated_deck("usb_pd_engine", complete=True))

    report = tmp_path / "sdc_validator.json"
    cp = _validate(proj, report)

    assert cp.returncode == 1, (
        "chip_top is a module this design DECLARES, so its deck is part of "
        "the constraint set and its missing I/O delays are a real FAIL — a "
        "resolver that keys on L9's phantom top discards it and reports "
        f"PASS:\n{cp.stdout}\n{cp.stderr}")
    assert "chip_top.sdc" in cp.stdout, cp.stdout
    assert survivor.is_file(), "the deck for the module that EXISTS was lost"
    doc = json.loads(report.read_text())
    # `.get` so this control is GREEN against the pre-fix program too (which
    # has no such key): its job is to go RED when a fix over-reaches, not to
    # depend on the fix existing.
    assert doc.get("sdc_files_superseded", []) == [], doc
    assert sorted(Path(p).name for p in doc["sdc_files_checked"]) == [
        "chip_top.sdc", "usb_pd_engine.sdc"], doc


def test_a_foreign_sdc_is_never_set_aside(tmp_path):
    """No banner => not ours => no licence to ignore it, whatever it names."""
    proj = _scaffold(tmp_path, l9_top="chip_top")
    fpga = _fpga(proj)
    (fpga / "chip_top.sdc").write_text(_generated_deck("chip_top",
                                                       complete=True))
    hand = fpga / "board_extra.sdc"
    hand.write_text(_foreign_deck())

    cp = _validate(proj)
    assert cp.returncode == 1, (
        "a hand-authored SDC is part of the constraint set even though its "
        f"`# Top entity:` names nothing the design declares:\n{cp.stdout}")
    assert "board_extra.sdc" in cp.stdout, cp.stdout
    assert hand.is_file()


def test_the_declared_top_deck_is_graded_even_if_the_rtl_lacks_that_module(
        tmp_path):
    """The deck this run is PRODUCING is never set aside.

    Without this guard the fix becomes the generator's bug in mirror image:
    a project whose L9 declares a top the RTL does not contain would have its
    only current deck filtered out, and step 8 would stop biting on the very
    file the flow just wrote.
    """
    proj = _scaffold(tmp_path, l9_top="usb_pd_engine",
                     rtl_modules=("chip_top",))
    (_fpga(proj) / "usb_pd_engine.sdc").write_text(
        _generated_deck("usb_pd_engine", complete=False))

    cp = _validate(proj)
    assert cp.returncode == 1, (
        "the deck for the top the project DECLARES must still be graded, and "
        f"an incomplete one must still FAIL:\n{cp.stdout}\n{cp.stderr}")
    assert "usb_pd_engine.sdc" in cp.stdout, cp.stdout


def test_every_deck_superseded_is_not_checked_never_pass(tmp_path):
    """The "made unfailable" guard.

    If the filter can empty the set and still report PASS, step 8 is
    certifiable by having no valid constraint file at all. Nothing that
    constrains a declared top was read, so this is the exit-2 NOT-CHECKED
    tier — the same one "no .sdc anywhere" already lives in.
    """
    proj = _scaffold(tmp_path, l9_top="chip_top")
    (_fpga(proj) / "ghost_top.sdc").write_text(
        _generated_deck("ghost_top", complete=False))

    report = tmp_path / "sdc_validator.json"
    cp = _validate(proj, report)
    assert cp.returncode != 0, (
        "an empty graded set must never certify step 8:\n" + cp.stdout)
    assert cp.returncode == 2, cp.stdout
    assert "NOT CHECKED" in cp.stdout and "ghost_top" in cp.stdout, cp.stdout
    doc = json.loads(report.read_text())
    assert doc["verdict"] == "SKIP" and doc["sdc_files_checked"] == [], doc
    assert len(doc.get("sdc_files_superseded", [])) == 1, doc


def test_nothing_is_removed_from_disk(tmp_path):
    """Set aside is not deleted. Being wrong here costs a stale artifact,
    not a lost one — the whole reason the fix is not a cleanup.

    Deliberately asserts nothing about the exit code, so it is GREEN against
    the pre-fix program and RED only against a fix that resolves the orphan
    by unlinking it.
    """
    proj = _scaffold(tmp_path, l9_top="chip_top")
    fpga = _fpga(proj)
    (fpga / "chip_top.sdc").write_text(_generated_deck("chip_top",
                                                       complete=True))
    orphan = fpga / "ghost_top.sdc"
    body = _generated_deck("ghost_top", complete=False)
    orphan.write_text(body)

    _validate(proj)
    assert orphan.is_file() and orphan.read_text() == body, (
        "the validator is READ-ONLY; a superseded deck stays on disk")


# ----- REVERSE: emitter/checker coupling -----------------------------

def test_the_generator_banner_the_consumer_looks_for_is_the_one_it_writes(
        tmp_path):
    """Drive `sdc_gen`, then parse its REAL output with the consumer's own
    reader. A source-text assertion would pass while the two drifted."""
    sys.path.insert(0, str(PROGRAMS))
    try:
        import sdc_constraints as sdc  # noqa: E402
    finally:
        sys.path.pop(0)

    proj = _scaffold(tmp_path, l9_top="chip_top")
    _fpga(proj)
    cp = subprocess.run([sys.executable, str(SDC_GEN), str(proj), "--force"],
                        capture_output=True, text=True, timeout=_GATE_TIMEOUT_S)
    assert cp.returncode == 0, f"{cp.stdout}\n{cp.stderr}"
    written = _fpga(proj) / "chip_top.sdc"
    assert written.is_file(), cp.stdout

    assert sdc.generated_top_entity_of(written) == "chip_top", (
        "the checker must recognise, in the generator's REAL output, both the "
        "banner that proves ownership and the top it claims — otherwise every "
        "deck reads as foreign and nothing is ever set aside")
    # And the reader refuses to claim what it did not write.
    assert sdc.generated_top_entity(_foreign_deck()) is None
