# Bucket A — program-rule sketches for programs/pad_ring_gen.py
# Corpus-sweep REQUIRED before merging into programs/pad_ring_gen.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: 
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_absence_verdict_names_its_search_space(sample_text, ports):
    """A refusal whose rule id declares a thing NOT FOUND / ABSENT / MISSING / `NOT_PRESENT` must carry, in the same refusal, an expression that names WHERE the program looked. LADDER: not Bucket T — upstream has no defect here. librelane declares `PAD_FAKE_SITES` (config/flow.py:494) and materialises it inside `read_tech_lef` (io.tcl:349) BEFORE its own site lookups run (`pad_cfg`.tcl:40), so the sites exist in the DB by the time any padring script asks for them. Ours was the only layer that never opened the declaration; a fork change would paper over our omission. Stop at A. THE EXACT INPUT a program sees: the module's own AST. THE EXACT DECISION from that input: does the call that constructs this refusal contain any expression naming a search locus? That is syntax, not judgement. The one decision it CANNOT make from that input is whether the named search space is COMPLETE — completeness is a property of the DISTRIBUTION, not of our source, and no amount of reading our Python decides whether the two views a PDK declares a site in were both opened. The rule is therefore scoped to the reachable half: refuse an absence verdict that names NO search space at all."""
    # Expected signal: ERROR
    # Suggested fix action: THE RULE, CORRECTED TWICE BY MEASUREMENT. Attempt 1 (the prior lane's, shipped nowhere): the message mentions a word from a locus vocabulary -- PASSES the real pre-fix refusal. Attempt 2 (my probe, evidence/`F1_rule_population_probe`.py, not shipped): the message interpolates a name the enclosing function iterated -- refuses 15 of 24, and the first two I read are model disclosures that name their exact path. Both are measuring something ADJACENT to the question and neither error is visible from inside its own implementation. What decides both cases is the thing neither looks at: THE CONDITION THAT RAISED THE REFUSAL. `if not d.is_dir()` -> subject is `d`, message names `d`, complete. `if site is None` -> subject is the lookup that returned None, and the provenance of THAT is what the pre-fix message never disclosed. So the rule is: AN ABSENCE VERDICT MUST NAME THE SUBJECT OF THE CONDITION THAT RAISED IT -- a dataflow question from the refusal back to its guard. Still deterministic, still Bucket A, and real program work rather than a predicate tweak. NOT ATTEMPTED A THIRD TIME: past this point I would be iterating shapes until one came out green on today's corpus, and a predicate arrived at that way is fitted to the corpus rather than to the rule. GENERAL-CORE TEST: reads refusal construction and control flow; no pad, no PDK literal.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: 
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_unhonoured_config_variable_degrades_loudly(sample_text, ports):
    """A configuration variable that a step DECLARES in its contract but does not implement must degrade loudly: at the upstream default (indistinguishable from never having set it) PROCEED and record the non-honouring in EVERY report including the skips, because a disclosure only on the happy path is not a disclosure; DELIBERATELY SET to a non-default, refuse rc=2 NOT DETERMINED naming the variable — never rc 0, never rc 1, because 'I cannot honour what you asked' is neither a pass nor a finding about the design. LADDER — AND THE BRIEF'S PREMISE FOR THIS ONE IS REFUTED. The brief states `PAD_ROTATION_VERTICAL` was 'proven inert by four separate OpenROAD processes'. It is NOT inert, and the source that proves it is the report I was sent to capture: re-measured in OpenROAD 26Q3-1581 holding one rotation parameter and varying the other across ALL FOUR sides, -`rotation_horizontal` moves WEST and EAST and -`rotation_vertical` moves SOUTH and NORTH. THE PARAMETERS ARE NAMED FOR THE ROW AXIS, NOT THE SIDE. The original probe varied `PAD_ROTATION_VERTICAL` while observing only WEST and EAST — the wrong pairing — so it correctly saw no change and the wrong conclusion was drawn from a correct measurement. WHICH HALF IS WHICH, as the brief asks: there is no tool half. The tool honours the variable and is self-consistent with its own naming convention; renaming a fork's CLI flags to match a side-based reading would break every upstream script that drives it. The whole of this finding is ours. Bucket T is empty for a MEASURED reason, not a judgement call. Stop at A. THE EXACT INPUT: the step's declared config contract plus the variable's resolved value. THE EXACT DECISION: is this name in the not-honoured set, and is its value non-default? A lookup and a comparison."""
    # Expected signal: ERROR
    # Suggested fix action: Keep a not-honoured set beside the contract. On a non-default value for any member, exit 2 NOT DETERMINED naming the variable. On the default, proceed and emit the disclosure into every report the step writes, skips included. THE SCHEMA KEY MUST NOT ASSERT THE REFUTED PREMISE: the shipped record keyed this `rotation_vertical_inert`, which asserts inertness in the schema itself; it is `rotation_vertical_not_honoured` (fixed in c56b8e1b1). The ruling's BEHAVIOUR is unchanged by the refutation and its justification gets stronger — the weak version was 'an author who sets a knob is entitled to be told it does nothing'; the true one is that the knob HAS an effect, it rotates the N/S pads, and this step does not implement it, so honouring the declaration silently would hand an author geometry they did not ask for. GENERAL-CORE TEST: generalise the RULE, not the variable — the logic reads a contract and a value, and knows nothing about pads or rotation.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: 
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_refuted_finding_must_lose_its_identifier(sample_text, ports):
    """A finding recorded in a SCHEMA KEY, a CONSTANT NAME or a REPORT FIELD cannot be retracted by prose elsewhere. When the finding is refuted, the identifier changes in the same commit that records the refutation, because every downstream reader keys on the identifier and none of them reads the retraction. LADDER: not Bucket T (no tool is involved in what we name our own fields), not B or C (nothing here needs judgement). THE EXACT INPUT: the shipped source plus the record of what was refuted. THE EXACT DECISION: does an identifier still assert a proposition the project has recorded as false? That is a comparison between two written-down things. MEASURED ON `origin/main` `a4caccefe`, and this is a LIVE state, not a historical one: the report that refutes the inertness premise says the rename landed in `c56b8e1b1`. `git merge-base --is-ancestor c56b8e1b1 origin/main` says it is NOT an ancestor. Main today ships the artefact key `rotation_vertical_inert` (`pad_ring_gen.py`:246), the constant `ROTATION_VERTICAL_INERT` with `honoured`: False (:185), the section heading that the variable IS INERT (:67), and the comment that the placer does not read it. Every one of those asserts, in the schema and in the source, the proposition the branch's own re-measurement withdrew."""
    # Expected signal: ERROR
    # Suggested fix action: Rename the key and the constant to `rotation_vertical_not_honoured` / `ROTATION_VERTICAL_NOT_HONOURED` and restate the two comments as what was actually measured: the variable is not inert, it steers the SOUTH and NORTH rows, and THIS STEP does not implement it. The behaviour of the ruling does not change and its justification gets stronger. AND A SECOND CONSEQUENCE, NAMED BUT NOT CONFIRMED BY ME, because I have run no tool: if the re-measured table is right that `rotation_horizontal` steers WEST and EAST while `rotation_vertical` steers SOUTH and NORTH, then main's side map is TRANSPOSED -- `pad_ring_gen.py`:317-318 drives SOUTH and NORTH from `PAD_ROTATION_HORIZONTAL`, and WEST and EAST come from the hard-coded `VERTICAL_SIDE_ORIENT` constants, which were measured only at that variable's default. A design declaring a non-default `PAD_ROTATION_HORIZONTAL` would then get emitted orientations the placer does not produce, and the rc=2 refusal guards the OTHER variable, so nothing stops it. THIS NEEDS ONE OPENROAD RUN TO SETTLE AND MUST NOT BE ACTED ON UNTIL IT HAS ONE. It is written down because an unverified consequence that is named can be checked, and one that is not named cannot.
    return []  # list of findings — TODO implement
