# Bucket A — program-rule sketches for programs/pad_ring_gen.py
# Corpus-sweep REQUIRED before merging into programs/pad_ring_gen.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: 
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_absence_verdict_names_its_search_space(sample_text, ports):
    """A refusal whose rule id declares a thing NOT FOUND / ABSENT / MISSING / `NOT_PRESENT` must carry, in the same refusal, an expression that names WHERE the program looked. LADDER: not Bucket T — upstream has no defect here. librelane declares `PAD_FAKE_SITES` (config/flow.py:494) and materialises it inside `read_tech_lef` (io.tcl:349) BEFORE its own site lookups run (`pad_cfg`.tcl:40), so the sites exist in the DB by the time any padring script asks for them. Ours was the only layer that never opened the declaration; a fork change would paper over our omission. Stop at A. THE EXACT INPUT a program sees: the module's own AST. THE EXACT DECISION from that input: does the call that constructs this refusal contain any expression naming a search locus? That is syntax, not judgement. The one decision it CANNOT make from that input is whether the named search space is COMPLETE — completeness is a property of the DISTRIBUTION, not of our source, and no amount of reading our Python decides whether the two views a PDK declares a site in were both opened. The rule is therefore scoped to the reachable half: refuse an absence verdict that names NO search space at all."""
    # Expected signal: ERROR
    # Suggested fix action: Walk every programs/*.py AST; collect calls whose first positional argument is a string literal matching *_NOT_FOUND|*_ABSENT|*_MISSING|*_NOT_PRESENT; require the same call to carry a locus expression (a path-shaped literal, an interpolated name from a locus vocabulary, or a Path/os.path expression). Population is REFUSAL CONSTRUCTION only — a rule id used as an env-var name or a dict key is not a refusal. GENERAL-CORE TEST: the logic reads no pad and no PDK literal; it reads refusal construction. It was written here first, that is all.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: 
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_unhonoured_config_variable_degrades_loudly(sample_text, ports):
    """A configuration variable that a step DECLARES in its contract but does not implement must degrade loudly: at the upstream default (indistinguishable from never having set it) PROCEED and record the non-honouring in EVERY report including the skips, because a disclosure only on the happy path is not a disclosure; DELIBERATELY SET to a non-default, refuse rc=2 NOT DETERMINED naming the variable — never rc 0, never rc 1, because 'I cannot honour what you asked' is neither a pass nor a finding about the design. LADDER — AND THE BRIEF'S PREMISE FOR THIS ONE IS REFUTED. The brief states `PAD_ROTATION_VERTICAL` was 'proven inert by four separate OpenROAD processes'. It is NOT inert, and the source that proves it is the report I was sent to capture: re-measured in OpenROAD 26Q3-1581 holding one rotation parameter and varying the other across ALL FOUR sides, -`rotation_horizontal` moves WEST and EAST and -`rotation_vertical` moves SOUTH and NORTH. THE PARAMETERS ARE NAMED FOR THE ROW AXIS, NOT THE SIDE. The original probe varied `PAD_ROTATION_VERTICAL` while observing only WEST and EAST — the wrong pairing — so it correctly saw no change and the wrong conclusion was drawn from a correct measurement. WHICH HALF IS WHICH, as the brief asks: there is no tool half. The tool honours the variable and is self-consistent with its own naming convention; renaming a fork's CLI flags to match a side-based reading would break every upstream script that drives it. The whole of this finding is ours. Bucket T is empty for a MEASURED reason, not a judgement call. Stop at A. THE EXACT INPUT: the step's declared config contract plus the variable's resolved value. THE EXACT DECISION: is this name in the not-honoured set, and is its value non-default? A lookup and a comparison."""
    # Expected signal: ERROR
    # Suggested fix action: Keep a not-honoured set beside the contract. On a non-default value for any member, exit 2 NOT DETERMINED naming the variable. On the default, proceed and emit the disclosure into every report the step writes, skips included. THE SCHEMA KEY MUST NOT ASSERT THE REFUTED PREMISE: the shipped record keyed this `rotation_vertical_inert`, which asserts inertness in the schema itself; it is `rotation_vertical_not_honoured` (fixed in c56b8e1b1). The ruling's BEHAVIOUR is unchanged by the refutation and its justification gets stronger — the weak version was 'an author who sets a knob is entitled to be told it does nothing'; the true one is that the knob HAS an effect, it rotates the N/S pads, and this step does not implement it, so honouring the declaration silently would hand an author geometry they did not ask for. GENERAL-CORE TEST: generalise the RULE, not the variable — the logic reads a contract and a value, and knows nothing about pads or rotation.
    return []  # list of findings — TODO implement
