# Bucket A — program-rule sketches for programs/changelog_command_reproducibility_check.py
# Corpus-sweep REQUIRED before merging into programs/changelog_command_reproducibility_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: Shipped documentation quotes a command as the way to run a tool. The tool's options change; the document does not, because nothing relates the two. An existing guard may already check that the named FILE exists — which it does — so the command looks verified while the invocation itself has never been tried. An agent following the instruction literally gets an argument error and no output, and the document that sent it there is the same document a reviewer would consult to confirm the instruction is right.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_documented_command_must_be_accepted_by_the_program_it_names(sample_text, ports):
    """Every command quoted in shipped instruction text must be ACCEPTED by the program it names, not merely name a file that exists. Two extensions over the usual form of this guard, and each was needed to see a real case: the population must include the instruction surface an agent actually follows, not only the release notes and manifests; and the test must reach the OPTIONS, because a stale flag and a correct one point at the same existing file."""
    # Expected signal: ERROR
    # Suggested fix action: Join backslash continuations FIRST, then extract each quoted invocation, then decide acceptance from the program's own declared options — or by invoking it in a way that can only fail on argument parsing. Report the document, the program and the offending options. MEASURED: 165 quoted commands name a program that exists; 11 use an option the program neither declares nor mentions; 2 of those 11 confirmed by running them, one reporting `unrecognized arguments` outright and both exiting on an argument error. WRITE THE SCREEN CAREFULLY — mine was wrong twice, in opposite directions, on this same corpus: matching greedily across lines bled the trailing compliance block into the preceding command and reported 47, and confining the match to one line excluded every multi-line invocation and reported 0, missing the one case already proven by execution. A checker for this that is itself built by grep will reproduce one of those two numbers. INVOCATION SWEEP, AND THE MASKING RULE IT TAUGHT: of the 11 static candidates, 8 are now CONFIRMED by running them and reporting unrecognized arguments; 3 remain masked rather than cleared. ARGPARSE REPORTS ONE ERROR, so a missing required argument is announced first and HIDES an unrecognized flag on the same command line. A naive invocation test therefore clears cases it has not tested: it confirmed 4 of the 11, and supplying the required arguments took that to 8 with no change to the documents. Satisfy required arguments first, or read the parser's declared actions instead of invoking. RE-RUN after merging main and still failing identically -- rc 2, 'the following arguments are required', with the declared form returning 0 as the control. The offending text is located exactly, in the repository and not only in the installed copy: `skills/benchmark-enhancement-capture/SKILL.md` line 532, a four-line continued invocation whose three output flags were all replaced by one. It is deliberately NOT hand-patched here -- the record's claim is that a checker must catch the class, and one corrected line would leave the population unguarded while making the motivating instance disappear.
    return []  # list of findings — TODO implement
