# Bucket A — program-rule sketches for programs/lec_post_layout_check.py
# Corpus-sweep REQUIRED before merging into programs/lec_post_layout_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.68
# Pattern: A step drives an external tool, the tool exits without a usable result, and the step records a verdict meaning tool-error. The verdict text names the tool as the cause. The tool's own message is not retained anywhere. Downstream a gate reads that verdict and repeats the attribution in its own finding — so the claim that the tool failed is asserted twice by two layers, neither of which saw the tool's output. The attribution is then unfalsifiable: a genuine tool defect and a setup gap in the step's own invocation produce a byte-identical record, and the only way to tell them apart is to reproduce the run.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_tool_error_verdict_must_carry_the_tool_s_own_diagnostic(sample_text, ports):
    """A verdict that attributes a failure to an external tool must carry that tool's own diagnostic — its exit status and the tail of what it wrote — or it must not name the tool. Without the diagnostic the record cannot be routed to a layer: the same verdict is produced by a defect in the tool and by a missing input the step was supposed to supply, and those two are fixed in different repositories. A consumer of the verdict must not restate the attribution it inherited, because repeating an unevidenced claim at a second layer makes it look corroborated."""
    # Expected signal: ERROR
    # Suggested fix action: At the site that INVOKES the tool, capture its exit status and a bounded tail of its output into the artefact beside the verdict, and make the tool-error branch refuse to write a verdict that names a tool without them. At the consuming gate, derive the finding text from the retained diagnostic rather than from a literal, and where none is present say that the failure was not attributed rather than naming a tool. MEASURED, AND IT SETTLED A QUESTION THAT HAD BEEN OPEN ACROSS THIS WHOLE LANE: a post-layout equivalence failure could not be assigned to the tool or to the invocation, because the consuming gate never runs the tool and the producing step retains nothing from it. The tree itself supplies the answer the record could not: the runner's own helper documents this exact abort — physical-only cells present in the routed netlist and absent from the timing library make the tool stop before the comparison starts — and calls it a FALSE tool-error, fixing it by emitting blackbox stubs. So the failure class is the step's own setup, NOT the tool, and the record that would have sent it to the forked-tool repository was never written. CORPUS-SWEPT, AND THE SWEEP MOVED THE CHECK TO THE ARTEFACT. A code scan cannot answer this. The verdict lives in a constant rather than a literal, so a literal scan finds one site of the several that exist; and asking whether the FILE mentions an exit status or an output tail is meaningless when the producing file is tens of thousands of lines long — it says yes for reasons that have nothing to do with this artefact. The predicate is artefact-level: does the written record carry a diagnostic beside a verdict that names a tool? Measured on the one record of this kind in the tree, the keys are verdict, tool, top, skipped and a skip reason — it NAMES the tool and carries nothing from it. AND THERE IS NO SCHEMA FOR THE ARTEFACT, which is why nothing requires the field: the rule's real home is a schema that makes the diagnostic mandatory whenever the verdict names a tool, not a scan over source.
    return []  # list of findings — TODO implement
