# Bucket A — program-rule sketches for programs/_ppa_corpus.py
# Corpus-sweep REQUIRED before merging into programs/_ppa_corpus.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: Code needs THE artefact -- the contract, the report, the bundle -- and locates it by searching. A search returns a collection, so the collection is reduced to one: the first entry is taken, or the loop returns on its first iteration. When exactly one thing matched, that is correct and invisible. When two matched, the code has not found the artefact, it has found a DISAGREEMENT, and reducing to one buries the disagreement instead of reporting it. Nothing about the output changes shape: a verdict is produced, about one of the claimants, with no indication that another existed. Where the search walks a directory tree, the order is the filesystem's rather than the program's, so which claimant wins can differ between two machines holding identical trees, and a verdict that changes with the order of a directory listing cannot be reproduced or argued with.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_search_result_consumed_as_if_unique_must_prove_it_is_unique(sample_text, ports):
    """A lookup whose contract is to find ONE artefact must establish that it found one. Where the search yields several, refuse and name every claimant with enough identity to tell them apart, rather than reducing to the first. Where several are byte-identical, that is a copy rather than a disagreement and belongs in the output as a note, never as a silent de-duplication: a population whose size depends on how many times something was copied is its own defect. Never take the first result of an UNORDERED walk for a decision -- if a reduction is genuinely wanted, the order must be the program's and stated, not the filesystem's."""
    # Expected signal: ERROR
    # Suggested fix action: At each lookup that promises one artefact, materialise the matches, and branch on the count: one is the answer; none is a stated absence; more than one is a refusal naming every claimant and a content digest for each, so a reader can see whether they disagree or were copied. MEASURED, and the population is split because the split is the finding. 14 sites reduce a search to a single result. 8 take the first of an explicitly SORTED glob: deterministic, plausibly deliberate, and not claimed here as defects. 4 take the first hit of an UNSORTED walk, where the answer is whatever the filesystem lists first. That those 4 are oversights rather than decisions is not an inference: the SAME glob expression over the same plugin directory appears sorted in one program and unsorted in another, so at least one of the two was not chosen. 2 more index position zero off a glob directly, and one of those is not code but a docstring recording the repair of this exact defect -- an earlier revision resolved a bundle by walking the project and taking the first hit, which let a NESTED snapshot's bundle certify the OUTER project. That is the consequence stated by the tree itself, and it was repaired at that one site. The remedy already exists at corpus scale and should be copied rather than redesigned: a shared helper keys records by identity across 5 gates, refuses two claimants whose content differs by naming both paths and both digests, and prints byte-identical duplicates as a note instead of dropping them. So the class has a working implementation, a documented casualty, and 4 live sites, and nothing connects them. The rule fires on the original because that site reduced a multi-match walk to its first element, and on a different instance because it keys on the reduction of a search to one result without a count, naming no lookup.
    return []  # list of findings — TODO implement
