# Bucket A — program-rule sketches for programs/landing_merge_verdict.py
# Corpus-sweep REQUIRED before merging into programs/landing_merge_verdict.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A repository loses its server-side enforcement -- the automation is switched off at the account level, the branch carries no protection rule -- and the remaining guarantee is a client-side version-control hook, which the documentation correctly identifies as the only enforcement left. The hook's SOURCE is tracked, reviewed and tested: there are tests that find it in the tree, read it, and assert on its logic and its messages. None of that says the hook is INSTALLED. A hook takes effect only from an untracked location that a fresh clone, and every isolated working copy, starts without. So the tests prove the script is correct while the enforcement is simply not there, and the two states are indistinguishable from the only place anyone looks: the operation succeeds either way. Testing the script is not testing that it runs.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_enforcement_point_named_as_the_only_one_must_be_proven_present(sample_text, ports):
    """Where a guarantee rests on a client-side hook, assert that the hook is installed at the location the tool actually consults and that its contents match the tracked source. A hook lives outside the tree it protects, so every check that reads the tracked copy can pass on a machine where nothing is wired up. State the result as a verdict rather than a note: an absent enforcement point and a satisfied one produce the same silence, and the silence is read as success."""
    # Expected signal: ERROR
    # Suggested fix action: Resolve the hook path the way the tool does -- honouring a configured hooks directory and falling back to the repository's own hooks directory, and resolving it through the COMMON directory so an isolated working copy is answered correctly -- then require the file to exist, to be executable, and to match the tracked source. Report a mismatch separately from an absence: a stale installed copy is a different failure from no copy. MEASURED, first-person, on the machine this batch was produced on. The tracked hook is present and executable at 23743 bytes. The installed path does not exist and no hooks directory is configured, so the hook does not run here. 3 tests reference the hook; all 3 locate the TRACKED copy and assert on its text, and 0 assert installation. The same document that names this hook the only enforcement also records the other two rungs as gone -- automation disabled at the account level and no branch protection -- so on this machine the count of enforcement points that actually execute is 0. The evidence that this is not theoretical is the batch itself: 9 pushes were made from an isolated working copy during it and not one was gated, and from the author's side a successful push looked exactly like a push that had passed. A sibling lane hit the opposite face of the same gap -- on a machine where the hook IS installed it refuses every push from an isolated copy, because the corpus it wants to inspect is untracked and therefore absent there -- so the two observable states of this enforcement point are refuse-everything and enforce-nothing, and which one a person gets is decided by an untracked file nobody checks. The rule fires on the original because the installed path is absent, and on a different instance because it compares a resolved path against a tracked source and names no particular hook.
    return []  # list of findings — TODO implement
