# Bucket A — program-rule sketches for programs/_ppa/cli_exit.py
# Corpus-sweep REQUIRED before merging into programs/_ppa/cli_exit.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: An interface fixes which output stream carries the human summary and which carries a refusal, so that a caller can capture one without the other and a grep over a log means something. Nothing enforces it, because the obvious test — run the command and look — is run with no arguments, which produces an argument-parser error rather than a verdict. So every program looks identical under the test, the clause is never measured, and programs drift onto whichever stream their author reached for.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_which_stream_carries_the_summary_is_part_of_the_contract_and_must_be_driven_to_a(sample_text, ports):
    """Stream assignment is part of a command's contract, not a formatting preference: a caller that captures one stream and not the other gets a different answer depending on which program it invoked, and a log grep that finds nothing cannot distinguish a clean run from a summary written where nobody looked. Enforcing it requires driving each command to a REAL verdict, because the argument-parser error path is on the refusal stream for every command and tells you nothing about the clause."""
    # Expected signal: ERROR
    # Suggested fix action: Give each command a known-verdict invocation in the layer's own contract test — an input that produces a finding, and one that produces a could-not-check — and assert per stream that the summary lands where the interface says and the refusal marker lands on the other. MEASURED, two-sided, on comparable runs: the comparison command driven to a vacuous corpus puts its summary line on the output stream and its could-not-check marker on the error stream, which is the contract observed exactly; the contract command driven to a real document with sixteen findings puts EVERYTHING on the error stream, summary line included, leaving the output stream empty. One conformant, one not, out of the two I drove to a real verdict — the other seventeen are NOT MEASURED and are not claimed. THE SCREEN WARNING, EARNED: running each command with no arguments and comparing stream byte counts reports eighteen of nineteen on the error stream and is worthless, because that is the argument-parser path. It measures argparse, not the contract. THE NUMBERS, because this record described its measurement in words and carried no figure, and the implementing lane needs the figure rather than the narrative: the layer presents 19 commands. Exactly 2 were driven to a real verdict -- one conformant, one not -- and the remaining 17 are NOT measured and are not claimed, because driving each needs valid inputs per command. Do not substitute a no-argument invocation for that work: an earlier probe did, compared stream byte counts, and reported 18 of 19 'on stderr', which measures the argument parser rather than the contract. THE SCREEN: the population is the executables whose name carries the layer's prefix, one level under the program directory. Re-run today it is 20, against the 19 recorded -- one added -- and every one of the 20 builds an argument parser, so the count of commands and the count of files coincide here and a reader need not wonder which was meant.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A program refuses correctly, states the obstacle precisely, and stops. The caller now knows what is wrong and not what to do, so the next action is a search rather than a command. Detect by requiring a refusal message to carry an executable remedy -- a flag, a command, or the accepted form -- wherever one exists, and to say so explicitly where none does.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_refusal_that_names_the_obstacle_also_names_the_remedy(sample_text, ports):
    """A refusal that names the obstacle also names the remedy.

A correct refusal with no next step spends the caller's time proving something the program already knew. Where the accepted form is knowable -- a flag the program declares, a command that produces the required value, the shape the validator wants -- put it in the message. Where it is genuinely not knowable, say that, so the absence is a statement rather than an omission."""
    # Expected signal: a refusal carries an executable remedy, or states that none exists
    # Suggested fix action: MEASURED across the layer's refusal messages, with the screen validated before the figure was believed: 23 refusal strings, and 0 carry a remedy. The screen was checked both ways first -- it detects 2 of 3 known remedy phrasings and rejects 2 of 2 messages that carry none -- so it under-detects by roughly a third and the true count is very small rather than provably zero. Said that way on purpose, because a clean sweep from an unvalidated screen is the failure this batch has recorded six times. THE COST IS ON RECORD FROM THE LANE THAT PAID IT: a contract builder refuses an image reference given in tag form, for a good reason, and prints no hint; the request that came out of it names the exact command that resolves it and says printing that command would have saved a cycle. BUILD: give the refusal path a remedy argument and require it wherever the accepted form is derivable from what the program already checked -- a declared flag, a validator's own pattern, a command whose output is the required value. The predicate is presence of a remedy on a refusal whose accepted form is knowable, the population is every refusal the layer emits, and the refusal for the check itself is a message that names an obstacle and offers nothing. ITS OWN DENOMINATOR IS QUALIFIED, and the qualification is the argument for a companion rule. The 23 were found by searching for the bracketed markers the interface requires a refusal to carry -- so the population is REFUSALS THAT ARE ALREADY MARKED, and a refusal printed without one is invisible to the very screen that counted them. That is not hypothetical: a previous lane found a checker printing a bare error prefix on three artefact-not-found refusals with no marker at all, and another printing a correct English refusal that the interface still rejected because a grep for the code could not find it. Both were repaired there. So this record's figure is a floor over the marked subset, and the rule it implies alongside is the one the interface already states: a refusal carries a findable marker, because the population of refusals must be discoverable before any property of it can be measured -- including this one. An attempt to measure the unmarked population by pattern failed, matching docstrings rather than printed refusals, which is itself the reason the marker exists rather than a reason to doubt the rule.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A program lets an unexpected exception escape its entry point. The interpreter exits 1, and the exit-code contract reserves 1 for a finding about the subject -- so a missing library, a permission error or a defect in the checker itself is reported as a defect in the thing being checked. Detect by requiring the entry point to catch what it did not anticipate and exit on a code the contract does not give to findings.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_unhandled_exception_may_not_exit_with_the_code_reserved_for_a_finding(sample_text, ports):
    """An unhandled exception does not exit with the code reserved for a finding.

The finding code is a claim about the subject. An exception is a statement about the run, and letting it fall through the interpreter converts one into the other silently. Worse than a code a caller may skip: a finding stops a sign-off and names something nobody can act on. Catch at the entry point and exit on a code that means the check did not complete."""
    # Expected signal: an unexpected exception exits on a non-finding code and names itself as a run failure rather than a subject failure
    # Suggested fix action: MEASURED, with the screen validated both ways before the count was believed. Of the 20 measurement-layer entry points, 5 catch an unexpected exception at the entry point and 15 do not; the screen is an abstract-syntax walk for a broad handler inside the main guard, checked against the one program a previous lane fixed (detected) and one it did not (not detected). THE CASE THAT PRODUCED IT is on record from that lane: a contract checker guarded the absence of an optional library honestly, did not guard the library being present and too old, and the resulting attribute error escaped the entry point and exited 1 -- so a missing library was indistinguishable from a broken contract. The asymmetry matters and the lane said it: a caller may skip the could-not-check code, but a finding STOPS A SIGN-OFF and names something nobody can act on. BUILD: wrap each entry point so an unanticipated exception exits on a code the contract does not give to findings, and print the exception where a reader looks for the verdict. The predicate is presence of a broad handler at the entry point, the population is every program the layer ships as a command, and the refusal is the check failing for any entry point that can still hand an exception to the interpreter. Copy the shape from the 5 that already have it rather than inventing one.
    return []  # list of findings — TODO implement
