# Bucket A — program-rule sketches for programs/gen_program_inventory.py
# Corpus-sweep REQUIRED before merging into programs/gen_program_inventory.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A generator publishes a manifest OF the repository -- an index, an inventory, a census -- and enumerates its subject by asking the version-control system for the tracked file set. That is the right source, and it is careful about the obvious failure: when the query cannot be answered at all it returns nothing rather than an empty list, so a missing tool cannot read as an empty repository. It is not careful about the other failure. When the query CAN be answered, it answers about the committed tree -- which, at the moment an author runs the generator to describe work they have just done, is precisely the tree WITHOUT that work. The manifest is regenerated, looks freshly built, is committed alongside the very files it omits, and is now wrong in a way that mentions nothing. The author's mental model is that the generator describes what they have; the generator describes what was already committed.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_generator_over_the_tracked_set_refuses_a_tree_that_is_not_the_one_being_publis(sample_text, ports):
    """A generator whose subject is the tracked file set and whose own output is a tracked artefact must establish that the tracked set it is about to describe is the one that will be published. Where the working tree carries additions or modifications inside the generator's own input scope, refuse and say which paths make the answer provisional, rather than emitting a manifest of the previous state. Guarding only the case where the enumeration source FAILS is half the problem: a source that succeeds while describing a different tree state produces a confident wrong answer, and a confident wrong answer is the one nobody re-checks."""
    # Expected signal: ERROR
    # Suggested fix action: Before enumerating, ask the version-control system whether anything inside the generator's input scope is added, modified or untracked; if so refuse with those paths named, or enumerate the tree that will be committed rather than the one already committed. Either is acceptable; silently describing the committed tree is not. MEASURED, and scoped narrowly on purpose. 42 programs consult the tracked-file query and 34 of those write something, but that is the wrong denominator: most are CHECKERS, and a checker reading committed state is SUPPOSED to ignore a dirty tree -- reading the committed tree is the whole point of it. The population for this rule is generators that publish a manifest of the tracked set as a tracked artefact, and there are 3. 1 guards. 2 do not. 1 of the 2 is confirmed to have bitten a working lane, which discovered by hand that the generator had to be run AFTER the commit and wrote that down as something worth knowing -- the fix being knowledge in a report rather than a refusal in the program is exactly the gap this batch exists to close. The same program is careful in the other direction: it returns nothing when the query cannot be answered, so somebody already thought about one half of this and shipped it. The rule fires on the original because the generator would have refused instead of emitting a manifest missing the new files, and on a different instance because it keys on the pairing of a tracked-set enumeration with a tracked output, naming no generator. THE COMMANDS: the population is `git ls-files` mentioned in a program that also writes an output, listed by reading each candidate rather than by pattern; the guard question is answered by searching each for a working-tree status query before it enumerates.
    return []  # list of findings — TODO implement
