# Bucket A — program-rule sketches for programs/_ppa/cli_exit.py
# Corpus-sweep REQUIRED before merging into programs/_ppa/cli_exit.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: An interface fixes which output stream carries the human summary and which carries a refusal, so that a caller can capture one without the other and a grep over a log means something. Nothing enforces it, because the obvious test — run the command and look — is run with no arguments, which produces an argument-parser error rather than a verdict. So every program looks identical under the test, the clause is never measured, and programs drift onto whichever stream their author reached for.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_which_stream_carries_the_summary_is_part_of_the_contract_and_must_be_driven_to_a(sample_text, ports):
    """Stream assignment is part of a command's contract, not a formatting preference: a caller that captures one stream and not the other gets a different answer depending on which program it invoked, and a log grep that finds nothing cannot distinguish a clean run from a summary written where nobody looked. Enforcing it requires driving each command to a REAL verdict, because the argument-parser error path is on the refusal stream for every command and tells you nothing about the clause."""
    # Expected signal: ERROR
    # Suggested fix action: Give each command a known-verdict invocation in the layer's own contract test — an input that produces a finding, and one that produces a could-not-check — and assert per stream that the summary lands where the interface says and the refusal marker lands on the other. MEASURED, two-sided, on comparable runs: the comparison command driven to a vacuous corpus puts its summary line on the output stream and its could-not-check marker on the error stream, which is the contract observed exactly; the contract command driven to a real document with sixteen findings puts EVERYTHING on the error stream, summary line included, leaving the output stream empty. One conformant, one not, out of the two I drove to a real verdict — the other seventeen are NOT MEASURED and are not claimed. THE SCREEN WARNING, EARNED: running each command with no arguments and comparing stream byte counts reports eighteen of nineteen on the error stream and is worthless, because that is the argument-parser path. It measures argparse, not the contract. THE NUMBERS, because this record described its measurement in words and carried no figure, and the implementing lane needs the figure rather than the narrative: the layer presents 19 commands. Exactly 2 were driven to a real verdict -- one conformant, one not -- and the remaining 17 are NOT measured and are not claimed, because driving each needs valid inputs per command. Do not substitute a no-argument invocation for that work: an earlier probe did, compared stream byte counts, and reported 18 of 19 'on stderr', which measures the argument parser rather than the contract.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A program refuses correctly, states the obstacle precisely, and stops. The caller now knows what is wrong and not what to do, so the next action is a search rather than a command. Detect by requiring a refusal message to carry an executable remedy -- a flag, a command, or the accepted form -- wherever one exists, and to say so explicitly where none does.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_refusal_that_names_the_obstacle_also_names_the_remedy(sample_text, ports):
    """A refusal that names the obstacle also names the remedy.

A correct refusal with no next step spends the caller's time proving something the program already knew. Where the accepted form is knowable -- a flag the program declares, a command that produces the required value, the shape the validator wants -- put it in the message. Where it is genuinely not knowable, say that, so the absence is a statement rather than an omission."""
    # Expected signal: a refusal carries an executable remedy, or states that none exists
    # Suggested fix action: MEASURED across the layer's refusal messages, with the screen validated before the figure was believed: 23 refusal strings, and 0 carry a remedy. The screen was checked both ways first -- it detects 2 of 3 known remedy phrasings and rejects 2 of 2 messages that carry none -- so it under-detects by roughly a third and the true count is very small rather than provably zero. Said that way on purpose, because a clean sweep from an unvalidated screen is the failure this batch has recorded six times. THE COST IS ON RECORD FROM THE LANE THAT PAID IT: a contract builder refuses an image reference given in tag form, for a good reason, and prints no hint; the request that came out of it names the exact command that resolves it and says printing that command would have saved a cycle. BUILD: give the refusal path a remedy argument and require it wherever the accepted form is derivable from what the program already checked -- a declared flag, a validator's own pattern, a command whose output is the required value. The predicate is presence of a remedy on a refusal whose accepted form is knowable, the population is every refusal the layer emits, and the refusal for the check itself is a message that names an obstacle and offers nothing.
    return []  # list of findings — TODO implement
