# Bucket A — program-rule sketches for programs/_ppa/feasibility.py
# Corpus-sweep REQUIRED before merging into programs/_ppa/feasibility.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: An axis can be established more than one way, because different tools and different runs publish different facts about the same property. The alternatives are declared as a list of groups and the aggregation is the obvious one: a violation in any group loses, and otherwise any SATISFIED group wins over the groups that could not be evaluated. The first half is safe -- an added alternative can never hide a violation it can see. The second half is where the widening lives, and it is invisible because it looks like coverage: an axis that was unprovable becomes proven, and WHICH group proved it is decided by which one happened to have data on that run. If two groups test predicates that are not the same predicate -- a count against a tool's own threshold, and a magnitude against the contract's limit -- then the axis passes on whichever threshold was measured, and the stricter one was never applied. Nothing in the output distinguishes an axis proven the strong way from the same axis proven the weak way.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_an_alternative_proof_admits_nothing_the_proof_it_stands_in_for_would_refuse(sample_text, ports):
    """Where an axis admits alternative proofs, each alternative must be shown to admit nothing the proofs it stands beside would refuse, and the demonstration belongs in a test rather than in a comment. Alternatives whose predicates differ in KIND -- a zero-count against a threshold the tool chose, versus a measured magnitude against a threshold the contract states -- are not interchangeable by default, because they are answers to different questions that agree only when the two thresholds agree. Record which alternative established the axis, so a reader can tell a strong proof from a weak one without re-deriving the run."""
    # Expected signal: ERROR
    # Suggested fix action: Enumerate the axes declaring more than one proof group and compare the predicate KIND across the groups of each; require every axis whose groups are not all one kind to name the equivalence that licenses the substitution, and require that name to resolve to a test that drives both groups across the boundary and asserts the verdicts agree. Publish, on the result, which group established the axis. MEASURED. The policy declares 10 axes; 6 admit more than one proof group; 5 of those 6 mix predicate kinds -- a non-negative-slack group beside a zero-count group on two of them, a verdict-membership group beside a zero-count group on one, and a zero-count group beside a magnitude-under-limit group on two more. Exactly 1 equivalence argument exists anywhere in the layer, and it covers the one pair that does NOT mix kinds: two slack metrics under one predicate, argued in a comment that states the algebra, states what the substitution is not allowed to do -- rescue a view nobody analysed -- and names the test that sweeps the range so the reader need not trust the comment. That comment is the model to copy and it is also the measurement: the 5 mixed-kind axes have nothing equivalent to it. The aggregation makes this reachable rather than theoretical, and it was read rather than assumed: a violation in any group forces VIOLATED, but a SATISFIED group beats an UNDETERMINED one, so the group carrying data on a given run decides the verdict on its own predicate. The rule fires on the original because those 5 axes declare mixed-kind groups today with no stated equivalence, and on a different instance because it keys on the shape -- alternatives under one subject with differing predicates and no licence -- naming no axis. THE SCREEN for the axis figures: import the policy module and read the declared axis list directly rather than counting occurrences in source -- the axes are a data structure, so the authority is the structure and not a pattern over the file that builds it. The per-axis group counts and the predicate kinds come from the same objects, which is why the mixed-kind split is exact rather than approximate.
    return []  # list of findings — TODO implement
