# Bucket A — program-rule sketches for programs/flow_compliance_check.py
# Corpus-sweep REQUIRED before merging into programs/flow_compliance_check.py.

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A step writes an artefact wherever its own option points. A later consumer needs that artefact and locates it by trying an ordered list of names it carries in its own source, taking the first that exists. The flow document ALREADY declares the path, and the consumer never reads it — so one artefact has two definitions of where it lives, and the list is where they drift. Nothing detects the drift, because a consumer that finds nothing reports the artefact as absent, which is indistinguishable from a step that did not run.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_consumer_must_resolve_a_declared_output_path_rather_than_guess_among_candidate(sample_text, ports):
    """Where the flow declares a step's output path, that declaration is the single definition of where the artefact lives, and a consumer must resolve it from there. A private candidate list re-implements the same fact in a second place, and the failure it produces is silent in the worst direction: the artefact is reported absent rather than mislocated, so the axis it feeds degrades to not-measured and the run stays green. A list remains legitimate where the flow declares nothing, and as a fallback BEHIND the declaration — but then the fallback must be disclosed when it fires, because a consumer that quietly found the file under its second-choice name has evidence the declaration is wrong."""
    # Expected signal: ERROR
    # Suggested fix action: Resolve every declared artefact through the flow declaration; keep a candidate list only as a disclosed fallback, and report which name satisfied the lookup so a second-choice hit is visible rather than silent. Refuse a candidate list whose first entry contradicts the declaration. MEASURED on this tree: 48 consumers carry an ordered candidate-path list for a single artefact; 33 of those name at least one path the flow document ALREADY declares; and of those 33, only 3 are in a program that reads the flow declaration at all — the other 30 guess. The instance that surfaced this is a reliability screen whose consumer tries three names, one of which the flow does not know about, so the axis is reachable only by a coincidence of naming. Some of the 30 may be supporting older trees deliberately, which is why the rule orders the declaration first rather than deleting the lists.
    return []  # list of findings — TODO implement

# Auto-captured by benchmark-enhancement-capture at plugin v1.11.69
# Pattern: A flow step produces a measurement artefact at a declared path. A gate is later wired to audit that step, and the gate is given an output option so its verdict can be published too. The path handed to that option is the measurement's own path -- the obvious choice, because that is the file everyone associates with the subject. The gate runs AFTER the producer, so it overwrites the measurement with its own verdict document. Nothing fails: the gate exits zero, the file exists, and it parses. What is gone is the evidence, replaced by a document that says the evidence was fine. Worse, the replacement is usually identity-free boilerplate, so the artefact stops distinguishing one subject from another and a later consumer reading it gets a well-formed answer about nothing in particular.
# CORPUS-SWEEP REQUIRED before merging: zero false-positives across
# the open-benchmark corpora used by `score_iverilog_tb.py`.

def rule_a_gate_writes_its_verdict_to_a_path_no_producer_owns(sample_text, ports):
    """An auditing step must publish its verdict into a namespace it owns, never onto the path of the artefact it audits. A verdict written over a measurement destroys the measurement and leaves a document whose shape and exit code both look healthy, so no downstream check can notice. Compare every declared output path of every gate against every path a producer writes, and refuse any equality at wiring time; where the audited artefact and the verdict genuinely belong together, the verdict is a sibling file or a field within the producer's document, written by the producer."""
    # Expected signal: ERROR
    # Suggested fix action: Build the two path sets and refuse their intersection. The gate side is already declarative: the flow document states every gate command, so its output options can be read straight out of it. The producer side is a literal path per write call in the runners, so an index of producer-written paths is a grep for the write helpers over the program directory. Refuse at wiring time, not at run time, because at run time the evidence is already gone. MEASURED. The flow states 138 gate output paths. Nine of them are also written by a program; most of those nine are the gate invoking that same program, which is not a collision. At least two are, and they are CONFIRMED in the producer's own source rather than inferred: a runner comment states that the gate-checkers run after the manifest-emitting step and OVERWRITE two stamped lint artefacts with bare identity-less payloads, one family collapsing to an empty list. The repair that was applied is a caller-side sweep that re-stamps those two directories AFTER the audit has clobbered them -- a repair of the damage, not a prevention of the collision, and scoped to two directories that somebody had already noticed. A third instance was caught by hand at wiring time and survives only as a comment in the flow, which records that had the option ever been honoured the checker would have destroyed the measurement it was auditing. Three instances, three different one-off responses, no rule. A cross-step-only screen finds ZERO and is the wrong screen: the confirmed collisions are WITHIN one step, because a step declares the artefact and wires the gate that overwrites it. That screen was checked with a negative control -- an injected collision is detected -- so its zero is a real zero about the wrong question, which is the failure mode this whole batch keeps meeting. The rule fires on the original because the original is a literal path equality, and it fires on a different instance because it compares two generated sets rather than any known filename. THE SCREEN for the 138: read the flow document line by line, skip comment lines, and collect the distinct paths appearing after the output option on each gate command. Distinct paths, not occurrences -- a path wired at two steps is one output path and counting it twice would inflate the denominator the intersection is measured against.
    return []  # list of findings — TODO implement
